### ISSUE TITLE
Failure to honor "Switch To Blog" Mode

### ISSUE THREAD

**Issue by andypotanin** [udx/wp-stateless#1]
For all the images that don’t have the correct buckets in their URLs, this function here returns false: https://github.com/DiscoDonniePresents/www.discodonniepresents.com/blob/staging/wp-content/plugins/wp-stateless-v1.5/lib/classes/class-bootstrap.php#L310 

The bucket name is definitely not synchronized while using switch_to_blog.

**Comment by felixarntz** [comment]
After using `switch_to_blog( $blog_id )` a call to `wpCloud\StatelessMedia\Bootstrap::get( 'sm.bucket' )` still returns the bucket name from the original site. Accessing the option directly using `get_option( 'sm_bucket‘ )` actually returns the correct bucket for the current site.

**Comment by ewsopp** [comment]
@antonkorotkov I don't fully understand this issue. Can you look it over and let me know your thoughts? Thanks

**Comment by antonkorotkov** [comment]
Fixed. Now switch_to_blog forces `settings` to be refreshed using new blog.
