### ISSUE TITLE
add thumbnail regeneration

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#10]
We usually add 'Thumbnail Regeneration' functionality via the very popular "Regenerate Thumbnails" plugin by Viper007Bond. ref: https://wordpress.org/plugins/regenerate-thumbnails/

However, this plugin only regenerates thumbnails from images that are stored locally. So if your images are only stored on Google Cloud Storage (GCS) and not locally, this plugin will skip thumbnail regeneration for that image.

We need to recreate this thumbnail regeneration functionality as a feature of WP-Stateless with the modification that it regenerates images that are stored on GCS.

**Comment by antonkorotkov** [comment]
Done. Latest version in installed on workspace.uds.io
