### ISSUE TITLE
Google Login Redirect URL

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#100]
When logging in via Google, the Google Login Redirect URL does not use the proper site url.

Discuss with @andypotanin for more details.

Does not support dynamic site urls. This should be fixed.

**Comment by andypotanin** [comment]
@fqjony To be clear, the redirection URL from Google oAuth uses whatever the `home` option value is in the `wp_options` table. 

In disregards what the URL of the current site is or what the `WP_HOME` constant is set to - as is the case on rabbit.ci containers.

**Comment by fqjony** [comment]
@andypotanin @ewsopp ok, will do.

**Comment by ewsopp** [comment]
@fqjony is this done?

**Comment by fqjony** [comment]
@ewsopp @andypotanin done today at https://github.com/wpCloud/wp-stateless/commit/01e2f37d4c07a169c6e3557b6eab33cc497d8f87. Commited to `latest`

**Comment by alimuzzaman** [comment]
@fqjony It does not work if installed in a directory. Ex. getting `http://localhost/wp-admin/upload.php` instead of `http://localhost/workspace.uds.io/wp-admin/`.

**Comment by andypotanin** [comment]
@ewsopp @fqjony @alimuzzaman I'm confused by what we're trying to do here. But whatever the solution is we need to trust and rely on WP functions like `admin_url()`, `get_site_url()`, etc. Those functions already take into account any constants, such as `WP_HOME` and `WP_SITEURL`, as well as any filters that may be added. 

@ewsopp would you be able to give us a link to one of our environments where this can be replicated? I would want to investigate why `admin_url()` was returning something wrong before looking into anything else.
