### ISSUE TITLE
dynamic options for project and bucket name dropdowns

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#102]
watch video at https://usabilitydynamics.slack.com/files/ewsopp/F5WMYJCKV/stateless-qc-dynamic_name_dropdowns.mp4

- [ ] Provide the original default project name in the dropdown as an option in the project field.
- [ ] Add a new option to the bucket dropdown that prefixes `stateless-` to the newly provided project field.

**Comment by ewsopp** [comment]
Project drop down looks good, but you are missing the dynamics bucket option.

![image](https://user-images.githubusercontent.com/5578537/27640520-8fa62da2-5be7-11e7-97ab-8bd19caf3bd5.png)

**Comment by alimuzzaman** [comment]
@ewsopp Have you copy/paste the project name?

**Comment by ewsopp** [comment]
No - it was typed.

I can see that sometimes the dynamic bucket name works, but it seems to be delayed. For example, the below screenshot uses the previous project name I typed in.

![image](https://user-images.githubusercontent.com/5578537/27640804-355d6238-5be8-11e7-91d9-b681288919a8.png)

**Comment by alimuzzaman** [comment]
Check now, fix for #104 could fix it.

**Comment by ewsopp** [comment]
also - please do not carry over the randomly generated number we add to the project name.

![image](https://user-images.githubusercontent.com/5578537/27641416-bb2d9f08-5be9-11e7-8665-988d81e51247.png)

**Comment by ewsopp** [comment]
the dynamic bucket option should fit the rules. For example, the dynamic bucket name below doesn't meet the '5 and 30 characters' rule.

![image](https://user-images.githubusercontent.com/5578537/27643948-72848986-5bf0-11e7-9788-e81e6a99ebfc.png)
