### ISSUE TITLE
cannot proceed from step 2 to step 3

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#103]
watch video at https://usabilitydynamics.slack.com/files/ewsopp/F5XJYJA5V/confidential-stateless-new_project_creation_qc.mp4

After filling out all fields with valid options in Step 2, I was not able to proceed to Step 3.

**Comment by alimuzzaman** [comment]
Sorry, I had disabled that for debugging.

**Comment by ewsopp** [comment]
Still not working.

![image](https://user-images.githubusercontent.com/5578537/27754040-52a49f80-5db6-11e7-9a00-827874527dd5.png)

**Comment by alimuzzaman** [comment]
@ewsopp check again few times.
