### ISSUE TITLE
skip setup assistant if Service Account JSON setting is already configured

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#105]
Settings can be set by constants or via the Network Settings.

When activating the plugin...
- [ ] If the Service Account JSON setting is already configured, skip the setup assistant and redirect the user to the settings panel.

**Comment by alimuzzaman** [comment]
What about **Stateless Sync** menu?
As everything configured shouldn't we moved directly to **Stateless Sync**?

**Comment by ewsopp** [comment]
@alimuzzaman they can access the 'Sync' tab from the 'Settings' tab. That should be good enough.
