### ISSUE TITLE
QC "body content media url rewrite" option

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#106]
- ~~if the image does not exist on GCS, do not replace the media URL.~~
- [x] Does this rewrite do all fields? or just the editor content?

**Comment by ewsopp** [comment]
I spoke with @andy about checking GCS before replacing the file url and he explained this would require a long process and make page load times very slow. For now - lets skip that.

Please do a general QC on this feature and see if anything should be improved here. Also - please look into my question I posted in my initial comment. Thanks

**Comment by alimuzzaman** [comment]
Only the **`the_content`** filter.

**Comment by alimuzzaman** [comment]
@ewsopp Do we need to replace in meta also?

**Comment by ewsopp** [comment]
Yes I think so.
