### ISSUE TITLE
add "Stateless" mode

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#109]
- [x] add "Stateless" as a mode option.
- [x] remove the "Remove local file." option.
- [x] after the file is sucesfully uploaded to GCS, delete the local file on disk.

**Comment by alimuzzaman** [comment]
Where `Remove local file.` exist?

**Comment by alimuzzaman** [comment]
> remove the "Remove local file." option.

Should I remove that feature entirely or just not include in `Stateless mode`.

**Comment by ewsopp** [comment]
Yea - this feature is shifting to a mode. Stateless mode

**Comment by alimuzzaman** [comment]
Two are opposite 
Where current option `Delete media from GCS when media is deleted from the site`.
And stateless delete when images exist in the cloud.
This option could be still useful in `CDN` mode.

**Comment by alimuzzaman** [comment]
To do: Need to hook into Upload on-fly, after getting clear understanding.

**Comment by Nks** [comment]
I think #112 can be removed if this task will complete soon.
Also, we should think about logic to regenerate thumbnails for new thumbnails if somebody added it with the `add_image_size` function.
It should download image original image from GCS, regenerate thumbnails with all available sizes, upload thumbnails to the GCS with removal all old files.
If I can help just ping me here.
