### ISSUE TITLE
google account name, email address, and logout button missing

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#110]
I logged-in with a Google Account (`admin@ocoeecafe.com`) that does not have an avatar set. However, it does have a name and email address.

I'm not sure why, but the name, email address, and logout button did not appear in the wp-stateless setup assistant.

Something is broken.

# WP-Stateless Setup Assistant

![image](https://user-images.githubusercontent.com/5578537/27754619-3ea5ced4-5db9-11e7-8d37-40a3a2e5cf2c.png)

# Google Account Settings

![image](https://user-images.githubusercontent.com/5578537/27754710-bf055d4c-5db9-11e7-9bba-d10d782e4d95.png)

**Comment by alimuzzaman** [comment]
@ewsopp It working for me. Can you replicate the issue again?

**Comment by ewsopp** [comment]
@alimuzzaman I just sent you the account login to hopefully recreate this issue.

**Comment by alimuzzaman** [comment]
API not returning email address what was unexpected.

**Comment by alimuzzaman** [comment]
Not sure what's wrong with that account. But log out button will show now without an email address.

**Comment by ewsopp** [comment]
What I see now...

![image](https://user-images.githubusercontent.com/5578537/28168080-e5b1e02c-67ab-11e7-8bb2-10feec5d066e.png)
