### ISSUE TITLE
Google API 503 - WP Plugin crash

### ISSUE THREAD

**Issue by Nks** [udx/wp-stateless#111]
So, yesterday Google had some troubles with the API and it returns a 503 error without any reason.
In this time some files which were uploaded from the different copies of the WordPress was unavailable.
For the small websites this is maybe okay, but when you have over 10k sessions on the website it can be a problem. Can we change logic from "when bucket is unavailable we are showing links from the wordpress instead google cloud storage links" to "when bucket is unavailable we are still showing correct url to the Google cloud storage but in the wp-admin we should notice users about problems with the google cloud bucket". And also when method `is_connected()` in the `GS_Client`  return `false` we can show to the user more friendly message instead just `Could not connect to Google Storage bucket. Please, be sure that bucket with name <b>%s</b> exists.`.

What do you think?

**Comment by andypotanin** [comment]
You were getting 503s when trying to open uploaded media assets, right? 

I've seen this happen once and the issue lasted for 10-15 minutes. It freaked us out so we ended up putting a CloudFront instance before GCS. When we had the problem we didn't have any indications of not being able to add new files - so I don't think the `is_connected` check would've triggered enough of a warning.

> when bucket is unavailable we are showing links from the wordpress instead google cloud storage links

That would work in some cases but not all - we prefer to not even retain local copies of uploaded media assets (makes multi-container Docker/RKT hosting easier to orchestrate), so failing-over to local assets may cause its own set of issues. Therefore, putting up a CF distribution in-front of the GCS bucket seems like an optimal setup. 

Let me know what you think.

**Comment by andypotanin** [comment]
By the way, Google has its own CDN solution (caches assets before reaching out to bucket backend), which you could probably use to achieve the same effect. We use CF because its setup is a lot more robust.

**Comment by andypotanin** [comment]
Looks like they recognize that they had an outage for your incident.
![image](https://user-images.githubusercontent.com/1255935/27960425-415aac36-62f9-11e7-9b81-1c3bc0f84a8a.png)
https://status.cloud.google.com/incident/storage/17002

**Comment by Nks** [comment]
@andypotanin 

> Looks like they recognize that they had an outage for your incident.

Yes, that was. And at this time while json was unavailable I had some troubles on my docker containers with all files which retrieving with the `get_the_post_thumbnail_url`, etc. Of course, I can install cloudfront, but for what?
Also when we are using solution from the google which calling Google Container Engine we should build the microservices and as I know microservice means that the in the pod (container, etc) we are not storing any files on the local. That is how google storage official plugin works, but I really wont reject wp-stateless plugin and, as I told, when google storage api is not working we will get links directly from the wordpress for all media instead google storage links and if you have 100-200 mb in the wordpress - if works, but when you have restrictions with 100 gb per each pod you can't and you haven't any time to copy all media from the storage to each pod. 
Also, yes, I know about persistent disks and that I can connect it to the container engine how it described in their official documentation (https://cloud.google.com/wordpress/) but in this case I can't use scale system without creating a persistent disk for each pod. That is not how docker should work I think. 

So, I propose to revise the logic regarding storing files on the local version and give an ability to select by user where he wants store this files and if google cloud is unavailable showing files from the google cloud storage in any case, because if I can't upload media - that is not a big problem and I can wait for this while google fixing this issue but if we are changing urls in all wordpress pages when just google storage API is unavailable - this can kill kittens :)

**Comment by Nks** [comment]
In trust solution is trivial. We can just move `if (!$this->has_errors()) {` in the class `class-bootstrap.php` a bit later if user select something like `Always use links from the google storage`. 
Also it will be great to see `Don't upload files local` option and in this case prevent any uploads to the local `upload` folder. What do you think, @andypotanin?

**Comment by Nks** [comment]
Look on this.
When we have an error from the Google Storage and can't connect to the server we are showing an error (simulated):
![image](https://user-images.githubusercontent.com/349293/27984828-4b3584d4-63e8-11e7-888e-cb40c3a43940.png)
But while we have selected a `CDN only` mode in the settings:
![image](https://user-images.githubusercontent.com/349293/27984825-26db47fe-63e8-11e7-9b03-d492ba0b7d12.png)
we are still can show images directly from the google storage
![image](https://user-images.githubusercontent.com/349293/27984837-9330f20a-63e8-11e7-8c9c-7981e2dafed1.png)
Also it works for the media library too
![image](https://user-images.githubusercontent.com/349293/27984840-b7f34c5a-63e8-11e7-9791-e3e52401a446.png)

**Comment by Nks** [comment]
**Total:**
- [x] Add CDN only mode
- [x] Notify user when he selecting a CDN only mode about risks (files will not store locally)

**When CDN only mode enabled:**
- [x] Show links from the GCS in any case
- [ ] Prevent any uploads if API is unavailable
- [ ] Prevent any deletions if API is unavailable
- [ ] Implement method to delete file without deleting it from the local upload folder
- [x] File should be deleted from the local `upload` folder after uploading to the GCS
- [ ] Disable `WP-Stateless` sync function if CDN Only mode enabled

What do you think?

**Comment by Nks** [comment]
@andypotanin can you look this https://github.com/Nks/wp-stateless/commit/44e80030a59682f7f3ae907f0dc5544ebb4b644c?
Also I'm not sure how you are building a release. Can you help me with this or apply changes by yourself? Or I can just send a PR. Thanks.

**Comment by andypotanin** [comment]
@Nks Go ahead and send a PR and we will look it over. We're working pretty actively on getting a release out that will simplify the setup process by automating things like service account creation - a lot of people are getting stuck there, especially since Google Console has changed their interface 2-3 times over last year.

That being said, I get what you're asking for, and we will try to get it into a release after we do some QC.

**Comment by ewsopp** [comment]
@alimuzzaman before interacting with Google Cloud, we should check to ensure it is online and ready to receive our commands and data.

We need some general function that we can call from different points (within setup assistant, before uploading a file, before thumbnail regeneration, etc) within the plugin. Maybe even check it whenever the settings panel is loaded to output a warning to the user via a nonce.

If Google Cloud or Google Cloud Storage is not available, we should prevent whatever the user is trying to do and inform them of the fact and to try again later. Maybe even link them to the Google Cloud Status Dashboard for more information. https://status.cloud.google.com/

**Comment by andypotanin** [comment]
@ewsopp Why don't we add this notification to the admin bar like we do with the WP-Upstream plugin?

**Comment by alimuzzaman** [comment]
In that case, we would have 2 status. One for Google status and another for current bucket configuration.

**Comment by dwbtoftshit** [comment]
ok, then I wait with a new bucket! Better to solve this

2017-09-11 1:57 GMT+02:00 Md. Alimuzzaman Alim <notifications@github.com>:

**Comment by ewsopp** [comment]
> Why don't we add this notification to the admin bar like we do with the WP-Upstream plugin?

I like that idea too.

**Comment by antonkorotkov** [comment]
@alimuzzaman does this old issue looks like there something we can do? Does it still make sense?

**Comment by alimuzzaman** [comment]
@antonkorotkov 
All of the suggested feature has been implemented already.

- [x] Stateless mode
- [x] Error notice when can't connect to GCS.
- [x] Using local URL when GCS is down.
