### ISSUE TITLE
Enable CDN mode with setup

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#114]
With project, bucket, and billing account setup in Step 2 of the setup assistant, CDN mode should be enabled. When they reach the last step, they are directed to upload a file and this would allow that to work as expected.

**Comment by alimuzzaman** [comment]
@ewsopp Should that replace current mode? Or only if the mode isn't set?

**Comment by ewsopp** [comment]
Only if mode isn't set, which should be the case on installation. Right?
