### ISSUE TITLE
Invalid client secret JSON file.

### ISSUE THREAD

**Issue by celandro** [udx/wp-stateless#119]
I am trying to set up wp-stateless on a google compute instance and am getting a very strange error

[Thu Jul 20 04:21:23.435462 2017] [:error] [pid 5794] [client 172.68.143.5:16255] PHP Warning:  json_decode() expects parameter 1 to be string, array given in /var/www/html/wp-content/plugins/gmail-smtp/google-api-php-client/src/Google/Client.php on line 168, referer: https://articles.pokebattler.com/wp-admin/options-media.php

Any thoughts?

**Comment by alimuzzaman** [comment]
@celandro Both gmail-smtp and wp-stateless uses different versions of Google APIs Client Library. wp-stateless uses a newer version than gmail-smtp what isn't backward compatible.

**Comment by celandro** [comment]
Thanks so much for getting back to me so quickly. I was very confused due
to this plugin working on the old site but not the new with the same
configs. Feel free to close this ticket unless you want to add a better
error message for this case.

**Comment by pemaxim** [comment]
@celandro  The error should be fixed now.
To solve the issue on your site, you have to update WP-Stateless plugin to version 2.0.1 and Gmail SMTP to version 1.1.4 and higher.
