### ISSUE TITLE
Support for GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by walle89** [udx/wp-stateless#123]
It would be nice if this plugin can detect and use the GOOGLE_APPLICATION_CREDENTIALS environment variable. 

This one way similar to issue #44, but using GOOGLE_APPLICATION_CREDENTIALS have some advantages:

1. The PHP Google APIs Client Library supports this [out of the box](https://developers.google.com/identity/protocols/application-default-credentials).
1. If you are using Google Cloud Platform, this variable is already set. There is no need to fiddle with a JSON-key file.
1. Makes it easier to move away from the Google Cloud Storage plugin.

Because this plugin is planned to be used for a project I'm currently working on at work, I'm interesting in to help you guys out. Not only I can implement this for you, I can look into fixing bugs and generally make this plugin stable for version 1.10. Many of the features I need for this project is in 1.10 (eg. sm_root_dir).

Let me know how we can collaborative and make this plugin more awesome than what it already is. ;)

**Comment by ewsopp** [comment]
@walle89 Yes - this makes sense. We are trying to finish up the current release, now labeled as v2.0.0, and if we can work this in - that would be great.

Give us this week to finish up what we are currently working on, and then we can cleanup the branches a bit and get you more involved. Does that sound good?

**Comment by walle89** [comment]
Sounds good. Let me know if there is something I can help you with.

**Comment by ewsopp** [comment]
@walle89 ok - I think we're ready for you. Want to try including this functionality within the v2.0 branch?

**Comment by walle89** [comment]
Sure, I will give it a shot. I will start look into this sometime this week. But I have a few things I need to clear up.

1. What coding standard are you using? It's either [PSR-2](http://www.php-fig.org/psr/psr-2/) or [Wordpress coding standard](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/). The reason for I'm asking this is I want to respect your coding style (even though I don't personally like 2 spaces  indentation).
1. What is the reason you are storing the key in the database if the WP_STATELESS_MEDIA_KEY_FILE_PATH constant is in use? My plan is just read the json-file from GOOGLE_APPLICATION_CREDENTIALS.
1. I think it's good to somehow in the settings panel (and setup assistant) to have some indication to that it's using the GOOGLE_APPLICATION_CREDENTIALS. But I currently don't have a good solution in mind. Do you have any suggestion?
1. In what priority order should each "json key method" be in? My idea is to have something like:
```php
<?php
if(!empty(get_site_option( 'sm_key_json' )))
// Use site option
elseif (!empty($this->get( 'sm.key_json' )))
// use $this->get( 'sm.key_json' )
elseif(is_defined('WP_STATELESS_MEDIA_KEY_FILE_PATH') )
// Use WP_STATELESS_MEDIA_KEY_FILE_PATH (in your implementation, this is stored in the database)
elseif(getenv('GOOGLE_APPLICATION_CREDENTIALS') !== false)
// Use GOOGLE_APPLICATION_CREDENTIALS
else
// No key, return some error message.
```

I would love to hear your feedback.

**Comment by ewsopp** [comment]
> What coding standard are you using? It's either PSR-2 or Wordpress coding standard. The reason for I'm asking this is I want to respect your coding style (even though I don't personally like 2 spaces indentation).

Not sure. Maybe @andypotanin or @alimuzzaman can chime in.

> What is the reason you are storing the key in the database if the WP_STATELESS_MEDIA_KEY_FILE_PATH constant is in use? My plan is just read the json-file from GOOGLE_APPLICATION_CREDENTIALS.

The original intent was to allow the key to be loaded from the JSON file or the settings panel (database). I don't think we need to store the JSON key in the database if it is being loaded from a file. @alimuzzaman can you advise on your implementation here?

> I think it's good to somehow in the settings panel (and setup assistant) to have some indication to that it's using the GOOGLE_APPLICATION_CREDENTIALS. But I currently don't have a good solution in mind. Do you have any suggestion?

For the setup assistant, I'm not sure we need to say anything. It's meant to be stupid simple and _just work_.

For the settings panel, we could just insert an uneditable message into the field describing that we are using the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. 

> In what priority order should each "json key method" be in?

Not sure, but maybe @alimuzzaman or @andypotanin can provide their thoughts?

**Comment by andypotanin** [comment]
Just to chime in regarding environment variable detection - I usually prefer to use `$_SERVER` instead of `getenv` in theory they should be same, or at least similar, but in many environments they can be rather different.

**Comment by alimuzzaman** [comment]
The priority order is:
1. Constant
2. Network Settings
3. Database

**Comment by walle89** [comment]
@andypotanin `getenv` [is case-insensitive](http://us3.php.net/manual/en/function.getenv.php#99134) (useful for user defined variables) and works in CLI mode. But the main reason I use it for is to distinguish between variables set by PHP/CGI and server environment variables. If your coding standard or code style prefer $_SERVER, then I can work with that.

@alimuzzaman Ok. When I implement GOOGLE_APPLICATION_CREDENTIALS, do you think it should take higher priority than the constant?

**Comment by walle89** [comment]
@ewsopp Regarding the JSON key in database if there is a constant. I did a test with a fresh WP installation with v2.0 branch. The reason for the key is saved in the database is because the field "Service Account JSON" in the settings panel is not disabled when a constant is in use. In other words, when you press save the key will be stored in the database.

Is it okay I fix this so that the field is disabled as part of the current task? Or shall I create a separate issue and report it as a bug?

One more thing. You did change this task to be part of version 2.1. Should I fork and send pull request to the v2.0 branch? Or will you create a 2.1 branch?

**Comment by ewsopp** [comment]
> Is it okay I fix this so that the field is disabled as part of the current task? Or shall I create a separate issue and report it as a bug?

Here is fine - thank you for testing this. 

> One more thing. You did change this task to be part of version 2.1. Should I fork and send pull request to the v2.0 branch? Or will you create a 2.1 branch?

I just cloned a v2.1 from v2.0. Let's go with v2.1. Unless there is a critical bug, I think we should release v2.0 as-is. It's currently with a handful of people for testing.

**Comment by ewsopp** [comment]
> When I implement GOOGLE_APPLICATION_CREDENTIALS, do you think it should take higher priority than the constant?

Maybe lower priority than a wp-config constant. Otherwise, how would the user overrule it easily if they needed to?

**Comment by walle89** [comment]
May I ask when you plan to release 2.1? I need this information for planning of my project at work.

Also let me know if there is something in my pull request you want me to fix or help you guys out with something.

**Comment by alimuzzaman** [comment]
@walle89 Thanks. There is smething need to change. But I will do it.

**Comment by ewsopp** [comment]
@walle89 I'm aiming to publicly release v2.0 today. Let's plan on a v2.1 release next week to allow any uncaught bugs to surface from v2.0.

**Comment by ewsopp** [comment]
@walle89 this has been worked into the v2.1 release. Would you mind testing this out for us? You can download it from https://github.com/wpCloud/wp-stateless/archive/v2.1.zip

**Comment by walle89** [comment]
I did just a quick test and initially every thing seems fine. Soon I have time later this week, I will do more testing. 

What's your current plan to release 2.1 (if you don't find any major issues)?

**Comment by ewsopp** [comment]
All that is left is more thorough testing. I'd like to release this week! :)

**Comment by walle89** [comment]
I have tested v2.1 (not RC) and GOOGLE_APPLICATION_CREDENTIALS variable works as expected. I have yet tested it Google Cloud Platform, but I feel quite conferment that this feature will work. I will continue the testing of other fixes and features that will be released. But as for this issue, in my opinion I would say this is working and ready for release.

Environment spec:
WP 4.8.1 subdir network (both with existing and brand new install with standard config)
PHP 7.1 (https://hub.docker.com/_/php/)
MySQL 5.7 (https://hub.docker.com/_/mysql/)
Environment variable set by Docker Compose

**Comment by ewsopp** [comment]
Thank you @walle89 - we are shipping v2.1.0 now! Expect an update today at https://wordpress.org/plugins/wp-stateless/
