### ISSUE TITLE
step 2 fails after clicking Continue button

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#129]
After I click continue, it seems to do some work but then fails and outputs...

> Something went wrong

Not a very helpful message, but better than nothing I suppose.

![image](https://user-images.githubusercontent.com/5578537/29146466-46cc2942-7d2f-11e7-8652-f137c0cfb6b7.png)

## Checking the Google Cloud Console, I can see the project was created correctly.

![image](https://user-images.githubusercontent.com/5578537/29146513-7fde4be8-7d2f-11e7-807e-94bb7e9f4514.png)

## However, the bucket was NOT created.

![image](https://user-images.githubusercontent.com/5578537/29146536-9b8790ca-7d2f-11e7-900c-ad5c656041b1.png)

## Also - the billing account was assigned correctly.

![image](https://user-images.githubusercontent.com/5578537/29146563-b97b5e68-7d2f-11e7-9536-3f7ee19b4e22.png)

**Comment by ewsopp** [comment]
Actually, it looks like the billing account WAS assigned correctly. So the only problem is with bucket creation.

**Comment by alimuzzaman** [comment]
The problem was we were trying to create the bucket before project initialize. Sometimes project creation takes some time instead of immediately.
