### ISSUE TITLE
conflict of google client versions

### ISSUE THREAD

**Issue by Mashenka** [udx/wp-stateless#131]
https://wordpress.org/support/topic/invalid-client-secret-json-file-after-activing-gmail-smtp-plugin/#post-9402860

**Comment by ewsopp** [comment]
We can do a little tweaking on our end, but ultimately this will require the plugin author of the conflicting plugin to do some updates of their own. The plugin author seems to be aware of their issues and is working to resolve them. Details at https://wordpress.org/support/topic/plugin-conflicts-27/#post-9432962

**Comment by pemaxim** [comment]
@Mashenka @ewsopp I'm closing the issue, since we already have related one:  https://github.com/wpCloud/wp-stateless/issues/119
