### ISSUE TITLE
error appeared when trying to sync non-images

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#138]
_Reported by @stbeli_

by choosing the option "Synchronize non-images files between Google Storage and local server" respond error is "Status: Error appeared". Even if WP_DEBUG is set as true I can't catch error at log file.

Server Configuration:
PHP: 7.0.19-1~dotdeb+8.1;
Web Server: Apache / nginx
WordPress: 4.8.1

**Comment by ewsopp** [comment]
I was not able to reproduce this report.

**Comment by ewsopp** [comment]
@alimuzzaman what did you do to fix this?

**Comment by alimuzzaman** [comment]
@ewsopp I did nothing. Maybe related to #140
