### ISSUE TITLE
conflict with WP Smush

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#139]
_Reported by @stbeli_

in case web site has activated WP Smush for Resize, optimize and compress image, wp-statteles output PHP Error:
PHP Catchable fatal error:  Object of class stdClass could not be converted to string in /home/ucdev/web/wp-stateless.update.care/public_shtml/wp-content/plugins/wp-stateless-2.0.0-rc1/lib/classes/class-bootstrap.php on line 521, referer: https://wp-stateless.update.care/wp-admin/post.php?post=11&action=edit

Server Configuration:
PHP: 7.0.19-1~dotdeb+8.1;
Web Server: Apache / nginx
WordPress: 4.8.1

**Comment by ewsopp** [comment]
It's causing a 500 error on `/wp-admin/upload.php` as well.

When WP-Smush is enabled with v2.0 (or higher), I get a 500 error in the console.

When WP-Smush is disabled, the 500 error goes away.

![image](https://user-images.githubusercontent.com/5578537/29688492-f4d553fa-88ed-11e7-998d-362fdc58132e.png)

**Comment by pemaxim** [comment]
@ewsopp I can not replicate any mentioned issue. I have two plugins activated:

![image](https://user-images.githubusercontent.com/308489/29707032-825efc78-898c-11e7-93f9-9787148ba87b.png)

Please, provide more details how I could replicate the issue ( and/or link me to site where you got 500 Error on loading `upload.php` ).

Thank you.

**Comment by pemaxim** [comment]
@ewsopp Fixed. The fix included to [2.0.2](https://github.com/wpCloud/wp-stateless/releases/tag/2.0.2) release
