### ISSUE TITLE
Warning while uploading image via Media > Add New

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#140]
_Reported by @stbeli_

Warning while uploading image via Media > Add New: 
Warning: Error while sending QUERY packet. PID=28098 in /home/ucdev/web/wp-stateless.update.care/public_shtml/wp-includes/wp-db.php on line 1877

Server Configuration:
PHP: 7.0.19-1~dotdeb+8.1;
Web Server: Apache / nginx
WordPress: 4.8.1

**Comment by ewsopp** [comment]
I was not able to recreate this.

**Comment by alimuzzaman** [comment]
@ewsopp Please contact with @stbeli if he still has the issue.
Seems like he needs to increase max_allowed_packet in mysql configuration file (my.ini).
Related topic on wp.org.
https://wordpress.org/support/topic/e_warning-error-while-sending-query-packet-pid18213-stack-trace-lled-at-ho/

**Comment by ewsopp** [comment]
Not sure what resolved the issue, but @stbeli is reporting all issues resolved on his end.
