### ISSUE TITLE
Setup wizard problem with a custom domain pointed bucket

### ISSUE THREAD

**Issue by alikuru** [udx/wp-stateless#142]
Tried to setup the plugin with an existing bucket on Google Cloud Storage, named specifically to use with a custom domain, but had an error: `Something went wrong`.

Since the error message is not clear enough, I'm assuming it must be related to bucket name. Because when I try to delete the ready bucket from the console and create it with the plugin, it tells me: `A bucket name can contain lowercase alphanumeric characters, hyphens, and underscores. Bucket names must start and end with an alphanumeric character.`

My bucket name is similar to this: `x.example.com`.

Any ideas how to fix this? Can't really find anything in the logs.

Also, wonder if there is a manual setup option available?

**Comment by ewsopp** [comment]
Hey @alikuru - can you try these manual setup instructions? https://github.com/wpCloud/wp-stateless/wiki/Manual-Setup

Let me know how that goes.

Regarding your original issue, did you use the setup assistant to create the bucket or was it already created?

**Comment by alikuru** [comment]
It was already created. Appreciated the link, will try setting manually.

**Comment by ewsopp** [comment]
Thanks @alikuru - if you don't mind, I'd like to learn more about this issue in case there is something we can do to fix this. 

In the setup assistant, did you select your existing project and see your bucket listed in the following drop down? If so, did you select it? When did the `Something went wrong.` message appear?

Thanks!

**Comment by alikuru** [comment]
I've selected my existing project and the bucket I'd like to use did appear in the drop-down. I chose it and hit continue. `Something went wrong` message appeared between the account information and the Google Cloud Project label.

**Comment by alikuru** [comment]
Manual setup worked, thanks again for the help.

**Comment by pemaxim** [comment]
@ewsopp @alimuzzaman We show `Something went wrong` message on all failures during Setup Wizard process.

I think, for better troubleshooting we should include Error Code or some more details ( e.g. failed task's name ) about the particular error. 

E.g.:  `Something went wrong. Error Code: 12345. Please ask UsabilityDynamics, Inc support for help.`. Where `12345` code belongs to fail response on `insertBucketAccessControls` step.

**Comment by ewsopp** [comment]
@pemaxim In this particular case, I think our bucket name rules were being applied to an existing bucket. Since the bucket already exists, we don't need to apply those rules.
