### ISSUE TITLE
ud-dismiss.js ERR_ABORTED

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#143]
> I noticed there's a dependency issue with the wp-stateless plugin.
>  
> Once it's installed and I access wp-admin I see two 404 errors that are caused by your plugin.
> 
> GET {{ path to my theme }}/{{ path to my plugins }}/plugins/wp-stateless/vendor/usabilitydynamics/lib-wp-bootstrap/static/scripts/ud-dismiss.js?ver=4.8.1 net::ERR_ABORTED
> 
> Kindly fix this issue.

**Comment by pemaxim** [comment]
@ewsopp So far, I can not replicate the issue on my local server. So, I have the following questions:

* Which server is the site being run on? (Windows/Linux)
* Which version of WP-Stateless user mentioned about?
* Did it happen on first WP-Stateless activation or after upgrading plugin to new version.
* If it happened on plugin upgrade: which old version of plugin? which new version of plugin?
* `ud-dismiss.js` script is being loaded only when Admin Warning is shown. Which Admin Warning was shown on WP-Stateless activation/upgrade ?

Thank you.

**Comment by pemaxim** [comment]
One more question, regarding the invalid link:

`{{ path to my theme }}/{{ path to my plugins }}/plugins/wp-stateless/vendor/usabilitydynamics/lib-wp-bootstrap/static/scripts/ud-dismiss.js?ver=4.8.1`

`{{ path to my theme }}..` is invalid path... The link must be:

`{{ path to my plugins }}/plugins/wp-stateless/vendor/usabilitydynamics/lib-wp-bootstrap/static/scripts/ud-dismiss.js?ver=4.8.1`

* Does the plugin installed to plugins directory or to some custom directory ( e.g. it's integrated to theme )?

**Comment by ewsopp** [comment]
More details from user:

> I’m using bedrock as Wordpress stack https://github.com/roots/bedrock and run it on Linux. I run a fresh installation of wp-stateless v2.0.1 and the plugin doesn’t show any warnings when I access the settings.
> 
> Without bedrock this issue does not occur. However, I suspect the way you detect the plugin file path causes the issue and I have not experienced a similar behaviour with other plugins.

**Comment by pemaxim** [comment]
@ewsopp It's fixed and included to `v2.0.2` release.

**UPDATE** the issue belongs to our `lib-wp-bootstrap` library which is included to all our plugins. We have to update `lib-wp-bootstrap` to version `1.2.2` in all our plugins..
