### ISSUE TITLE
Fatal Error During Activation

### ISSUE THREAD

**Issue by jhauer** [udx/wp-stateless#145]
When attempting to activate the plugin I receive a Fatal Error message and activation fails.  The message is as follows:
![screenshot 18](https://user-images.githubusercontent.com/224035/29745228-2864438e-8a83-11e7-8310-0599bda9289e.png)

**Comment by Mashenka** [comment]
Hello @jhauer 


Please, note, the fatal error you experienced ‘Can’t use function return value in write context‘, belongs to PHP 5.5 and less.

> Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false.

More details is [here](http://php.net/manual/en/function.empty.php)

In general, it means, that the version of PHP on your server is too old. And, you may face with a bunch of other Fatal Errors, even if the current Fatal Error will be fixed.

WP-Stateless plugin ( and most of other ones ) support PHP 5.6 and higher.

Anyway, the Fatal Error is fixed and it will be available in new ‘hotfix’ release 2.0.2 shortly. Until, new WP-Stateless 2.0.2 is not launched, you can download the plugin with fix here.

Please check following article where that was mentioned:
https://wordpress.org/support/topic/few-pdf-showing-older-url/page/2/

**Comment by pemaxim** [comment]
@jhauer @Mashenka @ewsopp Fixed. The issue included to [2.0.2](https://github.com/wpCloud/wp-stateless/releases/tag/2.0.2) release.

@jhauer you have to update your PHP version minimum to 5.5 to make it working.

**Comment by jhauer** [comment]
Thank you, php upgrade resolved issue
