### ISSUE TITLE
wp_calculate_image_srcset fails to rewrite default image

### ISSUE THREAD

**Issue by aschmoe** [udx/wp-stateless#148]
Since the processing in `foreach ($image_meta['sizes'] as $key => $meta)` only uses the sizes array for replacement, if the default (unsized) image is in the source array, it remains un-replaced.

https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-bootstrap.php#L232

Some debug of the $sources array before and after replacement:

Before wp_calculate_image_srcset
```
784 "https://site.com/wp-content/uploads/..../image.png" "w" 784
300 "https://site.com/wp-content/uploads/..../image-300x113.png" "w" 300
768 "https://site.com/wp-content/uploads/..../image-768x289.png" "w" 768
140 "https://site.com/wp-content/uploads/..../image-140x53.png" "w" 140
340 "https://site.com/wp-content/uploads/..../image-340x128.png" "w" 340
170 "https://site.com/wp-content/uploads/..../image-170x64.png" "w" 170
```

After wp_calculate_image_srcset
```
784 "https://site.com/wp-content/uploads/..../image.png" "w" 784
300 "https://storage.googleapis.com/..../image-300x170.png" "w" 300
768 "https://storage.googleapis.com/..../image-768x289.png" "w" 768
140 "https://storage.googleapis.com/..../image-140x53.png" "w" 140
340 "https://storage.googleapis.com/..../image-340x128.png" "w" 340
170 "https://storage.googleapis.com/..../image-170x64.png" "w" 170
```

**Comment by ewsopp** [comment]
@aschmoe thanks for investigating. We'll take a look!

**Comment by alimuzzaman** [comment]
@aschmoe @ewsopp Now wp_calculate_image_srcset will rewrite default image also.

**Comment by ewsopp** [comment]
@aschmoe would you mind testing this with the v2.1 branch? You can download it directly from https://github.com/wpCloud/wp-stateless/archive/v2.1.zip

Please let us know! :)

**Comment by aschmoe** [comment]
@ewsopp thank you, issue appears to be fixed... as you already know ;)

Sorry about the tardy response.

**Comment by ewsopp** [comment]
@aschmoe awesome - thanks for confirming! 👍
