### ISSUE TITLE
wildcards for bucket folder settings

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#149]
Wildcards would be a useful tool for separating different site's media files when using a shared bucket folder across an entire network. For example, we could have a wildcard that uses the site's URL as the replacement.

Are there other useful ideas for wildcards besides the site's url? 

_idea suggestion from the wordpress.org forum at https://wordpress.org/support/topic/serving-the-same-media-to-multiple-sites/#post-9459270_

**Comment by walle89** [comment]
For a subfolder multisite installation, I think it should be the name of the subfolder instead of the site url. For example `example.com/site1` becomes `site1`.

**Comment by Feleys** [comment]
To change path structure like WordPress's structure.
For example bucket: /(site-id)/(year)/(month)/file.jpg
I think top level of bucket should dynamically generate folder name of site id because user may mapping domain, if use site id it will not affected.

**Comment by deivamagalhaes** [comment]
Following up on this issue.

**Comment by deivamagalhaes** [comment]
One alternative is to implement a filter using WP hook pre_option hook in custom plugin until this wildcard thing is done:

```
add_filter( 'pre_option_sm_root_dir', [ $this, 'override_wp_stateless_bucket_folder_option' ], 1, 2 );

...

/**
 * Override WP-Stateless Bucket Folder option.
 *
 * @param  string  Option
 * @param  mixed   Default
 *
 * @return string  Site ID
 */
function override_wp_stateless_bucket_folder_option( $option, $default ) {
    return (string) get_current_blog_id();
}
```

**Comment by alimuzzaman** [comment]
@ewsopp @andypotanin @Feleys @deivamagalhaes 

What wildcard can we add?

`(year)/(month)` will be added by WordPress if enabled in settings. Not sure if we need those as a wildcard.

**Comment by alimuzzaman** [comment]
@ewsopp How you would like the syntax of the wildcard?

1. (.......)
2. {.......}
3. [.......]
4. ((.......))
5. {{.......}}
6. [[.......]]

**Comment by ewsopp** [comment]
What about this format?

- `%%date_year%%`
- `%%date_month%%`
- `%%site_id%%`
- `%%site_url%%`

What if the site url has a slash in it? For example: `mywebsite.com/wordpress`

**Comment by alimuzzaman** [comment]
@ewsopp 
> What if the site url has a slash in it? For example: mywebsite.com/wordpress

That can be sub folder.
Or we can use the site slug instead. Ex. `wordpress`.

**Comment by alimuzzaman** [comment]
Here are the things I have added.

`%%date_year%%`: Year in four-digit.
`%%date_month%%`: Month in two-digit.
`%%site_id%%`: Site id.
`%%site_url%%`: Site URL. Includes directory if installed in a directory.
`%%site_url_host%%`: Only the host part of the site URL.
`%%site_url_path%%`: Directory part of the site URL if any.

**Comment by ewsopp** [comment]
I believe I have thought of a solution that would satisfy this new feature requirement, problems with shared bucket multisites, and additional options for expert users wanting more control over file organization. 

Please read over everything carefully and share your thoughts in the comments. Thank you

# Bucket Folder Recipes

- Single Site
  - `/%date_year%/%date_month%/`
- Multisite
  - `/sites/%site_id%/%date_year%/%date_month%/`
- Custom

# Interface

![image](https://user-images.githubusercontent.com/5578537/73959707-bb8d7580-48d7-11ea-8dd2-f8a93539bbd3.png)

- [x] add drop down above the text field with the following options: _Single Site_, _Multisite_, _Custom_
- [x] Selecting _Single Site_ and _Multisite_ replaces the field contents with the above recipes.
- [x] Typing anything in the field switches the selected dropdown option to _Custom_.
- [x] Below the text field, show all the available variables as tags. Clicking these tags adds them into the text field. Exact same experience you have with building a custom permalink at `/wp-admin/options-permalink.php`

![IMG_20200206_115208](https://user-images.githubusercontent.com/5578537/73959385-40c45a80-48d7-11ea-84cb-968f9aaa3cc1.jpg)

# Other Items

- [ ] Remove the _Organization_ setting. It's now redundant.

![image](https://user-images.githubusercontent.com/5578537/73960757-6eaa9e80-48d9-11ea-864e-4e21ad512f10.png)

- [ ] I think we should now completely ignore the WordPress Core file organization setting and apply the organization set in this updated field.
  - [ ] **OR** we synchronize the setting based on the user's drop down selection...
    - if Single Site or Multisite is selected, we enable the WordPress core setting.
    - if Custom is configured, we disable the WordPress core setting.
  - [x] I spoke with @andypotanin and he suggested we gray out the WordPress Core option and add a note/link that explains that this setting is now managed in WP-Stateless settings (via Bucket Folder control). **I think I like this approach the best.**

![image](https://user-images.githubusercontent.com/5578537/73960503-08be1700-48d9-11ea-8e22-a03220adabee.png)

# Mapping for Existing Users

This should account for all current configurations. Are we missing anything? 

- [x] If _Organization_ is enabled **AND** _ Bucket Folder_ is empty: Single Site
- [x] If _Organization_ is enabled **AND** _ Bucket Folder_ is not empty: Previous bucket folder + Single Site
- [x] If _Organization_ is disabled: Custom
- [x] If they have a value in _Bucket Folder_: Custom, and keep that setting.
- [x] In multisite prefix with `/sites/%site_id%/` value evaluated from above condition.

# Other Items and Concerns

- [ ] This approach will allow the users to further organize their files beyond the year/month folders. Neat.
- [ ] Should we ignore the WordPress Core organization function entirely and only use our custom organization function? Doing so would keep things simpler I think and provide us more precise control on following the user setting.
- [ ] Any unforeseen issues with ignoring the WordPress Core organization option?
- [ ] Plugin conflicts? Example see issue https://github.com/wpCloud/wp-stateless/issues/407#issue-520105651 and how it only stores into the siteid folder (not within the full custom path that could be set with our new setting).
- [ ] Any other thoughts or concerns?!

**Comment by ewsopp** [comment]
I've ran the above concept by several people and everyone seems to agree with it. Let's proceed. @alimuzzaman

**Comment by alimuzzaman** [comment]
@ewsopp 
>  If Organization is enabled AND _ Bucket Folder_ is empty: Single Site

What will happen when Organization is enabled AND _ Bucket Folder_ is **Not** empty?
I think we should use custom with Year/Month.

**Comment by alimuzzaman** [comment]
In some cases, the location of the file will be changed in the server or GCS.

We may introduce a new sync method in the Sync tab, to move the file to appropriate locations.
Normal regeneration will duplicate files in GCS or server.

**Comment by alimuzzaman** [comment]
@ewsopp how this looks?
![image](https://user-images.githubusercontent.com/6744156/75150287-4078eb80-572e-11ea-95eb-73a3717281db.png)

**Comment by ewsopp** [comment]
> @ewsopp
> 
> > If Organization is enabled AND _ Bucket Folder_ is empty: Single Site
> 
> What will happen when Organization is enabled AND _ Bucket Folder_ is **Not** empty?
> I think we should use custom with Year/Month.

I covered this situation:
- If they have a value in Bucket Folder: Custom, and keep that setting.

I don't think we should change anything that will affect how it is working right now. Do you disagree?

**Comment by alimuzzaman** [comment]
As @ewsopp explained we will keep the existing attachment to its original location after regeneration.

And add a new sync method to regenerate/move the image to the new location in issue #449

**Comment by alimuzzaman** [comment]
- [x] Functionality is done for new attachments.

- [x] And add a new sync option in the Sync tab to move attachments to the new location.

- [x] Now we have to make sure that existing attachment doesn't change their location when we use existing sync methods. ("Regenerate and Sync with GCS" or Sync tab)

https://github.com/wpCloud/wp-stateless/blob/35a0bdf22ef2bf0cef1dc59843c803f2e57fe912/lib/classes/class-bootstrap.php#L1510

My idea is to accept attachment ID in `root_dir_wildcards` function and get/extract root dir from `sm_cloud` meta, for existing attachment.

**Comment by alimuzzaman** [comment]
@ewsopp in multisite the Mapping will apply to all sites?

**Comment by ewsopp** [comment]
> @ewsopp in multisite the Mapping will apply to all sites?

Great question. Any reason why we wouldn't provide a multisite option to force/override a setting upon all sites?

**Comment by alimuzzaman** [comment]
@planv need to `update_site_option` and `update_option` for all site in the network.

https://github.com/wpCloud/wp-stateless/blob/2eb30e86121185ed6c09b8bd2586ea819d14c307/lib/classes/class-upgrader.php#L148

**Comment by alimuzzaman** [comment]
@ewsopp 

Will this be ok?

With single-site `/%date_year%/%date_month%/`.

://storage.googleapis.com/udx-ci-develop-alim/**_2020/03_**/gravity_forms/1-3be54e6f7692b73c8bf3a64f7b5c27d2/**_2020/03_**/a2d40088-annotation.png

When it's synced via Sync tab the sync process downloads it to 

wp-content/uploads/**_2020/03_**/gravity_forms/1-3be54e6f7692b73c8bf3a64f7b5c27d2/**_2020/03_**/a2d40088-annotation.png

instead of 

wp-content/uploads/gravity_forms/1-3be54e6f7692b73c8bf3a64f7b5c27d2/**_2020/03_**/a2d40088-annotation.png.

**Comment by alimuzzaman** [comment]
@planv 

- [x] we forgot to set a default value for `Bucket Folder`.
- [x] Also need to disable `Available tags` if it's overridden by the network.

**Comment by alimuzzaman** [comment]
Created separated issues to review.

- [x] Filtering upload_dir #461
- [x] Review migration #462

**Comment by alimuzzaman** [comment]
# Review compatibility

- [x] Advanced Custom Fields Image Crop Addon
- [x] BuddyBoss
- [x] BuddyPress
- [x] Divi
- [x] Dynamic Image Support
- [x] Easy Digital Downloads
- [x] Elementor Page Builder
- [x] EWWW Image Optimizer
- [x] Gravity Forms
- [x] Imagify Image Optimizer
- [x] LearnDash LMS
- [x] LiteSpeed Cache
- [x] Polylang Pro
- [x] ShortPixel Image Optimizer
- [x] Simple Local Avatars
- [x] SiteOrigin CSS
- [x] SiteOrigin Widget Bundle
- [x] VidoRev
- [x] WooCommerce Extra Product Options
- [x] WP Retina 2x Pro
- [x] WP Smush
- [x] WPBakery Page Builder
- [x] WPForms

**Comment by planv** [comment]
FYI: `ShortPixel Image Optimizer` has original (WP-Stateless disabled) folder's structure for backups

<img width="464" alt="изображение" src="https://user-images.githubusercontent.com/5268508/78125549-dc76d080-7419-11ea-9bc9-20dc8547cb4c.png">

**Comment by planv** [comment]
Compatibility for ` LiteSpeed Cache` tested on single site. It is ok for images.
On multisite this plugin not working correctly.

Plugin ` WooCommerce Extra Product Options` not working for me, and I don't see any information and updates on their site - `https://themecomplete.com/`

**Comment by alimuzzaman** [comment]
@ewsopp can we close this?

**Comment by planv** [comment]
## Local server path

We won't do any changes on local server folder structure. Value from field `Folder` will be applied only for GCS. 

- [x] Revert changes for WordPress setting `Organize my uploads into month- and year-based folders`
- [x] Revert changes for local folder structure (hook `upload_dir`)
- [x] Remove copying media on local server in sync process

## Mapping field `Folder` for Existing Users

- [x] If _Organization_ is enabled **AND** _ Bucket Folder_ is empty: `/%date_year%/%date_month%/`
- [x] If _Organization_ is enabled **AND** _ Bucket Folder_ is not empty:  `/Previous_bucket_folder_value/%date_year%/%date_month%/`
- [x] If _Organization_ is disabled **AND** _ Bucket Folder_ is not empty: `/Previous_bucket_folder_value/`
- [x] If _Organization_ is disabled **AND** _ Bucket Folder_ is empty: Empty value
For `Single site` and `Multisite` the same values.

## Mapping field `Folder` for fresh install

- [x] If _Organization_ is enabled: `/%date_year%/%date_month%/`
- [x] If _Organization_ is disabled: Empty value
- [x] Multisite and _Organization_ is enabled: `/sites/%site_id%/%date_year%/%date_month%/`
- [x] Multisite and _Organization_ is disabled: `/sites/%site_id%/`

## For all multisites

- [x] Forcing `Cache Busting` to `Enabled` (it will fix problem for media with the same filenames)
- [ ] Add notice for users "We forced `Cache Busting` for prevent errors" (need text of message for it)

**Comment by planv** [comment]
Using tag like `%blog_id%` break media. 
We should allow using only letters and numbers (if it is not an our available tag), or do `urlencode` for media URL.

![image](https://user-images.githubusercontent.com/5268508/79437064-59897480-7fda-11ea-852b-b003e5eb43ed.png)

**Comment by alimuzzaman** [comment]
@planv I think we should do `urlencode` in `wp_stateless_handle_root_dir` filter.
And warn user using js that they shouldn't use special char in `Bucket Folder`.

**Comment by planv** [comment]
@alimuzzaman Do you propose use urlencoded value for folders name on GCS? 
If we add `%blog_id%` on  field `Folder` - it will be applied as `%25blog_id%25` on GCS.
I'm not sure that is good idea.

**Comment by alimuzzaman** [comment]
Working as expected.
