### ISSUE TITLE
improve support for Easy Digital Downloads

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#150]
When WP-Stateless is used alongside Easy Digital Downloads, the "redirect" download method is always used regardless of the setting in EDD. Ideally, WP-Stateless should respect the download method setting and support the "Forced" download method option.

![image](https://user-images.githubusercontent.com/5578537/30765103-d4cb463e-9fbb-11e7-827d-9a5cea2e0248.png)

**Comment by antonkorotkov** [comment]
Done.
