### ISSUE TITLE
test and improve support for advanced custom fields

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#151]
> can you tell me if this plugin works with both advanced custom fields media uploader and the image crop add-on?
> 
> Here are the URL's:
> https://wordpress.org/plugins/acf-image-crop-add-on/
> https://www.advancedcustomfields.com/resources/image/
> 
> I have checked the Support Forums and the FAQ's, and even googled to see if there is any information about compatibility, but I haven't seen it.

reference: https://wordpress.org/support/topic/advanced-custom-fields-compatability-acf/

**Comment by alimuzzaman** [comment]
[Here](https://github.com/wpCloud/wp-stateless/tree/v2.1-hot-fix) is a hotfix for the problem until [this pull request](https://github.com/andersthorborg/ACF-Image-Crop/pull/53) accepted.
https://github.com/wpCloud/wp-stateless/tree/v2.1-hot-fix
