### ISSUE TITLE
add support for siteorigin generated CSS files

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#153]
> siteorigin generates CSS files for certain pages/layouts and tries to write them to disk. could we have wp-stateless capture these files and uplodad them to GCS?

**Comment by antonkorotkov** [comment]
@ewsopp I think this is not finished. Feature requires manual syncing in order CSS files to appear in GCS.

**Comment by ewsopp** [comment]
Can it be automatic instead of manual?

**Comment by antonkorotkov** [comment]
@alimuzzaman could you check if it is possible to hook into SiteOrigin to intercept CSS generation and make this feature automatic for this kind of files?

**Comment by alimuzzaman** [comment]
@antonkorotkov Working on it.

- [x] Automated sync is working.
- [ ] But removing them is not working yet.
- [x] Delete local file in stateless mode.
