### ISSUE TITLE
WP Stateless saves images in root and double-slash (//) directory

### ISSUE THREAD

**Issue by ahmed-sigmalux** [udx/wp-stateless#154]
I am encountering an easily reproducible bug. My settings are:

* CDN
* Enable file URL replacement
* Enable dynamic image support
* Leave folder blank
* Domain = cdn.mysite.com
* Disable organization
* Enable cache-busting

Then go to the sync tab, select "Regenerate all stateless images," and click run. What happens is that images are placed in both the storage bucket root and a folder "/" (accessible as cdn.mysite.com//image.jpg). Therefore all images are duplicated without any clear reason or purpose.

**Comment by ewsopp** [comment]
Thank you for the clear feedback @ahmed-sigmalux 

We'll take a look and get a fix prepared

**Comment by ewsopp** [comment]
@ahmed-sigmalux can you try this fix? https://github.com/wpCloud/wp-stateless/archive/v2.1-hot-fix.zip

**Comment by ahmed-sigmalux** [comment]
That works.

Thank you for the prompt turnaround.
