### ISSUE TITLE
What GCS permissions are required?

### ISSUE THREAD

**Issue by chrissound** [udx/wp-stateless#155]
What permissions are required from the GCS service account?

**Comment by ewsopp** [comment]
Hey @chrissound - check the Manual Setup guide in the Wiki at https://github.com/wpCloud/wp-stateless/wiki/Manual-Setup#4-create-google-cloud-service-account for details.

Let me know if you need any further details. Thanks!

**Comment by ewsopp** [comment]
I'm closing this for now.

@chrissound feel free to open again and let us know if you need any further assistance. Thanks

**Comment by chrissound** [comment]
The answer is "Storage > Storage Admin"

**Comment by christophwolff** [comment]
Why are the Storage Admin permissions needed? In our organisation this is a real security issue. What would be a workaround? Thank you
