### ISSUE TITLE
fatal error with GuzzleHttp

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#156]
reported at https://wordpress.org/support/topic/error-guzzlehttpexceptionrequestexceptiongeterrors/

> Hello, i found this error message after authorized Google Cloud Storage.
> The authorization is success, but my entire WordPress installation showing this error message:
> 
> Fatal error: Call to undefined method GuzzleHttp\Exception\RequestException::getErrors() in D:\root\home\dev078\wp-content\plugins\wp-stateless\lib\classes\class-bootstrap.php on line 934
> 
> I running in development environment that currently working in my local computer using addressing my domain into local IP (127.0.0.1).
> 
> Is this plugins require that website need to be online?
> 
> I also has meet the requirement of GuzzleHttp below:
> 
> http://docs.guzzlephp.org/en/stable/overview.html#requirements
> 
> Thank you for your help

**Comment by asisten** [comment]
Thank you, now this problem fixed for GuzzleHttp by using the hotfix.
