### ISSUE TITLE
Multisite synced media libraries

### ISSUE THREAD

**Issue by ahmed-sigmalux** [udx/wp-stateless#160]
We're using WordPress multisite with [MultilingualPress](https://multilingualpress.org/) to create a multilingual website. Each subsite is identical to the primary site, but in a different language, i.e., site 1 is English, site 2 is the same content in German, site 3 is the same content in French, and so on. Because each subsite is identical other than the language, we end up having the same images in multiple media libraries, resulting in duplicate images totaling n * subsites.

To reduce wasted storage, we manually create hardlinks between each subsite's media library content and the primary site's media library content. Now that we're using WP Stateless to serve media content, I think we can further improve things by using the same CDN bucket for all subsites and thereby increase the browser cache hit rate (if a customer visits a page in English first and then switches to German, we shouldn't force him to redownload all the images simply because the URL changed). 

Therefore my questions are:

1. For existing media library content, what is the impact of using the same storage bucket and path for all subsites? Is manually syncing the media library mandatory for each subsite necessary or is it good enough to perform the sync once on the primary site and then WP Stateless will automagically see / use the existing storage bucket content on the subsites?

2. For new media library content, what is the impact of using the same storage bucket and path for all subsites? Will we need to upload images once on each subsite (perhaps to generate the database entries?) or can we simply upload the images once on the primary site and then have them show up in the media libraries of all the subsites?

**Comment by ewsopp** [comment]
> For existing media library content, what is the impact of using the same storage bucket and path for all subsites?

We have had talks internally about a synchronization tool that would have special handling for files on GCS that don't have any media library objects in WordPress (ref https://github.com/wpCloud/wp-stateless/issues/27). The tool would help the webmaster to identify and provide options for handling these orphaned files.

In your situation where multiple media libraries have the same storage location would have a problem with this (each site is unaware of files uploaded by other sites). In the end, this would be an option with the sync tool - so you wouldn't want to use this feature of new sync tool (still in the conceptual/planning phase). Hope that made sense. :)

In terms of how it will affect your sites now, it shouldn't do anything irregular. Each site will only see the files it uploaded itself. So if you have multiple sites using the same bucket and path, then they would only have knowledge of the files that they uploaded. This is the nature of how WordPress works - there is no concept of shared media library between network sites. 

> For new media library content, what is the impact of using the same storage bucket and path for all subsites?

From how WordPress handles this, I think I covered it above. From a webmaster point of view, it would be kind of messy - but not that crazy. A great benefit of WP-Stateless is that you shouldn't have to care how things are organized on the GCS -side. As long as you can see the files and manage them within WordPress, then who cares if multiple network sites are sharing the same bucket. I think its just a personal preference on the underlying organization. 

> Will we need to upload images once on each subsite (perhaps to generate the database entries?) or can we simply upload the images once on the primary site and then have them show up in the media libraries of all the subsites?

Yes - each media library is separate and doesn't know anything else outside of its own site. I think I covered this above.

@ahmed-sigmalux great questions, please let me know if you need any further clarification.

**Comment by ahmed-sigmalux** [comment]
Thanks for answering all my questions.
