### ISSUE TITLE
Some objects have wrong content-type

### ISSUE THREAD

**Issue by ahmed-sigmalux** [udx/wp-stateless#163]
WP Stateless is setting the wrong content-type on some objects. Specifically, I'm seeing that .png files are being uploaded with the content-type image/jpeg. This is important because CORS fails when the object content-type is incorrect.

**Comment by ewsopp** [comment]
@ahmed-sigmalux thanks for reporting this. We will get this resolved.

**Comment by ewsopp** [comment]
@ahmed-sigmalux I just tested this for both a JPG and PNG images and didn't see the problem.

![image](https://user-images.githubusercontent.com/5578537/31319838-0d3296ac-ac38-11e7-83b3-dff283c0c1bc.png)

![image](https://user-images.githubusercontent.com/5578537/31319842-194fdbb6-ac38-11e7-95e0-b9b292caa0c0.png)

**Comment by ahmed-sigmalux** [comment]
I double-checked and here's what I see happening:

1. I'm importing a WooCommerce CSV with URLs to product images.

2. The product image URLs are hosted at a 3rd party imaging service and return the correct content types.

3. Without WP Stateless, the product images are saved to the local disk are served with the correct content types (for .png, our web server returns a content-type of image/png).

4. With WP Stateless, the product images are saved to the Google storage bucket with the wrong content types (for .png, Google storage shows a content-type of image/jpeg). I confirmed this by manually inspecting the images in the Google storage GUI.

5. This normally isn't a problem because browser automatically correct the content-type to image/png. When loading the images via xmlhttprequest (such as the media library), however, the images fail to display because the wrong content-type is presented to CORS.

How does WP Stateless determine the content-type when uploading to a Google storage bucket? Does it perform some MIME type sniffing, use the file extension, or do nothing and let Google automatigically figure it out?

**Comment by ahmed-sigmalux** [comment]
I'm seeing the same problem when manually uploading a PNG file to the media library.

**Comment by alimuzzaman** [comment]
@ahmed-sigmalux Try this fix https://github.com/wpCloud/wp-stateless/archive/v2.1-hot-fix.zip
This should solve the problem.

**Comment by ahmed-sigmalux** [comment]
The hotfix works. Thank you!
