### ISSUE TITLE
Bucket link filtering issue

### ISSUE THREAD

**Issue by villesiltala** [udx/wp-stateless#164]
We are building a proxy on our clients' sites which sets the urls to point to the site's domain and then Nginx proxys the uploads url to the Google bucket. We tried using the custom domain setting, but it was not working and the urls still pointed to Google. Then we turned to filtering the bucket url with the `wp_stateless_bucket_link` filter. However, we don't want to create a filter for all our themes to be able to change the default url. To enable setting the bucket url with a constant I created this simple [mu-plugin](https://github.com/devgeniem/wp-stateless-bucket-link-filter).

Could it be possible to add this kind of feature in the plugin core so we don't need to use a custom mu-plugin to do it?

We are using version 2.1.0 on WP 4.8.2.

**Comment by leepeterson** [comment]
I would also like to know if/when this would be possible. In fact, having more control over assets hosted in GCP would be ideal.

I think a simple, generic UI within WP Stateless that allowed for the creation of asset metadata is the best way to handle this: creating VPC network metadata for the purpose of using it with CDN asset routing.

This solution would then offer additional benefits such as cache control, cache keys, asset versioning, and more.

[Google's CDN Best Practices](https://cloud.google.com/cdn/docs/best-practices) document speaks more on this subject.

**Comment by alimuzzaman** [comment]
@villesiltala Pull requests are welcome. Otherwise we will try to implement this as soon as possible.

**Comment by alimuzzaman** [comment]
@leepeterson We already have a page under Media menu. Where from you can set cache control now.

**Comment by ewsopp** [comment]
Thanks, everyone. I'll try to clear some time to dig into this and research it a bit.

**Comment by ewsopp** [comment]
It seems like the crux of this issue is...

> We tried using the custom domain setting, but it was not working and the urls still pointed to Google.

@planv can you investigate this please? Relevant constant here is [WP_STATELESS_MEDIA_CUSTOM_DOMAIN](https://github.com/wpCloud/wp-stateless/wiki/Constants#wp_stateless_media_custom_domain)

**Comment by planv** [comment]
@ewsopp You are right. 

Constant `WP_STATELESS_MEDIA_CUSTOM_DOMAIN` is designed for this.

Also we have field `Domain` on UI

![image](https://user-images.githubusercontent.com/5268508/80796404-bf175c80-8ba7-11ea-87ab-1b46919ad18f.png)

**Comment by ewsopp** [comment]
@planv can you test to ensure these fields are working as expected? It looks like this reported case was from a multisite install, so be sure to test that scenario as well.

**Comment by planv** [comment]
@ewsopp Tested on multisite too. Works fine.

![image](https://user-images.githubusercontent.com/5268508/80809232-ebdc6b80-8bc9-11ea-8de1-d40671773c83.png)
 
One urgent moment - value of constant and bucket name must match exactly. 

I updated Wiki, added `Be advised that the bucket name and domain name must match exactly, and HTTPS is not supported with a custom domain out of the box. `
