### ISSUE TITLE
cannot create directories

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#17]
When images do not exist locally, the plugin errors out when it needs to generate the folders that hold the images.

reference https://codex.wordpress.org/Function_Reference/wp_mkdir_p

example error output

> Directory /var/www/wp-content/blogs.dir/23/files/2014/09 does not exist for sink value of /var/www/wp-content/blogs.dir/23/files/2014/09/06282d2b7116fb85e8a4d94360dc23f878.jpg

We tested this by manually creating the directories and it continued without issue.

**Comment by antonkorotkov** [comment]
Done and released in 1.7.1
