### ISSUE TITLE
Undefined index: gs_link in class-bootstrap.php

### ISSUE THREAD

**Issue by ahmed-sigmalux** [udx/wp-stateless#170]
I'm seeing the below error in my debug log:

`Notice: Undefined index: gs_link in /var/www/wordpress/wp-content/plugins/wp-stateless/lib/classes/class-bootstrap.php on line 268`

**Comment by ahmed-sigmalux** [comment]
Any news on this?

**Comment by alimuzzaman** [comment]
@ahmed-sigmalux In which version of WP Stateless you found the error?
Can you please test with latest version?

**Comment by alimuzzaman** [comment]
@ahmed-sigmalux I don't see any reason this could still happen. I am closing the issue.
