### ISSUE TITLE
Typo in constant WP_STATELESS_MEDIA_BODY_REWTITE

### ISSUE THREAD

**Issue by niemenmaa** [udx/wp-stateless#171]
In [class-settings.php](https://github.com/wpCloud/wp-stateless/blob/06f1847f187ca39c0d7781bd27338decb95977b6/lib/classes/class-settings.php#L25) plugin cheks for set constants. There is a typo for setting the body rewrite. This probably should be `WP_STATELESS_MEDIA_BODY_REWRITE`.

```
 'body_rewrite'           => array('WP_STATELESS_MEDIA_BODY_REWTITE', 'true'), 
```

**Comment by ahmed-sigmalux** [comment]
Ran into this bug today...

**Comment by Mashenka** [comment]
Hello guys.

Thank you for pointing. Issue fixed. You could find a fix in latest branch https://github.com/wpCloud/wp-stateless/tree/latest
