### ISSUE TITLE
change permission of service account to 

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#173]
At the moment, the service account created during the setup assistant only gives permission to the bucket created by the setup assistant. This causes issues when the user updates the bucket setting with a newly created bucket, but does not update the service account setting.

To solve this problem, the webmaster would need to do one of the following:
1. create a new service account with proper permission on the new bucket.
2. updating the previously created service account with permission to access the newly created bucket.
3. or upgrade the permission of the existing service account (upgrade to Storage Admin for example).

This is a bit much to describe to most users, so to resolve the current incoming support requests and stem future inevitable requests - we should upgrade the default permission of the created service account to Storage Admin Project Role.

With a Storage Admin role for the entire Project, the service account would be able to read, write, and edit access any bucket on the project.

This update would also resolve an issue with using multiple buckets in network mode (separate buckets for each site) while trying to use a service account generated using the setup assistant.

We actually instruct such a setup within the Manual Setup instructions at https://github.com/wpCloud/wp-stateless/wiki/Manual-Setup#4-create-google-cloud-service-account

**Comment by antonkorotkov** [comment]
Done
