### ISSUE TITLE
visual composer - single image element

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#174]
Visual Composer's single image element doesn't play nice with WP-Stateless. The problem shows up when you provide a custom size for the image.

**Comment by alimuzzaman** [comment]
@ewsopp Can you please explain?

**Comment by alimuzzaman** [comment]
Done

**Comment by ewsopp** [comment]
Compatibility description meta...

title: `WPBakery Page Builder `
description: `Enables support for these WPBakery Page Builder features: single image element.`
constant: `WP_STATELESS_COMPATIBILITY_WPB`

**Comment by alimuzzaman** [comment]
Updated
