### ISSUE TITLE
How to use WP-Stateless only for uploading? Not reading tasks

### ISSUE THREAD

**Issue by ericleonardo** [udx/wp-stateless#175]
Hi! I want use WP-Stateless only for uploading media to GCloud Storage. Don't want it doing image URL replacement when loading pages. For retrieving images directly from Storage bucket, I changed WP database **wp_options > upload_url_path** to my bucket URL and added read permission to **allUsers** there. This way, Wordpress can read media files very fast with no redirect. Please, how can I nullify the read redirect function on WP-Stateless use it strictly for upload?

Best regards!

**Comment by ewsopp** [comment]
Did you try the `Backup` mode? That sounds like what you need.

**Comment by ericleonardo** [comment]
Will Backup mode directly upload to Storage bucket everytime I import a new image? I need cut the cost, so better upload directly to Storage which is less expansive. Will be dealing with high amount of images on daily basis (importing product feed from many stores with WP-All Import).

**Comment by ewsopp** [comment]
Best way to know if it works for you is to test it out. It's completely free. 👍

**Comment by ericleonardo** [comment]
Right! Well, I just tried **Backup** mode: image was uploaded both to local WP uploads folder and to Google Storage bucket. What you think is easier and what file should I edit? Edit **Backup** mode to avoid uploading to local server; Or Edit **Stateless** mode to avoid reading images from Storage? All this is because my WP performs better when loading images directly from Storage (putting Storage bucket URL on database wp_options > upload_url_path) without doing redirects. Thanks!
