### ISSUE TITLE
Update Google Libaries

### ISSUE THREAD

**Issue by tobsch** [udx/wp-stateless#176]
With PHP 7, I currently get the following error: 
https://github.com/google/google-api-php-client/issues/776

The issue states that updating helps. 
Could you do that?

**Comment by alimuzzaman** [comment]
@antonkorotkov I have updated the library directly from [google/google-api-php-client](https://github.com/google/google-api-php-client). 
Everything seems to be working fine.
And removed all services except Storage.
Stateless has been reduced in size by ~5 MB.

**Comment by antonkorotkov** [comment]
That's awesome!
