### ISSUE TITLE
WP Stateless making unnecessary database queries and slowing down site

### ISSUE THREAD

**Issue by ahmed-sigmalux** [udx/wp-stateless#177]
I recently partitioned my WordPress installation by blog ID (using the HyperDB extension). I noticed a severe slowdown in my site, with admin pages going from ~2 seconds to load to >30 seconds to load. I checked with Query Monitor and noticed WP Stateless is querying every single options table regardless of which blog is being requested, thereby causing the slowdown.

For example, I access https://site99.example.com/wp-admin/, which is stored in wp_99 tables. Before the page can load, WP Stateless performs selects for 'sm_hashify_file_name', 'sm_custom_domain', 'sm_delete_remote', 'sm_cache_control', 'sm_key_json', 'sm_root_dir', 'sm_bucket', 'sm_on_fly', and 'sm_body_rewrite_types' for all 98 other blog IDs. In total, WP Stateless makes **882 unnecessary database queries** to load a single admin page!

Can you look into this and reduce the number of database queries?

**Comment by tobsch** [comment]
Related: https://github.com/wpCloud/wp-stateless/issues/178

**Comment by ahmed-sigmalux** [comment]
Thanks for directing me to your related ticket.

**Comment by ewsopp** [comment]
@ahmed-sigmalux Hello - are you still experiencing slowness? or can we close this issue?

**Comment by ahmed-sigmalux** [comment]
I've reduced the number of DB calls by defining constants in my wp-config.php.
