### ISSUE TITLE
Constant to network disable organizing media uploads?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [udx/wp-stateless#179]
Does such a constant exist? If so, what is it?

**Comment by ahmed-sigmalux** [comment]
?

**Comment by alimuzzaman** [comment]
Hello @ahmed-sigmalux 
`Organization` is a WordPress settings found in _Settings_ >> _Media_.
We just change that setting of WordPress.

![image](https://user-images.githubusercontent.com/6744156/43166395-48a6999a-8fb8-11e8-9bb4-05587652db3c.png)
