### ISSUE TITLE
Cloud Functions to Compress Images

### ISSUE THREAD

**Issue by djedlajn** [udx/wp-stateless#180]
First of all thanks for such a great plugin that is free.

I was wondering since It is not clear if the synchronization between local server and bucket actually optimizes the pictures, if there is a way to hook up cloud functions to trigger on upload. I know that it can be done manually and I am probably going to do that my self but having option to do that from plugin would make it killer feature.

I will dig bit more into the code of the plugin to get familiar with it, meanwhile I would appreciate if someone was to clarify if the images are being compressed while syncing. 

Best regards,
Uros

**Comment by antonkorotkov** [comment]
@ukaric The answer for now is no. We were thinking about this feature and probably will add it some day... =)

**Comment by djedlajn** [comment]
@antonkorotkov Thanks good to know.
