### ISSUE TITLE
WebP format support ?

### ISSUE THREAD

**Issue by djedlajn** [udx/wp-stateless#181]
Hi,

Even tho I added webp to supported field  it does not seem to care about that as It does not pull webp images to the bucket.

Is webp supported and if it is how do I make use of it. Or do I have to manually transfer all webp to bucket from the server ?

Thanks,
Uros

**Comment by alimuzzaman** [comment]
`WebP` isn't supported by WordPress.
`Supported File Types` field is only for `File URL Replacement`.

**Comment by alimuzzaman** [comment]
@ukaric Please use third party plugin to upload WebP image.

**Comment by dukuo** [comment]
@alimuzzaman Sorry to revive an old issue, but is there any support for [WebP Express](https://wordpress.org/plugins/webp-express/) ?

**Comment by brenovieira** [comment]
> @alimuzzaman Sorry to revive an old issue, but is there any support for [WebP Express](https://wordpress.org/plugins/webp-express/) ?

I'm trying to achieve the same goal.. That would be super useful..
As I'm a developer, if anyone can give me some direction, I'd try to make this work :)

**Comment by JuanxCursed** [comment]
+1 I'm trying the same thing. 
Since the file is served (or even converted) to WebP, the plugin should upload the webp file on storage as well

**Comment by JuanxCursed** [comment]
+1
