### ISSUE TITLE
add new "Compatibility" tab to settings area

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#182]
I would like this tab to list a title, description, and an enable/disable control for each compatibility we add.

Each compatibility needs to have its own separate file and all compatibilities should be stored together in a shared folder. Each compatibility file should also have something at the top that allows the file to describe the title and description (similar to a wordpress plugin file).

**Comment by alimuzzaman** [comment]
Existing compatibility:

- [x] Dynamic Image Support

- [x] ACF image crop addon.

- [x] EDD Download Method

**Comment by alimuzzaman** [comment]
@ewsopp Can you confirm the existing compatibility?

**Comment by alimuzzaman** [comment]
@ewsopp Added the compatibility tab in the settings page. Can you do a quick review of the implementation?

**Comment by ewsopp** [comment]
For the interface, let's follow a format similar to the SiteOrigin settings panel. See my screenshot and markup below.

![image](https://user-images.githubusercontent.com/5578537/35598152-ad6d8c92-05ef-11e8-8ab0-0977f7e61502.png)

**Comment by ewsopp** [comment]
- [x] Move the "Dynamic Image Support" option from the "Settings" tab to the new "Compatibility" tab.

**Comment by alimuzzaman** [comment]
@ewsopp Should I hide **Easy Digital Downloads** compatibility from compatibility tab if the Easy Digital Downloads plugin isn't enabled?

![image](https://user-images.githubusercontent.com/6744156/36635966-c3878f8a-19e7-11e8-931d-4264a22c0697.png)
