### ISSUE TITLE
Specify custom crop coordinates via query param in URL

### ISSUE THREAD

**Issue by kjbenk** [udx/wp-stateless#183]
This is more of a feature request than a bug, but I was wondering if WP Stateless could handle, or support, cropping an image on the fly via crop coordinates passed as a query param in the image URL?  So you would make a request to get a custom image crop like this `http://example.com/wp-uploads/2018/01/image.png?crop=0-0-150-150`.

You can see an example of this being used in the [WPCOM Thumbnail Editor plugin](https://github.com/Automattic/wpcom-thumbnail-editor) when Jetpack photon is active.

Here is a specific link to how the coordinates are passed as a query param - https://github.com/Automattic/wpcom-thumbnail-editor/blob/master/wpcom-thumbnail-editor.php#L760-L774.

Thanks for your time :)

**Comment by alimuzzaman** [comment]
Closing the issue as this is out of the scope of our plugin.
