### ISSUE TITLE
Google security issue

### ISSUE THREAD

**Issue by FutureMedia** [udx/wp-stateless#186]
I received an e-mail from Google stating the WP-Stateless service has excessive access rights to my account and invited me to remove them which I did.

**Comment by ewsopp** [comment]
That should be fine. It's only needed during the initial setup using the setup assistant.

**Comment by ewsopp** [comment]
We've submitted an application to Google to get this fixed.

> You will hear back from us between 1 and 2 business days. Generally, the approval process takes between 3 and 7 business days, but the approval time may vary depending on the initial completeness of the application, and how quickly you respond to any additional information needed.
