### ISSUE TITLE
Cropped image sizes are not synced/tranferred (Dynamic Image Support)

### ISSUE THREAD

**Issue by DESIGNMENOW** [udx/wp-stateless#187]
Hey Dev Team,

first things first: great plugin, integration and authentication work like a charm.

There is one thing that does not seem to work as expected.
I am running Wordpress MU 4.9.2 with WP Stateless 2.1.1
In addition the following plugin is installed:
https://wordpress.org/plugins/crop-thumbnails/
I have tried several other cropping tools. Result is the same allover.
The cropping shows no effect at all. There is no cropped image size uploaded/synced to GCS.

The following option is enabled network-wide.
![grafik](https://user-images.githubusercontent.com/25547046/35688304-2b2b4b6a-0771-11e8-87a5-4bd436e16996.png)

Right after clicking the button "Artikelbild zuschneiden" (Crop image), the cropped image should be available. Instead, the preview refreshes without any alteration.
![grafik](https://user-images.githubusercontent.com/25547046/35688222-f3981a98-0770-11e8-9409-1ff995c61322.png)
Cropping only works if Stateless stays disabled. Any other mode shows the results.

The Wordpress-own image edit function (Media->Select image->Edit) works. After cropping the image it seems to be uploaded to GCS. But this editor alters the original file and does not give access to change the "viewport" of the given image sizes.

Any thoughts on this? 
Thank you very much. Let me know if I can help.
Appreciate. Cheerio

**Comment by antonkorotkov** [comment]
Hey @DESIGNMENOW 

Sorry for the late response.

I'm going to investigate your issue. Do you still have problems with it? I know it must be late but maybe you have something to add. Thanks.

**Comment by antonkorotkov** [comment]
@DESIGNMENOW I just tested both plugins in terms of compatibility and I was able to crop the image using Crop-Thumbnails plugin.

In the `CDN` mode, the cropped images have been resized and saved both on the local server and GCS. The only thing I noticed is that images on GCS are cached in correspondence to the Cache-Control setting, that you can adjust on the WP-Settings page. So, this could be the reason why you did not see the result of cropping the image instantly. 

So, there are some possible reasons:
 - both plugins have evolved and things started to work by itself (try it with 2.3.2 at least);
 - it was a Cache-Control issue;
 - there was a conflict with some third plugin.

I'll close this issue for now but feel free to open a new issue if you still think it does not work. Thanks.
