### ISSUE TITLE
PHP Warning:  array_merge()

### ISSUE THREAD

**Issue by ahmed-sigmalux** [udx/wp-stateless#189]
I'm seeing this error message sporadically in my debug.log:

`PHP Warning:  array_merge(): Argument #2 is not an array in /var/www/wordpress/plugins/wp-stateless/lib/Google/src/Google/Client.php on line 133`

**Comment by alimuzzaman** [comment]
@ahmed-sigmalux This line is only called when you save the settings. I am not sure how the warning is happening.

**Comment by ahmed-sigmalux** [comment]
The error shows up sporadically when I run cron via wp-cli.

**Comment by antonkorotkov** [comment]
@alimuzzaman were you able to replicate this issue via wp-cli somehow?

**Comment by alimuzzaman** [comment]
@antonkorotkov No I wasn't able to replicate.

**Comment by ahmed-sigmalux** [comment]
I'm not seeing this error anymore.
