### ISSUE TITLE
record errors and add ability to retry them at a later point.

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#19]
- [x] Make a log of all the files that failed to regenerate, upload to GCS, or any other error that prevented a success.
- [x] Add ability to run a sync for just those failed files.
- [x] If they continue to fail, keep them in the log so that they can be retried at a later point.

![image](https://cloud.githubusercontent.com/assets/5578537/13606260/6598efa4-e519-11e5-809e-35c42437ddd2.png)

**Comment by antonkorotkov** [comment]
https://github.com/wpCloud/wp-stateless/releases/tag/1.7.2

![3e5b82f881](https://cloud.githubusercontent.com/assets/2276882/13642634/f9e6c49e-e625-11e5-8398-a24c05e38bca.jpg)
