### ISSUE TITLE
Extra space in converted URLs

### ISSUE THREAD

**Issue by tomtoday** [udx/wp-stateless#193]
I noticed that the code here:
https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-bootstrap.php#L622

Introduces a space into a URL that is converted using the `convert_to_gs_link()` method. This breaks links processed in this way.

**Comment by ewsopp** [comment]
@tomtoday thanks for reporting. Going into the next release v2.1.3. Hoping to get it out today.
