### ISSUE TITLE
WP-Stateless plugin JSON error while regenerating and syncing with GC

### ISSUE THREAD

**Issue by bingollu** [udx/wp-stateless#195]
Error occures when GC sync is being triggered, either from Dashboard or Plugin itself. No error log, audit, messages, wp-debug log having an entry.

Only catcheable errors are :
 <ul>
<li>Dashboard-&gt;Media-&gt;Stateless Settings-&gt;Sync Tab-&gt;Run
    generates : "Status: Error appeared"</li>
<li>Dashboard-&gt;Media-&gt;Library-&gt;List mode-&gt;Regenerate and Sync with GCS
    generates : "SyntaxError: JSON Parse error: Unrecognized token '&lt;'. Check your server configuration."
</ul>

Screenshots :

<a href="https://app.box.com/s/m1dpxvp5thwv8go0tg55ahb8fxspnmdb">Regenerate and sync GC</a>

<a href="https://app.box.com/s/95fnq8m3ksi7lo2x9rhfmkrque0optcj">Sync - Run</a>

**Comment by ewsopp** [comment]
adding screenshots here just in case those links die.

"Regenerate and sync GC"

![1](https://user-images.githubusercontent.com/5578537/36277236-52f6f3e0-125e-11e8-92e3-eb201b219d1b.png)

"Sync - Run"

![2](https://user-images.githubusercontent.com/5578537/36277245-5a65c6ec-125e-11e8-9574-cb5b69eb90b1.png)

**Comment by ewsopp** [comment]
@bingollu did you use the Setup Assistant or the Manual Setup to do the initial setup of WP-Stateless?

**Comment by bingollu** [comment]
Yes, I have acknowledged the setup and followed the procedure well since we have other WP sites running perfectly. This particular one was also, but for some reason I can not find the error. Is it not in the logs, debug or anywhere else. Just a died! message.


Burak Bingollu
Developer / IT
(631) 644-4003

**Comment by bingollu** [comment]
Found the error. An entry outputting space in the functions.php was causing the order of the rendering the code.
