### ISSUE TITLE
Gravity Forms File Upload Field

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#2]
Gravity Forms has an advanced field for uploading files as the user fills out a form on the frontend. The functionality appears to work, but when I try to access the file from the notification email the link is broken.

For my test, this was the URL given to me by the notification email to access the file:
`https://storage.googleapis.com/media.discodonniepresents.com/gravity_forms/6-e2c3e2afe00dd2051a2a351997e171d9/2015/06/95715596-teaser..jpg`

**Comment by ewsopp** [comment]
I think it might be related to https://github.com/wpCloud/wp-stateless/issues/3

**Comment by antonkorotkov** [comment]
Should be working now with new option 'Upload on-fly generated (by third-party scripts) images to GCS.'

**Comment by ewsopp** [comment]
Can we please actually test these things before closing the issue?

This does not work. I just tested it.
- Test Entry https://www.discodonniepresents.com/wp-admin/admin.php?page=gf_entries&view=entry&id=6&lid=9291&dir=DESC&filter&paged=1&pos=0&field_id&operator
- Media Settings: https://www.discodonniepresents.com/wp-admin/options-media.php
- Preview Page with Form: https://www.discodonniepresents.com/wp-admin/post.php?post=96713&action=edit
- File URL for test form submission with file upload https://www.discodonniepresents.com/files/gravity_forms/6-e2c3e2afe00dd2051a2a351997e171d9/2016/02/01eb0a07-test..pdf

**Comment by antonkorotkov** [comment]
I've just tested and realized that this issues is not connected to Stateless Media plugin at all. For some reason GF tries to upload files to some dir name 'files/...'. Not sure if it is custom thing specific to DDP. But anyway, you can't find that file because it was not actually created. I would call it 'DDP + Gravity Forms conflict'.

**Comment by ewsopp** [comment]
I submitted a support request with Gravity Forms to see if it is possible to change the default storage location for uploaded files.

**Comment by ewsopp** [comment]
It looks like we would need to create a Gravity Forms add-on that would make it compatible with stateless media.

useful references
https://www.gravityhelp.com/documentation/article/add-on-framework/
https://www.gravityhelp.com/documentation/article/gform_upload_path/

**Comment by ewsopp** [comment]
title: `Gravity Forms`
description: `Ensures compatibility with the File Upload field of the Gravity Forms plugin.`
constant: `WP_STATELESS_COMPATIBILITY_GF`

**Comment by ewsopp** [comment]
@alimuzzaman does this also include support for the Post Image field? This looks like an image upload field.

**Comment by alimuzzaman** [comment]
@ewsopp Yes it's include support for Post Image field.

**Comment by ewsopp** [comment]
@alimuzzaman I tweaked the description to mention the post image field.

title: `Gravity Forms`
description: `Enables support for these Gravity Forms features: file upload field, post image field.`
constant: `WP_STATELESS_COMPATIBILITY_GF`

**Comment by ewsopp** [comment]
@alimuzzaman there is a "Custom Field" field that allows you to configure it as a _File Upload_ field type. Can you test this field as well?

![image](https://user-images.githubusercontent.com/5578537/38224790-97dc647e-36bf-11e8-80d8-4f893cedfa2c.png)

**Comment by alimuzzaman** [comment]
@ewsopp Custom Field File Upload works.

**Comment by ewsopp** [comment]
Ok great. I revised the compatibility description to mention this fact.

title: `Gravity Forms`
description: `Enables support for these Gravity Forms features: file upload field, post image field, custom file upload field type.`
constant: `WP_STATELESS_COMPATIBILITY_GF`

**Comment by alimuzzaman** [comment]
@ewsopp Done.
