### ISSUE TITLE
Test Compatibility of Stateless with Image compression plugins

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#202]
- [x] [Smush Image Compression and Optimization](https://wordpress.org/plugins/wp-smushit/) [ Problem] WP Smush
- [x] [EWWW Image Optimizer](https://wordpress.org/plugins/ewww-image-optimizer/) 600K [ Working ]
- [x] [Compress JPEG & PNG images](https://wordpress.org/plugins/tiny-compress-images/) 100K [ Working ]  TinyPNG
- [x] [Imagify Image Optimizer](https://wordpress.org/plugins/imagify/) 100K [ Working]
- [x] [ShortPixel Image Optimizer](https://wordpress.org/plugins/shortpixel-image-optimiser/) 60K [ Working]
- [x] [Optimus – WordPress Image Optimizer](https://wordpress.org/plugins/optimus/) 40K [ Working ]

**Comment by ewsopp** [comment]
- [ ] TinyPNG https://wordpress.org/plugins/tiny-compress-images/
