### ISSUE TITLE
Plugin Conflict with ACF Image Crop

### ISSUE THREAD

**Issue by JessBoctor** [udx/wp-stateless#203]
Hey everyone!

I have an interesting problem, after a recent update, whenever I run [ACF Image Crop ](https://github.com/andersthorborg/ACF-Image-Crop) together with WP Stateless, it triggers a fatal error when an image is cropped. Here is the error:

PHP Fatal error:  Call to undefined method WP_Error::set_quality() in /home/montere7/staging/dashboard/wp-content/plugins/acf-image-crop-add-on/acf-image-crop-v5.php on line 528

I found [this Issue](https://github.com/andersthorborg/ACF-Image-Crop/issues/58) on the ACF Image Crop repo which said the issue was because the GD or Imagick library wasn't loading. I checked with my hosting company to make sure both were installed and loading, but I was still getting the same error. Interestingly enough, I don't have this issue on my local version of the site which is built using Desktop Server, only on the staging site on my actual server. Also, when I deactivate WP Stateless on the staging site, ACF Image Crop works without a problem.

Any ideas/tips on how to resolve this?

Thanks again for a great plugin.

**Comment by JessBoctor** [comment]
Never mind!! Apparently I need to pay more attention to the change logs. 

I found the compatibility settings in the backend and activated the ACF Image Crop setting. Everything is working fine now. 

Thanks again, you guys rock!

**Comment by ewsopp** [comment]
@JessBoctor glad it resolved your issue. Thanks for the support!
