### ISSUE TITLE
Options for Dynamic Bucket selection?

### ISSUE THREAD

**Issue by wkw** [udx/wp-stateless#205]
Here's our situation: We need to split uploads into three different buckets:
1. images
2. Copyrighted streams
3. Copyright-free streams.

I've been through the source code fairly extensively sussing out possible filter points but still don't have a clear roadmap for how I might accomplish this (and am getting close to forking and customizing, but would like to avoid that).

On initial upload, I'd like to check media mime type and initially route between an images Bucket and a default Streams bucket.

Once a stream is uploaded, a user can edit a media item where we have a custom field indicating it does/does-not contain copyrighted songs in the stream. At this point I would possibly need to move the stream to a different bucket. (we will default everything initially to the copyright-protected streams bucket since that's our business rule, but upon changing the custom field flag to indicate it's (C)-free, I'd need to copy to other bucket and delete from bucket it was in, which I think I can do using Stateless' google storage client.

And course there's the issue of storing correct meta info for the attachments as the bucket location changes.

So, any suggestions as to whether this is doable, and some pointers into the classes for effecting the overrides?
Appreciate any feedback. Thanks!

**Comment by wkw** [comment]
Two days and no response, so I'll close this soon. I know it's something of a fringe use case.

At this point I'm still trying to avoid forking the project. Looking at tapping into the `wp_update_attachment_metadata` filter after Stateless does it's thing. I think I can move the asset around at that point, and delete it from the default bucket as needed.

**Comment by alimuzzaman** [comment]
@wkw Hi, sorry for the late replay.  So far I think it can be done in one bucket. 
You can control each object whether it's private or public. Here is the [google documentation](https://cloud.google.com/storage/docs/access-control/making-data-public). To access private item you need to check [this document](https://cloud.google.com/storage/docs/access-control/create-signed-urls-program).
If you think you can make a solution then go ahead or if you need action/filter somewhere, send pull request.

**Comment by alimuzzaman** [comment]
This function is responsible to upload all the image [GS_Client->add_media()](https://github.com/wpCloud/wp-stateless/blob/develop-alim/lib/classes/class-gs-client.php#L171).

Step 1: I think you will need a filter [here](https://github.com/wpCloud/wp-stateless/blob/develop-alim/lib/classes/class-gs-client.php#L230) to override the default behavior.

Step 2: When your custom field update you can [do this](https://github.com/wpCloud/wp-stateless/blob/develop-alim/lib/classes/class-gs-client.php#L230-L234).

**Comment by wkw** [comment]
Thanks @alimuzzaman. I'd welcome keeping it all in one bucket, but boss man wants separate buckets, mostly for organization I think.  I do like your idea of a PR if I can find some place(s) to add new stateless filters. I'm going to leave this open for a few more days in case others have any suggestions, but thereafter you can close it or I will. Thank you!

**Comment by alimuzzaman** [comment]
@wkw Any luck finding solution?

**Comment by wkw** [comment]
I got pulled away from this task for time being, but the path I'm still attempting (short of a PR) is what I mentioned here: https://github.com/wpCloud/wp-stateless/issues/205#issuecomment-369475291

I'll reopen if I have more to contribute on this subject. Thanks!
