### ISSUE TITLE
Imagify Image Optimizer sync fix

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#206]
Related to #202

**Comment by alimuzzaman** [comment]
Don't work on localhost.

**Comment by alimuzzaman** [comment]
Imagfy Now also work on Stateless Mode.

**Comment by ewsopp** [comment]
@alimuzzaman are we compatible with these Imagify features?

- [x] bulk optimizer.
- [x] resize larger images
- [x] optimization levels: normal, agressive, ultra
- [x] auto-optimize images on upload. 
- [x] backup original images [ [Backup image not stored in GCS](https://github.com/wpCloud/wp-stateless/commit/8b06695758ed80e027cc7c339a30b41bb50846f7#diff-810d2d3f3aeae303e527c22d230190bdR133) ]
- [x] restore original
- [x] Do these features work across the different modes? Backup, CDN, Stateless

**Comment by alimuzzaman** [comment]
Non image files not getting sync. [ Fixed ]

**Comment by ewsopp** [comment]
Compatibility Meta

title: `Imagify Image Optimizer`
description: `Enables support for these Imagify Image Optimizer features: auto-optimize images on upload, bulk optimizer, resize larger images, optimization levels (normal, aggressive, ultra).`
constant: `WP_STATELESS_COMPATIBILITY_IMAGIFY`

**Comment by ewsopp** [comment]
@alimuzzaman from your notes, I understand that we do not support the "backup original images" and "restore original" features. Why?

**Comment by alimuzzaman** [comment]
Fixed the Restore original. 
Do we need to move the backup image to GCS?
It's only make sense to move to GCS if mode is Stateless.
It is possible to do this for Imagify.

**Comment by ewsopp** [comment]
The original image should be stored according to the current wp-stateless mode.

- Backup: stored both on local and GCS.
- CDN: stored both on local and GCS.
- Stateless: stored on GCS.

Is it possible to have the original image stored according to the current wp-stateless mode?

**Comment by alimuzzaman** [comment]
@ewsopp It is possible to store backup image in GCS but in Stateless mode the local image is deleted. Because of no local image is found the **Re-optimize** and **Restore from backup** feature is disabled.

**Comment by Screenfeed** [comment]
Hello, I'm Grégory, lead developer of Imagify's plugin.
First, thanks for showing interest in our plugin :)
I took a quick look at the code and noticed few things (but only small details though). Do you want my feedback here or do you prefer me to open a new ticket?
Thanks.

**Comment by Mashenka** [comment]
Hello @Screenfeed Feel free to open new issue ;)

**Comment by Screenfeed** [comment]
OK, will do, thanks.
