### ISSUE TITLE
ShortPixel Image Optimizer sync fix

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#207]
Related to #202

**Comment by alimuzzaman** [comment]
Automatic optimization don't work on localhost.

**Comment by alimuzzaman** [comment]
Shortpixel image optimization is now working. Enable it via compatibility tab.
Images will be sync once Shortpixel finished  the optimization.

**Comment by ewsopp** [comment]
@alimuzzaman are we compatible with these ShortPixel features?

- [x] bulk image optimization 
- [x] compression type: lossy, lossless
- [x] thumbnail optimization
- [x] image backup [ Backup image not stored in GCS ]
- [x] resize large images
- [x] optimize media on upload
- [x] re-optimize
- [x] restore backup 
- [x] Do these features work across the different modes? Backup, CDN, Stateless [ Stateless mode have problem ]

**Comment by alimuzzaman** [comment]
Non image files not getting sync. [ Fixed ]

**Comment by alimuzzaman** [comment]
@antonkorotkov 
Shortpixel uses schedule queue to optimize image. After optimization it fire `shortpixel_image_optimised` action. 
I have hooked into this action to sync with GCS and removed **original stateless hook** for sync `add_filter( 'wp_update_attachment_metadata', array( 'wpCloud\StatelessMedia\Utility', 'add_media' ), 999, 2 );`.

But the problem is `shortpixel_image_optimised`  hook only work for image only and other type of attachment isn't get sync.

If I don't remove the **original stateless hook** in stateless mood the local file get removed after sync with GCS. And Shortpixel can't find local file.
https://github.com/wpCloud/wp-stateless/blob/develop-alim/lib/classes/compatibility/shortpixel.php#L24

**Comment by antonkorotkov** [comment]
@alimuzzaman Can you check if what I did here https://github.com/wpCloud/wp-stateless/commit/ef8167ffe08ea88fbf9c61c32026f7740722d230 works as expected? And if it is good for you to continue with this issue?

**Comment by alimuzzaman** [comment]
@antonkorotkov It's working fine. Now I will try to implement this on Imagify #206.

**Comment by alimuzzaman** [comment]
@antonkorotkov Do you think it is possible to hook into [handleRestoreBackup](https://github.com/UsabilityDynamics/sandbox.uds.io/blob/develop-alim/wp-content/plugins/shortpixel-image-optimiser/class/wp-short-pixel.php#L1577)?

https://github.com/wpCloud/wp-stateless/blob/develop-alim/lib/classes/compatibility/shortpixel.php#L25

**Comment by antonkorotkov** [comment]
@alimuzzaman I think so. Try using the same filter `get_attached_file` with determination that it is called from `doRestore` function in `wp-short-pixel.php` file.

This doesn't work? `add_action('admin_action_shortpixel_restore_backup', array($this, 'handleRestoreBackup'), 11);`

**Comment by alimuzzaman** [comment]
@antonkorotkov Got it.
`[Fixed]` Only problem remaining is **Optimized image** preview in **bulk image optimization**. 
![image](https://user-images.githubusercontent.com/6744156/38214846-b3e8a3f8-36e7-11e8-897c-e3ef66a9d8fb.png)

**Comment by ewsopp** [comment]
@alimuzzaman you mentioned there is a problem with stateless mode at https://github.com/wpCloud/wp-stateless/issues/207#issuecomment-374807717

Has this been fixed?

**Comment by alimuzzaman** [comment]
@ewsopp Yes

**Comment by ewsopp** [comment]
@alimuzzaman ok great. Is there anything not working with ShortPixel compatibility?

**Comment by alimuzzaman** [comment]
Backup image not stored in GCS.

**Comment by ewsopp** [comment]
The backup image should be stored according to the current wp-stateless mode.

- Backup: stored both on local and GCS.
- CDN: stored both on local and GCS.
- Stateless: stored on GCS.

Is it possible to have the backup image stored according to the current wp-stateless mode?

**Comment by alimuzzaman** [comment]
@ewsopp Working on it.

**Comment by alimuzzaman** [comment]
Done, except stateless mode.
Backup file sync won't work in stateless mode.
