### ISSUE TITLE
save_network_settings

### ISSUE THREAD

**Issue by mjezegou** [udx/wp-stateless#208]
When i go in wp-admin/network/settings.php with back office and then i save setting, this message appears : 
'wpCloud\StatelessMedia\Settings' does not have a method 'save_network_settings' 

I think, it is  on wp-stateless/lib/classes/class-settings.php => the method save_network_settings is not exist in this class !!

**Comment by alimuzzaman** [comment]
@mjezegou Thanks for reporting. We will fix this in next release.
In the mean time if this causing trouble you can just delete this line [class-settings.php#L77](https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-settings.php#L77).
This function isn't required.
