### ISSUE TITLE
[Question] So...how much are you guys spending?

### ISSUE THREAD

**Issue by RetroGameTalk** [udx/wp-stateless#209]
I wonder, how does this compare to other CDN providers in terms of cost?
I'ts nearly impossible to find any straight answer like "$0.04 / GB" for example.
There's that google calculator with a billion options that requires 3 astronauts to understand it.
So.
Is there anyone who actually used this on a site and got billed already? How much are they charging you?

**Comment by ewsopp** [comment]
Hello @Salamander3 - you may want to ask your question over on our WordPress.org forum at https://wordpress.org/support/plugin/wp-stateless

GitHub is primarily focused on developer discussions around improving the plugin and organizing new releases.
