### ISSUE TITLE
when uploading an image, sometimes it uploads duplicates

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#21]
I have demonstrated this issue to Anton.

Occasionally when uploading an image, it will upload multiple times until it errors out (wordpress prints out _HTTP Error_). When visiting the media library after this, sometimes you will find two to six copies of the same file uploaded multiple times.

This has happened with or without extra options checked (upload on-fly generated, etc) in the media library setting.

**Comment by ewsopp** [comment]
I think this may be related to the number of thumbnails being generated. Try recreating 20 thumbnail sizes and uploading a set of large images (4,000px+).

**Comment by antonkorotkov** [comment]
I tested using DDP image sizes set and 20+ images over 4000px at a time. Test was successful but I test on local WP installation. 

I've noticed that processing of one image (uploading, resizing and pushing to GCS) takes about 2 minutes.  It means that `max_execution_time` on our servers must be greater than 2 minutes (as well as memory limit should be high enough). If it is less than 2 minutes HTTP Error may occur. Also it is not allowed to switch branches while uploading photos. That also may cause errors.

I'll do more tests, probably on local DDP installation. Maybe something is connected to DDP network...

**Comment by ewsopp** [comment]
Spoke with @andypotanin about this. Apparently our configuration has unlimited max_execution_time, so I'm not sure if that is the problem.

**Comment by mrmiroslav** [comment]
post_max_size / upload_max_filesize ?

**Comment by andypotanin** [comment]
Okay, here are the PHP-FPM settings for the Docker container where Eric's site is running:
- upload_max_filesize - 80m
- post_max_size - 80m
- max_execution_time - 30
- max_input_time - 60

So I was wrong in regards to not having a `max_execution_time` limit, but I'm pretty sure that wp-stateless overrides that.

I think that it's going to be impossible for us to work around server limitations, instead we should focus on the fault-tolerance of the JS logic - e.g. if something fails, it should retry it, or make a note of it.  So, @antonkorotkov just try to tune down your server settings low enough so you start seeing failures on large images, and then try to do add some JS logic to catch the failures - unless you can think of something better.

**Comment by antonkorotkov** [comment]
Ok - 
`upload_max_filesize - 80m`
`post_max_size - 80m`
do not make sense when wp-stateless is working. `max_input_time` also affects only when uploading an image (if WordPress was able to upload it - then 60 is enough)

The only left is `max_execution_time` which is now overridden with `-1` in wp-stateless. Not going to work on any setup since some may not allow overriding but for other cases we show corresponding `Internal Server Error` (we cannot say what actually failed but it shows error at least.)
