### ISSUE TITLE
Woo-Commerce addon compatibility 

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#210]
### WooCommerce + Printful compatibility 
reference https://wordpress.org/support/topic/woocommerce-372/
I seem to be having a problem with WooCommerce, all main Pictures aren’t showing up, but when I edit such item the pics are there. I have disabled the mode and it works. I’m using the Printful addon to add products created at the Printful website and it syncs the images to WordPress. I have also Sync your program and it seems to be syncing the images in the log.

### Woocommerce extra product options 
https://wordpress.org/support/topic/dynamic-image-support/#post-10424222
While using Woocommerce extra product options plugin for image uploads from frontend, I enabled the Dynamic Image Support in Compatibility section to upload the uploads to cloud storage, but the images are not uploaded to cloud storage instead uploaded inside the uploads directory. Is there any way to upload to cloud storage?

**Comment by alimuzzaman** [comment]
WooCommerce + Printful working fine. Nothing is wrong there.

**Comment by Mashenka** [comment]
@alimuzzaman there was a new comment from the user, he sent a zip of his woo plugin - https://wordpress.org/support/topic/dynamic-image-support/#post-10424222

**Comment by alimuzzaman** [comment]
Created separated issue for **Woocommerce extra product options**.
The new issue is #266
