### ISSUE TITLE
Modify storage path structure

### ISSUE THREAD

**Issue by Feleys** [udx/wp-stateless#212]
Hi,
I'm using multisite. Is it possible change path structure like WordPress's structure.

For example: 
WordPress: /(site-id)/(year)/(month)/file.jpg 

Top level folder will dynamically create site-id folder.

Thanks!

**Comment by ewsopp** [comment]
Are you using a shared bucket across the entire network? If so, seems like this idea has been raised before at https://github.com/wpCloud/wp-stateless/issues/149

**Comment by Feleys** [comment]
Yes, I shared bucket across the entire network.

Are you still working on it?

Thanks!

**Comment by ewsopp** [comment]
Not yet, but please share your interest in the original issue. I'm thinking we can bump the priority since others have requested it. Thanks
