### ISSUE TITLE
compatibility constants supported v2.1.5

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#213]
What are the current compatibility constants?

**Comment by alimuzzaman** [comment]
- `WP_STATELESS_COMPATIBILITY_ACFIC` **Advanced Custom Fields Image Crop Addon**
- `WP_STATELESS_MEDIA_ON_FLY` **Dynamic Image Support**
- `WP_STATELESS_COMPATIBILITY_EDD` **Easy Digital Downloads**
- `WP_STATELESS_COMPATIBILITY_GF` **Gravity Form File Upload**
- `WP_STATELESS_COMPATIBILITY_IMAGIFY` **Imagify**
- `WP_STATELESS_COMPATIBILITY_SHORTPIXEL` **ShortPixel Image Optimizer**
- `WP_STATELESS_COMPATIBILITY_SOCSS` **SiteOrigin CSS**
- `WP_STATELESS_COMPATIBILITY_WPB` **WPBakery Page Builder**

**Comment by ewsopp** [comment]
@alimuzzaman can you change `WP_STATELESS_COMPATIBILITY_SO_CSS` to `WP_STATELESS_COMPATIBILITY_SOCSS`? This way it is more in line with our naming scheme.

**Comment by alimuzzaman** [comment]
@ewsopp Done.
