### ISSUE TITLE
E_WARNING: Illegal string offset 'gs_bucket'

### ISSUE THREAD

**Issue by andypotanin** [udx/wp-stateless#215]
Keep seeing this warning come up in our New Relic logs. Site is using Houzez theme.

Extract of tracelog:
```
in wpCloud\StatelessMedia\Bootstrap::wp_get_attachment_metadata called at /var/www/wp-includes/class-wp-hook.php (286)
in WP_Hook::apply_filters called at /var/www/wp-includes/plugin.php (203)
in apply_filters called at /var/www/wp-includes/post.php (5067)
in wp_get_attachment_metadata called at /var/www/wp-includes/media.php (892)
in wp_get_attachment_image called at /var/www/wp-content/themes/houzez/property-details/lightbox.php (92)
```

On the front-end there is this usage:

```php
<?php echo wp_get_attachment_image( $img_id, 'houzez-imageSize1170_738' ); ?>
```
Site has `2.1.3` installed. 

In what situation would this happen?

**Comment by alimuzzaman** [comment]
@andypotanin `wpCloud\StatelessMedia\Bootstrap::wp_get_attachment_metadata($metadata, $attachment_id)`
Maybe the `$metadata` passed wasn't array.
I am thinking to implement **unit testing** to be sure.

**Comment by andypotanin** [comment]
@alimuzzaman Do you mean "unit" or "functional" and assurance testing? In other words, for your testing, would you need to have a WordPress site (with database, server, etc.) setup?

**Comment by andypotanin** [comment]
@alimuzzaman If you need full-suite "end-to-end" tests, than we could definitely get something setup. We actually have the infrastructure and workflow for this, and we did this on wp-property about a year ago, but it lacked having people put together the actual tests. 

* We used CircleCI to provision a testing environment, so on each commit tests would run. 
* We would run a Docker container from one of our images that provides a standard WordPress environment, then adding the currently being tested version of the plugin into the container, simulating a new install. 
* We created a separate repository that contains all the tests and test assets from wp-property.
* Then we had some wp-cli commands to in and add/remove data to populate the database, attempting to emulate usage. 
* Finally we would run `mocha` tests that would do some basic things like open up front-end pages.

That's where it ended, we never had the time to actually create some real tests and kept it up, but the workflow and process can be fairly quickly setup for wp-stateless, if that will help you.

**Comment by alimuzzaman** [comment]
@andypotanin It's sounds good, we should do this. I don't have experience in tests, what should I know to do this?

**Comment by andypotanin** [comment]
@alimuzzaman Can you put together a general description of the test you would like to put together?

**Comment by andypotanin** [comment]
@alimuzzaman Take a look at the wp-cli QC structure and language https://github.com/wp-cli/wp-cli/tree/master/features

**Comment by alimuzzaman** [comment]
@andypotanin I would like to have functional testing and simulate media upload and check if it gets sync properly in various situation.
If you think implementation is simple then we should do this.
I will need some time to gather what I want to do.
What I need to know to implement functional testing?

**Comment by alimuzzaman** [comment]
I am afraid that if same thing happen with Stateless as WP Property.
