### ISSUE TITLE
PDF preview not working in edit attachment page or in media library.

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#217]
And also not getting synced to GCS.
![image](https://user-images.githubusercontent.com/6744156/38166924-049fd334-354e-11e8-9a3d-d78fddbbca7a.png)

**Comment by davidcommarmond** [comment]
Hi,
I also can't sync existing PDFs to GCS. Getting a series of "Unknown failure reason." when trying to "Synchronize non-images files between Google Storage and local server"

Not sure if it's a related issue ?

![image](https://user-images.githubusercontent.com/34420248/43405134-312c9960-942a-11e8-89a8-cfe035c3c91e.png)
