### ISSUE TITLE
EDD Front-end Submission  Author Avatar not working

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#218]
https://docs.easydigitaldownloads.com/article/966-frontend-submissions-profile-form-editor

EDD Author Avatar not working in Stateless Mode.

Related WP.org issue https://wordpress.org/support/topic/wp-author-avatar-issues/

**Comment by yudiarnanda** [comment]
Also, EDD Front-end Submission forms not working with WP Stateless. Like File Upload, Price & Files URL, and Avatar.

**Comment by alimuzzaman** [comment]
@yudiarnanda 
I have added fix for the **_File Upload_** field.
And the **Price and Files** and **Featured Image** works fine out of the box.

You can download the updated version [from here](https://github.com/wpCloud/wp-stateless/tree/b68e88c5dba24c1d3a4792abc1a6cc23bd3b9186) for testing.

**Comment by yudiarnanda** [comment]
@alimuzzaman Thanks for the updates.  The zip file is uploaded to GCP. But the URL file from GCP does not appear in the Download Files form in the back-end.

**Comment by alimuzzaman** [comment]
Sorry @yudiarnanda,
Forgot to consider **Bucket Folder**. Probably because you have **Bucket Folder** set that's why it didn't worked.

I have uploaded a fix, you can [download from here](https://github.com/wpCloud/wp-stateless/tree/eec1b2e9d121dec953cac61a23d3aacafd0a414b).
Please let us know if it works.
Thanks

**Comment by yudiarnanda** [comment]
@alimuzzaman  Work well now. 

Another question, is there no option to store files directly to GCS? So the file is not stored locally.
This is only to prevent load on the server when there are large files.

Thanks

**Comment by alimuzzaman** [comment]
@yudiarnanda yes there is.
Use Stateless mode. It will remove the local copy from server after upload compete to GCS.

**Comment by yudiarnanda** [comment]
Hello @alimuzzaman 

Sorry for late reply. I've tried it tomorrow, but I still get the error, "Files must be uploaded through the upload form". May I know what happens?
