### ISSUE TITLE
improve admin notice design

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#219]
Follow the design used by Jetpack. I saw this on the "Updates" screen without the Jetpack Backup feature enabled.

![image](https://user-images.githubusercontent.com/5578537/38337574-dedc70ec-3833-11e8-8aac-baef1d98403b.png)

- [ ] For the left border, use the #FC5922 color.
- [ ] Use our plugin icon.
- [ ] Title and description.
- [ ] Button
- [ ] Dimiss

**Comment by alimuzzaman** [comment]
@ewsopp Which logo should I use?

**Comment by ewsopp** [comment]
This one would be fine...

![image](https://user-images.githubusercontent.com/5578537/41432473-4242845e-6fe4-11e8-8299-06b76d898f7c.png)

**Comment by alimuzzaman** [comment]
We have three type of notice now
1. errors #dc3232 (.error)
2. messages #46b450 (.updated)
3. warnings #46b450 (.updated)

**Comment by alimuzzaman** [comment]
This is how it's looks now.
![image](https://user-images.githubusercontent.com/6744156/41688661-d95f0504-750e-11e8-905a-4df3d22c9729.png)

**Comment by ewsopp** [comment]
- [ ] white space around the icon should be identical. 
- [ ] title should be bold.
- [ ] spacing around text should be uniform.
- [ ] description text should not be bold. 
- [ ] button and dismiss control should be vertically centered
- [ ] notice should be placed at the very top, above the page title.

**Comment by alimuzzaman** [comment]
> notice should be placed at the very top, above the page title.

WordPress move all error message after title on page load using js.

> white space around the icon should be identical.

How much space should I use?

**Comment by alimuzzaman** [comment]
@ewsopp 
![image](https://user-images.githubusercontent.com/6744156/42135226-aeb5a016-7d69-11e8-8f3f-4184282a86d9.png)
![image](https://user-images.githubusercontent.com/6744156/42135216-8d66e082-7d69-11e8-9dd5-ac7d4b749bf5.png)
![image](https://user-images.githubusercontent.com/6744156/42135217-94835cec-7d69-11e8-992d-e94912ffc277.png)

**Comment by ewsopp** [comment]
@alimuzzaman this looks 100% better.
