### ISSUE TITLE
add option to scan for broken/missing thumbnails and regenerate/sync them

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#22]
Many times thumbnails are incorrectly generated or there is a failure to sync a thumbnail correctly. Create an option to scan for these broken thumbnails, regenerate them, and then sync them to Google.

This would be an option enabled for the new `Regenerate Image Thumbnails` tool. Reference https://github.com/wpCloud/wp-stateless/issues/38

**Comment by ahmed-sigmalux** [comment]
Any progress on this feature?

**Comment by ewsopp** [comment]
This is being developed separately as an extension. Closing this issue.
