### ISSUE TITLE
compatibility file renaming

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#220]
The file names are a bit misleading. Lets clean it up a bit...

- [x] `gravity-form.php` should be `gravity-forms.php`.
- [x] `edd-download-method.php` should be `easy-digital-downloads.php`
- [x] `so-widget-css.php` should be `siteorigin-css.php`
- [x] `wpbakery-single-image.php` should be `wpbakery-page-builder.php`

**Comment by alimuzzaman** [comment]
@ewsopp FYI `siteorigin-css.php` is for  **SiteOrigin Widgets Bundle** addon.

**Comment by ewsopp** [comment]
@alimuzzaman it isn't for this one? https://wordpress.org/plugins/so-css/

**Comment by alimuzzaman** [comment]
No I did for this one: https://wordpress.org/plugins/so-widgets-bundle/

**Comment by ewsopp** [comment]
Ok - what compatibilities did you add for this plugin?

**Comment by alimuzzaman** [comment]
I am confused! 
It's generate CSS file in `siteorigin-widgets` dir, where SO CSS generate file in `/so-css/` dir.

**Comment by alimuzzaman** [comment]
It would be easy to add support for SO CSS addon.
