### ISSUE TITLE
add compatibility for SiteOrigin CSS plugin

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#221]
https://wordpress.org/plugins/so-css/

**Comment by ewsopp** [comment]
Compatibility description meta.

title: `SiteOrigin CSS`
description: `Enabled support for CSS files generated by SiteOrigin CSS.`
constant: `WP_STATELESS_COMPATIBILITY_SOCSS`

**Comment by alimuzzaman** [comment]
@ewsopp Done
