### ISSUE TITLE
Breaks Divi Builder Export

### ISSUE THREAD

**Issue by danyell-hubrix** [udx/wp-stateless#224]
Divi v3.0.106
Divi Builder Export (pops a modal allowing download of page content as JSON)
WP-Stateless v2.1.4

Activate plugin: Export produces empty file
Deactivate plugin: Export behaves correctly as expected

This happens in/on .../wp-admin/post.php (Page/Post edit) where WP-Stateless has no business intercepting anything (neither URL rewrite nor XHR nor Ajax)

P.S. I love this plugin and I love that someone is trying to support GCS as a CDN. Sadly this bug is a deal-breaker. Perhaps add an exclusion-list configuration parameter ("do nothing on these URPLs" sort of thing)?

**Comment by dchenk** [comment]
@danyell-hubrix is Divi trying to persist the file before allowing the data to be downloaded? If so, in what directory?

**Comment by alimuzzaman** [comment]
@danyell-hubrix @dchenk 
The problem was with our **Cache-Busting** feature.

**Comment by alimuzzaman** [comment]
You can get the fix from here.
https://github.com/wpCloud/wp-stateless/releases/tag/2.1.8-beta-3

**Comment by danyell-hubrix** [comment]
@alimuzzaman This is great, thank you! And gratz on your awesome progress in your current build cycle
