### ISSUE TITLE
WP-Stateless + WPML with per-domain languages

### ISSUE THREAD

**Issue by danyell-hubrix** [udx/wp-stateless#227]
Our setup (quite common for larger multilingual WordPress sites) is:

- WPML (latest)
- One domain per language: oursite.co for English, oursite.fr for French and so on.
- There is only 1 image fileset for **all** languages.

Running WP-Stateless 2.1.4, we see GCS CDN-URL rewriting occurring for our default-language site (img URIs properly rewritten to point to GCS bucket) but **not** for our 2nd-language site. To be clear, there is only _one_ WordPress installation and only one WP-Stateless plugin installed.

Is this a bug? An unsupported configuration? On the roadmap anywhere? Please tell us, we love your plugin but multilingual support is a must-have for us. We are prepared to help code the changes if necessary, or subsidize the effort.

**Comment by alimuzzaman** [comment]
@danyell-hubrix It's probably unsupported configuration. Is it multi site?

**Comment by danyell-hubrix** [comment]
No, it is _not_ multisite. Each domain-name maps to the same site (and WordPress installation) in a specific language.

**Comment by alimuzzaman** [comment]
@danyell-hubrix 
What url is used for 2nd-language site?
Is it the local one?

**Comment by danyell-hubrix** [comment]
As indicated in my original post april 13: we are using per-domain multilingual. website.co for English, website.fr for French. I do not know what you mean by "the local one."

**Comment by danyell-hubrix** [comment]
Please let me know what tests you want me to run, or what data I can provide, to help you out. I have a development environment with wp-stateless installed so I can install "experimental" or master-branch code there if you wish.

**Comment by alimuzzaman** [comment]
I am not clear exactly what is the problem.
You are getting GCS url in first domain.
What media url you get on your 2nd-language site?

What do you mean by **GCS CDN-URL rewriting**?
Do you mean rewrite existing site URL with GCS URL (File URL Replacement)?

**Comment by danyell-hubrix** [comment]
GCS: Google Cloud Storage
CDN: Content Delivery Network
URL: Uniform Resource Locator

YES we are getting GCS url in first domain.
In 2.1.4 we were not getting GCS url in 2nd domain.

It seems your 2.1.7 upgrade somehow fixed this.
We are now correctly getting GCS urls in pages served from _both_ language domains.

Thanks!
