### ISSUE TITLE
fatal error with php 5.4.45 on activation

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#228]
submitted via the .org forum at https://wordpress.org/support/topic/fatal-error-on-activation-155/

> I get a fatal error when I am trying to activate this plugin.

# host configuration

![jwblkx0](https://user-images.githubusercontent.com/5578537/38894838-679f7802-425c-11e8-8821-1e738629e4dd.png)

# plugin list

![movyykn](https://user-images.githubusercontent.com/5578537/38894855-73e2247a-425c-11e8-84ba-0f8f3ccc73f2.png)

**Comment by alimuzzaman** [comment]
Stateless require at least  PHP 5.5,
