### ISSUE TITLE
Whether images address will changed automatically when I stop using WP-Stateless?

### ISSUE THREAD

**Issue by huangyuyu003** [udx/wp-stateless#229]
HI There,
By now, I am using WP-Stateless in CDN mode for my website. I want to know if I stop this plugin, what the images UrlS will be in my webiste? Can they server from local storage and change the URLs automatically? I didn’t see an option to choose where to server the images. Besides, can this choice be switch just like a turn on/off switch which you can select it whenerver you want to?
Because I want to test the speed of my website, It looks like the google storage + CDN not make my website speeding or maybe I just not setting it correctly. So I just want to test it.
Thanks for help!

**Comment by alimuzzaman** [comment]
Stateless doesn’t change the url in database, it save extra metadata in database and rewrite the URL in runtime using filter.
So if you disable Stateless there is nothing to worry about. If you upload image when Stateless was disabled, you need to do  a manual sync from Sync tab from Media >> Stateless Settings.

**Comment by huangyuyu003** [comment]
@alimuzzaman thank you for your reply.
Sorry I mis-understand it. Infact I want my website to use local storage images instead of using Google cloud images. So is there possible to disable my google cloud storage? If I have only to delete those images from Goolge cloud storage, can those images automatically load from local storage in server? 
If they can't, that means I have to edit those pictures manually one by one, that's a lot of work to do.
SO if WP-state plugin has a select switch to control where those pictures server from will be quite great for me to control the whole thing.

**Comment by alimuzzaman** [comment]
1. If you want to use your local image URL: Use **Backup** mode. It will upload image to GCS but use local image.
2. Yes you can disable it. Use **Disable** mode, it will disable all functionality of Stateless.
3. No they won't load from local server automatically. You have to use **Disable** or **Backup** mode to use image from local server.
4. You can switch between CDN and Backup mode to switch from GCS to local server.

**Comment by huangyuyu003** [comment]
@alimuzzaman 
It works. thank you so much for you help. You are so kind and handsome man! Have a good day!
