### ISSUE TITLE
add option to regenerate/sync thumbnails from the media library

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#23]
Similar to the regenerate thumbnails plugin, we need an easy to regenerate and sync a single image from the media library. 

![image](https://cloud.githubusercontent.com/assets/5578537/14069533/64071c7e-f469-11e5-8b91-99305fd78e2a.png)

**Comment by antonkorotkov** [comment]
Done

**Comment by ewsopp** [comment]
How are you handling broken images? At the moment, it just says "Please wait..." forever.
- [x] Maybe check to see if the original is available before beginning the regenerate process. If available, proceed as planned. If not available, output "Local file missing. Cannot proceed." or something similar.
- [x] You can take it one step further. If the file is missing locally, check for the file on GCS. If the file exists in GCS, download it to local, and proceed as planned (regenerate/sync with the newly downloaded file).

![image](https://cloud.githubusercontent.com/assets/5578537/15880239/7e3afd7c-2cf9-11e6-893f-427320616fd4.png)

![image](https://cloud.githubusercontent.com/assets/5578537/15880258/964bd4e0-2cf9-11e6-90ce-f77b0f8295d3.png)

**Comment by antonkorotkov** [comment]
All you described is exactly how that works. The only thing I missed is proper exceptions handling. It is more user friendly now.

**Comment by ewsopp** [comment]
Not working. 

Tested https://www.discodonniepresents.com/wp-admin/post.php?post=155494&action=edit and the 400x225 thumbnail used at https://www.discodonniepresents.com/photo/2016-0501-dallas-sisuuptown remains broken.

![image](https://cloud.githubusercontent.com/assets/5578537/15974167/14ac3e7a-2f15-11e6-968a-3b59fafc5980.png)

**Comment by antonkorotkov** [comment]
I've checked that and found that image was created but for some reason it was not set as publicly accessible. I'm going to look into the plugin and make it check access rights and not only that image exists.

To fix the image I just deleted 400-225 size image from GCS and clicked Regenerate again.

**Comment by antonkorotkov** [comment]
That is fixed.

**Comment by ewsopp** [comment]
Yep - works great now.
