### ISSUE TITLE
wpforms - add new experience is lost when wp-stateless is active

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#231]
Related wp.org issue https://wordpress.org/support/topic/wpforms-conflict-with-wp-stateless/

![2018-04-26_17-08-12](https://user-images.githubusercontent.com/5578537/39332225-d4a21a76-4974-11e8-8f28-f729f8fbb3b5.gif)

**Comment by alimuzzaman** [comment]
@ewsopp It's our **Cache-Busting** feature.
WPForms uses sanitize_file_name to include class but we are adding random number before it.
Turning **Cache-Busting** off solve the problem though.

**Comment by alimuzzaman** [comment]
Issue has been solved for https://wordpress.org/plugins/wpforms-lite/
@ewsopp can you provide pro version for testing?
