### ISSUE TITLE
Sync programmatically

### ISSUE THREAD

**Issue by deivamagalhaes** [udx/wp-stateless#232]
I am wondering if there is a way (or if such feature is on the roadmap) to sync all files for a site programmatically, instead of using the page. This would be especially useful for multisite installations with several sites (like hundreds of sites). Thank you.

**Comment by alimuzzaman** [comment]
@deivamagalhaes 
You can use[ `Utility::add_media()`](https://github.com/wpCloud/wp-stateless/blob/latest/lib/classes/class-utility.php#L153) method to sync programmatically.

**Comment by jjtroberts** [comment]
See: https://github.com/wpCloud/wp-stateless/issues/343
