### ISSUE TITLE
Video (mp4) not playable

### ISSUE THREAD

**Issue by kilatepro** [udx/wp-stateless#236]
Hi,
I could upload a video (mp4) through wordpress media library, but the GCS file is not playing, while the local file is playing perfectly (using CDN mode in Stateless). The uploaded video to Google Cloud is not recognized as video, although the video uploaded to my domain is recognized!

The message when opening the link is: “There’s no video format or MIME type supported.”

I am using Featured Video Plus plugin (https://br.wordpress.org/plugins/featured-video-plus/) to display videos on some pages of my blog.

Can you please give me the clue??

**Comment by alimuzzaman** [comment]
@kilatepress

> The message when opening the link is: “There’s no video format or MIME type supported.”

What link? 

There is nothing we can do to support Featured Video Plus plugin  from our side. Please contact them.
