### ISSUE TITLE
2.1.5 QC and Outreach

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#237]
https://github.com/wpCloud/wp-stateless/releases

- Test all existing and new functionality.
- Report bugs and assign to Alim for further investigation. 
- Reach out to plugin authors and make them aware of the compatibility and offer them the pre-release for testing and direct communication with us.

**Comment by Mashenka** [comment]
Checking compatibility

- [x] COMPATIBILITY - Added support for WP Forms plugin
- [x] COMPATIBILITY - Added support for WP Smush plugin
- [x] COMPATIBILITY - Added support for ShortPixel Image Optimizer plugin.  - **Backup file sync won't work in stateless mode.**
- [x] COMPATIBILITY - Added support for Imagify Image Optimizer plugin. -  **issue added**
- [x] COMPATIBILITY - Added support for SiteOrigin CSS plugin. - **issue added**
- [x] COMPATIBILITY - Added support for Gravity Forms plugin. - **issue added**
- [x] COMPATIBILITY - Added support for WPBakery Page Builder plugin.

Outreach
 

- [x] WP Forms plugin - **Siad thanks, but won't mentioned.**
- [x]  WP Smush plugin - **reviewing** - **reminder sent** - **Will mention if we have more installs**
- [x]  ShortPixel Image Optimizer plugin. - **will mention, waiting for a release.** - **Notified about release** - **will mention in article**
- [x]  Imagify Image Optimizer plugin. - **reviewing** - - **reminder sent** - **Notified about release** - **They will think**
- [x]  SiteOrigin CSS plugin. - **tnanks, will recommend us and probably add to description in future**
- [x] Gravity Forms plugin. - **reviewing** (in facebook) - - **reminder sent**
- [x] WPBakery Page Builder plugin. - **reviewing** - - **reminder sent**
