### ISSUE TITLE
WP-Stateless deactivated, can't write to storage directory

### ISSUE THREAD

**Issue by limist** [udx/wp-stateless#239]
From the WordPress admin screens, I'm seeing this notification:

> WP-Stateless is not active due to following errors:
> 
> Could not create storage directory: /tmp/Google_Client/97

My webhost is using a load-balancing environment, and the only writable file system/directory they allow is under `wp-content/uploads`   Assuming the problem is what it seems, that WP-Stateless can't access or write to `/tmp`, is there a way to change the location of the storage directory?  Or does the problem lie elsewhere?  Thanks!

**Comment by alimuzzaman** [comment]
@limist Are you sure the google client library isn't loading from any other plugin?
Please disable other plugins and change to default theme.

**Comment by limist** [comment]
@alimuzzaman  Thanks; there was a message earlier about,
> WP-Stateless plugin may have potential Google SDK version conflicts with WooCommerce Google Analytics Pro plugin. WP-Stateless is using Google SDK v2.0, when WooCommerce Google Analytics Pro loads old Google SDK version v1.1.4.

We tried disabling the analytics plugin; then disabling and re-enabling the WP-Stateless plugin, but the error message remains.

**Comment by antonkorotkov** [comment]
@limist This is not something WP-Stateless does explicitly. It looks like Google Client tries to use File System for caching. Reference https://github.com/google/google-api-php-client/issues/574 But in our plugin we don't set File System as Cache storage. Instead we leave this option empty and therefore it is using Memory for caching.

**Comment by limist** [comment]
@antonkorotkov  OK, is there some way to prevent Google Client from trying to write to the server /tmp file system?  Because that causes WP-Stateless to go offline.  Thanks for help!

**Comment by alimuzzaman** [comment]
I don't see any reason why the API trying to use file cache, it should have fallback to memory cache.

Can you try to add this code `$this->client->setCache(new \Google_Cache_Memory());` after this line https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-gs-client.php#L72.

**Comment by ewsopp** [comment]
@limist any update regarding Alim's suggestion above?
