### ISSUE TITLE
SSL domain and media library translation

### ISSUE THREAD

**Issue by filipe-cantarelli** [udx/wp-stateless#241]
If I have a bucket `mybucket.domain.com` and set the custom domain to `mybucket.domain.com` all the images urls are translated to `http://mybucket.domain.com/...` which is correct.

When I set the domain to `https://mybucket.domain.com` only the new images I upload have the correct address, all the old images stay with `https://storage.googleapis.com/` domain.

**Comment by alimuzzaman** [comment]
The GCS url is saved as attachment meta data in database.
You have to do a manual sync from **Media >> Stateless Settings >> Sync** tab.
