### ISSUE TITLE
HTTPS is not supported with a custom domain

### ISSUE THREAD

**Issue by ihsanberahim** [udx/wp-stateless#242]
I already configure Cloud CDN, means i already checked that i can can use custom domain with HTTPS (`https://cdn.mydomain.com/...`)

My Setting:
1) set bucket name `cdn.mydomain.com`
2) set custom domain `https://cdn.mydomain.com`

Current plugin behavior:
it still uses `https://storage.googleapis.com/cdn.mydomain.com/...`

Expected behavior:
It uses `https://cdn.mydomain.com/...`

Suggestion:
![image](https://user-images.githubusercontent.com/1956846/40269384-5e16ae6e-5bb0-11e8-87c9-2a4a611f2fa5.png)

Add checkbox to allow user force use custom domain with https.

I myself, try to find a way. Unfortunately, can't manage to make it. (T_T).

**Comment by alimuzzaman** [comment]
@ihsanberahim For new attachment it should work fine, but for existing attachment you need to regenerate using **Regenerate and Sync with GCS** from **Media >> Library** or use **Sync** tab from **Media >> Stateless settings**.

**Comment by dchenk** [comment]
> @ihsanberahim For new attachment it should work fine, but for existing attachment you need to regenerate using **Regenerate and Sync with GCS** from **Media >> Library** or use **Sync** tab from **Media >> Stateless settings**.

I did Sync-Regenerate on an image after setting the custom domain, but it still shows the storage.googleapis.com domain
