### ISSUE TITLE
SiteOrign CSS plugin

### ISSUE THREAD

**Issue by Mashenka** [udx/wp-stateless#243]
I have created new css file in Appearance/Custom CSS tab
Run the sync  - Synchronize non media library files between Google Storage and local server

and do not see that file on Google Cloud

here is my project - https://console.cloud.google.com/storage/browser/stateless-wordpress-loc-maria?project=wordpress-loc-179190&organizationId=450511995436

file with the name so-css-twentyseventeen.css is located here 
![image](https://user-images.githubusercontent.com/5111163/40373138-ed4bd54c-5dee-11e8-80fb-62f9ef382283.png)

The question is also how can I sync that file separately from backend?

**Comment by alimuzzaman** [comment]
@Mashenka css file is synced to GCS after visiting frontend.

**Comment by Mashenka** [comment]
so do you see that file now on GCS? Can you link me?

**Comment by alimuzzaman** [comment]
I can't access your GCS storage.
The CSS file should be sync when you visit the frontend.

**Comment by Mashenka** [comment]
ok, now see
