### ISSUE TITLE
Compat Imagify feedback

### ISSUE THREAD

**Issue by Screenfeed** [udx/wp-stateless#245]
Hi, I'm Grégory, lead developer of Imagify's plugin.

Here is a small feedback after reviewing v2.1.5-RC2 code (haven't tested yet). These are only small details, I haven't seen anything alarming (the first one could be an issue though).

- [ ] 1- In the `add_media_wrapper()` method, you use `$imagify->is_extension_supported()`, but this method appeared only recently, in version 1.7 (we're currently 1.7.3). I would do that instead:

```php
if ( function_exists( array( $imagify, 'is_extension_supported' ) ) ) {
    // Use `$imagify->is_extension_supported()`.
} elseif ( function_exists( 'imagify_is_attachment_mime_type_supported' ) ) {
    // Use `imagify_is_attachment_mime_type_supported( $attachment_id )`.
} else {
    // Use `wp_attachment_is_image()`.
}
```

- [x] 2- In the `fix_missing_file()` method: while the upload basedir has no trailing slash normally, doing `$upload_dir[ 'basedir' ] . "/"` may be a problem if some weird plugin adds one (yeah I'm this kind of person that want to make sure that the impossible stays impossible). So I would do that instead (and it's simpler):

```php
$upload_basedir = wp_upload_dir();
$upload_basedir = trailingslashit( $upload_basedir[ 'basedir' ] );
$meta_data = wp_get_attachment_metadata( $attachment_id );
$file = $upload_basedir . $meta_data['file'];

/**
 * Try to get all missing files from GCS
 */
if ( !file_exists( $file ) ) {
    ud_get_stateless_media()->get_client()->get_media( apply_filters( 'wp_stateless_file_name', $meta_data['file']), true, $file );
}

if ( !empty( $meta_data['sizes'] ) && is_array( $meta_data['sizes'] ) ) {
    foreach( $meta_data['sizes'] as $image ) {
        if ( !empty( $image['gs_name'] ) && !file_exists( $file = $upload_basedir . $image['gs_name'] ) ) {
            ud_get_stateless_media()->get_client()->get_media( apply_filters( 'wp_stateless_file_name', $image['gs_name']), true, $file );
        }
    }
}
```

- [x] 3- In the `hook_from_imagify()` method: I recently added the method `is_running()`, maybe it could be used instead of `debug_backtrace()`? (for performance)
And for back-compat': `get_transient( imagify-async-in-progress-' . $attachment_id ) !== false`.

- [x] 4- In the `get_image_from_gcs()` method, `$overwrite` is not used. #CopyPasteDrama ^^

Regards.

PS: I assume you work only with the media library.

**Comment by alimuzzaman** [comment]
@Screenfeed We are not gonna include *add_media_wrapper* in this release, as this return local image URL when image is uploaded/added using add media button.

Is it possible to know if a image is added in Imagify queue in `wp_update_attachment_metadata` filter?

**Comment by Screenfeed** [comment]
@alimuzzaman I can't think of any way. If I'm not mistaken, you want to upload the file to the bucket after it has been optimized, right? In that case you should use the hook `after_do_imagify`.

**Comment by alimuzzaman** [comment]
That's ok,
Yes that's what we are doing.
Thanks @Screenfeed

**Comment by TheOneWizard1** [comment]
image minification was working for a short time but in a recent test it appears to be broken any ideas on how to fix?
