### ISSUE TITLE
Gravity forms warning when form is submitted

### ISSUE THREAD

**Issue by Mashenka** [udx/wp-stateless#246]
Warning: Missing argument 3 for wpCloud\StatelessMedia\GravityForm::modify_db(), called in /Users/mariakravchenko/sites/wordpress.loc/wp-includes/class-wp-hook.php on line 286 and defined in /Users/mariakravchenko/sites/wordpress.loc/wp-content/plugins/wp-stateless/lib/classes/compatibility/gravity-forms.php on line 83

![image](https://user-images.githubusercontent.com/5111163/40433101-df86ca00-5eb3-11e8-92e2-eb2afbc90ca3.png)

and only 1 file was uploaded from post image field. File upload and Custom post field weren't uploaded.

**Comment by Mashenka** [comment]
Still images not showing
![image](https://user-images.githubusercontent.com/5111163/40541818-1e2f124e-6026-11e8-9e46-7f75feff346b.png)

![image](https://user-images.githubusercontent.com/5111163/40541850-35fcc722-6026-11e8-989a-b0b5afc3ff5b.png)

![image](https://user-images.githubusercontent.com/5111163/40541869-496709ee-6026-11e8-88c3-a35c1d065d47.png)


and only 1 file was uploaded to media library from post image field, but not showing. File upload and Custom post field weren't uploaded.

**Comment by alimuzzaman** [comment]
@Mashenka I wasn't able to replicate the issue. Only one the Post Image filed upload image to media library. But all image will be synced.
