### ISSUE TITLE
'wp_generate_attachment_metadata' filter commented out on class-bootstrap.php line 220

### ISSUE THREAD

**Issue by JessBoctor** [udx/wp-stateless#248]
Hey everyone!

I am running into a problem. I have a set of images which I edit on save, adding an overlay so that the corners look cropped. 

The trouble I am running into is getting GS to recognize the updated file and save it to the original post id. I have been kinda running around in circles until today when I noticed that the filter for 'wp_generate_attachment_metadata' has been commented out in the class-bootstrap.php file. Once I uncommented it, everything worked perfectly.

Can you tell me why this is being excluded or if there is a better function ( such as wp_update_attachment_metadata ) for accomplishing what I need to do? 

Thanks so much!

Jess

**Comment by alimuzzaman** [comment]
Yes, you should use `wp_update_attachment_metadata`.
You are editing image using plugin or custom code by yourself?

`wp_generate_attachment_metadata` always follows by `wp_update_attachment_metadata` filter so we remove the filter on generate metadata to avoid extra workload.

**Comment by JessBoctor** [comment]
Thanks so much @alimuzzaman! That solved it for me. 

Yes, I am using my own custom code to edit the images. I had forgotten that the intended way to update an attachment is a three fold process: updating the image, generating the new metadata, and then actually updating the metadata. 

Thanks again!
