### ISSUE TITLE
Unique filenames when using `stateless` mode

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#249]
Issue has been reported by our client. He has frontend submission form with file upload. He is using `WP-Stateless` is `stateless` mode. 

Imaging a situation:

1. **Visitor 1** uploads file with name `image.jpg`. It is being uploaded to GCS and removed from local server.
2. **Visitor 2** uploads file with the same name `image.jpg`. By default WordPress checks for existing files and creates names like `image-1.jpg` to keep it unique. But in our case there are no files on local server because `stateless` mode is enabled. Therefore newly uploaded file is being overriding the file that already exists on GCS and belongs to **Visitor 1**.

**Comment by ewsopp** [comment]
**Cache-Busting** option should resolved this, no?

**Comment by antonkorotkov** [comment]
Yes. We need to make it impossible to disable cache busting in `stateless` mode.

**Comment by ewsopp** [comment]
Yes, you can do that with a wp-config constant. https://github.com/wpCloud/wp-stateless/wiki/Constants#wp_stateless_media_hash_filename

**Comment by ewsopp** [comment]
After reading the initial message and speaking with @antonkorotkov - this is actually a serious problem. 

- [ ] To fix this, we should force "Cache-Busting" mode to be enabled when "Stateless" mode is set.
- [ ] Webmaster can override this default setting by `WP_STATELESS_MEDIA_HASH_FILENAME` to `false`.

**Comment by alimuzzaman** [comment]
@ewsopp What about the multisite/network settings?

**Comment by ewsopp** [comment]
> What about the multisite/network settings?

What do you propose we do?

**Comment by alimuzzaman** [comment]
We could also force/disable in network.

**Comment by alimuzzaman** [comment]
Constant works fine on multisite.
