### ISSUE TITLE
integrate wp-hashify-media-filename as a cache-busting option

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#25]
Deleting and re-uploading images with the same file name will produce mixed results. Sometimes you will see the change right away, and other times GCS will serve a cached version of the originally uploaded file.

wp-hashify-media-filename works around this by randomizing the media file name by prepending some random numbers and letters to the beginning of the filename. `mypicture.jpg` becomes `2f693eab-mypicture.jpg`

I run wp-hashify-media-filename with every site I run wp-stateless and has really become a requirement. We should just build this into wp-stateless as an optional feature.

ref https://github.com/UsabilityDynamics/wp-hashify-media-filename

**Comment by antonkorotkov** [comment]
Done

**Comment by andypotanin** [comment]
@antonkorotkov can you please start including the link to GH issues in your commits? It makes it easier to others to track down in what commit things were actually done.

Thanks.
