### ISSUE TITLE
update name of WP_STATELESS_MEDIA_ON_FLY constant

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#251]
Change `WP_STATELESS_MEDIA_ON_FLY ` to `WP_STATELESS_DYNAMIC_IMAGE_SUPPORT` to be more accurate of the setting name and inline with our naming scheme.

**Comment by alimuzzaman** [comment]
@ewsopp we are having that constant for a very log time. Instead of replacing old constant we should keep them both and mark old constant as deprecated.

**Comment by ewsopp** [comment]
@alimuzzaman that's fine. Lets just add support for the new one and I'll remove the old from the documentation.
