### ISSUE TITLE
Improve Shortpixel compatibility with newly added hooks.

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#254]
do_action( 'shortpixel_image_optimised', $post_id ); // There is an action which is called upon successful optimization

New hooks:
do_action("shortpixel_before_restore_image", $attachmentID) //at the beginning of the doRestore function.
do_action("shortpixel_after_restore_image", $attachmentID); // before the function returns

return apply_filters("shortpixel_backup_folder", $ret); //last line of getBackupFolderAny()

**Comment by ewsopp** [comment]
@alimuzzaman what's the status of this issue?

**Comment by alimuzzaman** [comment]
@ewsopp will start today.

**Comment by alimuzzaman** [comment]
Further improvement require contacting ShortPixel again.

**Comment by ewsopp** [comment]
@alimuzzaman what's the status here? Did you add support for these new hook locations? and did you contact ShortPixel?

**Comment by alimuzzaman** [comment]
I have added support for new hook. We have done for v2.1.6.
I think more research and communication can improve the integration between this two plugin.

**Comment by ewsopp** [comment]
Will this require that all users upgrade their version of Shortpixel, or will v2.1.6 continue to work with older versions of Shortpixel?

**Comment by alimuzzaman** [comment]
Will need new version of shortpixel.

**Comment by ewsopp** [comment]
What is the minimum ShortPixel version required?

**Comment by alimuzzaman** [comment]
4.11.0
