### ISSUE TITLE
Recent Update broke ACF Image Crop Compatability

### ISSUE THREAD

**Issue by JessBoctor** [udx/wp-stateless#256]
Hi there!

I had a recent problem after updating the wp-stateless plugin. The 'Compatibility' tab was showing that the ACF Image Crop plugin was not active, so I was not able to enable this option. 

I tried using the constant 'WP_STATELESS_COMPATIBILITY_ACFIC' to enable the option, and while it would then show that the constant was defining the option, it still showed the ACFIC plugin as deactivated (even though it was active).

I did some poking around and was able to come up with a fix. In '/lib/classes/compatability/acf-image-crop.php', I changed line 19 from:

`protected $plugin_file = 'ACF-Image-Crop/acf-image-crop.php';`

to: 

`protected $plugin_file = 'acf-image-crop-add-on/acf-image-crop.php';`

I am not sure if this is connected to anything else or even if anyone else has run into this issue, but I thought I would just let you know and put it out there in case anyone else has this problem.

Thanks again for such as awesome plugin!

Jess

**Comment by antonkorotkov** [comment]
@alimuzzaman can you check folder name correctness?

**Comment by alimuzzaman** [comment]
@JessBoctor 
I was tested using the plugin from GitHub instead of wp.org.
The fix will be in next release.
Thanks

**Comment by JessBoctor** [comment]
Thanks @alimuzzaman!

**Comment by ewsopp** [comment]
@JessBoctor could you test this for us? 

@alimuzzaman where can Jess download the version with this fix?

**Comment by alimuzzaman** [comment]
You can download from [here](https://github.com/wpCloud/wp-stateless/archive/2.1.6-RC1.zip).

**Comment by JessBoctor** [comment]
Hi @ewsopp & @alimuzzaman!

I added the version you sent me to a local testing environment. Works like a charm!

I like the alert that you added when you detected that I had ACF image crop installed and active but had not yet enabled it in my wp-stateless settings. Great help!

Thanks again for a great plugin!
