### ISSUE TITLE
Loading images that are uploaded directly to Bucket.

### ISSUE THREAD

**Issue by hemiipatu** [udx/wp-stateless#258]
Is it possible to load images into `Wordpress > Media` if the image(s) in question have been directly uploaded into the linked bucket?

For example: I have gone ahead and created some folders and inside each folder, uploaded images. However these images don't show in `Wordpress > Media` at all.

The reason that I want to do it  this way, as opposed to uploading the images through wordpress itself is so that the images the website depends on are sorted into a neater file structure.

**Comment by alimuzzaman** [comment]
@hemiipatu Sorry not possible yet.
Check out [this answer](https://github.com/wpCloud/wp-stateless/issues/211#issuecomment-374914217) from @ewsopp.

**Comment by antonkorotkov** [comment]
Closing due to no responses.
