### ISSUE TITLE
ICompatibility.php Notice errors

### ISSUE THREAD

**Issue by walle89** [udx/wp-stateless#259]
When I updated to version 2.1.5 I getting these errors:

> Notice: Undefined index: acf-image-crop in /var/www/html/public/app/plugins/wp-stateless/lib/classes/compatibility/ICompatibility.php on line 71

> Notice: Undefined index: edd-download-method in /var/www/html/public/app/plugins/wp-stateless/lib/classes/compatibility/ICompatibility.php on line 71

+8 more similar errors for so-widget-css, so-css, gravity-form, wp-bakery-page-builder etc.

And this error:

> Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/public/app/plugins/wp-stateless/lib/classes/compatibility/ICompatibility.php:71) in /var/www/html/public/backend/wp-admin/includes/misc.php on line 1116

I'm using WP 4.9.6 Multisite subdir installation, PHP 7.2.

**Comment by alimuzzaman** [comment]
Can you try to save the settings from **Media >> Stateless Settings**?
Fix will be added in next release.

**Comment by alimuzzaman** [comment]
You can download the fix from this link.
https://github.com/wpCloud/wp-stateless/tree/929602f9491b5c89a47f7f0fb60784791f0f4b98

**Comment by alimuzzaman** [comment]
Same as #257
