### ISSUE TITLE
UI cleanup on media edit detail screen

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#26]
- [x] Create a new meta-box here to present WP-Stateless information.
- [x] Move the ‘Storage Bucket URL’ and ‘Storage Bucket’ fields into it.

This will also become the place where we add new options, information, and features.

![image](https://cloud.githubusercontent.com/assets/5578537/14217753/f3eec956-f81d-11e5-80ae-615013347816.png)

**Comment by antonkorotkov** [comment]
Fixed

**Comment by ewsopp** [comment]
New Edit Media Screen

![image](https://cloud.githubusercontent.com/assets/5578537/15839912/541f18e2-2c14-11e6-925b-e9fe8afa99ad.png)
