### ISSUE TITLE
Fix Google SDK conflict

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#261]
Reference:
Issue #119 and #131 
https://wordpress.org/support/topic/again-error-500-when-active-plugin/
https://wordpress.org/support/topic/google-sdk-plugin-conflict/

We could try to add namespace to the SDK.
Any other idea!

**Comment by alimuzzaman** [comment]
This should be done after issue #176 (Update Google Libraries)

**Comment by antonkorotkov** [comment]
This is fork we use https://github.com/UsabilityDynamics/google-api-php-client

In order to update it we need to merge from source repo.

It is installed not via composer as I can see. So we could probably try to add it into our own namespace but I can't imaging how much effort will it take right now. As an option we could try to not include this lib if such already included by any other theme or plugin by checking class existence for example.

**Comment by alimuzzaman** [comment]
@antonkorotkov The problem with that is other theme/plugin include different/older version of the SDK, that create the conflict.
Now we have only 66 files in [lib/Google/src/Google](https://github.com/wpCloud/wp-stateless/tree/develop-alim/lib/Google/src/Google) dir.
Shouldn't take much effort to add it into our own namespace. Should it?

**Comment by antonkorotkov** [comment]
@alimuzzaman Yeah I understand. So if we want to be sure 100% that libs do not conflict then we should wrap it into namespace.

**Comment by leepeterson** [comment]
My boss: “I thought we agreed to not run WordPress as a stateful application...? Now I see WP-Stateless has caused fatals and conflicts with other plugins which rely on Google SDK...?”

Fun times. 

Add WP-SMTP-Mail to the list of plugins affected by WP-Stateless’ use of and reliance on Google’s Auth SDK. 

Also, it appears that even a fully manual setup of WP-Stateless still leaves it vulnerable and reliant on an SDK that’s been manually authenticated ahead of time.

**Comment by ewsopp** [comment]
@leepeterson thanks for the feedback. We'll discuss this and come up with a solution.

**Comment by alimuzzaman** [comment]
@leepeterson Can you please test the plugin from [this branch](https://github.com/wpCloud/wp-stateless/tree/google-sdk-conflict)?
I have wrapped the SDK in our namespace. Seems to be working. Should not conflict with other plugins SDK now.
https://github.com/wpCloud/wp-stateless/tree/google-sdk-conflict

**Comment by leepeterson** [comment]
@ewsopp @alimuzzaman That branch appears to correct the SDK conflict. However, I'm unable to use that branch as few of the other features work. 

For instance: 

1. Only 1 file will re-generate and sync itself before providing what appears to be an error (status with red border on left but with "success" message inside).
2. I was unaware that the `WP_STATELESS_MEDIA_HASH_FILENAME` and  `WP_STATELESS_MEDIA_ON_FLY` constants had been deprecated until I found thousands of warnings in error logs
3. Pre-existing constants set for things like disabling file name hashing remained as "Yes" no matter how many times I attempted to change it back to "No"
4. The OAuth process during setup always leads to a UD website by passing my website's URL as a param resulting in "Site not found." failures

Couldn't get very far using that branch. I wasn't expecting to encounter such foundational changes, either. Thank goodness for staging!

**Comment by alimuzzaman** [comment]
Thanks @leepeterson,
I have build that branch on top of our current updates for v 2.1.6. That's why there are some unexpected errors. 

1. We are aware of that error and fixing it. #269 
2. We are going to deprecate it from 2.1.6 version. Will do something about the warning.
3. We will look into it, is it only for **File name hashing**? **File name hashing** will be forced to Yes in **Stateless Mode** unless set by constant.
4. This problem is fixed.

**Comment by alimuzzaman** [comment]
@leepeterson Please try this pre-release version [2.1.6 RC3](https://github.com/wpCloud/wp-stateless/releases/tag/2.1.6-RC3).

**Comment by leepeterson** [comment]
1. Thank you. 
2. Let old constants continue to work and throw warning about deprecation? 
3. Appeared to be any setting which existed previously and also set by constant. For instance, if I’d never selected Yes or No in the UI and I’d also never set a constant for that field, I could change it in the UI and it’d save; but the ACF media crop field, a field which had never been changed in the UI and only ever set via constant would not save in the UI after repeated attempts. 

I’ve seen this issue before with other plugins that offer a UI to update data saved in wp_options but I never figured out exactly what caused it. I believe it had to do with cookies (options saved during a user’s session) or perhaps cache key conflicts in APC or, when installed, APCu. 
4. Noticed this in another ticket. Thank you.

**Comment by ewsopp** [comment]
@alimuzzaman can you check over this additional feedback please? I think Lee has some good feedback here.

**Comment by alimuzzaman** [comment]
@leepeterson 
> Appeared to be any setting which existed previously and also set by constant. For instance, if I’d never selected Yes or No in the UI and I’d also never set a constant for that field, I could change it in the UI and it’d save; but the ACF media crop field, a field which had never been changed in the UI and only ever set via constant would not save in the UI after repeated attempts.

3. Is this error still happening? Is this still happening in the 2.1.6 RC3?
    I think I have already fixed something like this.
