### ISSUE TITLE
Slow query: wpCloud\StatelessMedia\Bootstrap::attachment_url_to_postid

### ISSUE THREAD

**Issue by ahmed-sigmalux** [udx/wp-stateless#262]
I'm running into a slow query (~0.3s) when using this plugin:

```
SELECT post_id
FROM 1Hnx_postmeta
WHERE meta_key = 'sm_cloud'
AND meta_value LIKE '%https://cdn.mydomain.com/resources/media/yoast_seo-banner.png%'
```

The image is set in Yoast for Google's Knowledge Graph results.

I have object caching enabled, yet this slow query happens on nearly every page. Anyone encounter something similar or know how to fix it?

**Comment by SahriHamza** [comment]
I have the same issue on a website having a large number of images

**Comment by antonkorotkov** [comment]
@alimuzzaman Can you investigate how we use `attachment_url_to_postid` filter exactly? The issue goes from there.

**Comment by AJB99** [comment]
+1

I'm seeing the same queries showing up in my slow query log as well:

```
SELECT post_id
FROM wp_postmeta
WHERE meta_key = 'sm_cloud'
AND meta_value LIKE '%https://cdn.thenewstack.io/media/2015/08/VMware@2x.png%'
```
As a result, one of the pages on the site (which has ~50 images on it) takes 1.5-2.5 MINUTES to load when it's not cached.

What is the purpose of the `attachment_url_to_postid()` method?
Why is it hitting the DB for every single image on the page?
How can I disable this and get reasonable page-loading speed back?

Thanks!

**Comment by alimuzzaman** [comment]
The performance issue is most likely because we used `like`.
@antonkorotkov We don't use this function at all [nor the WordPress](https://developer.wordpress.org/reference/functions/attachment_url_to_postid/#used-by-table) on frontend. Maybe it used by theme or plugin.

**Comment by alimuzzaman** [comment]
@ahmed-sigmalux @SahriHamza @AJB99 
I have added caching and changed our implementation of  [`attachment_url_to_postid`](https://github.com/wpCloud/wp-stateless/blob/e372ed2962d3512836410009494b7f07d59eee65/lib/classes/class-bootstrap.php#L1199) filter/method.
New implementation is based on what wp did in [`attachment_url_to_postid`](https://developer.wordpress.org/reference/functions/attachment_url_to_postid/#source) function.

You can download latest version from here.
https://github.com/wpCloud/wp-stateless/tree/e372ed2962d3512836410009494b7f07d59eee65

Please let us know if this solve the problem.

**Comment by AJB99** [comment]
@alimuzzaman Thanks for the quick turn-around on this.

I believe I've found a typo in the commit you posted above.

https://github.com/wpCloud/wp-stateless/commit/e372ed2962d3512836410009494b7f07d59eee65

line 1205 contains this: `WP_STATELESS_LAGECY_URL_TO_POSTID`.
(The A and the E of 'legacy' are transposed).

I believe it should read: `WP_STATELESS_LEGACY_URL_TO_POSTID`.

**Comment by alimuzzaman** [comment]
@AJB99 typo is fixed.
Can you test the performance and let us know about performance.

**Comment by AJB99** [comment]
@alimuzzaman Where am I downloading the latest version from?

Have you released a new version that I can update via the WP Admin?

**Comment by alimuzzaman** [comment]
@ajb99
No it's not released yet.
You can download it from here. 
https://github.com/wpCloud/wp-stateless/tree/7bfd63b91a805fc7a2af0cdd33552b166861a1a8

**Comment by alimuzzaman** [comment]
The current implement only supports the full-size image.

`https://example.com/image-1024x542.png`
Maybe remove `-\d+x\d+` from the end of the URL then do the query.
https://github.com/wpCloud/wp-stateless/blob/e372ed2962d3512836410009494b7f07d59eee65/lib/classes/class-bootstrap.php#L1230-L1241

**Comment by planv** [comment]
WordPress core function works on the same way. 

<img width="979" alt="изображение" src="https://user-images.githubusercontent.com/5268508/78544108-520be380-7802-11ea-841a-550d1ccff23f.png">

You can see more information about it - `https://core.trac.wordpress.org/ticket/42437`, also  other implementation for this hook - `https://gist.github.com/pbiron/d72a5d3b63e7077df767735464b2769c` .

**Comment by alimuzzaman** [comment]
@planv I think then we can close this?

**Comment by planv** [comment]
Yes, closed
