### ISSUE TITLE
Woocommerce extra product options

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#266]
https://wordpress.org/support/topic/dynamic-image-support/#post-10424222
While using Woocommerce extra product options plugin for image uploads from frontend, I enabled the Dynamic Image Support in Compatibility section to upload the uploads to cloud storage, but the images are not uploaded to cloud storage instead uploaded inside the uploads directory. Is there any way to upload to cloud storage?
Parent issue #210

**Comment by alimuzzaman** [comment]
@ewsopp please review
File name: `woo-extra-product-options.php`
> protected $id = 'woo-extra-product-options';
> protected $title = 'WooCommerce Extra Product Options';
> protected $constant = 'WP_STATELESS_COMPATIBILITY_WOO_EXTRA_PRODUCT_OPTION';
> protected $description = 'Ensures compatibility with WooCommerce Extra Product Options.';

**Comment by ewsopp** [comment]
@Mashenka @alimuzzaman has anyone tested this? Would be great to get feedback from the user who submitted this issue to begin with.

**Comment by alimuzzaman** [comment]
Yes, tested by the reported user.
https://wordpress.org/support/topic/dynamic-image-support/#post-10457427

**Comment by ewsopp** [comment]
Good work

**Comment by alimuzzaman** [comment]
# How to test 
## Add file upload meta:
![image](https://user-images.githubusercontent.com/6744156/78819686-6c0f1700-79f8-11ea-81b3-e203d35aae4d.png)

## Upload file when adding to cart:
![image](https://user-images.githubusercontent.com/6744156/78819762-8cd76c80-79f8-11ea-99fe-bcc28c6c0f1a.png)

## Go to view cart:
![image](https://user-images.githubusercontent.com/6744156/78819916-d031db00-79f8-11ea-9cd0-b33e6733253a.png)
