### ISSUE TITLE
Disable Resize and Optimization

### ISSUE THREAD

**Issue by alihs** [udx/wp-stateless#267]
Is it possible to sync the files to GCS without the resizing/generating thumbs or optimizing images?
I ask this as i have a client with 24gigs of images :(

**Comment by antonkorotkov** [comment]
@alihs currently it is impossible (we are working on separate sync solution). But as a workaround you can try deregister all image sizes and do sync. After that register image sizes back.

**Comment by kLOsk** [comment]
Any news on this? It also seems that the bulk processing is not working. It always does one file at a time...

**Comment by antonkorotkov** [comment]
Separate sync solution is still underway. Not much progress, though. Follow this issue for details https://github.com/wpCloud/wp-stateless/issues/211 Closing this issue due to duplicating.
