### ISSUE TITLE
record generated thumbnail sizes for each attachment posts

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#268]
We need a place to store generated thumbnail sizes for each media library image. This will be useful information that can be utilized by our forthcoming synchronization tool. 

As an image is uploaded and the thumbnails generated, record those generated sizes in a dedicated meta field. This meta field should be namespaced (prevent plugin compatibility issues) and accessible to other plugins and the admin interface.

**Comment by antonkorotkov** [comment]
I think this information needs to be recorder to separate MySQL table created by WP-Stateless. 

This metadata is going to be an array of sizes and basically be not a simple value. We will have to have it for each image object and that means post_meta table will get additional information flow that will slow down queries to post meta... In case of a lot of images this will potentially affect performance significantly, in addition to the wp-stateless metadata that we already store in post meta table. 

We will still be able to use this data to show it on edit image page in metabox.

**Comment by ewsopp** [comment]
@antonkorotkov whatever you think is best.

**Comment by planv** [comment]
Added current information to `postmeta` table. 
After optimization and minimization data (issue #383 ) it is ok, discussed it with @antonkorotkov .
