### ISSUE TITLE
[Pre-Release 2.1.6 RC2] Sync option

### ISSUE THREAD

**Issue by Mashenka** [udx/wp-stateless#269]
Sync option syncs only 1 image. 
![image](https://user-images.githubusercontent.com/5111163/42582392-a195a6a8-8537-11e8-85d4-b334c416138f.png)

It starts the process of syncing 104 images then give that message that 1 image was synced

The issue can be replicated on workspace - https://workspace.uds.io/wp-admin/upload.php?page=stateless-settings

**Comment by Mashenka** [comment]
now this error

![image](https://user-images.githubusercontent.com/5111163/42636644-f744daa0-85f1-11e8-8ee8-5c1177351791.png)

**Comment by antonkorotkov** [comment]
It means you don't have files to resize. They are missing because you deleted them locally and on GCS. This is not an issue.

**Comment by alimuzzaman** [comment]
@Mashenka can you test again?
Sync process won't break if it can't process a image.

**Comment by Mashenka** [comment]
Issue resolved
