### ISSUE TITLE
image sync tools

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#27]
Our "Stateless Image Synchronisation" tool offers two options:
- Regenerate all stateless images and synchronize GCS with local server.
- Synchronize non-images files between GCS and local server.

but I think it should really be...
- Synchronize Media Library
- Regenerate Image Thumbnails

**Synchronize Media Library**
Issue https://github.com/wpCloud/wp-stateless/issues/37
- [ ] The new `Synchronize Media Library` option scans the local media storage and GCS to create a list of files that do not reside on both ends. Some files might only be on GCS, and other files may only on local storage.
- [ ] For files that are only on local storage and DO exist in the media library, push copy to GCS and find/replace references of local file url.
- [ ] For files that are only on local storage and DO NOT exist in the media library, push copy to GCS, create media library object, and find/replace references of local file url.
- [ ] For files that are only on GCS and DO exist in the media library, push copy to local storage.
- [ ] For files that are only on GCS and DO NOT exist in the media library, push copy to GCS and create media library object.

**Regenerate Image Thumbnails**
Issue https://github.com/wpCloud/wp-stateless/issues/38
- [ ] The new 'Regenerate Image Thumbnails` option scans each media item, takes note of the current thumbnail sizes of the image by looking at file names of the existing thumbnails, takes note of the defined thumbnail sizes set by plugins and themes, and regenerates a new thumbnail for all of these sizes.
- [ ] Once the thumbnail regeneration is complete for the image, it then does a find and replace for each thumbnail file.

**Other Thoughts**
Some other ideas we might want to implement...
- [ ] The find/replace functionality should only happen when the user has selected another checkbox requesting it. We can also use this to warn them it will take extra long to perform.
- [ ] The thumbnail regeneration should only generate missing thumbnails by default.

**Comment by antonkorotkov** [comment]
I have a lot of comments for each point so it probably would be better to create separate issues.

**Comment by AJB99** [comment]
Is there any update on this? I'd love the option to just transfer the existing files without regenerating thumbnails. Currently, there's 4500 uploads on the site I'm working on and it would take 22.5 hours to regen and transfer all the files to GCS.

**Comment by andypotanin** [comment]
@AJB99 we're working on this. Let me know if you're interested in this, perhaps you could do some testing for us.

**Comment by ewsopp** [comment]
This is being developed separately as an extension. Closing this issue.

**Comment by gepd** [comment]
@ewsopp Can you tell me what is the name of the extension and where can I find out?

**Comment by Mashenka** [comment]
@gepd That add-on is still under construction.

**Comment by gepd** [comment]
@Mashenka thanks for the info!

**Comment by larsha** [comment]
@Mashenka @ewsopp Is this still something that is being developed? Would be awesome to just sync and skip the whole regeneration procedure since I know we have every image in the bucket. We have over 50k original images and the option that is available now will take forever.
