### ISSUE TITLE
Stateless Mode Not Compatible With ELEMENTOR

### ISSUE THREAD

**Issue by TheOneWizard1** [udx/wp-stateless#271]
Elementor | V 2.1.2
WP-Stateless | V 2.1.5

When using the element builder and adding an image element:
The only Image size that works properly is the: **custom image size** 
The rest of the image sizes appear to work but once you click away from the element it disappears.

It also breaks other random things like sides and carousels

WP-Stateless Settings | 
Mode | Stateless
File URL Replacement | Enabled
Delete GCS File |  Enabled 
Bucket | CDN.Domain.com
Domain | CDN.Domain.com
Organization | Disabled
Cache-Busting | Enabled

Server Environment |  
Operating System: | Linux |  
Software: | nginx/1.13.8 |  
MySQL version: | 5.7.22 |  
PHP Version: | 7.2.7 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 8M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right |  

WordPress Environment |   |  
Version: | 4.9.7
Max Upload Size: | 8 MB |  
Memory limit: | 256M |  
Permalink Structure: | /%postname%/

**Comment by alimuzzaman** [comment]
@TheOneWizard1 I have tested Image element it's working fine with this configuration.

Elementor | V 2.1.7 
WP-Stateless | V [2.1.8-beta-2](https://github.com/wpCloud/wp-stateless/releases/tag/2.1.8-beta-2)

**Comment by TheOneWizard1** [comment]
alimuzzaman,

Appreciate your help here just tried the plugin 2.1.8-beta2 and am still having the same issue.

It appears as tho when I initially add the picture it works fine. 

But once I click off to another elementor still breaks.

This holds true with all image sizes besides the thumbnail and custom sizes.

Have added images below to demonstrate. 

I know that this has something to do with images being http - https
Thumbnail Work Fine clicked on or off
![home 1](https://user-images.githubusercontent.com/41242850/44370580-6752c380-a4a0-11e8-9366-8ef15f791c81.png)
medium sized image works fine while **clicked on**
![home 2](https://user-images.githubusercontent.com/41242850/44370579-66ba2d00-a4a0-11e8-9676-5e8afc85f002.png)
Medium Images Breaks as soon as you **click off** 
![home 3](https://user-images.githubusercontent.com/41242850/44370578-66ba2d00-a4a0-11e8-9923-c3d4a55292b7.png)
Custom Image Size Works Fine
![home 4](https://user-images.githubusercontent.com/41242850/44370577-66ba2d00-a4a0-11e8-94be-da6dcae599e3.png)

**Comment by alimuzzaman** [comment]
@TheOneWizard1 

> I know that this has something to do with images being http - https

Yes, that might be the problem. `https` on custom domain isn't supported.

**Comment by TheOneWizard1** [comment]
I have found a way for https to work with cloudflare on custom domain. Would be possible to make with work?

**Comment by alimuzzaman** [comment]
Yes, I think so. But I never tried.

**Comment by TheOneWizard1** [comment]
The think its possible for you too?

**Comment by alimuzzaman** [comment]
@TheOneWizard1 please check the issue #291
