### ISSUE TITLE
Multi Regional Vs Regional Storage

### ISSUE THREAD

**Issue by m444estro** [udx/wp-stateless#273]
Hello, is there any point to create multi regional google cloud storage? Other than increasing unnecessary cost?

My understanding:
My nginx+php+wordpress webserver is in US-West1. Then, wp-stateless (stateless mode) will store in X region.

???> No matter where the web visitors are, it will always be a US-West1 server requesting image/object from X region.

So, it would make sense to only make X regions = US-West1 and no need multi region? +same region = less transfer cost

Is my understanding correct? Can anyone please clarify?

Thank you

**Comment by ewsopp** [comment]
Hello - this is more of a question for Google Cloud. I suggest checking GCS documentation to find the differences between Multi-Regional and Regional Storage.

**Comment by m444estro** [comment]
I guess I need to rephrase my questions.
