### ISSUE TITLE
#2 Benefits may be not applicable for this plugin?

### ISSUE THREAD

**Issue by m444estro** [udx/wp-stateless#274]
In your readme text for benefits #2:
"Google Cloud Storage is geo-redundant, meaning your media is delivered by the closest server - reducing latency and improving page speed."

***But this is only for multi regional storage option.***

The statement is correct but I think it's not applicable or rather misleading for this plugin. Because this suggest people to opt for "multi regional" cloud storage option which is not utilized by this plugin.

If I understand correctly how your plugin work (especially in stateless mode), wp-content/uploads = a folder in google cloud storage.

Say your webserver is in us-west1. No matter where your visitors are, it will always be a us-west1 box connecting/requesting to the cloud storage. Hence, you should have same region cloud storage regardless.

Meaning people should opt "regional" cloud storage instead of "multi regional". This will reduce latency and cost.

Please correct me if my understanding is wrong.

**Comment by ewsopp** [comment]
WP-Stateless configures the bucket to have a Multi-Regional Storage Class. Details about the multi-regional storage class can be found at https://cloud.google.com/storage/docs/storage-classes#multi-regional

Google will proxy the user to the closest storage location on image request. They handle all the technical details here.

**Comment by m444estro** [comment]
Apologies, I didn't know the plugin is set to opt MR storage regardless. Will there be option for regional storage in the future?

If I understand correctly, the "image" will always be requested by a wordpress server in X region. Hence, Multi Regional option doesn't help to reduce latency/improve page speed.

The only part of "geo-redundant" that benefit this plugin is that if disaster happen, data can be recovered from other regions.

*If it happens to a local region storage, it's gone, unless one has backup plan e.g. data are downloaded to offline disk routinely.

**Comment by ewsopp** [comment]
> Will there be option for regional storage in the future?

Maybe

> If I understand correctly, the "image" will always be requested by a wordpress server in X region. Hence, Multi Regional option doesn't help to reduce latency/improve page speed.

The image is requested by the user's web browser. Not sure how WordPress fits in here...

> The only part of "geo-redundant" that benefit this plugin is that if disaster happen, data can be recovered from other regions.

That's not how it works. Every file has a URL and when accessing that URL, Google determines where to load that file from based on many details - including where the requestor (the user loading the web page) is located.

**Comment by m444estro** [comment]
I have been misunderstanding completely.

So, basically, it's like an embedded youtube video. Directly to youtube, not/barely using the resources of the site owner's webserver.

That's awesome! Thanks a lot
