### ISSUE TITLE
BuddyPress Compatibility

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#275]
https://wordpress.org/support/topic/buddypress-avatars-not-syncing/

**Comment by alimuzzaman** [comment]
I don't see any way to make it work in stateless mode.
May be possible if we save some data in database.

**Comment by alimuzzaman** [comment]
@antonkorotkov 
Can you please check?

**Comment by alimuzzaman** [comment]
Some new idea https://github.com/wpCloud/wp-stateless/commit/20d07d06e479e477d773933b7327d2a5f75f8d7b

**Comment by ewsopp** [comment]
@alimuzzaman what's the status here?

**Comment by antonkorotkov** [comment]
@alimuzzaman can you explain in detail what happens here? I see this commit https://github.com/wpCloud/wp-stateless/commit/20d07d06e479e477d773933b7327d2a5f75f8d7b was reverted later. What 'some new idea' you mean? 

And what exactly I should test/review?

**Comment by alimuzzaman** [comment]
@antonkorotkov seems like I have applied that commit later. It was a way to sync the Banner image.

Please test if the avatar/banner image syncing working. Or is there anything more that can be done.

I don't think there is anything left to do than testing.

**Comment by antonkorotkov** [comment]
Ok, will try to setup BuddyPress and test.

**Comment by antonkorotkov** [comment]
Looks like the current state of BuddyPress Compatibility breaks avatars, even not BP avatars. 

![image](https://user-images.githubusercontent.com/2276882/74945370-47d38880-5400-11ea-8565-1b2a090b4e5a.png)

Going to investigate that.

**Comment by antonkorotkov** [comment]
All avatars work now. Custom user avatars also work and load from GCS.

![image](https://user-images.githubusercontent.com/2276882/74952022-c03e4780-5408-11ea-8b97-b824e2938566.png)
