### ISSUE TITLE
display notice when clicking stateless option 

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#277]
When the user clicks the "Stateless" option within the Mode settings, display a notice with the following message.

**Title**
`Stateless mode enables and requires the Cache-Busting option.`

**Description**
`WordPress looks at local files to prevent files with the same filenames. Since Stateless mode bypasses this check, there is a potential for files to be stored with the same file name. We enforce the Cache-Busting option to prevent this. Override with the WP_STATELESS_MEDIA_CACHE_CONTROL constant.`

Link "WP_STATELESS_MEDIA_CACHE_CONTROL" to https://github.com/wpCloud/wp-stateless/wiki/Constants#wp_stateless_media_cache_control

**Button**
no button.

Notice is dismissible, but should be displayed every time the user tries to enable stateless mode. 

![image](https://user-images.githubusercontent.com/5578537/43339378-289f0d1c-91a7-11e8-8e77-e8467fc2ba17.png)

**Comment by ewsopp** [comment]
In addition to above, we need to handle existing users...

Can we make a dashboard-wide notice for those who already have Stateless enabled and Cache-Busting disabled? 

I created a separate issue for this at https://github.com/wpCloud/wp-stateless/issues/279

**Comment by alimuzzaman** [comment]
![image](https://user-images.githubusercontent.com/6744156/43972430-29eb412c-9cf6-11e8-8730-69e116291031.png)
