### ISSUE TITLE
display required message on Cache-Busting setting description with Stateless is enabled.

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#278]
When Stateless mode is enabled, we need to enable/enforce the Cache-Busting setting. 

- [x] Update the Cache-Busting setting with the following message...

> Required by Stateless Mode. Override with the WP_STATELESS_MEDIA_CACHE_CONTROL constant. Prepends a random set of numbers and letters to the filename. This is useful for preventing caching issues when uploading files that have the same filename.

- [x] "Required by Stateless Mode. Override with the WP_STATELESS_MEDIA_CACHE_CONTROL constant." should be **bold**.

- [x] link WP_STATELESS_MEDIA_CACHE_CONTROL to https://github.com/wpCloud/wp-stateless/wiki/Constants#wp_stateless_media_cache_control

# Should Look Like This

![image](https://user-images.githubusercontent.com/5578537/43339929-c00ed88e-91a8-11e8-9b62-90ce82955013.png)

**Comment by alimuzzaman** [comment]
![image](https://user-images.githubusercontent.com/6744156/43972406-14435256-9cf6-11e8-9c97-1fdd1a0eb1dc.png)
