### ISSUE TITLE
display dashboard-wide notice for existing users

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#279]
For existing WP-Stateless users that are upgrading from a previous version, we need to show them a notice.

Display this notice across the entire dashboard.

**Title**
`Stateless mode now requires the Cache-Busting option.`

**Description**
`WordPress looks at local files to prevent files with the same filenames. Since Stateless mode bypasses this check, there is a potential for files to be stored with the same file name. We enforce the Cache-Busting option to prevent this. Override with the WP_STATELESS_MEDIA_CACHE_CONTROL constant.`

Link "WP_STATELESS_MEDIA_CACHE_CONTROL" to https://github.com/wpCloud/wp-stateless/wiki/Constants#wp_stateless_media_cache_control

**Button**
"View Settings" and link to the stateless settings panel.

Notice is dismissible

**Comment by alimuzzaman** [comment]
![image](https://user-images.githubusercontent.com/6744156/43972328-cca50e9e-9cf5-11e8-8c4c-3a83c7b84feb.png)

**Comment by ewsopp** [comment]
@alimuzzaman lets adjust this a bit please.

- For existing WP-Stateless users that are upgrading from a previous version
- *AND* have stateless mode enabled
- *AND* have cache-busting disabled, we need to show them a notice.

This way we are not displaying the message to people unaffected by this forced setting.

**Comment by leepeterson** [comment]
When might this fix fully roll out?

![screen shot 2018-10-21 at 7 55 44 am](https://user-images.githubusercontent.com/972141/47266675-e21f7580-d507-11e8-88f3-5bf8071d46ed.png)

1. Stateless Mode *is not* enabled
2. Constant `WP_STATELESS_MEDIA_CACHE_BUSTING` *is* set to `false`
3. `Cache-Busting` dropdown *is* set to `Disable`
4. Settings *have been* verified in database, yet this notification persists

**Comment by alimuzzaman** [comment]
@leepeterson 
Please use this version https://github.com/wpCloud/wp-stateless/releases/tag/2.1.8-rc6

Click the close button on the right side, that will hide the notice.
`WP_STATELESS_MEDIA_CACHE_BUSTING` don't hide the notice, should it?

**Comment by alimuzzaman** [comment]
@ewsopp What do you think?

**Comment by Mashenka** [comment]
@alimuzzaman 

 >For existing WP-Stateless users that are upgrading from a previous version
 > AND have stateless mode enabled

didn't receive notice, only when tried to change to CDN mode and then check back Stateless that notice appeared 

checked with 2.1.8-rc6

**Comment by alimuzzaman** [comment]
@Mashenka Yes, that's the expected outcome.

**Comment by Mashenka** [comment]
ok, then good
