### ISSUE TITLE
edit media support

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#28]
ref https://codex.wordpress.org/Edit_Media#Edit_Image

Not sure of all the details around 'edit media' functionality, but we should ensure that we fully support it in all modes (CDN and Stateless modes).

**Comment by antonkorotkov** [comment]
I think we do it by default

**Comment by Mashenka** [comment]
The issue that Edit image option is not saving you edit results

when you edited image and save it will stay the same
![image](https://cloud.githubusercontent.com/assets/5111163/15154227/27bf27b8-16e5-11e6-826e-f416f849ffc3.png)

**Comment by techstroke** [comment]
I'm having the exact same issue on debugging found out that the metadata is not being generated and xdebug shows that on image edit and save , the handle_on_fly method is called which just upload cropped images to cloud but doesn't update meta ! I'm using 1.7.3 available on wordpress plugin repo, kindly fix on priority :)

**Comment by antonkorotkov** [comment]
@techstroke it seems you are talking about #31. Check `latest` branch, it is fixed there.

**Comment by techstroke** [comment]
No, @antonkorotkov  I'm talking about the same issue which @Mashenka  has mentioned ie. 

If you edit a media file (ie. crop it and press save ) then normally it should show cropped image that you can then insert into post , but when stateless is active  and when I press save after cropping a image , It does upload the cropped version to GCS and also creates file on local disk but the image that shows up after pressing save is the original one ! 

I created a short gif screencast to explain the issue - http://recordit.co/Lopa4qOMFv

**Comment by antonkorotkov** [comment]
Yes, we know about the issue with image editor, but it is not connected to `handle_on_fly` method. Anyway we are working on it.

You can do pull requests if you want btw.

**Comment by techstroke** [comment]
Oh great ! by the way really nice plugin and regarding that pull request my WP dev skills are a bit shaky, but I'll contribute with code in near future :)

**Comment by alimuzzaman** [comment]
@ewsopp Wasn't the problem solved?

**Comment by ewsopp** [comment]
Not sure, I will review it.

**Comment by Mashenka** [comment]
@alimuzzaman I have checked, for me was working

**Comment by Mashenka** [comment]
@ewsopp I have checked that issue. Image can be edited(you can change size, turn it) and it will be updated on Google cloud also

do you need some more options or we can close this issue?

**Comment by ewsopp** [comment]
@Mashenka I need some time to test. I'll try to get to this tomorrow. Thanks for the reminder.
