### ISSUE TITLE
Possible documentation discrepancy with WP_STATELESS_MEDIA_BODY_REWRITE constant

### ISSUE THREAD

**Issue by dchenk** [udx/wp-stateless#281]
Looking at just this line: 
https://github.com/wpCloud/wp-stateless/blob/23696e1b99c9b0d3db3418eb0ab97b23bda181aa/lib/classes/class-settings.php#L25

I get the impression that the WP_STATELESS_MEDIA_BODY_REWRITE constant is false by default. However, the [wiki here](
https://github.com/wpCloud/wp-stateless/wiki/Constants#wp_stateless_media_body_rewrite) says that the default value is true. Is this a mistake in docs or code, or something I’m missing?

Also, can someone help me understand how this feature works? The wiki only says, “Scans post content and meta during presentation and replaces local media file urls with GCS urls. This setting does not modify your database.” Can someone offer a more detailed explanation? I’d be wary of turning on a feature that automatically transforms links in the post content displayed.

Thank you in advance.

**Comment by alimuzzaman** [comment]
It's hook into `the_content` and `get_post_metadata` filter and replace any old local url, it's don't sync file to GCS.
We will fix confusion about the default value.

**Comment by dchenk** [comment]
@alimuzzaman thank you. Looking forward to the fix.

**Comment by alimuzzaman** [comment]
@ewsopp What should be the default value?
Should I follow the wiki and change the code?

**Comment by ewsopp** [comment]
Should be TRUE by default.
