### ISSUE TITLE
Can we upload full size before generating thumbnails? 

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#286]
I've been working on a project where the size of the original image was so large that wordpress could not generate the thumbnails properly due to limited resources. In this scenario, it was generating a problem with using the Sync feature in WP-Stateless.

One of the solutions I thought of was to synchronize the original image (full size) onto GGS before processing the thumbnails. Is this possible? 

Upon image upload or sync, can we upload the full size image first before generating and storing the thumbnails?

**Comment by alimuzzaman** [comment]
@ewsopp What if we add a option to ignore the regeneration at all?

**Comment by alimuzzaman** [comment]
Some time regeneration isn't required. And if user have lots of file it can slow a lot.
I think having option to skip regeneration would be helpful in this situation.
If user have lots of image and they just need to sync, regeneration is unnecessary.

**Comment by alimuzzaman** [comment]
@ewsopp 
Now full size image will be synced before generating thumbnail.
Using `intermediate_image_sizes_advanced` filter in [`wp_generate_attachment_metadata`](https://developer.wordpress.org/reference/functions/wp_generate_attachment_metadata/#source) function.
Stateless will try to upload again (in wp_update_attachment_metadata filter) but will ignore because image exist in GCS.

**Comment by ewsopp** [comment]
@alimuzzaman ok this is interesting.

Please detail step by step how an upload is processed now and how it would be if we uploaded the original file first. I'm mostly interested in the steps for `stateless` mode. Thanks

**Comment by alimuzzaman** [comment]
@ewsopp I really didn't thought about the stateless mode.
There is gonna be a problem in Stateless mode because file will be deleted.
Fixing the Stateless mode problem first.

**Comment by alimuzzaman** [comment]
@ewsopp 
### How it worked previously:
First run: `Utility::add_media()`
- we hook into `wp_update_attachment_metadata` filter.
- Sync all local files to GCS.
- Save metadata in sm_cloud meta.

### How it will work now:
First run: `Utility::add_media()`
- Now we hook into `intermediate_image_sizes_advanced` filter and sync the full size image.
- `intermediate_image_sizes_advanced` filter is called before generating the thumbnails in `wp_generate_attachment_metadata` function.
- Ignore other image sizes and don't delete the image in Stateless mode.
- Save metadata in sm_cloud meta.

Second run: `Utility::add_media()`
- we hook into `wp_update_attachment_metadata` filter.
- tries to sync full size image and ignore as it's exist in GCS.
- Sync all image sizes to GCS.
- Save metadata in sm_cloud meta.

**Comment by alimuzzaman** [comment]
Previous workflow:
1 - user adds image, original file upload begins.
2 - original file is uploaded locally. (in `tmp` dir)
3 - local upload completes. (in `wp-upload` dir)
5 - local file is used to create thumbnails.
6 - thumbnail generation completes.
7 - Images upload to GCS begins.
8 - Images upload to GCS completes.
9 - local files are deleted. (in Stateless mode)

Current workflow:
1 - user adds image, original file upload begins.
2 - original file is uploaded locally. (in `tmp` dir)
3 - local upload completes. (in `wp-upload` dir)
4 - GCS upload begins. (full size image)
5 - local file is used to create thumbnails.
6 - thumbnail generation completes.
7 - thumbnail upload to GCS begins.
8 - thumbnail upload to GCS completes.
9 - local files are deleted. (in Stateless mode)

**Comment by ewsopp** [comment]
@alimuzzaman is this implemented?

1 - user adds image, original file upload begins.
2 - original file is uploaded locally. (in tmp dir)
3 - local upload completes. (in wp-upload dir)
4 - GCS upload begins. (full size image)
5 - local file is used to create thumbnails.
6 - thumbnail generation completes.
7 - thumbnail upload to GCS begins.
8 - thumbnail upload to GCS completes.
9 - local files are deleted. (in Stateless mode)

**Comment by alimuzzaman** [comment]
@ewsopp Yes.

**Comment by alimuzzaman** [comment]
@ewsopp We need to wrap this feature into settings or a constant.
~~It's causing some conflict with other plugins.~~
