### ISSUE TITLE
SVG Upload

### ISSUE THREAD

**Issue by nicolaiskogheim** [udx/wp-stateless#287]
When on the `Sync` tab and using 

> Regenerate all stateless images and synchronize Google Storage with local server

`wp-stateless` reports `Unknown failure reason.` when it hits an SVG.

I have tried adding `svg` to the list of supported types, to no avail.
It would be great to be able to upload SVG's.

**Comment by alimuzzaman** [comment]
@nicolaiskogheim How you are uploading SVG images?
WordPress doesn't support SVG out of the box.

**Comment by nicolaiskogheim** [comment]
Via FTP. So when I use `wp-stateless`, I have some SVG files in my `/uploads` folder, but `wp-stateless` won't transfer them to Google Storage.

**Comment by alimuzzaman** [comment]
If you upload via FTP then there is no record of it in Media Library, in that case Stateless can't find them.
Stateless only transfer files in Media Library.

JFYI *Supported File Types* only work for *File URL Replacement* setting and don't transfer file only replace the url in content and meta.

**Comment by nicolaiskogheim** [comment]
Thank you! I installed a plugin to get support for SVG now.
Okay, so the files get uploaded, but `wp-stateless` still gives errors.

It would be much easier if `wp-stateless` reported something about the error. I know I have some HTML files that it may choke on, but the only message printed is, as I said, "Unknown failure reason."

Anyways, this issue can be closed, as `wp-stateless` clearly has support for SVG. :)
Thank you for your quick, and helpful response.

**Comment by alimuzzaman** [comment]
Thanks @nicolaiskogheim,
We will investigate the "Unknown failure reason".

**Comment by alimuzzaman** [comment]
Hi, @nicolaiskogheim
The problem has been fixed. Sorry for the miscommunication. 
The problem was that SVG image has no metadata.
You can download the fix from here:
https://github.com/wpCloud/wp-stateless/tree/fb285525753b8633d5e5b93963d4dc2c8ad922a4

Please check and let us know.

**Comment by nicolaiskogheim** [comment]
It works. I get no errors when running `Regenerate all stateless images and synchronize Google Storage with local server`.

Thank you again.

**Comment by dchenk** [comment]
I ran into this issue when trying to sync up existing SVG files. WordPress certainly supports SVG uploads—it just needs to be enabled. This is an important feature, so thank you for implementing it.

I'd like this fix in the main plugin trunk and published as soon as possible please. :) Thanks!
