### ISSUE TITLE
image thumbnail size metadata issue

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#29]
The full size image is reporting a 0x0 size. Looks like something went wrong with thumbnail generation.

ref http://smftampa.com/wp-admin/post.php?post=1528&action=edit

![2016-04-07_20-45-51](https://cloud.githubusercontent.com/assets/5578537/14371091/e954bbde-fd01-11e5-835d-8cb60ac913f7.jpg)

![image](https://cloud.githubusercontent.com/assets/5578537/14371105/14ffcabc-fd02-11e5-86d5-6c8ee93e7ad6.png)

**Comment by antonkorotkov** [comment]
No idea how could that happen. But I can say for sure it is not connected to metadata. Looks like file is physically missed.

I need to reproduce it somehow (I still cannot) to fix

**Comment by ewsopp** [comment]
How many thumbnails are you generating on your test setup?
