### ISSUE TITLE
revise domain field functionality to allow webmaster to control http or https

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#291]
[Several](https://github.com/wpCloud/wp-stateless/issues/242) [users](https://github.com/wpCloud/wp-stateless/issues/222) have requested the ability to enforce SSL with custom domains.

- [x] adjust placeholder value for _Domain_ field to `https://storage.googleapis.com`
- [x] allow webmaster to control "http" or "https" from _Domain_ field.
- [x] adjust the setting description text:
> Replace the default GCS domain with your own custom domain. This will require you to configure a CNAME. Be advised that the bucket name and domain name must match exactly, and HTTPS is not supported with a custom domain out of the box.

![image](https://user-images.githubusercontent.com/5578537/44173933-6c360280-a0af-11e8-8797-b89ee6218192.png)

**Comment by wiiiimm** [comment]
@ewsopp i have already added this feature and merged the feature into v2.1 https://github.com/wpCloud/wp-stateless/pull/282 

unless i have missed something here?

**Comment by alimuzzaman** [comment]
@williamli Sorry about that.
We have decided to not use that solution. 
The feature was available before your pull request but wasn't usable due to [a js bug](https://github.com/wpCloud/wp-stateless/commit/dd134f11c18059c800eacd438ce5e09b15dcda69#diff-0a3aef487b3735ff2b6f416c52ef637fL756).

**Comment by wiiiimm** [comment]
@alimuzzaman i see. sorry about that ;)

**Comment by roku6185** [comment]
Why is it a requirement that the bucket name and custom domain must match? That doesn't make sense. 

> Be advised that the bucket name and domain name must match exactly,

If I want a custom domain it shouldn't depend on my bucket name. I want to use this plugin with my custom CDN domain, but I can't because you impose restrictions how I setup my buckets.

**Comment by alimuzzaman** [comment]
Hello @roku6185 
It's restricted by Google. 
I am not sure how you can access the bucket with any domain!

https://cloud.google.com/storage/docs/naming
https://cloud.google.com/storage/docs/domain-name-verification

**Comment by roku6185** [comment]
That only applies if you want HTTP, i.e. setup a CNAME DNS record to point to your bucket. But, if you want to use HTTPS using Google Cloud you need a load balancer that handles SSL using your own certificate. I'm using the load balancer setup with multiple bucket names mapped to my CDN domain, e.g.

- https://cdn.mydomain.com/pdf/... => bucket-pdf-<MY_COMPANY_NAME>
- https://cdn.mydomain.com/video/... => bucket-video-<MY_COMPANY_NAME>
- https://cdn.mydomain.com/wordpress/... => bucket-wordpress-<MY_COMPANY_NAME>

**Comment by wiiiimm** [comment]
@roku6185 I think having an SSL option for a natively (Google) supported bucket - domain mapping is different to mapping domain / custom paths to different buckets

**Comment by alimuzzaman** [comment]
@roku6185 
Can you please test the recent update? You can get it [from here](https://github.com/wpCloud/wp-stateless/tree/431a049c9491425082e838f957dc41eb9a190aaa).

This could cause issue with non advance user. Who don't know what they are doing. I am thinking about adding a warning like the following.

@ewsopp what do you think?
![image](https://user-images.githubusercontent.com/6744156/45333517-71944900-b598-11e8-9225-1c1c2c26c43c.png)

**Comment by roku6185** [comment]
Awesome :+1: It works as expected:
* Files are uploaded to bucket
* Public URL for images use the custom domain

Thank you for fixing this issue.

**Comment by wiiiimm** [comment]
@roku6185 @alimuzzaman I tried this version as well and could not get the https to stick inside the domain text field, as soon as https:// is detected, it was removed.

**Comment by alimuzzaman** [comment]
@williamli 
It's probably browser or server cache.

**Comment by ewsopp** [comment]
@alimuzzaman if a custom domain is provided, shouldn't we update the preview file URL in real time?

![image](https://user-images.githubusercontent.com/5578537/46165927-e9809580-c25f-11e8-8465-bd9619272f7a.png)

**Comment by alimuzzaman** [comment]
@ewsopp Yes, we do that. It's working for me.
Could be browser caching problem. 
Check the browser console if there is any error.

**Comment by Mashenka** [comment]
working for me

**Comment by PaulChen79** [comment]
@roku6185  I have a question about your setup process. 

When you mention "That only applies if you want HTTP, i.e. setup a CNAME DNS record to point to your bucket", did you initially:

1. Set up HTTP access first using CNAME records pointing directly to your GCS buckets (like `cdn.mydomain.com CNAME c.storage.googleapis.com`), and then later migrate to the Load Balancer setup for HTTPS support?

OR

2. Go directly to the Load Balancer + A record setup from the beginning, skipping the HTTP + CNAME step entirely?

I'm trying to understand if the HTTP + CNAME approach is a stepping stone or if you're recommending to bypass it completely when HTTPS is the end goal.

Also, for your current Load Balancer setup with multiple buckets (pdf, video, wordpress), are you using:
- A single A record pointing `cdn.mydomain.com` to the Load Balancer IP?
- Path-based routing in the Load Balancer to different backend buckets?

Your setup sounds exactly like what I need, so any additional details would be super helpful! 🙏

**Comment by roku6185** [comment]
First of all I don't access to the setup I worked on 2018, so I probably don' t remember all the details, but let me try to give you an answer 😅I think I initially went with option 1 and later understood the limitations and changed to option 2. If I you want https then I say skip option 1.Yes, path-based routing was the way I did it using the single dns record.I hope you manage to set it up, good luck. 
-------- Originalmeddelande --------Från: Pin Hsu Chen ***@***.***> Datum: 2025-05-26  12:01  (GMT+01:00) Till: udx/wp-stateless ***@***.***> Kopia: Robin Kuivinen ***@***.***>, Mention ***@***.***> Ämne: Re: [udx/wp-stateless] revise domain field functionality to allow webmaster to control http or https (#291) PaulChen79 left a comment (udx/wp-stateless#291)
@roku6185  I have a question about your setup process.
When you mention "That only applies if you want HTTP, i.e. setup a CNAME DNS record to point to your bucket", did you initially:

Set up HTTP access first using CNAME records pointing directly to your GCS buckets (like cdn.mydomain.com CNAME c.storage.googleapis.com), and then later migrate to the Load Balancer setup for HTTPS support?

OR

Go directly to the Load Balancer + A record setup from the beginning, skipping the HTTP + CNAME step entirely?

I'm trying to understand if the HTTP + CNAME approach is a stepping stone or if you're recommending to bypass it completely when HTTPS is the end goal.
Also, for your current Load Balancer setup with multiple buckets (pdf, video, wordpress), are you using:

A single A record pointing cdn.mydomain.com to the Load Balancer IP?
Path-based routing in the Load Balancer to different backend buckets?

Your setup sounds exactly like what I need, so any additional details would be super helpful! 🙏

**Comment by PaulChen79** [comment]
@roku6185 Thanks for the detailed explanation! 🙏

I'm currently using your option 2 approach (HTTPS + Load Balancer + A record) as well. However, I'm running into an issue: even though I've configured my custom domain and the preview shows that it's using my custom domain correctly, when I actually upload images, the URLs still show the GCS default domain `https://storage.googleapis.com/` instead of my custom domain 🥹

I'm not sure what I might have configured incorrectly. BTW, I'm using stateless mode.

Have you encountered this issue before, or do you have any suggestions on what I should check? Any insights would be much appreciated!
