### ISSUE TITLE
wp-stateless conflict with Learndash plugin

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#292]
https://wordpress.org/support/topic/wp-stateless-conflict-with-learndash-plugin/
Hello there!

I need help troubleshooting an issue I’m having with my WordPress with Learndash plugin installed.

Problem:

When I enabled wp-stateless, the following message appears:

“One or more translation files have had their originals updated. Please update your edited versions of them.

pomo-editor/plugins/sfwd-lms/languages/learndash-pt_BR.po”

After that I checked my LearnDash and some of my selection box were missing:

BEFORE enabling wp-stateless
![image](https://user-images.githubusercontent.com/6744156/44221545-a5e83580-a1a3-11e8-86c4-cdc2a1df9000.png)

AFTER enabling wp-stateless
![image](https://user-images.githubusercontent.com/6744156/44221554-a97bbc80-a1a3-11e8-898c-2dd58abbfed5.png)

If I disable/delete wp-stateless everything works normally again on Learndash.
Any suggestions?

**Comment by alimuzzaman** [comment]
LearnDash had conflict with our <strong>Cache-Busting</strong> feature.

**Comment by ewsopp** [comment]
Please explain the problem in more detail. What do you suggest we change?

**Comment by ewsopp** [comment]
@alimuzzaman can we lowercase the related compatibility file?

![image](https://user-images.githubusercontent.com/5578537/46166970-86dcc900-c262-11e8-822d-56a1adb49d15.png)

**Comment by alimuzzaman** [comment]
@ewsopp done.

**Comment by Mashenka** [comment]
issue resolved
