### ISSUE TITLE
Need to revise Cache-Busting feature code

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#293]
Currently it's break many plugins if they uses sanitize_file_name.
If we can limit it's scope.

**Comment by alimuzzaman** [comment]
@ewsopp 
If we can limit the filter only to attachment upload or when we are uploading to GCS.
So that no other plugin get the randomized file name.

**Comment by ewsopp** [comment]
If the file is being uploaded to the Media Library, the feature should apply. 

If the feature is conflicting with a plugin, we should create specialized logic to allow the feature to work (via a compatibility), the plugin author should change their implementation, or the webmaster should disable the cache-busting feature.
