### ISSUE TITLE
Always getting an error - Could not connect to Google Storage bucket

### ISSUE THREAD

**Issue by tanint** [udx/wp-stateless#294]
Hi guys,
In a month ago it work correctly.
But now I always get below error:
WP-Stateless is not active due to following errors:
Could not connect to Google Storage bucket. Please, be sure that bucket with name MY_BUCKET exists.

I try to create new bucket name and create new credentials JSON file. account role is Storage admin , My Bucket name is the same with field in setting on Wordpress. But still has an errors.

Thank you,

**Comment by alimuzzaman** [comment]
@mypum How do you configured the Stateless?
Can you try automatic setup. 
There could be something wrong with **Service Account JSON**.

**Comment by tanint** [comment]
@alimuzzaman 
I try to automatic setup it work now. And I find how difference with manual config.
I found automatic setup will add Account permission again in Bucket. 
Default Storage Admin account will show in permission as "inherited", But If you add permission more 
 the label will change to "mixed". So I add permission for old account and It work now :)

Thank you,
