### ISSUE TITLE
Add compatibility with WP-Property-PDF add-on

### ISSUE THREAD

**Issue by Mashenka** [udx/wp-stateless#298]
you could check the new version of pdf here - https://udx-ci-develop-den.rabbit.ci/wp-admin/upload.php

right now pdf is not syncing with GCS, this is when I try to sync
![image](https://user-images.githubusercontent.com/5111163/45282756-87483680-b4e4-11e8-86b5-5fe00a766373.png)

**Comment by alimuzzaman** [comment]
@Mashenka I am getting `File not found` error.

**Comment by ewsopp** [comment]
Can we modify WP-Property PDF addon to work without a compatibility within WP-Stateless?

**Comment by Mashenka** [comment]
@Alim try with another file. That issue is resolving right now how to store/update pdf. Just update the property and use the latest file from the media library. I have sent you pdf zip so you could test on your branch if you need

@ewsopp I’m not sure why it is not working now so I can’t answer the question, I need some comments from @Alim

**Comment by alimuzzaman** [comment]
@ewsopp Yes, we should make changes to the `WP-Property PDF` plugin.

**Comment by Mashenka** [comment]
Ok. closing this issue right now here and will open in WP-Property-PDF repository
