### ISSUE TITLE
Switch from one bucket to an other

### ISSUE THREAD

**Issue by jacquesletesson** [udx/wp-stateless#30]
Hello there,

Thank you for this really cool plugin, it saves us a lot of time.

All our assets were on a simple bucket, we transfer all our assets to assets.company.com

Is there an easy way to replace all postmeta with key_value 'sm_cloud' to our new bucket?

Would love to avoid to regenerate all images, cause it took a while.

Cheers,

J.

**Comment by Mashenka** [comment]
Hello.

You can just add new bucket and sync all you images from your site to there. This option under Tools tab.

Regards.
