### ISSUE TITLE
Gzip

### ISSUE THREAD

**Issue by mjezegou** [udx/wp-stateless#305]
I would like compress all image with GZIP (Content-Encoding:gzip - $args['contentEncoding'] ) on google storage.
Is it possible or i add another plugin for compression only images ?
Thank you for your reply

**Comment by mjezegou** [comment]
So i add wp-smushit in my project.  
For now, the tests are satisfactory since version 2.1.7 and integration of compatibility.

**Comment by mjezegou** [comment]
I work with docker and I build my containers. I am fully stateless.
I find that with wp-smushit that when an image is not used, it is stored locally and not in the cloud. It is then impossible to rework with (integration in the pages and compression Smush).

**Comment by mjezegou** [comment]
I also note that images are not removed from the cloud, when we delete the image from the library

**Comment by alimuzzaman** [comment]
> I also note that images are not removed from the cloud, when we delete the image from the library

Are you sure that **Delete GCS File** setting is enabled?

**Comment by mjezegou** [comment]
![image](https://user-images.githubusercontent.com/26108995/48057028-536f5180-e1b3-11e8-82e2-cf1eeef2fcd0.png)
![image](https://user-images.githubusercontent.com/26108995/48057234-cc6ea900-e1b3-11e8-8f76-825f960a381a.png)
Yes.
on the other hand, it is not defined in the wp-config in this form:
define ('WP_STATELESS_MEDIA_DELETE_REMOTE, true);

**Comment by antonkorotkov** [comment]
@alimuzzaman is it related to WP Smush compatibility? Were you able to check what is wrong there?

**Comment by planv** [comment]
Hello @mjezegou 

Is issue still relevant?
