### ISSUE TITLE
Corrupt and missing attachement metadata with Polylang

### ISSUE THREAD

**Issue by Hooace** [udx/wp-stateless#306]
When Polylang plugin's Media translation is enabled and user uploads an image to Media gallery, the _wp_attachment_metadata is corrupted for the image. Also no _wp_attachment_metadata is written for other than main language at all.
![screen shot 2018-10-05 at 11 34 38](https://user-images.githubusercontent.com/469061/46524829-b14a0a00-c892-11e8-9e77-938cbf5778fc.jpg)
 
Here is the corrupted meta:
![screen shot 2018-10-05 at 11 36 51](https://user-images.githubusercontent.com/469061/46524946-fa01c300-c892-11e8-9290-2fd6531e994d.jpg)

If user regenerates metadata using WP Stateless plugin's sync feature the metadata is fixed for all languages.

![screen shot 2018-10-05 at 11 40 51](https://user-images.githubusercontent.com/469061/46525168-93c97000-c893-11e8-99a7-970af6deb747.jpg)

![screen shot 2018-10-05 at 11 40 09](https://user-images.githubusercontent.com/469061/46525139-7d231900-c893-11e8-84f4-01eceb9014f7.jpg)

**Comment by alimuzzaman** [comment]
Hello @Hooace 
Wasn't able to replicate the issue with latest version of Polylang (2.5).
I used [development version](https://github.com/wpCloud/wp-stateless/tree/develop-alim) of the WP Stateless.

**Comment by Hooace** [comment]
Ok, thanks for the info. I'll try to replicate the issue with Polylang 2.5  and dev version.

**Comment by antonkorotkov** [comment]
@ewsopp can we move this to the next milestone?

**Comment by antonkorotkov** [comment]
@Hooace hey, do you still have any issues with Polylang?

**Comment by antonkorotkov** [comment]
Ok, assuming there are no issues anymore. Please create a new issue if you still have any problems.
