### ISSUE TITLE
sm_synced very large

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#307]
https://wordpress.org/support/topic/sm_synced-very-large/

Hello,
I’ve been looking in the WP_options (after seeing a decrease in load time on the site). The option “sm_synced”, is auto-loaded everywhere – and currently is almost 2MB (!!!), which is an impact on the system u don’t want.

I’ve found the code – relating to files that needs to be registered. Currently it’s only populated with Backup media from ShortPixel; which is already offloaded to Google Cloud (integration is turned on). The files do appear in Google cloud The complete list looks to be populated in the following order:

ShortpixelBackups/wp-content/uploads/2018/08/filename.png”;i:975;s:80:”ShortpixelBackups/wp-content/uploads/2018/08/filename.jpg”;i:976;s:80:”ShortpixelBackups/wp-content/uploads/2018/08/filename.jpg”

Few options to fix it that I could think of, but maybe you have a better idea?
– Turn the autoload off in WP_options
– Clean /empty the field (don’t know the impact?)
– ???
Could you please advice, I see it hapening on a different set-up and domain that we have as well (also having Shortpixel & Stateless).

Loving the work and features for the rest btw!

**Comment by alimuzzaman** [comment]
I am thinking about creating a DB table

![image](https://user-images.githubusercontent.com/6744156/50789689-2c361d00-12e7-11e9-94b7-3c36b2e9d892.png)

**Comment by antonkorotkov** [comment]
@alimuzzaman Ok. Can you explain the idea of using `expire` field?

**Comment by alimuzzaman** [comment]
@antonkorotkov Some plugin generated files isn't possible to track when it's get updated, we can resync after a period of time.
Skipping the `expire` field for now.

**Comment by alimuzzaman** [comment]
### status: this field have two options.

- queued
- synced

**Comment by antonkorotkov** [comment]
It works. I see new table created after upgrade and files are being logged into it upon non-library sync.
