### ISSUE TITLE
Make the process completed if there is nothing to do

### ISSUE THREAD

**Issue by Mashenka** [udx/wp-stateless#309]
e.g I do not have non-media files and when trying to sync them just looks like this forever

![image](https://user-images.githubusercontent.com/5111163/47093548-1eb24f00-d232-11e8-8763-a5f59a9ad121.png)

**Comment by alimuzzaman** [comment]
@Mashenka how this sounds?
![image](https://user-images.githubusercontent.com/6744156/47108022-99985b80-d26c-11e8-8a32-af76e165ffc3.png)

**Comment by Mashenka** [comment]
@alimuzzaman Not clear about what I need to enable and why. Wу could end up on Nothing to sync and without details. What do you think @ewsopp ?

**Comment by alimuzzaman** [comment]
By default it's sync nothing. It's only work when some compatibility enabled.
That's why sometime user can get confused.

**Comment by ewsopp** [comment]
Is this option for compatibilities only?

**Comment by alimuzzaman** [comment]
@ewsopp Yes

**Comment by ewsopp** [comment]
Can we display this option only when a relevant compatibility is enabled?

**Comment by ewsopp** [comment]
Which compatibilities require a sync process?

**Comment by alimuzzaman** [comment]
- Elementor
- GravityForm
- SO Widgets Bundle

**Comment by alimuzzaman** [comment]
> Can we display this option only when a relevant compatibility is enabled?

We can do that.

**Comment by ewsopp** [comment]
SiteOrigin CSS doesn't require manual sync functionality?

**Comment by alimuzzaman** [comment]
SO Widgets Bundle is so css

**Comment by ewsopp** [comment]
They are two separate plugins, which should have separate compatibilities. 

![image](https://user-images.githubusercontent.com/5578537/47158521-db9bbe80-d2b9-11e8-99f4-44758d8006b0.png)

**Comment by alimuzzaman** [comment]
Sorry, yes they are separated.

> SiteOrigin CSS doesn't require manual sync functionality?

No, it's not require manual sync.

**Comment by alimuzzaman** [comment]
> Can we display this option only when a relevant compatibility is enabled?

Done

**Comment by ewsopp** [comment]
Great. One last scenario then...

If these compatibilities are enabled and a process is ran that has no files to process, display this message:

> There are no files to process.

**Comment by ewsopp** [comment]
@alimuzzaman please assign to @Mashenka for review once the above comment is implemented.

**Comment by alimuzzaman** [comment]
@Mashenka please review this.

**Comment by Mashenka** [comment]
Checked
