### ISSUE TITLE
Metadata missing on thumbnails

### ISSUE THREAD

**Issue by stbeli** [udx/wp-stateless#31]
Metadata doesn't exist on generated thumbnails as on original image.
![nometadata](https://cloud.githubusercontent.com/assets/1846634/15215612/ac510dce-1853-11e6-858f-4fdae148ad05.jpg)

**Comment by ewsopp** [comment]
seems related to https://github.com/wpCloud/wp-stateless/issues/29

**Comment by antonkorotkov** [comment]
Sorry, cannot replicate that. There actually should not be any difference between original and rezised.
<img width="1003" alt="00000210" src="https://cloud.githubusercontent.com/assets/2276882/15783586/741e025c-29b7-11e6-8afd-7c852fa2f87e.png">

Try resyncing

**Comment by ewsopp** [comment]
I couldn't replicate either. Below is a screenshot of the meta data of an original and thumbnail.

![image](https://cloud.githubusercontent.com/assets/5578537/15787208/ebd8b694-298e-11e6-980b-1a3497f6e3c1.png)

![image](https://cloud.githubusercontent.com/assets/5578537/15787210/edf59abe-298e-11e6-90cb-82add857afa1.png)

@stbeli what version of stateless media are you using?

**Comment by antonkorotkov** [comment]
From `latest` branch

**Comment by ewsopp** [comment]
Closing since there is no problem here.

**Comment by antonkorotkov** [comment]
I actually could replicate it. Re-openning.

**Comment by antonkorotkov** [comment]
fixed
