### ISSUE TITLE
HTTPS with custom domain

### ISSUE THREAD

**Issue by izzuddinrazi** [udx/wp-stateless#311]
is it possible to use custom domain with https?

**Comment by alimuzzaman** [comment]
Hi @izzuddinrazi,
Not by default, but you can do it by using CDN services like **Cloudflare** or **load balancer**.

**Comment by walle89** [comment]
As alimuzzaman said it's not possible out of the box(https://cloud.google.com/storage/docs/request-endpoints#cname). You need to setup a load balancer and use a front-proxy CDN service like Coludflare. It's maybe possible to use a regular CDN Service like Google CDN, I haven't tied it.

**Comment by antonkorotkov** [comment]
Closing. Reopen if still have questions.

**Comment by pritamroy2018** [comment]
i am using this plugin here
https://guidetour.in/media-test/
media does not show on the page but WP editor show media. Right click on page "open media on new page" then show media here "https://cdn.guidetour.in/2023/06/e1757ec8-parking-bg.ecaf4b09-1024x276.png"
Now Plugin setting i am using "Ephemeral"
Please give me a solution how to solve this (same issue on "Stateless" mode
