### ISSUE TITLE
Support .doc and .docx files

### ISSUE THREAD

**Issue by dchenk** [udx/wp-stateless#316]
The plugin should support syncing “.doc” and “.docx” files. Such files are permitted to upload even on wordpress.com. This is no different from PDF files.

This is a pressing need especially when activating WP-Stateless on an existing site that has such documents. If you can’t sync all images and files, it may not be possible to use the plugin at all (as it was for me).

I’m looking forward to this enhancement, and thank you for all the great work you do!

**Comment by ewsopp** [comment]
Did you try adding these file extensions to the _Supported File Types_ field?

**Comment by alimuzzaman** [comment]
@ewsopp `Supported File Types` don't sync the files.

**Comment by dchenk** [comment]
Sorry, where can I find this setting anyway?

**Comment by alimuzzaman** [comment]
Stateless Settings page.

**Comment by alimuzzaman** [comment]
What problems are you facing actually?
Stateless can sync everything on your media library. 
Is the doc files 📂 are being uploaded to the library?

**Comment by dchenk** [comment]
The docs were previously there, uploaded to WP the normal way. When I
installed the plugin and clicked the Sync button, I got errors for all doc
and docx files.

**Comment by alimuzzaman** [comment]
@dchenk 
Are you sure you choose this option?

> Synchronize non-images files between Google Storage and local server

![image](https://user-images.githubusercontent.com/6744156/47812968-f10def80-dd73-11e8-9e36-3bee5bd8954c.png)

**Comment by alimuzzaman** [comment]
@dchenk 
Please [try this fix](https://github.com/wpCloud/wp-stateless/tree/1cff7bd2b2a846145af2856832e92b97f1313e9f) and let me know if this solves your problem.
https://github.com/wpCloud/wp-stateless/tree/1cff7bd2b2a846145af2856832e92b97f1313e9f

**Comment by leepeterson** [comment]
Same problem since first using this plugin. The "Supported File Types" should take a cue from CDN Enabler and offer up an *exclusion list* rather than trying to guess what a client might upload.

Trying any of these:
`jpg jpeg png tif gif pdf svg json css js html txt m4v m4a mp3 mp4 webm ogg ogv md yml ttf woff woff2 otf doc docx xls xlsx ppt pptx csv rtf`
may only sync `jpg jpeg png gif pdf mp4`, and not reliably either.

**Comment by dchenk** [comment]
Thank you!
