### ISSUE TITLE
Conflict between wp-stateless 2.1.8 and Onecodeshop RML AWS/S3 plugin 

### ISSUE THREAD

**Issue by jjtroberts** [udx/wp-stateless#317]
We use wp-stateless to store client uploaded assets in GCS, while simultaneously using RML AWS/S3 to serve a curated library of images out of S3 and Cloudfront.

We did not experience the conflict below with wp-stateless 2.1.7, and reverting to that version resolved the issue.

| remote-medias-lite                  | active   | none      | 1.6.3   |
| remote-media-pro-amazons3           | active   | none      | 2.0.0   |
| wp-stateless                        | active   | available | 2.1.7   |

Kubernetes 1.10.x
PHP 7.1.17
Alpine Linux 4.14.x base image
Wordpress 4.9.8

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function wpCloud\\StatelessMedia\\Bootstrap::before_intermediate_image_sizes(), 1 passed in /var/www/localhost/htdocs/web/wp/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /var/www/localhost/htdocs/web/app/plugins/wp-stateless/lib/classes/class-bootstrap.php:1263
Stack trace:
#0 /var/www/localhost/htdocs/web/wp/wp-includes/class-wp-hook.php(286): wpCloud\\StatelessMedia\\Bootstrap->before_intermediate_image_sizes(Array)
#1 /var/www/localhost/htdocs/web/wp/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#2 /var/www/localhost/htdocs/web/app/plugins/remote-media-pro-amazons3/vendor/onecodeshop/wprmlbase/src/Media/WPImageSizes.php(78): apply_filters('intermediate_im...', Array)
#3 /var/www/localhost/htdocs/web/app/plugins/remote-media-pro-amazons3/vendor/onecodeshop/wprmlbase/src/Media/WPImageSizes.php(111): WPRMLAmazonS3\\Onecodeshop\\RMLBase\\v120\\Media\\WPImageSizes::getRegisteredSizes()
#4 /var/www/localhost/htdocs/web/app/plugin in /var/www/localhost/htdocs/web/app/plugins/wp-stateless/lib/classes/class-bootstrap.php on line 1263
```

**Comment by jjtroberts** [comment]
For reference:

https://www.onecodeshop.com/downloads/wordpress-rml-for-amazon-s3-cloudfront-plugin/

**Comment by alimuzzaman** [comment]
@gd-jroberts 
I have added a fix, you can get it [from here](https://github.com/wpCloud/wp-stateless/tree/8bd0dde55bcef05768dd2e7350f4b3da437393a9): 
It was related to this feature #286.

Seems like they called the filter with only one argument instead of two. Second parameter was added in WordPress 4.4.0 version.
