### ISSUE TITLE
Bucket Value No Longer Included as of v2.1.8 

### ISSUE THREAD

**Issue by leepeterson** [udx/wp-stateless#318]
WP-Stateless v2.1.8 has broken over a dozen websites we maintain within the past 48 hours.

Bucket name hasn't changed and continues to show within the field below "Bucket".

However, the URL displayed within the field below "Preview" as well as all front-end references to newly-uploaded media is 100% broken.

Example: https://storage.googleapis.com/bucket-name/bucket-folder/2018/11/filename.jpg is now https://storage.googleapis.com/bucket-folder/2018/11/filename.jpg

This is the final issue we'll be logging for WP-Stateless. We're uninstalling it from all websites today, replacing it with something that's more carefully checked for errors.

Good luck, wpCloud.

**Comment by ewsopp** [comment]
@leepeterson thanks for reporting, and good luck.

**Comment by alimuzzaman** [comment]
@leepeterson Seems like you have set the `Domain` field to `storage.googleapis.com`, which should have been empty unless you use a custom domain.

**Comment by leepeterson** [comment]
@alimuzzaman that is an incorrect assumption. That is also not the issue at hand.

**Comment by alimuzzaman** [comment]
@leepeterson 
Here is [a fix](https://github.com/wpCloud/wp-stateless/tree/13a5e1fca19f418d856aa9b9eb7c3bbaa3f97573) if you change your mind. 
https://github.com/wpCloud/wp-stateless/tree/13a5e1fca19f418d856aa9b9eb7c3bbaa3f97573
