### ISSUE TITLE
Support bmp files

### ISSUE THREAD

**Issue by dchenk** [udx/wp-stateless#319]
The plugin does not appear to support .bmp files. The [BMP](https://en.wikipedia.org/wiki/BMP_file_format) image format can be common and is accepted as WP media.

**Comment by alimuzzaman** [comment]
Hi @dchenk ,
It's just WordPress not allowing you to upload BMP files.

If you can make it to the media library then **Stateless** will sync the image.
WP Stateless will sync anything if it can make to the media library.

On my test Stateless was successfully able to sync the image to GCS on upload.
> To test it I enabled unfiltered uploads by constant.

**Comment by antonkorotkov** [comment]
@dchenk Hey. So as you can see WordPress (at least 5.0) does not support BMP image format by default:

![image](https://user-images.githubusercontent.com/2276882/54109447-5e4b2480-43e7-11e9-9f16-f21d310e895f.png)

Check this out https://wpsmackdown.com/add-remove-filetypes-wordpress-media-library/ on how to control allowed types. 

WP-Stateless will be able to process it once type is allowed.
