### ISSUE TITLE
Don't show Service Account JSON contents when set by a constant

### ISSUE THREAD

**Issue by dchenk** [udx/wp-stateless#320]
I think an important security feature that should be added is to not display the Service Account JSON field value in the settings panel when the JSON key is set with a PHP constant. What's the point of showing the JSON anyway? The user can't edit it from wp-admin, and they don't need to see it for any reason. This is especially a security threat where I'm letting a client use a bucket that I'm paying for.

I'd like to hear all your thoughts about this. Doesn't it sound like the right thing to do?

Thanks!

**Comment by dchenk** [comment]
@alimuzzaman or @ewsopp will we be seeing this feature in the next release? I'd really appreciate it.

**Comment by alimuzzaman** [comment]
@dchenk yes this will be on next release.

**Comment by alimuzzaman** [comment]
@dchenk @ewsopp how does this look? Any suggestion?
Should I make the box empty or the message is good?
![image](https://user-images.githubusercontent.com/6744156/50405072-932cdf80-07d9-11e9-8678-4ce593c6e931.png)

**Comment by dchenk** [comment]
That's really great. You can even have the textbox not show up but just display the message. Thank you :)

**Comment by ewsopp** [comment]
Looks good, but adjust the text within the text box...

> Currently configured via a constant.

You missed the "a" before _constant_.

**Comment by alimuzzaman** [comment]
@dchenk removing isn't good idea.

**Comment by alimuzzaman** [comment]
@antonkorotkov do you have any idea about what to do with the `textarea` when not showing the JSON key?

Showing `Currently configured via a constant.` inside `textarea` is redundant because it's already exists bottom.

**Comment by ewsopp** [comment]
It's fine, just leave it as is.
