### ISSUE TITLE
Serve Images from Google Cloud, but disable Cloud for new images

### ISSUE THREAD

**Issue by kLOsk** [udx/wp-stateless#321]
Bit of a silly question maybe, but I would like to disable cloud upload for new images, but continue serving already uploaded images from cloud. This is a setting just for my local dev environment. Currently I have all images on cloud, and none locally, but when I disable Stateless, the urls are replace by local urls again and thus not available. Is it possible to keep urls with cloud for existing images and only serve new uploads locally?

**Comment by alimuzzaman** [comment]
@kLOsk You have to do some hacking. Remove this filter and image will no longer be synced.
`add_filter( 'wp_update_attachment_metadata', array( 'wpCloud\StatelessMedia\Utility', 'add_media' ), 999, 2 );`

This is the main entry point for sync to start, though there are others.

**Comment by alimuzzaman** [comment]
Some **Stateless Compatibility** could initiate the sync even you remove the above filter. In that case you should look in `lib/classes/compatibility` dir.

**File URL Replacement** setting could cause some issue if enabled.

Let us know if this works.

**Comment by kLOsk** [comment]
Thanks ali! I'll give it a shot!

**Comment by barrosohub** [comment]
> @kLOsk You have to do some hacking. Remove this filter and image will no longer be synced.
> `add_filter( 'wp_update_attachment_metadata', array( 'wpCloud\StatelessMedia\Utility', 'add_media' ), 999, 2 );`
> 
> This is the main entry point for sync to start, though there are others.

In which file and on which line is this snippet of code?

add_filter ('wp_update_attachment_metadata', array ('wpCloud \ StatelessMedia \ Utility', 'add_media'), 999, 2);

**Comment by kLOsk** [comment]
@barrsofilho wp-content/plugins/wp-stateless/lib/classes/class-bootstrap.php line 224
tho better than uncommneting is probably:
`remove_filter( 'wp_update_attachment_metadata', array( 'wpCloud\StatelessMedia\Utility', 'add_media' ), 999 );` (not tested yet)

**Comment by barrosohub** [comment]
Not working :/

**Comment by alimuzzaman** [comment]
Sorry forgot to mention another new filter added recently. Please checkout this issue #286.

**Comment by antonkorotkov** [comment]
Looks resolved. Closing.
