### ISSUE TITLE
PHP Warnings and Notices

### ISSUE THREAD

**Issue by Mashenka** [udx/wp-stateless#322]
```
I have seen tons of this warnings in wp-content/debug.log when I turn on wordpress debugging.

[29-Nov-2018 14:57:02 UTC] PHP Warning: Invalid argument supplied for foreach() in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/classes/class-bootstrap.php on line 259
```

https://wordpress.org/support/topic/invalid-argument-supplied-for-foreach-124/

**Comment by alimuzzaman** [comment]
dcngibson (@dcngibson)
https://wordpress.org/support/topic/plugin-conflict-on-webapp/

1 month ago
Hello Dynamic,
Stateless is have conflict with this my super progressive webapps plugin.
See message hereunder:

Warning: Illegal string offset ‘file’ in /home/dcngibso/public_html/wp-content/plugins/wp-stateless/lib/classes/compatibility/wp-smush.php on line 118

Warning: Illegal string offset ‘gs_name’ in /home/dcngibso/public_html/wp-content/plugins/wp-stateless/lib/classes/compatibility/wp-smush.php on line 120

I need a fix to this.
Thanks
