### ISSUE TITLE
WPBakery Page Builder compatibility

### ISSUE THREAD

**Issue by fujixmad** [udx/wp-stateless#324]
Hi,

I have a theme that uses WPBakery Page Builder but it comes part of the theme so the location of the plugin is not in the standard location and thus, Stateless doesn't seem to see it as installed or activated...

Is there a file I can edit to change some sort of path to tell it to look in another location?

**Comment by alimuzzaman** [comment]
@fujixmad in this line
https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/compatibility/wpbakery-page-builder.php#L19

**Comment by fujixmad** [comment]
Thank you
