### ISSUE TITLE
Issue With Imagify

### ISSUE THREAD

**Issue by TheOneWizard1** [udx/wp-stateless#326]
Image minification & sync was working for a short time but in a recent test, it appears to be broken any ideas on how to fix?

Server Detailed:

Server Environment |   |  -- | -- | --
Operating System: | Linux |  
Software: | nginx/1.14.1 |  
MySQL version: | (Ubuntu) v5.7.24 |  
PHP Version: | 7.2.13 |  
PHP Max Input Vars: | 1000 |  
PHP Max Post Size: | 512M |  
GD Installed: | Yes |  
ZIP Installed: | Yes |  
Write Permissions: | All right

Settings:
Wp-stateless
Mode | Stateless 
File URL Replacement | Enabled
Compatibility | Imagify (Checked)

Imagify 
Auto-Optimize images on upload | (Checked)
Backup original images | (Checked)
Resize | 1920px

On Upload PHP Error|
4283#0: *13591 FastCGI sent in stderr: "PHP message: PHP Warning: exif_imagetype(/var/www/vhosts/in-telligent.com/staging.in-telligent.com/wp-content/uploads/86a808eb-e-logo-horizontalartboard-1152-px.png): failed to open stream: No such file or directory in /var/www/vhosts/in-telligent.com/staging.in-telligent.com/wp-content/plugins/imagify/inc/classes/class-imagify-filesystem.php on line 506" while reading response header from upstream
--

**Comment by alimuzzaman** [comment]
@TheOneWizard1 can you please try [this hotfix](https://github.com/wpCloud/wp-stateless/archive/hotfix.zip) and let us know.
https://github.com/wpCloud/wp-stateless/tree/hotfix

**Comment by alimuzzaman** [comment]
Also problem is reported in WP.org forum
https://wordpress.org/support/topic/imagify-and-wp-stateless/

**Comment by alimuzzaman** [comment]
~With this update the when adding image with `Add Image button` in post editor image will seems to be broke because the optimization and upload to GCS take some time.
In that case you have to enable `File URL Replacement` to replace your server URL to GCS URL on the fly.~

**Comment by TheOneWizard1** [comment]
alimuzzaman, forgive me been away for just jumping in been away for the holidays.

Can confirm that all checks out with the Hotfix plugin.

Much appreciate your efforts here.
