### ISSUE TITLE
This two feature are causing problem.

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#327]
1. File URL Replacement on post meta. (#265)
2. ~~The new upload full image first. (#286) Causing problem in stateless and image optimizer.~~

Possible Solution:
1. Need to rewrite the code for that function. ([suggested by](https://github.com/wpCloud/wp-stateless/issues/265#issuecomment-412843090) @antonkorotkov)
2. ~~maybe disable by default.~~

**Comment by alimuzzaman** [comment]
@ewsopp Please advice.

**Comment by alimuzzaman** [comment]
@ewsopp 
Though feature #286 (upload full image first) not causing any problem we should add constant to disable it if needed.

How this sounds `WP_STATELESS_MEDIA_DISABLE_FULL_IMAGE_FIRST`?
Not available in `Settings` tab.

**Comment by alimuzzaman** [comment]
Issue no 1 handled in #336.

**Comment by antonkorotkov** [comment]
Will close this issue once https://github.com/wpCloud/wp-stateless/issues/265 is closed.

**Comment by antonkorotkov** [comment]
All points done here
