### ISSUE TITLE
Bug in wp_calculate_image_srcset

### ISSUE THREAD

**Issue by larsha** [udx/wp-stateless#328]
Hi,

I think I have found a bug in https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-bootstrap.php#L253

The bug is that you are only checking against the width there. (https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-bootstrap.php#L265) That will result in wrong srcset output for certain images. Let's say we have two images registered in WP with the same width but different height/crop etc. Your check there can grab the wrong file url and replace with gs_link. 

That functions has to be changed, to use something like `wp_image_matches_ratio` instead. Or rewrite it in some way. Because the variable `$sources` will include the correct file urls since WP is using the `wp_image_matches_ratio` in their filter.

Let me know if you understand the bug then I can provide a PR solving this issue if you don't have time to adjust it.

**Comment by Mashenka** [comment]
@alimuzzaman please check this

**Comment by alimuzzaman** [comment]
Hi @larsha,
PR requests are always welcome and it would be helpful.
Send a PR request to the `latest` branch.

**Comment by larsha** [comment]
@alimuzzaman I have created a PR now (#333). Let me know what you think of the approach.
