### ISSUE TITLE
Serve image from existing google cloud storage

### ISSUE THREAD

**Issue by scne** [udx/wp-stateless#329]
Hi there, I've my google storage bucket organized to match my inner policy:

```
├── ...
├── manufacturer_id
│   ├── code_image.jpg          
│   ├── code_image.jpeg
│   └── code_image.jpeg
```
This bucket is filled by a custom integration between google cloud storage and my products management software. On the other hand, another integration to push my products on woocommerce. I'm using woocommerce API to insert new products and update old ones. When I insert new product I need to pass a google storage cloud address related to its photo. How can I use this plugin in this scenario?

**Comment by scne** [comment]
Is it possible using dynamic **Bucket Folder** into configuration?

**Comment by antonkorotkov** [comment]
Hey @scne. Is it still relevant? It looks like I do not completely understand your use case. Can you describe it in more details?

**Comment by antonkorotkov** [comment]
Closing due to no response. Please feel free to re-open.
