### ISSUE TITLE
Moving existing media to cloud storage

### ISSUE THREAD

**Issue by solepixel** [udx/wp-stateless#33]
Has anyone come up with a way to get existing media over to cloud storage? I've started working on a TSV generator script to do the transfer but nothing is transferring, still trying to figure out a way to get a TON of media files on there. Any suggestions?

**Comment by ewsopp** [comment]
Did you try the stateless sync feature under the 'Tools' menu? It will regenerate all the thumbnails, upload them into GCS, and update the file-paths to point to the GCS urls on the library objects. Works on images and non-images.

**Comment by solepixel** [comment]
Tried it but nothing transferred. The site is behind basic authentication,
could that be why it failed?

**Comment by solepixel** [comment]
I disabled basic authentication, but this is what I get when I try: http://3cd.co/2v1s12140Y0Q (No images media objects found. - Status: Error appeared)

**Comment by solepixel** [comment]
Still researching this, I think I'm having disk space issues which is why the query to fetch the images is throwing an error. I'll update if this is an issue on my end.

**Comment by Mashenka** [comment]
Hello, solepixel 

Do you have feedback? I will close this issue here. If you will have questions or suggestions, please use following contact form
https://www.usabilitydynamics.com/contact-us
or our user feedback forum here
http://feedback.usabilitydynamics.com/forums/353541-wp-statless
