### ISSUE TITLE
Gravity forms single file upload issue

### ISSUE THREAD

**Issue by Jeradin** [udx/wp-stateless#332]
Hello there,

Single file uploads do not seem to be working with your plugin, multiple files do seamlessly. 

I have been var_dumping to track down the issue and not finding found to fix it, but I think it relates to unique_names. Your function gform_save_field_value on line 44 of gravity-forms.php filter seems to var dump the filename of the GF unique name, but the actual file with the unique name has not been moved to the temp folder yet.

So no file moves to the google storage. I will try to get more detailed information.

**Comment by Jeradin** [comment]
I have tracked down the cause but did not track down the fix.

Its the plugins own setting of **Cache-Busting**, when I disable that the single file field works as it should

**Comment by antonkorotkov** [comment]
@alimuzzaman need to check if this could be fixed in term of Gravity Forms compatibility.

**Comment by alimuzzaman** [comment]
@Jeradin it's working fine for me.
@antonkorotkov I can't replicate the issue.

**Comment by antonkorotkov** [comment]
@alimuzzaman you checked with Cache-Busting enabled/disabled, right?

**Comment by alimuzzaman** [comment]
@antonkorotkov Yes, I tested with both enabled and disabled.
I have used `File Upload` field without any modification.

**Comment by Jeradin** [comment]
@alimuzzaman Single field upload, not multi upload? I will update the plugin and test again.

**Comment by alimuzzaman** [comment]
@Jeradin Yes, I used single file field, didn't select the `Enable Multi-File Upload` checkbox.

**Comment by antonkorotkov** [comment]
Hey @Jeradin 

Did you have a chance to test with the latest plugin version?

**Comment by Jeradin** [comment]
@antonkorotkov I did and right now having GF Stateless extension being active breaks my upload fields completely after the latest update. I am going to assume its something on the WP multisite install since its working for you all. 

I will create a fresh local site this weekend and run more tests.

Thank you for your time.
