### ISSUE TITLE
GIF resizing changes GIF to a single static image

### ISSUE THREAD

**Issue by tomlarkworthy** [udx/wp-stateless#335]
The source gif is uploaded fine:-
https://storage.googleapis.com/stateless-corepoxblog-com/2019/01/Jan5_2019-1.gif

But stateless resizes it and loses the video aspect in the process.
https://storage.googleapis.com/stateless-corepoxblog-com/2019/01/Jan5_2019-1-320x348.gif

I tried to disable gif processing but https://github.com/wpCloud/wp-stateless/issues/334

**Comment by alimuzzaman** [comment]
Hello @tomlarkworthy,
The issue isn't on our side, that's how WordPress handle the GIF.

**Comment by tomlarkworthy** [comment]
dang, thanks
