### ISSUE TITLE
extend "File URL Replacement" options

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#336]
![image](https://user-images.githubusercontent.com/5578537/50844737-6203f180-1339-11e9-835f-72eb02d60b86.png)

- [x] Change options to the following:

- Disable
- Enable Editor
- Enable Meta
- Enable Editor & Meta

- [x] Adjust the description from: 
> Scans post content and meta during presentation and replaces local media file urls with GCS urls. This setting does not modify your database.

to:
> Scans post content and meta during presentation and replaces local media file urls with GCS urls. Depending on the amount of meta, this could be significantly impact performance negatively. This setting does not modify your database.

- [ ] ensure that "File URL Replacement" option is disabled by default for new installations.

**Comment by alimuzzaman** [comment]
@ewsopp 
What if user had it enabled, then which one it should get migrated to?
`Enable Editor & Meta`?

**Comment by alimuzzaman** [comment]
![image](https://user-images.githubusercontent.com/6744156/50929722-2fb4da00-1488-11e9-9395-855353f6bf17.png)

**Comment by ewsopp** [comment]
Correct, if they had it `Enable` previously we will migrate them to the new `Enable Editor & Meta` option.

**Comment by ewsopp** [comment]
We need to update the related constant. https://github.com/wpCloud/wp-stateless/wiki/Constants#wp_stateless_media_body_rewrite

- default value: `false`
- options: `editor`, `meta`, or `true`

True would enable both editor and meta scanning. The other options should explain themselves. 

This would allow it work well for people who are already using this setting.

**Comment by alimuzzaman** [comment]
@ewsopp Options updated.


I think we should add **When selecting `meta` or `true`** to be clear.

> Scans post content and meta during presentation and replaces local media file urls with GCS urls. Depending on the amount of meta, this could be significantly impact performance negatively. This setting does not modify your database.

To

Scans post content and meta during presentation and replaces local media file urls with GCS urls. When selecting `meta` or `true` depending on the amount of meta, this could be significantly impact performance negatively. This setting does not modify your database.

**Comment by antonkorotkov** [comment]
> I think we should add When selecting meta or true to be clear.

Makes sense

**Comment by ewsopp** [comment]
Agreed

**Comment by antonkorotkov** [comment]
@alimuzzaman I think this section should show up for each option from `enable` group. Right now it only shows up for `Editor & Meta`.

![image](https://user-images.githubusercontent.com/2276882/51024305-de910d00-1591-11e9-9617-bf4bfc4dfe10.png)

**Comment by ewsopp** [comment]
Also - the options should be `Disable`, `Enable Editor`, `Enable Meta`, and `Enable Editor & Meta`.

In the screenshot above, it is missing the word "Enable".

**Comment by antonkorotkov** [comment]
@alimuzzaman this one done as well? 

![image](https://user-images.githubusercontent.com/2276882/51102953-a2f08000-17e9-11e9-83ac-f17a01b29fe3.png)

**Comment by alimuzzaman** [comment]
@antonkorotkov Sorry missed it.
Just made a commit.

**Comment by renduples** [comment]
You will have to re-open this issue 
Upgrading from Version 2.1.9 to 2.2.1 - breaks everything 
We have tried every setting for File URL Replacement but no joy.
It incorrectly sets the path in the srcset element

**Comment by ewsopp** [comment]
@renduples what do you mean by "breaks everything." Can you be more specific?

**Comment by ewsopp** [comment]
I think this may be related to https://github.com/wpCloud/wp-stateless/issues/342. Could you try using the latest version linked to within that issue please?

**Comment by renduples** [comment]
Correct after upgrading to 2.2.1 srcset no longer reference Google Cloud but rather wp-uploads

**Comment by ewsopp** [comment]
@renduples the issue with srcset should be resolved with today's v2.2.2 release (see issue https://github.com/wpCloud/wp-stateless/issues/342).

Please upgrade and let us know if you have any more problems. Thank you
