### ISSUE TITLE
enable compatibility button in notice is not working

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#339]
![2019-01-11_09-46-13](https://user-images.githubusercontent.com/5578537/51040620-febacf00-1585-11e9-954f-a07b3bb77ed7.gif)

**Comment by ewsopp** [comment]
Clicking the "Enable compatibility" button should enable the feature without having to navigate to the setting.

**Comment by ewsopp** [comment]
Also - please capitalize the "C" in "Enable Compatibility"

**Comment by antonkorotkov** [comment]
@alimuzzaman I tested it and I can confirm it, in fact, enables the option but for some reason it does not update the dropdown right away without page refresh. Can you check that?

**Comment by alimuzzaman** [comment]
@antonkorotkov It's probably browser cache. It's working for me.

**Comment by antonkorotkov** [comment]
Ok, let me test again

**Comment by antonkorotkov** [comment]
Yeah, probably it was a cache.
