### ISSUE TITLE
large image constantly fails uploading

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#34]
I keep getting an "HTTP Error." when trying to upload the image below the screenshot. It is a large image: 3MB and 5250x5400

![image](https://cloud.githubusercontent.com/assets/5578537/15482246/a081d08a-20fc-11e6-93dc-4dd3f3f7c791.png)

![map-background](https://cloud.githubusercontent.com/assets/5578537/15482261/adb29708-20fc-11e6-96b1-80bca509906e.jpg)

![image](https://cloud.githubusercontent.com/assets/5578537/15482285/cd26fe58-20fc-11e6-8fad-5d61bcd81433.png)

**Comment by antonkorotkov** [comment]
All my tests on local WP installations were successful. I'm going to debug this on `staging`.

**Comment by antonkorotkov** [comment]
Just tested that large image on SMF staging. Uploading took 2 minutes.
<img width="1076" alt="00000212" src="https://cloud.githubusercontent.com/assets/2276882/15899538/b7411cb8-2da4-11e6-9295-d9cac8add3e3.png">

Not sure what exactly I should do to make it appear for me...

**Comment by antonkorotkov** [comment]
I've set time limit to `unlimited`. Let's test...
