### ISSUE TITLE
Exclude files starting with certain characters

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#344]
https://wordpress.org/support/topic/exclude-files-starting-with-certain-characters/

> Hello,
We walked into an issue using HTML to Canvas, where the Google Cloud bucket doesn’t allow us to take a screenshot of a certain image. It does work when we don’t use GC for these files, but host them on our normal server. Using CORS on the bucket isn’t an option, due to security reasons and running a multisite environment.
We use completely stateless.
Is it possible to exclude files being uploaded that for example start with specific characters? So for example: If a file starts with SPECIFCHAR the file doesn’t get uploaded to GC, the URL doens’t get replaced & the file isn’t removed from our regular server? So for example; SPECIFCHARfilename.png doesnt get uploaded to the cloud, filename.png does get uploaded?
Thanks in advance!

**Comment by alimuzzaman** [comment]
I am thinking about adding a short-circuit filter, so that users/other plugin can skip the **sync** if wants.

**Comment by alimuzzaman** [comment]
I have added `wp_stateless_skip_add_media` as filter.
With this filter user can skip the sync if they want.


```
/**
* To skip the sync process.
*
* Returning a non-null/true value
* will effectively short-circuit the function.
*
* $force and $args params are optional.
* This two will be passed on by compatibility.
* 
* @since 2.2.4
*
* @param bool              $value          This should return true if want to skip the sync.
* @param int               $metadata       Metadata for the attachment.
* @param string            $attachment_id  Attachment ID.
* @param bool              $force          Whether to force the sync even the file already exist in GCS.
* @param bool              $args           Whether to only sync the full size image.
*/

$check = apply_filters('wp_stateless_skip_add_media', null, $metadata, $attachment_id, $force, $args);
```

**Comment by antonkorotkov** [comment]
Looks good. Is it done? Could be closed?

**Comment by alimuzzaman** [comment]
@antonkorotkov yes.

**Comment by Spiegelberg** [comment]
has anyone an example how to implement this. i wanna exclude csv files from being uploaded to GCS, if its a regex of the starting characters i could name the file csv-blablabla.csv
