### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by danielsalare** [udx/wp-stateless#348]
For some reason I get an empty space on the preview url, and all images load in the site with that empty space, how can I fix that? 

<img width="110" alt="screen shot 2019-01-30 at 11 01 21 am" src="https://user-images.githubusercontent.com/364171/51998560-86f20d00-247e-11e9-832f-1a67de04efdf.png">

![screen shot 2019-01-30 at 11 01 57 am](https://user-images.githubusercontent.com/364171/51998627-9e30fa80-247e-11e9-8960-988102265c2a.png)

**Comment by antonkorotkov** [comment]
@danielsalare it looks like you Domain setting has an empty space as well. Check please and remove it and save settings. We will fix it on our end as well for future releases.

**Comment by danielsalare** [comment]
Thanks, but if I remove the domain, then save, and add it again, the issue persists, is there any other way to change this?

**Comment by antonkorotkov** [comment]
@danielsalare I mean remove the unwanted space but not the entire domain. In any case, it is going to be fixed in the next release.
