### ISSUE TITLE
SVGs with Smush

### ISSUE THREAD

**Issue by etchalon** [udx/wp-stateless#349]
If you have both WP-Stateless enabled, and Smush enabled, with compatibility turned on, SVGs will upload to the Library, but are not transferred to GCS.

Replicated with Smush 3.0.2 and WP-Stateless 2.2.2

**Comment by alimuzzaman** [comment]
@etchalon 
SVG isn't supported by default in WordPress.
What plugin are you using to allow the SVG Upload?

**Comment by alimuzzaman** [comment]
@etchalon 
I have tested with [SVG Support](https://wordpress.org/plugins/svg-support/) plugin. It's working fine.

I am not sure how that happened in your case but I wasn't able to replicate the issue.

**Comment by antonkorotkov** [comment]
Hey @etchalon

Can you please try if it works with the latest plugin version that is 2.2.3? The issue also may be related to the plugin that enables SVG upload. 

Thanks.

**Comment by antonkorotkov** [comment]
Ok, moving this issue over the next milestone.

**Comment by antonkorotkov** [comment]
Closing due to no response. Feel free to re-open if still have questions.
