### ISSUE TITLE
thumbnail meta data incorrect?

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#35]
In my investigation of issue https://github.com/wpCloud/wp-stateless/issues/31, I noticed the height and width metadata of a thumbnail was incorrect.

@antonkorotkov is this a bug or intentional?

![image](https://cloud.githubusercontent.com/assets/5578537/15787231/21e35dca-298f-11e6-875e-c55e17c81659.png)

**Comment by antonkorotkov** [comment]
I see. I think that is incorrect. Will try to fix that

**Comment by antonkorotkov** [comment]
Fixed

**Comment by ewsopp** [comment]
Looks good.

![image](https://cloud.githubusercontent.com/assets/5578537/15840164/ff38e87e-2c15-11e6-8819-cff5307aff01.png)

![image](https://cloud.githubusercontent.com/assets/5578537/15840166/010f6416-2c16-11e6-977f-c523c1ec3fb2.png)

![image](https://cloud.githubusercontent.com/assets/5578537/15840168/0a52c766-2c16-11e6-8d6b-f57b1f19ea9e.png)
