### ISSUE TITLE
Error after update v2.2.2

### ISSUE THREAD

**Issue by pappinvijak** [udx/wp-stateless#350]
PHP message: PHP Warning:  substr_compare(): The start position cannot exceed initial string length in /path/cloudbooklet.com/wp-content/plugins/wp-stateless/lib/classes/class-bootstrap.php on line 303

Server Details:
WP-version: 5.0.3
PHP: 7.2
WP-Stateless: 2.2.2

**Comment by larsha** [comment]
Nice work @antonkorotkov, my bad missing this warning adding the new calculation for srcset.

**Comment by martin-dmtrv** [comment]
In `wp-stateless/lib/classes/class-bootstrap.php`
On line 305 you can change the if/else block to:

```
if (isset($image['url']) AND $image['url']) {
    if (substr_compare($image['url'], $thumb_gs_name, -strlen($thumb_gs_name)) === 0) {
        $image['url'] = $meta['gs_link'];
        $found = true;
        break;
    }
}
```

I am not sure this is the best way to fix it but it fixed it for me. I had this problem on a production news website and had to act quickly.

If someone else has the problem - you can try this quick fix.

**Comment by antonkorotkov** [comment]
@martin-dmtrv this is the fix we already did but not released yet: https://github.com/wpCloud/wp-stateless/commit/4a2213ff36aae5ece8445f6a8c824209e56f4d04

**Comment by martin-dmtrv** [comment]
@antonkorotkov I just tested that fix. It appears ok. But the official plugin update is currently broken. I saw many other websites display the same error at the moment.

**Comment by antonkorotkov** [comment]
@martin-dmtrv we will try to make a release ASAP.
