### ISSUE TITLE
get_post_metadata filter breaks multi-dimensional arrays when retrieved with $single = true

### ISSUE THREAD

**Issue by surrealwebs** [udx/wp-stateless#352]
I'm running into an issue where I'm getting the wrong data when I call get_post_meta( $post_id, 'my_meta_field', true);

My data is in a multidimensional array:

`$data = array( array( 'foo' => 'bar', 'boo' => 'far' ), array( 'far' => 'boo', 'bar' => 'foo' ) );`

This is how I save the data:

`update_post_meta( $post_id, 'my_meta_field', $data );`

Because of how postmeta works in WordPress, what I expect to be returned:

with $single = false; ( get_post_meta( $post_id, 'my_meta_field' ) $single = false is default )
`$data = array( array( array( 'foo' => 'bar', 'boo' => 'far' ), array( 'far' => 'boo', 'bar' => 'foo' ) ) )`

with $single = true; ( get_post_meta( $post_id, 'my_meta_field', true) )
`$data = array( array( 'foo' => 'bar', 'boo' => 'far' ), array( 'far' => 'boo', 'bar' => 'foo' ) )`

What I actually get back:

`$data =array( 'foo' => 'bar', 'bar' => 'foo')`

I have tracked it down to the get_post_metadata filter. Hook is added in \wpCloud\StatelessMedia\Bootstrap::init

Callback method is \wpCloud\StatelessMedia\Bootstrap::post_metadata_filter this method is checking the value of $single it get's passed, if true, it passes back the first element.

When the data from this method is passed back to the built-in WordPress get_metadata method the get_metadata method is also checking the value of $single and if true checks to see if the data is an array, if it is, it also passes back the first element of the array.

Since the date from your method get passed back to the built-in method and checked against single, your method should not be checking against single and instead just return. (https://github.com/wpCloud/wp-stateless/blob/v2.2/lib/classes/class-bootstrap.php#L693)

**Comment by antonkorotkov** [comment]
@surrealwebs hey. Thanks for sharing. We were able to replicate the issue. It actually appears when meta value has URLs to the attachments. It will be fixed in the next plugin release.
