### ISSUE TITLE
Woocommerce IDP images

### ISSUE THREAD

**Issue by danielsalare** [udx/wp-stateless#353]
For some reason product images are not changing the url to the cloud storage url. Is there any other special configuration to accomplish this?

**Comment by danielsalare** [comment]
Hi, any ideas on why images are not working from the CDN on woocommerce ? Thanks

**Comment by antonkorotkov** [comment]
Hello, can you describe how to replicate this in details?

**Comment by danielsalare** [comment]
If we activate the plugin, everything seems to work fine, but for some reason on a woocommerce product detail page, the images of the product are not displayed using statless cdn url are we missing any configuration or why these images don't load with the cdn ?

**Comment by draped12** [comment]
I get the same issue! Product images do not load on product page and I am not able to upload featured images for products.

**Comment by danielsalare** [comment]
> I get the same issue! Product images do not load on product page and I am not able to upload featured images for products.

Have you managed to make it work?

**Comment by draped12** [comment]
Only reverting back to the storage.googleapis.com domain.

Using a custom subdomain with https creates issues with the product image not showing and feature images not uploading. Disabling https to http prevents images from loading site wide.

**Comment by alimuzzaman** [comment]
@danielsalare 
Can you test with the latest version of the plugin again?

Can you explain the term `IDP`? I am not familiar with it.

In my test feature image and gallery images seems to be working fine. 

I have used 
- WP-Stateless: 2.2.3
- WooCommerce: 3.5.4 
- Divi: 3.19.7

**Comment by danielsalare** [comment]
Hi, 

Thanks... 

IDP is the Item detail page or product page, for some reason images on product pages are not working with stateless url. 

We have:
WP-Stateless: 2.2.3
Woocommerce: 3.5.3
Divi: 3.19.1

**Comment by antonkorotkov** [comment]
@alimuzzaman were you able to replicate the issue on our end?

**Comment by alimuzzaman** [comment]
@antonkorotkov No, it was working fine.

**Comment by danielsalare** [comment]
Is there a way I can contact you privately to show you the site and configuration so we can debug this?

**Comment by alimuzzaman** [comment]
@danielsalare 
Here is my email address alim.alimuzzaman@usabilitydynamics.com

**Comment by antonkorotkov** [comment]
Moving this issue over the next milestone.

**Comment by antonkorotkov** [comment]
@alimuzzaman Can you let me know what is the status of this issue?

**Comment by alimuzzaman** [comment]
@antonkorotkov 
According to Marcus the user have resolved the issue. 
And the issue was on there side.
