### ISSUE TITLE
A public API of the plugin

### ISSUE THREAD

**Issue by dchenk** [udx/wp-stateless#354]
First, this is a great plugin, so thanks for all your work whoever develops it.

I have a situation where I need to upload files (e.g., photos cropped using another plugin) to my GCS bucket just the way WP-Stateless does it. However, I don't want to add another version of the large Google client library for PHP to access the GCS service. Since WP-Stateless already has the client set up with the parameters I need (the location where to put files), I'd like to use a public function of the WP-Stateless plugin to do these uploads. My question is: Is there such a function I can rely on?

**Comment by alimuzzaman** [comment]
Hi @dchenk 
### For media library attachments:
you can use `wp_update_attachment_metadata` filter. It's defined in `wpCloud\StatelessMedia\Utility` class. [lib/classes/class-utility.php](https://github.com/wpCloud/wp-stateless/blob/v2.2/lib/classes/class-utility.php#L168)
You can also look into this file [lib/classes/class-bootstrap.php](https://github.com/wpCloud/wp-stateless/blob/v2.2/lib/classes/class-bootstrap.php#L227).

You can use all of the methods of this two class using ud_get_stateless_media() function. It's return object of the bootstrap class. 

### Without media library:
You can use [`sm:sync::syncFile`](https://github.com/wpCloud/wp-stateless/blob/v2.2/lib/classes/class-sync-non-media.php#L29) filter. 
Check classes in this dir: [lib/classes/compatibility](https://github.com/wpCloud/wp-stateless/tree/v2.2/lib/classes/compatibility)

Fell free to send pull request.

**Comment by antonkorotkov** [comment]
@dchenk do you still have questions?

**Comment by dchenk** [comment]
Oh sorry I should've replied. That answered my question. Thanks a lot!
