### ISSUE TITLE
filter uploads and upload folder

### ISSUE THREAD

**Issue by stefanomaxis** [udx/wp-stateless#356]
Hi, is it possible to filter by content-type (pdf, docx, …)?
I’d like to use it only to store uploaded documents and not for the website.
And it’s possible to change the upload folder from year/month to post_id? It could be easier to find files on cloud storage.

Thanks
Stefano

**Comment by antonkorotkov** [comment]
@alimuzzaman we will need to investigate if this is possible later.

**Comment by alimuzzaman** [comment]
@stefanomaxis @antonkorotkov I suggested a possible solution in [wp.org forum](https://wordpress.org/support/topic/filter-uploads-and-upload-folder/#post-11212723).

**Comment by antonkorotkov** [comment]
Ah, yeah, sorry. 

@stefanomaxis do you still have questions?

**Comment by antonkorotkov** [comment]
Closing the issue assuming it is resolved. Please reopen/create new one if you think it is not.
