### ISSUE TITLE
Feature request: Support for webp files (LiteSpeed Cache)

### ISSUE THREAD

**Issue by afonseca08** [udx/wp-stateless#357]
Although not yet a native WordPress format, several image conversion plugins support webp as well as caching plugins. Webp support is growing around the web and supported by modern browsers today. Those looking to optimize loading times are leveraging this new format as well as CDN technology so adding support for webp in wp-stateless would be beneficial.

**Comment by alimuzzaman** [comment]
Hi @afonseca08,
So far I have found that **ShortPixel Image Optimizer** can generate webp when it optimize image.

I think it's not something we can find generic solution, we have add support plugin by plugin.

So we will try to include support for webp generated by ShortPixel inside of the existing compatibility for ShortPixel.

**Comment by afonseca08** [comment]
Hi @alimuzzaman, thank you for following-up. I am already using the LiteSpeed Cache for WP plugin:
 [https://wordpress.org/plugins/litespeed-cache/](url) which also supports webp. Something like ShortPixel would duplicate functionality and is an additional cost so not an option for me.

Would you be able to look into LiteSpeed Cache plugin compatibility?

**Comment by alimuzzaman** [comment]
@afonseca08
Yes will take a look.

**Comment by alimuzzaman** [comment]
Hi @afonseca08 to test LiteSpeed do I have to install LiteSpeed server?

**Comment by alimuzzaman** [comment]
Hi @afonseca08 
Would you like to help me setting up the LiteSpeed, I don't experience with LiteSpeed.
Please contact me so that I can send you login details. alim@udx.io

**Comment by afonseca08** [comment]
@alimuzzaman Sure, I just sent you an e-mail. You don't need LiteSpeed server to use the plugin.

**Comment by antonkorotkov** [comment]
@alimuzzaman Can you let me know what is the status of this issue?

**Comment by alimuzzaman** [comment]
@antonkorotkov 
Contacted with LiteSpeed support team, they added some new hook.

Here is the response:

> Hi,
> Thanks for reaching us. Regarding this request, we added couple hooks to WebP generation and validation process. The commit is in https://github.com/litespeedtech/lscache_wp/commit/e33861db9144ae02b9a6feddc56807eb49c90bc0
> Please let us know if there is anything more that we need to do.
> Best regards,
> Hai
>

**Comment by alimuzzaman** [comment]
@afonseca08 
Can you please test? 
To test you have to enable compatibility from Media >> Stateless Settings >> Compatibility tab.

https://github.com/wpCloud/wp-stateless/tree/5751b06f2d38a9ffa3a973d0f1d51c7995086f17

**Comment by alimuzzaman** [comment]
Compatibility for ShortPixel Image Optimizer will be handle in separate issue #364.

**Comment by antonkorotkov** [comment]
@alimuzzaman Can you explain how to test `LiteSpeed Cache` with `WP-Stateless`? When/Where the webp appears or should it be uploaded manually? I tried but WP does not allow it so I assume this is not what I should do.

**Comment by alimuzzaman** [comment]
@antonkorotkov 
You have to enable the `Optimize WebP Versions` setting in `LiteSpeed Cache Settings` >> `Media` tab

**Comment by antonkorotkov** [comment]
Ok, it works for me. I see webp files on GCS

![image](https://user-images.githubusercontent.com/2276882/54696030-b8f52680-4b33-11e9-81f6-fe579280253c.png)

**Comment by JuanxCursed** [comment]
Hi, unfortunately this is not working for me, I just have the original files uploaded, none of then has webp version.
> You have to enable the Optimize WebP Versions setting in LiteSpeed Cache Settings >> Media tab

Someone can provide me some assistance?
