### ISSUE TITLE
Issue with non SSL custom domain.

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#358]
`->get_gs_host()` function wasn't returning the correct URL.

**Comment by antonkorotkov** [comment]
@alimuzzaman Is it something users reported or you found that?

**Comment by alimuzzaman** [comment]
@antonkorotkov I found it.

**Comment by antonkorotkov** [comment]
@alimuzzaman Not sure if that is ok but can you check?

When I type some domain name it does not reflect it in the preview and it does not use it on front-end.

![image](https://user-images.githubusercontent.com/2276882/53425276-6077b100-39ed-11e9-8ba6-85d91928e218.png)

But it does when I add `https://` (`http://` is not working as well)

![image](https://user-images.githubusercontent.com/2276882/53425388-8f8e2280-39ed-11e9-81b9-18a046617903.png)

**Comment by alimuzzaman** [comment]
@antonkorotkov 
> Be advised that the **bucket name** and **domain name** must match exactly,

This is why it wasn't working for you.

It's true only when using non SSL domain with [google CNAME](https://cloud.google.com/storage/docs/xml-api/reference-uris#cname).

But when using CDN/load balancer it's not required.

**Comment by antonkorotkov** [comment]
Ok, got it. Closing the issue then.
