### ISSUE TITLE
Update compatibility with new filter when #344 completes.

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#359]
**Imagify** and **Smush** compatibility need to be updated with the new filter `(wp_stateless_skip_add_media)` added in #344.

**Comment by antonkorotkov** [comment]
Is it something you would do in 2.2.4 milestone?

**Comment by alimuzzaman** [comment]
Yes, simple changes.

**Comment by alimuzzaman** [comment]
@antonkorotkov you can review now.

**Comment by antonkorotkov** [comment]
@alimuzzaman just to clarify - before you added this new filter you were using `remove_filter` in order to disable sync in different conditions. And now you did the same but using the newly created filter, right?

**Comment by alimuzzaman** [comment]
@antonkorotkov 
Yes, disabled sync when the attachment is supported for optimization.
