### ISSUE TITLE
wp multisite switch_to_blog

### ISSUE THREAD

**Issue by mrmiroslav** [udx/wp-stateless#36]
Plugin does not play nicely with multisite when switching between blogs in source.

Say you wanted to copy media from blog A to blog B in wp-mu, which can be achieved by reading a media file, then switch_to_blog(B) and upload the media using media_handle_sideload(file , ...).

The issue is that bucket folder option is read on Settings instantiation. This though would be wrong as we switched to blog B and the option value is still from blog A.

The quick fix would be to simply read the option value when needed rather than relying on settings class.

It is very specific example, but potentially there might be other issues with reading options on instantiation.

**Comment by mrmiroslav** [comment]
I could do a quick dirty fix with pull request for my specific problem if pull requests accepted?

**Comment by antonkorotkov** [comment]
hey, you will not believe but we've just fixed that a moment ago (https://github.com/wpCloud/wp-stateless/commit/f675c462657818094429b3b6cd33d672272ac177) And going to release it soon.
