### ISSUE TITLE
Start manual sync from a specific point/attachment.

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#360]
https://wordpress.org/support/topic/continue-didnt-work/

**Comment by alimuzzaman** [comment]
Sync process start from new to old attachment.

We will add a input field to so that user can manually enter the id from which he wants to process the image.

I am not sure where should I add the field.

**Comment by alimuzzaman** [comment]
@ewsopp here is the UI I have come up with.

![image](https://user-images.githubusercontent.com/6744156/54075861-7ed38b80-42ce-11e9-8f88-f69d2e149698.png)

**Comment by antonkorotkov** [comment]
@alimuzzaman @ewsopp UI looks dirty on my end. What if we re-design these warnings somehow? Probably locate them under the option? Also, I think Attachment ID should be hidden unless `Continue the last process` is checked.

![image](https://user-images.githubusercontent.com/2276882/54108935-e29ca800-43e5-11e9-990a-9f82c760f74a.png)

**Comment by ewsopp** [comment]
I agree. Can we style the descriptions to look similar to the settings tab?

**Comment by alimuzzaman** [comment]
@antonkorotkov is this look good?
![image](https://user-images.githubusercontent.com/6744156/54429410-a4d3b280-474a-11e9-87df-84eb696a6b37.png)

**Comment by antonkorotkov** [comment]
Looks better now. Need input from @ewsopp

**Comment by ewsopp** [comment]
I think it's good enough. At some point we will need to redesign it, but not now. 

As long as it works good! :)

**Comment by antonkorotkov** [comment]
Works for me.
