### ISSUE TITLE
Change default value for CACHE BUSTING

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#361]
- [x] Change the default value for CACHE BUSTING from `TRUE` to `FALSE`.

- [x] Update the dafault value in wiki.

**Comment by ewsopp** [comment]
If they choose `Stateless` for the *Mode* setting, we still enforce CACHE BUSTING with a notice.

**Comment by ewsopp** [comment]
@planv can you test this please?

**Comment by planv** [comment]
@ewsopp checked, it works for me.

**Comment by ewsopp** [comment]
@planv good to close here then?

**Comment by alimuzzaman** [comment]
@ewsopp we have to update the wiki.

We should keep this open till release.

**Comment by antonkorotkov** [comment]
I'm going to work on this. The wiki and github site is still not updated.

**Comment by antonkorotkov** [comment]
Done
