### ISSUE TITLE
ShortPixel image optimization

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#364]
- [x] Support for webp files

- [x] Backup sync

- [x] Improve sync

**Comment by alimuzzaman** [comment]
### How to test:

Install WP-Stateless from here: https://github.com/wpCloud/wp-stateless/tree/shortpixel
Insatall ShortPixel from here: https://github.com/wp-stateless/shortpixel-image-optimiser/tree/wp-stateless

Go to **Settings >> ShortPixel**,  then enable `Image backup` from **General** tab and 
enable `WebP Images`  > `Using the <PICTURE> tag syntax` > `Only via Wordpress hooks (like the_content, the_excerpt, etc)` from **Advanced** tab.
Then create a Page/Post with a image and view on frontend. Check if the image used is WebP or not.

### Review ShortPixel code before sending pull request to them: 
I have added a bunch of new hooks to ShortPixel plugin.
https://github.com/wp-stateless/shortpixel-image-optimiser/pull/1

**Comment by antonkorotkov** [comment]
I did review the PR but I think we will have to move this issue to some of the next milestones because we have to wait for the approval from the ShortPixel team. Otherwise, the feature will not work.

**Comment by tripledm** [comment]
> ### How to test:
> Install WP-Stateless from here: https://github.com/wpCloud/wp-stateless/tree/shortpixel
> Insatall ShortPixel from here: https://github.com/wp-stateless/shortpixel-image-optimiser/tree/wp-stateless
> 
> Go to **Settings >> ShortPixel**, then enable `Image backup` from **General** tab and
> enable `WebP Images` > `Using the <PICTURE> tag syntax` > `Only via Wordpress hooks (like the_content, the_excerpt, etc)` from **Advanced** tab.
> Then create a Page/Post with a image and view on frontend. Check if the image used is WebP or not.
> 
> ### Review ShortPixel code before sending pull request to them:
> I have added a bunch of new hooks to ShortPixel plugin.
> [wp-stateless/shortpixel-image-optimiser#1](https://github.com/wp-stateless/shortpixel-image-optimiser/pull/1)

First a HUGE thank you for getting this setup.

I've set a large busy website to CDN only to 
"StatelessStore and serve media files with Google Cloud Storage only. Media files are not stored locally."
So with the updated version of the plugin;
- will this be included with the next wp-stateless update?
- will it now upload wepb images to GCS as well? 
- will there be support for serving wepb via .htaccess and,
- how will I regenerated webp images as it's not stored on GCS so I have to somehow regenerate them?

Thank you in advance and again thank you for your hard work I really appreciate everything you are doing!

**Comment by alimuzzaman** [comment]
1. This update will be release after ShortPixel add our suggested hooks and do release. Hopefully they will add them in next release.
2. Yes, it will upload webp to GCS.
3. Not at the moment.
4. ShortPixel generates webp images when you (re)optimize the image. So if you (re)optimize your image webp image will be generated and WP Stateless will upload them to GCS.

**Comment by antonkorotkov** [comment]
Ok, so [pull request](https://github.com/short-pixel-optimizer/shortpixel-image-optimiser/pull/9) has been merged and released in 4.14.0:

![image](https://user-images.githubusercontent.com/2276882/61208055-36562f80-a6ff-11e9-8fba-cd554d8bf41f.png)

I've updated Shorpixel plugin to the latest version and used [shortpixel](https://github.com/wpCloud/wp-stateless/tree/shortpixel) branch of WP-Stateless in order to test the compatibility.

I've optimized 2 files and thumbnails have updated in the bucket as well:

![image](https://user-images.githubusercontent.com/2276882/61208799-db253c80-a700-11e9-8a74-ef3223e2e33f.png)

1

![image](https://user-images.githubusercontent.com/2276882/61208844-f6904780-a700-11e9-8587-7db6bc95c844.png)

2

![image](https://user-images.githubusercontent.com/2276882/61208881-0dcf3500-a701-11e9-9562-8648653e6720.png)

The newly added images are also being optimized and pushed to the bucket.

@alimuzzaman can you confirm this is the complete test of the compatibility?

**Comment by alimuzzaman** [comment]
@antonkorotkov 
Sorry I had some local changes forgot to pushed.

Please check in Stateless mode.

In Stateless mode:
The main purpose is when Shortpixel optimize image, we don't have to download the image to server. Now with `shortpixel_image_urls` filter we can make sure Shortpixel will use image directly from GCS.

We are converting GCS urls using `shortpixel_image_urls()` function from https://storage.googleapis.com/udx-ci-develop-alim/...
to https://udx-ci-develop-alim.storage.googleapis.com/

So that Shortpixel don't count all as  one domain (storage.googleapis.com).

**Comment by antonkorotkov** [comment]
Ok, I'll do one more test.

**Comment by antonkorotkov** [comment]
@alimuzzaman I need you to check this Missing Dependency 

![image](https://user-images.githubusercontent.com/2276882/61226724-9f539c80-a72b-11e9-8404-d28d0c9a2c49.png)

Looks like a bug in Shortpixel compatibility to me.

**Comment by antonkorotkov** [comment]
@alimuzzaman optimization works in Stateless mode with your latest changes as well. I think we are good to make a release if this after you fix the asset warning above.

**Comment by alimuzzaman** [comment]
@antonkorotkov Fixed.
Please check.

**Comment by antonkorotkov** [comment]
It is ok now. I think it is ready to be released.

**Comment by alimuzzaman** [comment]
@antonkorotkov Lets fix `shortpixel_image_exists` first.

**Comment by antonkorotkov** [comment]
Well, ShortPixel compatibility is not ready. `Restore From Backup` function does not work. Problem is that ShortPixel plugin developers did not add a `shortpixel_image_exists` filter to the specific place to handle backups. I think I'll need to create a new Pull Request to their plugin.

**Comment by antonkorotkov** [comment]
@alimuzzaman I see some changes to the SHortPixel plugin that were not pushed for the approval? I see there something related to backups. Can you explain what is that and if that is something that we need?

**Comment by antonkorotkov** [comment]
I'm talking about these changes https://github.com/short-pixel-optimizer/shortpixel-image-optimiser/compare/master...wp-stateless:wp-stateless

**Comment by alimuzzaman** [comment]
@antonkorotkov 

> I'm talking about these changes short-pixel-optimizer/shortpixel-image-optimiser@master...wp-stateless:wp-stateless

no, it's not something we need. 
It's just further improvement so that we don't make any unnecessary upload/download on GCS.

### We may create new issue and add it to the next milestone for this.

**Comment by alimuzzaman** [comment]
@antonkorotkov 
`Restore From Backup` is working now.
You can test it with `develop-alim` branch.

As for `shortpixel_image_exists` function:
I have spent some time to find a better solution but wasn't able to find any. Just wrapped the function with short(10 minutes) transient cache.
