### ISSUE TITLE
LiteSpeed Cache Image Optimization compatibility

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#365]
https://wordpress.org/support/topic/litespeed-cache-image-optimization-2/
Ok, so I have just swithed to Litespeed hosting, configured Lightspeed cache properly, and I wanted to optimize the images on the website using Litespeed.

Prior to this, I have configured WP Stateless plugin to stateless mode, meaning that all my images are served from GCS, and none of them are on my server.

I hit “Send optimization request” and I get the error: Image files missing: 1263 groups (13793 images)

Optimization won’t start because of this. I know your latest release added compatibility to LSCache plugin. Do the images still need to be on my server for the optimization to work?

**Comment by alimuzzaman** [comment]
https://github.com/litespeedtech/lscache_wp/issues/143
https://store.litespeedtech.com/store/viewticket.php?tid=751737&c=hYcv6VlM

**Comment by hi-hai** [comment]
https://github.com/litespeedtech/lscache_wp/commit/3ff72fd135f36b521e806592181b3ea291922c2b
https://github.com/litespeedtech/lscache_wp/commit/14fb30a21527af68b8473273819b64b0d920c3e5

**Comment by ewsopp** [comment]
@alimuzzaman please proceed with this. Let's support them!

**Comment by alimuzzaman** [comment]
WP Stateless is now compatible with **LiteSpeed Cache**.
