### ISSUE TITLE
Check compatibility with WP Smush

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#366]
https://wordpress.org/support/topic/after-synchronize-the-images-still-in-media-library/#post-11337831

Related #362

**Comment by antonkorotkov** [comment]
@alimuzzaman so, both #362 and #366 are fixed?

**Comment by alimuzzaman** [comment]
@antonkorotkov  yes

**Comment by antonkorotkov** [comment]
Ok, I tested. Seems to be working for me.
