### ISSUE TITLE
Fatal error leading to 500 error page across site when activated

### ISSUE THREAD

**Issue by ram-nadella** [udx/wp-stateless#367]
When I activated this plugin and proceeded to set the values in Stateless Settings (went the manual route) and set to Stateless mode, I started seeing all my Wordpress admin pages return 500 (haven't checked the user facing pages).

Found this in the apache error log:

```
[Thu Mar 21 19:16:57.240184 2019] [:error] [pid 6370] [client 35.245.169.99:46214] PHP Fatal error:  Interface 'Psr\\Log\\LoggerInterface' not found in /some/path/deployment/releases/123/src/wp-content/plugins/wp-stateless/lib/Google/vendor/monolog/monolog/src/Monolog/Logger.php on line 27, referer: https://our-domain.com/something/wp-admin/upload.php
```

Looks like the install step needs a composer install? Or is the vendor directory out of date?

Running `composer install` in the `wp-stateless` directory under `wp-content/plugins` resolved the issue.

Our environment:

Wordpress 5.1.1
PHP 7.x
Apache 2.4.x

WP Stateless 2.2.5

**Comment by antonkorotkov** [comment]
@ram-nadella  

Do you use Git or SVN on your deployment? If so check what it's ignoring, probably there is a `log` entry which could cause the following issue.

**Comment by ram-nadella** [comment]
@antonkorotkov thanks for the quick reply.

We are using git + capistrano and it turned out to be what you guessed, `log` was in the `.gitignore` file in the parent directory.

Closing this since it's not an issue with the plugin.
