### ISSUE TITLE
Add notice for JS error.

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#369]
From Eric:
> I’m noticing some staging styling issues on the settings panel in the NCMF network area. 
> Strange styling and output issues on the Network Settings area.

From Andy:
> perhaps we should have a notice up top that says “you have a problem with JS” that is hidden if JS is working? pretty sure that’s a common pattern to show a message when JS fails for whatever reason

![image](https://user-images.githubusercontent.com/6744156/54866094-23a79b80-4d9a-11e9-8b1f-e2c7f4c26282.png)

**Comment by antonkorotkov** [comment]
I don't see any JS errors. I think that the required JS or CSS file is not simply included on the network. Working on it.

**Comment by antonkorotkov** [comment]
@alimuzzaman I've fixed assets inclusion but there still something incorrect as for me.

![image](https://user-images.githubusercontent.com/2276882/54908900-9b3c0e80-4ef1-11e9-80f5-c168c0340d23.png)

Not sure what means false in these fields. These are default values after the network setup by setup assistant. Can you check that? Merge my branch into yours to get the fix.

**Comment by alimuzzaman** [comment]
@antonkorotkov
OK will check that.

**Comment by antonkorotkov** [comment]
As I understand this is done.

I see no `false` values now:

![image](https://user-images.githubusercontent.com/2276882/55710381-30133180-59f3-11e9-8f89-4415d37ce400.png)
