### ISSUE TITLE
Synchronize Media Library

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#37]
- [ ] The new `Synchronize Media Library` option scans the local media storage and GCS to create a list of files that do not reside on both ends. Some files might only be on GCS, and other files may only on local storage.
- [ ] For files that are only on local storage and DO exist in the media library, push copy to GCS and find/replace references of local file url.
- [ ] For files that are only on local storage and DO NOT exist in the media library, push copy to GCS, create media library object, and find/replace references of local file url.
- [ ] For files that are only on GCS and DO exist in the media library, push copy to local storage.
- [ ] For files that are only on GCS and DO NOT exist in the media library, push copy to GCS and create media library object.

**Comment by antonkorotkov** [comment]
@andypotanin @ewsopp The global problem here is that it is not always possible to say whether remote file exists in media library or not.

Look at the example:

Let say we have Media Object for `image.jpg` and corresponding files for it:
`image.jpg`, 
`image-150x150.jpg`,
`image-300x300.jpg`,
`image-600x600.jpg`

Then imaging we ran a script that should try to determine whether file has corresponding Media Object or not. Script goes over files and checks if `image.jpg` exists in `wp_postmeta` under `_wp_attached_file` key. This means that Media Object exists. But when we take next file - `image-150x150.jpg` and check the same then we don't get it because resized images are stored in another key in serialized way like:

```
a:5:{s:5:"width";i:4000;s:6:"height";i:2667;s:4:"file";s:59:"2016/06/2d09e539-smf2016_0529_235816-0306_alivecoverage.jpg";s:5:"sizes";a:19:{s:9:"thumbnail";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-150x150.jpg";s:5:"width";i:150;s:6:"height";i:150;s:9:"mime-type";s:10:"image/jpeg";}s:6:"medium";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-300x200.jpg";s:5:"width";i:300;s:6:"height";i:200;s:9:"mime-type";s:10:"image/jpeg";}s:5:"large";a:4:{s:4:"file";s:60:"2d09e539-smf2016_0529_235816-0306_alivecoverage-1024x683.jpg";s:5:"width";i:1024;s:6:"height";i:683;s:9:"mime-type";s:10:"image/jpeg";}s:9:"square-sm";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-500x500.jpg";s:5:"width";i:500;s:6:"height";i:500;s:9:"mime-type";s:10:"image/jpeg";}s:9:"square-md";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-800x800.jpg";s:5:"width";i:800;s:6:"height";i:800;s:9:"mime-type";s:10:"image/jpeg";}s:9:"square-lg";a:4:{s:4:"file";s:61:"2d09e539-smf2016_0529_235816-0306_alivecoverage-1200x1200.jpg";s:5:"width";i:1200;s:6:"height";i:1200;s:9:"mime-type";s:10:"image/jpeg";}s:12:"landscape-xs";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-400x225.jpg";s:5:"width";i:400;s:6:"height";i:225;s:9:"mime-type";s:10:"image/jpeg";}s:12:"landscape-sm";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-800x450.jpg";s:5:"width";i:800;s:6:"height";i:450;s:9:"mime-type";s:10:"image/jpeg";}s:12:"landscape-md";a:4:{s:4:"file";s:60:"2d09e539-smf2016_0529_235816-0306_alivecoverage-1200x675.jpg";s:5:"width";i:1200;s:6:"height";i:675;s:9:"mime-type";s:10:"image/jpeg";}s:12:"landscape-lg";a:4:{s:4:"file";s:60:"2d09e539-smf2016_0529_235816-0306_alivecoverage-1600x900.jpg";s:5:"width";i:1600;s:6:"height";i:900;s:9:"mime-type";s:10:"image/jpeg";}s:12:"landscape-xl";a:4:{s:4:"file";s:61:"2d09e539-smf2016_0529_235816-0306_alivecoverage-2000x1125.jpg";s:5:"width";i:2000;s:6:"height";i:1125;s:9:"mime-type";s:10:"image/jpeg";}s:11:"portrait-xs";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-200x300.jpg";s:5:"width";i:200;s:6:"height";i:300;s:9:"mime-type";s:10:"image/jpeg";}s:11:"portrait-sm";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-600x900.jpg";s:5:"width";i:600;s:6:"height";i:900;s:9:"mime-type";s:10:"image/jpeg";}s:11:"portrait-md";a:4:{s:4:"file";s:60:"2d09e539-smf2016_0529_235816-0306_alivecoverage-800x1200.jpg";s:5:"width";i:800;s:6:"height";i:1200;s:9:"mime-type";s:10:"image/jpeg";}s:11:"portrait-lg";a:4:{s:4:"file";s:61:"2d09e539-smf2016_0529_235816-0306_alivecoverage-1200x1800.jpg";s:5:"width";i:1200;s:6:"height";i:1800;s:9:"mime-type";s:10:"image/jpeg";}s:14:"shop_thumbnail";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-180x180.jpg";s:5:"width";i:180;s:6:"height";i:180;s:9:"mime-type";s:10:"image/jpeg";}s:12:"shop_catalog";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-300x300.jpg";s:5:"width";i:300;s:6:"height";i:300;s:9:"mime-type";s:10:"image/jpeg";}s:11:"shop_single";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-600x600.jpg";s:5:"width";i:600;s:6:"height";i:600;s:9:"mime-type";s:10:"image/jpeg";}s:14:"post-thumbnail";a:4:{s:4:"file";s:59:"2d09e539-smf2016_0529_235816-0306_alivecoverage-825x510.jpg";s:5:"width";i:825;s:6:"height";i:510;s:9:"mime-type";s:10:"image/jpeg";}}s:10:"image_meta";a:12:{s:8:"aperture";s:1:"4";s:6:"credit";s:0:"";s:6:"camera";s:21:"Canon EOS 5D Mark III";s:7:"caption";s:0:"";s:17:"created_timestamp";s:10:"1464566296";s:9:"copyright";s:0:"";s:12:"focal_length";s:2:"15";s:3:"iso";s:4:"2500";s:13:"shutter_speed";s:6:"0.0125";s:5:"title";s:0:"";s:11:"orientation";s:1:"0";s:8:"keywords";a:0:{}}}
```

Sure I can decode this data and get info from it but it is going to be much more time and memory consuming. It is probably will work forever with buckets like DDP because I need to get every image file name and check if it exists in that serialized array or not. Even more then I need to compare it with the same huge list of files on GCS...

Honestly not sure we can create something more efficient than we have now. 

Just in case let me explain in details how it works now:
1. We take EXISTING Media Objects one by one (or by batches);
2. For each Media Object we check whether we have it's original file locally or not (it is required to be able to regenerate sizes). If it exists then we continue, in another case we try to get it from GCS. If it exists there then we download it to local (this is actually a Sync part of this function), in another case we mark Media Object as broken and it can't be restored;
3. We run thumbnails regeneration for each object (actually we cannot regenerate specific sizes, it regenerates all of them and this can't be changed);
4. After regeneration of each Media Object we check if it's files (original and resized) exist on GCS and if so then we take next Media Object and go to step 2. If some of the files of current Media Object does not exist on GCS then we upload it there. After all we take next Media Object and go to step 2.

So, this approach in general allows us to keep existing Media Objects synced with GCS and vice versa. Over the same process Media Object goes when you click "Regenerate and Sync" in Media Library or on Media Edit page btw.

I'm not really sure if we should worry about abandoned files in uploads because some of them may be put there manually and intensionally or something...

**Comment by ewsopp** [comment]
We also need to synchronize other file types - not just images. It important that we handle all of this in one process if at all possible. Users shouldn't have to run separate tasks for images and non-images; it should be one button that does everything.

**Comment by ewsopp** [comment]
How does this treat thumbnail sizes that were generated in the past, but are no longer defined? These wont be generated again because they are no longer defined, and they may be referenced within body content. We need to sync these as well.

**Comment by antonkorotkov** [comment]
Ok... basically I think we can make some sort of files sync but the only thing I can't do is to create Media Objects while syncing. Is that ok?

In other words file systems will be synced but not every file will have corresponding Media Object.

**Comment by antonkorotkov** [comment]
Actually, here is a live example. This is my local `uploads` folder. I've no idea what are these files except `2016`.

<img width="439" alt="00000217" src="https://cloud.githubusercontent.com/assets/2276882/16120141/37eb9a8a-33e7-11e6-936f-b520b493af38.png">
Which of them should be synced and which should not?

**Comment by ewsopp** [comment]
I think at some point we will need to create extensions for WP-Stateless that support these files. For example, a Gravity Forms extension mentioned at https://github.com/wpCloud/wp-stateless/issues/2

**Comment by antonkorotkov** [comment]
You did not understand what I mean. When sync script will look into `uploads` it does not matter for it what these files are and which plugin created them. The problem is I cannot separate them and they will be synced as well with ALL other uploads.

**Comment by ewsopp** [comment]
I guess what I'm saying is that we sync only files that has corresponding Media Library objects and create separate extensions for plugins that add files into /uploads that are not indexed in the Media Library.

**Comment by antonkorotkov** [comment]
But as I can see from todo list your initial idea was to sync entire local media storage, not only files that have Media Object.

**Comment by ewsopp** [comment]
Part of my objective here is to sync thumbnail images that have sizes that are no longer defined. This happens with old websites that change themes and plugins that add/remove thumbnail sizes.

We need to make sure we bring these sync images.

**Comment by antonkorotkov** [comment]
Yes, that is possible but once again - I cannot create Media Objects for these abandoned thumbnails. Will that work for us?

**Comment by ewsopp** [comment]
Why would you create media objects for thumbnails? It is already associated with a media library object.

**Comment by antonkorotkov** [comment]
Imaging Media Object was removed but files are still in bucket. Then we run sync and see that we simply don't know what these images are but they still may be used in content. That's the key problem.

**Comment by ewsopp** [comment]
I'm not sure you understand the problem I am describing. We will need to voice on this so I can explain it to you.

**Comment by antonkorotkov** [comment]
ok, let's do it tomorrow...

**Comment by andypotanin** [comment]
Im confused a bit also. Lets do call with three of us to figure out best way to handle this.

**Comment by alimuzzaman** [comment]
@antonkorotkov @ewsopp @andypotanin What was the result of talk?

**Comment by ewsopp** [comment]
@alimuzzaman I'm available for a phone call. Lets voice.

**Comment by danielperezr88** [comment]
I need some of this functionalities in order to be able to make Wordpress installations truly stateless. Any workaround or script to help synchronize existing GCE media? More specifically, I'd like to be able to programmaticaly create non-existent Wordpress media library objects, and choose if I want to keep a copy inside "uploads" directory or not.

**Comment by danielperezr88** [comment]
Found a solution for my situation. Using CDN mode, gcsfuse for mounting my bucket as the uploads folder and "Add From Server" plugin to register files in Wordpress. Adding some Javascript scripting for recursive file registration with "Add From Server", avoiding resizing already resized images again, completed it all. Not an easy solution, but it did the trick.

**Comment by ewsopp** [comment]
@danielperezr88 glad you got it worked out. We want to add functionality to support this sort of case, but it might take quite a bit of time and effort to pull it together. I'm happy to see you found a workaround in the meantime.

**Comment by ijakparov** [comment]
I have th same problem. Using timber plugin witch resize images (custom resize), wp-stateless doesn't see them and doesn't upload.

**Comment by ewsopp** [comment]
This is being developed separately as an extension. Closing this issue.
