### ISSUE TITLE
Support for EWWW Image Optimizer

### ISSUE THREAD

**Issue by plenge** [udx/wp-stateless#371]
Are there any plans to support EWWW Image optimizer?
https://ewww.io/

**Comment by alimuzzaman** [comment]
@antonkorotkov Lets keep this open, and move to next milestone.
Only works in CDN mode now.

**Comment by alimuzzaman** [comment]
@plenge @antonkorotkov @ewsopp 
EWWW  added support for WP Stateless. Now it also works on `Stateless` mode.


We will need support from EWWW team to support this feature.
- [x] WebP support
- [ ] Converted Files (Ex. jpg to png)

**Comment by alimuzzaman** [comment]
WebP sync is working properly.
Not sure how jpg to png (or vice versa) work. I wasn't able to make it work.

**Comment by alimuzzaman** [comment]
There is nothing more to do.
