### ISSUE TITLE
Is it possible to use the plugin with permissions?

### ISSUE THREAD

**Issue by Steffi3rd** [udx/wp-stateless#374]
Hi, I tried this plugin but I doesn't work as I excepted.

In my case, I would like each Wordpress user can upload their photos but others Wordpress Users can see OR access to these files. Even Wordpress administrators cannot access to the files. (That's why I don't want them is the "Wordpress Media Library")

Is there a way to do that with this plugin please?

**Comment by alimuzzaman** [comment]
@Steffi3rd Sorry there is no way to do that.

WP-Stateless doesn't support private files yet.
You can keep your eye on issue #168.
Though private file isn't supported out of the box, it would be possible to develop custom solution.

**Comment by Steffi3rd** [comment]
@alimuzzaman okay, thanks.

And at this time, do you we know which user uploaded the file on GCP? 

That way, later, we could change permissions, no?

**Comment by alimuzzaman** [comment]
> And at this time, do you we know which user uploaded the file on GCP?

No user id isn't saved in media meta in GCP.

> That way, later, we could change permissions, no?

Ye, it could be possible.

**Comment by Steffi3rd** [comment]
The alternative to the user ID could be organiser by folder.

I know we can define a ´bucket folder´

but is there a way with WP-Stateless to upload inside dynamic folder?

Example : 
- User 1 uploads to ‘folder 1´
- User 2 uploads to ´folder 2’
- User 3 uploads to ´folder 3’ if not exists, create it

Etc.

**Comment by antonkorotkov** [comment]
Not something we will be able to do in the nearest future. Closing for now.
