### ISSUE TITLE
Error on multi-site

### ISSUE THREAD

**Issue by gustavotero7** [udx/wp-stateless#376]
Hi, I got this error after installing and activate the plugin

![Screenshot_2019-04-21 WordPress › Error](https://user-images.githubusercontent.com/8619784/56474527-b93d5600-6440-11e9-80a3-7addc0154d95.png)

It only appears on /wp-admin, the public site seems to work fine 

Here is a list of my active plugins (I removed wp-stateless)
![Screenshot_2019-04-21 Plugins ‹ Administrador de la red ultraCloud Sites — WordPress](https://user-images.githubusercontent.com/8619784/56474621-d0307800-6441-11e9-8996-5983eba2d953.png)

**Comment by antonkorotkov** [comment]
WP-Stateless does not use `SECURE_AUTH_COOKIE` variable. Check other plugins.
