### ISSUE TITLE
Metadata for attachment missing with Polylang Pro

### ISSUE THREAD

**Issue by Hooace** [udx/wp-stateless#378]
When Polylang Pro plugin's Media translation is enabled and user uploads an image to Media gallery, the _wp_attachment_metadata does not include image sizes for the image for other than the default language.

![image](https://user-images.githubusercontent.com/469061/46524829-b14a0a00-c892-11e8-9e77-938cbf5778fc.jpg)

Here is screenshot from database for uploaded image that has correct metadata (image sizes) for default language and incorrect meta for other language.
![image](https://user-images.githubusercontent.com/469061/56794091-1c026900-6816-11e9-9158-c902e627b6fb.png)

Disabling WP Stateless and uploading an image with same settings will result in correct metadata for both languages:
![image](https://user-images.githubusercontent.com/469061/56794275-77345b80-6816-11e9-8f12-403a351fbc49.png)

If thumbnails are regenerated and synced, the metadata for other languages are corrected.
![image](https://user-images.githubusercontent.com/469061/56794358-a21eaf80-6816-11e9-94c6-e9c25a0d6e9e.png)

Used WP Stateless 2.2.6 and Polylang Pro 2.5.3 for testing.

This I reopened this issue as it has not been corrected. Old issue is https://github.com/wpCloud/wp-stateless/issues/306

**Comment by Hooace** [comment]
Any news about this?

**Comment by ironland** [comment]
Can you look into this @alimuzzaman @antonkorotkov ? This is potentially a big issue for everyone using polylang and wp-stateless together.

**Comment by villesiltala** [comment]
I'm having the same issue. Any updates on this?

**Comment by alimuzzaman** [comment]
@Hooace @ironland @villesiltala can you please test with [this version](https://github.com/wpCloud/wp-stateless/archive/5a2de99c223c0a786ab8c9a7ee3aea7d157a20d6.zip) of the WP-Stateless?
https://github.com/wpCloud/wp-stateless/tree/5a2de99c223c0a786ab8c9a7ee3aea7d157a20d6

I have tested with Polilang Pro 2.6.

**Comment by villesiltala** [comment]
@alimuzzaman I can still reproduce this issue with Polylang Pro 2.6.7 and Stateless  2.3.3. Here is an example of metadata created after uploading an image in the default language with the automatic duplication setting enabled:

**sm_cloud**
```
array (
  'id' => 'mybucket/2020/02/myimage.png/1582015663207144',
  'name' => '2020/02/myimage.png',
  'bucket' => 'mybucket',
  'storageClass' => 'STANDARD',
  'fileLink' => 'https://mysite.test/uploads/2020/02/myimage.png',
  'mediaLink' => 'https://www.googleapis.com/download/storage/v1/b/mybucket/o/2020%2F02%2Fmyimage.png?generation=1582015663207144&alt=media',
  'selfLink' => 'https://www.googleapis.com/storage/v1/b/mybucket/o/2020%2F02%2Fmyimage.png',
  'cacheControl' => 'public, max-age=36000, must-revalidate',
  'contentDisposition' => NULL,
  'object' =>
  array (
    'bucket' => 'mybucket',
    'cacheControl' => 'public, max-age=36000, must-revalidate',
    'componentCount' => NULL,
    'contentDisposition' => NULL,
    'contentEncoding' => NULL,
    'contentLanguage' => NULL,
    'contentType' => 'image/png',
    'crc32c' => 'fImIFw==',
    'etag' => 'COjlic3b2ucCEAE=',
    'eventBasedHold' => NULL,
    'generation' => '1582015663207144',
    'id' => 'mybucket/2020/02/myimage.png/1582015663207144',
    'kind' => 'storage#object',
    'kmsKeyName' => NULL,
    'md5Hash' => 'sleGoKCewcU+Mj3f9ki1fw==',
    'mediaLink' => 'https://www.googleapis.com/download/storage/v1/b/mybucket/o/2020%2F02%2Fmyimage.png?generation=1582015663207144&alt=media',
    'metadata' =>
    array (
      'file-hash' => '4b817a3f5d6606d1af97a106a85048b8',
      'object-id' => '38860',
      'width' => '498',
      'source-id' => '866cba34c6e4013272f26e277fec3f51',
      'height' => '179',
    ),
    'metageneration' => '1',
    'name' => '2020/02/myimage.png',
    'retentionExpirationTime' => NULL,
    'selfLink' => 'https://www.googleapis.com/storage/v1/b/mybucket/o/2020%2F02%2Fmyimage.png',
    'size' => '20805',
    'storageClass' => 'STANDARD',
    'temporaryHold' => NULL,
    'timeCreated' => '2020-02-18T08:47:43.206Z',
    'timeDeleted' => NULL,
    'timeStorageClassUpdated' => '2020-02-18T08:47:43.206Z',
    'updated' => '2020-02-18T08:47:43.206Z',
  ),
  'sizes' =>
  array (
  ),
  'filesize' => 20805,
)
```

**_wp_attachment_metadata**
```
array (
  'file' => '2020/02/myimage.png',
  'filesize' => 20805,
)
```

**Comment by villesiltala** [comment]
@alimuzzaman I'm unable to install that version since the required packages are not available via composer. I tried to manually add the repository from https://repository.usabilitydynamics.com and still no luck.

Could you provide a zipped version of that plugin version or a functioning composer installation guide?

**Comment by antonkorotkov** [comment]
Hey @villesiltala @Hooace

you should not actually try installing it using Composer. Anyways, try this zip https://github.com/wpCloud/wp-stateless/archive/5a2de99c223c0a786ab8c9a7ee3aea7d157a20d6.zip

**Comment by villesiltala** [comment]
Hi @antonkorotkov! I tested the zipped version with WP 5.2.5 and Polylang Pro 2.6.10. The mode is set to `stateless` and duplicating media to all languages is enabled in Polylang. I get the following XHR error, when uploading an image on the `wp-admin/upload.php` page.

```
{
    "success": false,
    "data": {
        "type": "Whoops\\Exception\\ErrorException",
        "message": "Undefined index: path",
        "file": "\/var\/www\/project\/web\/app\/plugins\/wp-stateless\/lib\/classes\/class-bootstrap.php",
        "line": 1486,
        "trace": [
            {
                "file": "\/var\/www\/project\/web\/app\/plugins\/wp-stateless\/lib\/classes\/class-bootstrap.php",
                "line": 1486,
                "function": null,
                "class": "Whoops\\Exception\\ErrorException",
                "args": [
                    "Undefined index: path"
                ]
            },
        ]
    }
}
```

**Comment by alimuzzaman** [comment]
Please try this version and let us know.
https://github.com/wpCloud/wp-stateless/archive/develop-alim.zip

**Comment by villesiltala** [comment]
@alimuzzaman tried that one and I got another error. We use [whoops](https://github.com/filp/whoops) and develop with strict error and warning handling, thus these type of errors stop the execution and throw an error.

```
{
    "success": false,
    "data": {
        "type": "Whoops\\Exception\\ErrorException",
        "message": "Undefined index: use_wildcards",
        "file": "\/var\/www\/project\/web\/app\/plugins\/wp-stateless\/lib\/classes\/class-utility.php",
        "line": 426,
        "trace": [
            {
                "file": "\/var\/www\/project\/web\/app\/plugins\/wp-stateless\/lib\/classes\/class-utility.php",
                "line": 426,
                "function": null,
                "class": "Whoops\\Exception\\ErrorException",
                "args": [
                    "Undefined index: use_wildcards"
                ]
            },
            {
                "file": "\/var\/www\/project\/web\/app\/plugins\/wp-stateless\/lib\/classes\/class-utility.php",
                "line": 426,
                "function": "handleError",
                "class": "Whoops\\Run",
                "args": [
                    8,
                    "Undefined index: use_wildcards",
                    "\/var\/www\/project\/web\/app\/plugins\/wp-stateless\/lib\/classes\/class-utility.php",
                    426,
                    {
                        "metadata": {
                            "file": "2020\/03\/26201697-pensive-parakeet.jpg",
                            "filesize": 480098
                        },
                        "attachment_id": 44312,
                        "gs_name_path": [],
                        "full_size_path": "\/var\/www\/uploads\/2020\/03\/\/26201697-pensive-parakeet.jpg",
                        "base_dir": "\/var\/www\/uploads\/2020\/03"
                    }
                ]
            },
        ]
    }
}
```

**Comment by alimuzzaman** [comment]
@villesiltala I have updated the code. Please try again.
https://github.com/wpCloud/wp-stateless/archive/develop-alim.zip


Please feel free to send pull request. Use the **develop-alim** branch.

**Comment by alimuzzaman** [comment]
HI @villesiltala,
Were you able to test successfully?
What was the result?

**Comment by ewsopp** [comment]
@planv can you test this please?

**Comment by planv** [comment]
Fixed, tested with Polilang Pro 2.6 for 3 selected languages.
For each language was added all image sizes data to `_wp_attachment_metadata`

**Comment by ewsopp** [comment]
@planv are we good to close here? or is additional development and testing needed?

**Comment by planv** [comment]
@ewsopp 

> are we good to close here?

Yes, task is completed
