### ISSUE TITLE
Revise doc links

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#379]
> go through the WP-Stateless code and remove all links that go to `https://github.com/wpCloud/wp-stateless` and `https://wordpress.org/plugins/wp-stateless` and replace them with links that go to `https://wp-stateless.github.io/`.
We want all visitors to go through the github.io page because we have our google analytics and other tracking codes on there.

**Comment by antonkorotkov** [comment]
@andypotanin wp-stateless.github.io is outdated. I will work on updating it before we release any fixed links.

**Comment by antonkorotkov** [comment]
The subscribe form is missing:

![image](https://user-images.githubusercontent.com/2276882/57065159-41d5b500-6cd1-11e9-9e1a-7dfcb3c6082d.png)

The following code is there:

```html
<!--[if lte IE 8]>
        <script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2-legacy.js"></script>
        <![endif]-->
        <script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
        <script>
          hbspt.forms.create({
            portalId: '3453418',
            formId: '5983755b-8a87-41cf-8695-57f410c83568'
          });
        </script>
```

I assume the form was deleted on HubSpot. Investigating that with @Mashenka .

**Comment by antonkorotkov** [comment]
The form has been restored. The task is done. Fixed links will be rolled out with the nearest release.

**Comment by andypotanin** [comment]
@antonkorotkov Excellent, thank you.
