### ISSUE TITLE
Regenerate Image Thumbnails

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#38]
- [ ] The new `Regenerate Image Thumbnails` option scans each media item, takes note of the current thumbnail sizes of the image by looking at file names of the existing thumbnails, takes note of the defined thumbnail sizes set by plugins and themes, and regenerates a new thumbnail for all of these sizes.

**Comment by ewsopp** [comment]
This is being developed separately as an extension. Closing this issue.
