### ISSUE TITLE
Check the ability to add WP Retina 2x plugin compatibility

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#380]
https://wordpress.org/plugins/wp-retina-2x/
https://wordpress.org/support/topic/syncing-retina-image/
> Hi,
Thanks for this plugin.
Recently I added the WP Retina 2x plugin. This plugin generates retina images for image sizes defined in the plugin settings.
I have set up the CDN mode for this plugin. The 2x images that are generated by the WP Retina 2x plugin are not synced with the Google Storage Bucket. Is there a way to make this work?
Thanks,
Adi

**Comment by alimuzzaman** [comment]
### It is only compatible with **WP Retina 2x Pro** plugin.

 **Over HTTP Check(Pro)** Must be enabled to make it work.

    
![image](https://user-images.githubusercontent.com/6744156/67227689-8a3c8700-f459-11e9-9f6e-bd8539869e26.png)

**Comment by alimuzzaman** [comment]
@ewsopp is this warning good or should we add WP notice if the setting is disabled?

![image](https://user-images.githubusercontent.com/6744156/67228270-bad0f080-f45a-11e9-9113-bef0b9195910.png)

**Comment by ewsopp** [comment]
Let's do both. A notice _AND_ mention it in the description. I don't think we need the orange color in the description.

**Comment by alimuzzaman** [comment]
@ewsopp 
![image](https://user-images.githubusercontent.com/6744156/67230758-b6f39d00-f45f-11e9-940b-0888ba14438b.png)
![image](https://user-images.githubusercontent.com/6744156/67230779-c4a92280-f45f-11e9-840e-5f4706e6b56f.png)

**Comment by alimuzzaman** [comment]
@antonkorotkov I am not sure how to verify if it's working or not.

There are some **@2x.jpg** in `srcset` of the image.

Here is img element generated:
`<img src="https://storage.googleapis.com/udx-ci-develop-alim/rabbit.ci/2019/11/b6dd0d95-alim.jpg" alt="" class="wp-image-604" srcset="https://storage.googleapis.com/udx-ci-develop-alim/rabbit.ci/2019/11/b6dd0d95-alim.jpg 1000w, https://storage.googleapis.com/udx-ci-develop-alim/rabbit.ci/2019/11/b6dd0d95-alim-300x225.jpg 300w, https://storage.googleapis.com/udx-ci-develop-alim/rabbit.ci/2019/11/b6dd0d95-alim-768x576.jpg 768w, https://storage.googleapis.com/udx-ci-develop-alim/rabbit.ci/2019/11/b6dd0d95-alim-300x225@2x.jpg 600w" sizes="(max-width: 1000px) 100vw, 1000px">`

**Comment by ewsopp** [comment]
I'm going to close out this issue. If it need further improvement, we can create a new issue.
