### ISSUE TITLE
Can't show 'stateless setup' menu again after first-setting.

### ISSUE THREAD

**Issue by ghost** [udx/wp-stateless#385]
After first-setting, 'stateless setup' menu will be deleted, and never show up.
I removed plugin and installed again, but it doesn't work.

I need to change project, but is there any way to solve?

**Comment by 4lenz1** [comment]
same problem here,

the only way is manual setup for now I thought.

**Comment by alimuzzaman** [comment]
@ryuta69 @4lenz1 
You have to remove JSON key from the setting page.

**Comment by ghost** [comment]
@alimuzzaman 
thank you, it's solved.
by the way, shouldn't it be mentioned?

**Comment by skillmatic-co** [comment]
I can't get the settings page to display at all under Media, am I missing something?
