### ISSUE TITLE
Field to enable billing

### ISSUE THREAD

**Issue by mlmunited** [udx/wp-stateless#386]
Hi, during set up I got this error
“Field to enable billing”

This is my second installation, previous was ok.

How can I fix it?
![Wp-Stateless error](https://user-images.githubusercontent.com/51192887/58621137-fc54d980-82c8-11e9-8697-bb279a851f64.jpg)

**Comment by kentprimrose** [comment]
Upvote: I have the same issue.

**Comment by alimuzzaman** [comment]
Hi @mlmunited @kentprimrose 

In case automatic setup fails please use the [Manual Setup process](https://github.com/wpCloud/wp-stateless/wiki/Manual-Setup).

Thanks
