### ISSUE TITLE
Test/dev site & live site

### ISSUE THREAD

**Issue by drandolph** [udx/wp-stateless#387]
I'm testing this on a clone of a live site that has about 3100 images. Other than running into gateway timeouts, which I think are from the host limiting scripts, it worked well. Can I install the plug-in on the live site & point it to the  images in the cloud bucket I created with the test site or do I have to go through the upload/synch process again?

The test site is not a staging site so I cannot push changes back & the live site is updated almost every day

**Comment by antonkorotkov** [comment]
Theoretically, if settings are the same on both sites then media should work on them in the exact same manner. But you always can do a re-sync if you feel that something is missing. 

Thanks for the question. Open a new issue if you still have questions.
