### ISSUE TITLE
The find/replace functionality

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#39]
The find/replace functionality should only happen when the user has selected another checkbox requesting it. We can also use this to warn them it will take extra long to perform.

**Comment by antonkorotkov** [comment]
@ewsopp can you explain/describe what you mean saying "find/replace"? We already do content search/replace on fly when needed. 

This option:
<img width="936" alt="00000215" src="https://cloud.githubusercontent.com/assets/2276882/16111113/c1041f28-33b9-11e6-883c-4fd5223a4478.png">

**Comment by ewsopp** [comment]
At this point, I think the best way forward is to not modify the post content and use filters to find/replace on the fly (without actually modifying database).
