### ISSUE TITLE
Settings Page Missing?

### ISSUE THREAD

**Issue by skillmatic-co** [udx/wp-stateless#390]
I'm working on a client's site that uses this plugin and trying to debug an issue. Is there any reason why I wouldn't be able to see the WP Stateless settings? There is nothing in the dropdown under Media or on the Settings > Media page.

**Comment by alimuzzaman** [comment]
@skillmatic-co 
It could be hidden by this constant https://github.com/wpCloud/wp-stateless/wiki/Constants#wp_stateless_media_hide_settings_panel

**Comment by skillmatic-co** [comment]
> @skillmatic-co
> It could be hidden by this constant https://github.com/wpCloud/wp-stateless/wiki/Constants#wp_stateless_media_hide_settings_panel

There is no WP Stateless constant defined in my clients wp-config.php file.

**Comment by skillmatic-co** [comment]
Found it, they had it hidden via another plugin called Adminimize.
