### ISSUE TITLE
Replace media.

### ISSUE THREAD

**Issue by DeysonOrtiz** [udx/wp-stateless#391]
Hello, I need to replace a few media files that need to be optimized further. Could I use a plugin like this to replace media files with this plugin?

https://wordpress.org/plugins/enable-media-replace/

Thank you.  :)

**Comment by antonkorotkov** [comment]
Theoretically, it should work out of the box it worth just trying. 
If not then it may mean we will have to think about adding such compatibility. 

Closing for now. Feel free to open a new issue if still have questions.
