### ISSUE TITLE
Cache busting not working with uppercase extension name

### ISSUE THREAD

**Issue by jasperkooij** [udx/wp-stateless#393]
Hello,

The cache-busting option is not working for me where images are uploaded with upper case extension name.

I'm using the CDN option as I have had a heap of trouble with the stateless setting overwriting existing files. 

With the CDN option enabled and the cache busting set in wp-config:

define('WP_STATELESS_MEDIA_CACHE_BUSTING', true );

I can upload a file "placeimg_640_480_nature.jpg" and I will end up with the uploaded file as:

2019/08/531bcf1b-placeimg_640_480_nature.jpg

I can upload a file "placeimg_640_480_nature.**JPG**" and I will end up with the uploaded file as:

2019/08/placeimg_640_480_nature.jpg

**Comment by alimuzzaman** [comment]
HI @jasperkooij,

This issue is no longer exists in our latest version of the plugin.

It was fixed with issue #377.

**Comment by jasperkooij** [comment]
Great, thanks for the update
