### ISSUE TITLE
Compatibility issue with shortpixel

### ISSUE THREAD

**Issue by arpanjot** [udx/wp-stateless#398]
We're using wp stateless along with shortpixel on our website. When both the plugins are enabled, it causes significant impact on the load times. To dig deeper, we tried analysing this by query monitor and it seems there is an issue with wp stateless plugin and shortpixel(when both of them are enabled together). As per the query monitor, one of the dependency short-pixel.min.js seems missing from shortpixel.

It seems shortpixel have renamed their shortpixel.min.js to short-pixel.min.js and that is causing the issue.
![Screenshot 2019-09-17 at 11 47 29 PM](https://user-images.githubusercontent.com/9058879/65071211-e1a78d00-d9ab-11e9-9533-c1214c087582.png)

**Comment by alimuzzaman** [comment]
Thanks, @arpanjot for reporting the problem.
The problem has been fixed and will be included in the next release.
