### ISSUE TITLE
10x10 Thumbnails Are Generated and Replacing Full Size Images (+403 Errors)

### ISSUE THREAD

**Issue by aquaextensions** [udx/wp-stateless#400]
On my site, there are no image sizes set to 10x10. Using the wp-stateless plugin on my Bitnami installation, images are being replaced by 10x10 versions (which do not exist within the bucket) and then creating multiple 403 errors. See below:

`<img width="10" height="10" src="https://storage.googleapis.com/stateless-bitnami-xicfntdnlw/2016/09/Clip-In-Hair-Extensions-10x10.jpg" class="vc_single_image-img attachment-full basel-lazy-load basel-lazy-fade wp-stateless-item" alt="Clip-In Hair Extensions" srcset="" sizes="(max-width: 10px) 100vw, 10px" data-basel-src="https://storage.googleapis.com/stateless-bitnami-xicfntdnlw/2016/09/Clip-In-Hair-Extensions-10x10.jpg" data-srcset="https://storage.googleapis.com/stateless-bitnami-xicfntdnlw/2016/09/Clip-In-Hair-Extensions-100x100.jpg 100w, https://storage.googleapis.com/stateless-bitnami-xicfntdnlw/2016/09/Clip-In-Hair-Extensions.jpg 480w" data-image-size="full" data-stateless-media-bucket="stateless-bitnami-xicfntdnlw" data-stateless-media-name="2016/09/Clip-In-Hair-Extensions.jpg">`

The 403 Errors for these 10x10 images are occurring for images that are displaying at the correct size as well. URL: [https://aquaextensions.com/](https://aquaextensions.com/)

<img width="1259" alt="Screen Shot 2019-09-19 at 4 24 13 PM" src="https://user-images.githubusercontent.com/52828865/65278340-ed08ce80-daf9-11e9-98d2-92568d008cd8.png">

**Comment by antonkorotkov** [comment]
@aquaextensions hey

sorry for the late response. 

Do you still have this issue?

**Comment by aquaextensions** [comment]
@antonkorotkov, thank you for your response. At the moment, we're not using GCP to host our website. The free credit ran out, but we're planning a move soon. If the issue occurs again, I'll reach out to you. For now, you can close this ticket. Quick question, is WordPress Stateless Media still the best option to offload images if our eCommerce site is image-intensive? Some of our products have over 20+ variations, so with the primary product images, some of them will load almost 30. Additionally, can WP-Stateless be used alongside CloudFlare, and if so, what's the best way to set up the configuration? And between CDN & Stateless, which is the faster option in terms of page load time?

**Comment by antonkorotkov** [comment]
> @antonkorotkov, thank you for your response. At the moment, we're not using GCP to host our website. The free credit ran out, but we're planning a move soon. If the issue occurs again, I'll reach out to you. For now, you can close this ticket. Quick question, is WordPress Stateless Media still the best option to offload images if our eCommerce site is image-intensive? Some of our products have over 20+ variations, so with the primary product images, some of them will load almost 30. Additionally, can WP-Stateless be used alongside CloudFlare, and if so, what's the best way to set up the configuration? And between CDN & Stateless, which is the faster option in terms of page load time?

We do everything to make it the best option. In regards to the third-party services configuration - it is all individually, I just don't know what could be best for your project right now. Please, open a new issue when you have some specific questions. Thanks.
