### ISSUE TITLE
How do I remove wp-stateless and restore image urls?

### ISSUE THREAD

**Issue by jasperkooij** [udx/wp-stateless#402]
How do I remove Wp-stateless and restore the local image URLs?

I was working in stateless mode but I kept running issues and so I want to remove wp-stateless.

I’ve turned on “BackupUpload media files to Google Storage and serve local file urls.”

then I resynced all the files.

then I turned on “DisabledDisable Stateless Media.”

But my image url’s are still pointing to Google Cloud Storage.

**Comment by alimuzzaman** [comment]
Hi @jasperkooij,

If you select the  Disable mode, image URLs should be pointing to your server.

Are you talking about URLs in page/posts?
Image URLs in page/post won't be changed if you disable WP Stateless.

You have to change them manually or use some tools to do it.

**Comment by hubertnguyen** [comment]
jasperkooij , try to clear all caches, or are the URLs hard-coded in the post?

alimuzzaman, what do you mean by "You have to change them manually or use some tools to do it."?

**Comment by antonkorotkov** [comment]
@jasperkooij were you able to solve your problem?

**Comment by blendjasper** [comment]
@antonkorotkov I turned off wp-stateless and then did a search a replace in the database. Then I removed the plugin.

**Comment by kwabowusu** [comment]
@jasperkooij : I am having the same issue.
Could you please walk me through the steps you took?
Esp. the "search and replace" part.

Thank you

**Comment by jasperkooij** [comment]
@kwabowusu I used the sync option available to bring back all the files or most of them. Then I did an extensive search and replace on the database to update all the image URLs. The WP CLI has been a great help with that. https://developer.wordpress.org/cli/commands/search-replace/.
