### ISSUE TITLE
Option to hide from wp-admin if enabled via wp-config.php

### ISSUE THREAD

**Issue by Mashenka** [udx/wp-stateless#41]
Much like how there is already options for bucket and mode with "define( 'WP_STATELESS_MEDIA_BUCKET', '*' );" etc. There should be an option to hide all WP-Stateless plugin menu's from the admin dashboard. This will be incredibly useful for multisite installs where users don't know what they're messing with. But will also help simplify the single site interface.

It could be something along the lines of; 
define( 'WP_STATELESS_DASHBOARD_CONFIG', 'true/false' ); 
with default behaviour being true.

http://feedback.usabilitydynamics.com/forums/353541-wp-statless/suggestions/14960856-option-to-hide-from-wp-admin-if-enabled-via-wp-con

**Comment by ewsopp** [comment]
@alimuzzaman while you are working on the settings constants, let's add support for this as well.

**Comment by alimuzzaman** [comment]
OK, 
#108

**Comment by alimuzzaman** [comment]
@ewsopp Should I also add to network settings?
