### ISSUE TITLE
Is there a way to exclude certain image sizes from being stored in GC?

### ISSUE THREAD

**Issue by oalexdoda** [udx/wp-stateless#412]
While in Stateless mode, there are image sizes that are not needed, and all they do is just clutter the site & bucket. 

Is there any filter we can use to make those image sizes not be uploaded to Google Cloud, and also have them not be in the uploads folder either?

Thanks!

**Comment by alimuzzaman** [comment]
Hello @Abruptive,

This question isn't related to WP Stateless but WordPress in general.

This article might help you. 
https://wpbeaches.com/remove-unused-image-media-sizes-wordpress-theme/

Or do a Google search.
