### ISSUE TITLE
File size doesn't show under attachment details using Stateless mode.

### ISSUE THREAD

**Issue by oalexdoda** [udx/wp-stateless#413]
![image](https://user-images.githubusercontent.com/8274669/68690653-0b7bcb00-057b-11ea-8730-d72bb4dd1591.png)

**Comment by alimuzzaman** [comment]
@Abruptive Problem has been fixed.

Please test and let us know. 
You can get the fixed version from here https://github.com/wpCloud/wp-stateless/tree/c91778ff5a42e081bf0f4f614531e11c6fd154fa

The fix will be included in the next release.
