### ISSUE TITLE
Theme page breaking after updating from 2.2.7 to any newer version

### ISSUE THREAD

**Issue by 3dwesupport** [udx/wp-stateless#417]
I have buddyboss theme and platform installed on my wordpress website, after updating from 2.2.7 to a newer version some parts of my webpages are not coming up and no error is coming in the console. just the content of the page is empty.
![image](https://user-images.githubusercontent.com/57365244/69245248-80c74b80-0bcc-11ea-9a00-91df78fe1562.png)

**Comment by alimuzzaman** [comment]
Hello @3dwesupport 

Can you please provide step by step instructions on how we can replicate the issue?

**Comment by alimuzzaman** [comment]
`Cache-Busting`  feature was causing the problem.

@3dwesupport I am assuming you were using `BuddyBoss Platform`.

**Comment by 3dwesupport** [comment]
@alimuzzaman Yes, We're using Buddyboss paltform. Have you found any solution for it?

**Comment by alimuzzaman** [comment]
@3dwesupport 
Yes, we have a solution. You can download the fix from here 
https://github.com/wpCloud/wp-stateless/releases/tag/2.3.2.RC1


Please let us know if this fixes your problem.

Thanks

**Comment by 3dwesupport** [comment]
Using this plugin does not resolve the problem totally, now some errors are coming in the console and the images of users are coming as invalid.
![image](https://user-images.githubusercontent.com/57365244/70687780-1c347380-1cd6-11ea-8360-096f5502ecd7.png)


Thanks

**Comment by alimuzzaman** [comment]
@3dwesupport Sorry for the trouble. 
Can you please test again with the new fix?
https://github.com/wpCloud/wp-stateless/releases/tag/2.3.2-RC.2

**Comment by 3dwesupport** [comment]
@alimuzzaman  Still there is an error after installing the above plugin.
![image](https://user-images.githubusercontent.com/57365244/70793775-19af4800-1dc2-11ea-8c2d-a1c12ece2a6b.png)

**Comment by alimuzzaman** [comment]
@3dwesupport 
I wasn't able to fully replicate your issue.

Can you please try this and let us know?
https://github.com/wpCloud/wp-stateless/releases/tag/2.3.2-RC.3

**Comment by 3dwesupport** [comment]
@alimuzzaman 
i tried again. Now all the images from stateless are not coming and there is this error coming in console for every image:

avatars189abf4a0-5dd10f46b531c-bpthumb.png:1 GET https://storage.googleapis.com/stateless-dev-itinker/avatars189abf4a0-5dd10f46b531c-bpthumb.png 403
Image (async)
(anonymous) @ jquery.js?ver=1.12.4-wp:3
X @ jquery.js?ver=1.12.4-wp:3
html @ jquery.js?ver=1.12.4-wp:3
bpInjectNotifications @ main.js?ver=1.2.9:1494
bpHeartbeatTick @ main.js?ver=1.2.9:1478
dispatch @ jquery.js?ver=1.12.4-wp:3
r.handle @ jquery.js?ver=1.12.4-wp:3
trigger @ jquery.js?ver=1.12.4-wp:3
a.event.trigger @ jquery-migrate.min.js?ver=1.4.1:2
(anonymous) @ jquery.js?ver=1.12.4-wp:3
each @ jquery.js?ver=1.12.4-wp:2
each @ jquery.js?ver=1.12.4-wp:2
trigger @ jquery.js?ver=1.12.4-wp:3
(anonymous) @ heartbeat.min.js?ver=5.3:1
i @ jquery.js?ver=1.12.4-wp:2
fireWith @ jquery.js?ver=1.12.4-wp:2
x @ jquery.js?ver=1.12.4-wp:4
c @ jquery.js?ver=1.12.4-wp:4
XMLHttpRequest.send (async)
send @ jquery.js?ver=1.12.4-wp:4
ajax @ jquery.js?ver=1.12.4-wp:4
l @ heartbeat.min.js?ver=5.3:1
(anonymous) @ heartbeat.min.js?ver=5.3:1
setTimeout (async)
d @ heartbeat.min.js?ver=5.3:1
(anonymous) @ heartbeat.min.js?ver=5.3:1
i @ jquery.js?ver=1.12.4-wp:2
fireWith @ jquery.js?ver=1.12.4-wp:2
ready @ jquery.js?ver=1.12.4-wp:2
J @ jquery.js?ver=1.12.4-wp:2

**Comment by alimuzzaman** [comment]
@3dwesupport 
Sorry for the inconvenient.

Can you try this update?
https://github.com/wpCloud/wp-stateless/archive/develop-alim.zip

If this doesn't work then I have to take look into your site.

**Comment by 3dwesupport** [comment]
@alimuzzaman this version seems working fine with the platform as i don't see any errors and missing images. still if you want  to test it yourself i can give you access to the platform (do drop us your email id). 
Do this version of the plugin will receive the timely updates?

**Comment by alimuzzaman** [comment]
> Do this version of the plugin will receive the timely updates?

Yes

>  still if you want to test it yourself i can give you access to the platform (do drop us your email id).

No

The new update will be released soon on WordPress.org.

**Comment by 3dwesupport** [comment]
@alimuzzaman Thanks for your help and Support. Happy Holidays
