### ISSUE TITLE
Plugin not working with Bucket_policy_only 

### ISSUE THREAD

**Issue by vrobert78** [udx/wp-stateless#419]
Hello,

We have tested your plugin with a bucket in Bucket_policy_only mode.
The upload failed silently. The media stayed on the disk instead of going in the bucket.

Switch the Bucket_policy_only to false solved the problem.

Your competitor, WP Media Cloud, support this option.

Regards,

**Comment by ewsopp** [comment]
`Bucket_policy_only` has been deprecated and replaced with `uniform_bucket_level_access`.

Relevant issue at https://github.com/udx/wp-stateless/issues/521
