### ISSUE TITLE
Add this plugin to packagist.org

### ISSUE THREAD

**Issue by onnimonni** [udx/wp-stateless#42]
This would help us to use it more easier.

Also please add your custom libraries it's using to packagist.

Thanks :)!

**Comment by onnimonni** [comment]
In order to install this plugin with composer I have to add following to my composer:

```
{
  "repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/wpcloud/wp-stateless"
    },
    {
        "type": "vcs",
        "url": "https://github.com/usabilitydynamics/lib-settings"
    },
    {
        "type": "vcs",
        "url": "https://github.com/usabilitydynamics/lib-wp-bootstrap"
    },
    {
        "type": "vcs",
        "url": "https://github.com/usabilitydynamics/google-api-php-client"
    },
    {
        "type": "vcs",
        "url": "https://github.com/usabilitydynamics/lib-utility"
    }
  ],
  "require": [
    "wpcloud/wp-stateless": "^1.9.1"
  ]
}
```

You could make this all easier by using packagist.org for all your custom packages. So after that the composer installation would be just:

```
"require": [
    "wpcloud/wp-stateless": "^1.9.1"
]
```

**Comment by shaneog** [comment]
From what I can see, it's only the fork of `google-api-php-client` that is preventing the use of Packagist. 
Is there any reason why a fork is required - it doesn't look too different to the released API library from Google?
It would be great to see Packagist implemented.

**Comment by leepeterson** [comment]
Probably already well-known by now, but before someone sees this open issue and thinks WP-Stateless cannot be managed using Composer:

```json
{
	"name" : "your/project",
	"type" : "project",
	"repositories" : [
		{ "type" : "composer", "url" : "https://wpackagist.org" }
	],
	"require" : {
		"wpackagist-plugin/wp-stateless" : "^2.1.0"
	},
	"prefer-stable" : true
}
```

**Comment by ewsopp** [comment]
Published at https://packagist.org/packages/wpcloud/wp-stateless

@leepeterson @shaneog @onnimonni Would you guys mind testing this out?
