### ISSUE TITLE
Downgrade from Stateless Mode to Backup/CDN Modes

### ISSUE THREAD

**Issue by matthewlenz** [udx/wp-stateless#422]
A Sync option to downgrade from Stateless mode to Backup/CDN modes would be very useful.

**Comment by planv** [comment]
Hello @matthewlenz 

You can change mode to `Backup` or `CDN`

![image](https://user-images.githubusercontent.com/5268508/95301857-d7dc1a80-0889-11eb-8389-c7da667fcdbc.png)

And when you re-sync - all media will be stored locally.

Closing the ticket.
