### ISSUE TITLE
wpbakery compatibility does not account for bucket_folder name

### ISSUE THREAD

**Issue by jjtroberts** [udx/wp-stateless#428]
When adding an image to a gallery using wpbakery page builder, I receive the following error:
![wpstateless_wpbakery_compatibility_error_absolutepath](https://user-images.githubusercontent.com/18486187/71627490-56e44a00-2bb8-11ea-84d3-65f5b30c82d0.png)

In our GCS buckets, and in the wp-stateless settings, our bucket folder (root_dir) is set to "uploads" which is not accounted for in the str_replace and results in an invalid filepath because "uploads/uploads" does not exist.

`Error is being thrown by this code: https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/compatibility/wpbakery-page-builder.php#L51-L57
 
wp eval "var_dump(wp_upload_dir());"
array(6) {
  'path' =>
  string(37) "/var/www/html/web/app/uploads/2019/12"
  'url' =>
  string(53) "https://xxxxxxxxxxx/app/uploads/2019/12"
  'subdir' =>
  string(8) "/2019/12"
  'basedir' =>
  string(29) "/var/www/html/web/app/uploads"
  'baseurl' =>
  string(45) "https://xxxxxxxxxxx/app/uploads"
  'error' =>
  bool(false)
}

sm_root_dir	uploads

wp eval "var_dump(str_replace('https://storage.googleapis.com/xxxxxxxxxxx', '', 'https://storage.googleapis.com/xxxxxxxxxxx/uploads/New-2018-slide-ext-9.jpg'));"
string(33) "/uploads/New-2018-slide-ext-9.jpg"

$absolute_path = $dir['basedir'] . '/' . $path;
So the resulting value of $absolute_path: "/var/www/html/web/app/uploads" + "/uploads/New-2018-slide-ext-9.jpg"`

Should the str_replace also remove the sm_root_dir?

**Comment by jjtroberts** [comment]
In my GCS bucket, any file uploaded through wpbakery was saved in "sm_root_dir/uploads", which for us results in "gs://bucket-name/uploads/uploads". That "uploads/uploads" filepath does not exist on the local filesystem.

**Comment by antonkorotkov** [comment]
Hey @jjtroberts 

I was trying to reproduce your issue but I could not. 

Can you provide some details about how we can replicate it? 
Maybe some specific steps or configuration. 

I was trying to upload images from inside the Image Gallery component and it all works with custom Bucket Folder setting.

My version of WPBakery is 5.3 and WP is latest.

**Comment by jjtroberts** [comment]
I don't recall which site this error took place on. I'll close this issue and if it recurs I'll create a new issue.
