### ISSUE TITLE
font and Cors

### ISSUE THREAD

**Issue by mjezegou** [udx/wp-stateless#431]
I would like to upload a font to google storage. It works well with wp-statless and custom fonts.

The font file is blocked by the Cors policy in the page header (@ font-face {font-family: XXX; src: url (xxx) ...).

I then modified the configuration of my bucket => https://cloud.google.com/storage/docs/configuring-cors.

with "origin": ["*"] but is it possible to set the current domain because my policy is paid?

Google_Service_Storage_Bucket-> setCors (..).

**Comment by antonkorotkov** [comment]
@mjezegou plugin does not allow managing CORS configuration remotely, for now. You need to set CORS manually as described in docs you sent https://cloud.google.com/storage/docs/configuring-cors
