### ISSUE TITLE
Profile Images are not syncing on buddyboss platform using WP-Stateless

### ISSUE THREAD

**Issue by 3dwesupport** [udx/wp-stateless#437]
When i am uploading new profile image for a user, it is not syncing.
There is no error on the console.
And sometimes there is different profile image on different locations

**Comment by antonkorotkov** [comment]
I think it was fixed in this issue in terms of BuddyPress compatibility https://github.com/wpCloud/wp-stateless/issues/275

It will be rolled out in the next release.
