### ISSUE TITLE
max_upload_size error sync with gcs

### ISSUE THREAD

**Issue by swillfed** [udx/wp-stateless#439]
I cannot sync files larger than 128MB with gcs. keep getting error '. Check your server configuration.' 

server max_upload_size and max_post_size is 512MB and nginx configured as well. uploading and media sync via SFTP is working. Just can't sync the files to gcs.  

Is there any limit on file size with wp-stateless?

**Comment by alimuzzaman** [comment]
@swillfed 
Can you please share a screenshot of the error?

Is this the error you are getting?

![image](https://user-images.githubusercontent.com/6744156/73196872-99b72480-415a-11ea-8e71-c01ccbb350de.png)

**Comment by swillfed** [comment]
That's the error but I don't get a 413 for files larger than 200MB. Anywhere between 128 and 200 gives 413. 

<img width="1123" alt="Console-Image" src="https://user-images.githubusercontent.com/44353512/73314630-6ff91d00-4282-11ea-9538-ac62e8464ee7.PNG">

<img width="1126" alt="Console-Image-413" src="https://user-images.githubusercontent.com/44353512/73314919-cc5c3c80-4282-11ea-8f3a-6afea7d0b7eb.PNG">

**Comment by alimuzzaman** [comment]
@swillfed 
There is nothing wrong on our side. We ware able to upload a 256mb file to GCS.
I think there is a problem with your server configuration.

**Comment by antonkorotkov** [comment]
Closing for now. Feel free to reopen if it is still relevant.
