### ISSUE TITLE
Add ability to set keyfile JSON via environment variable

### ISSUE THREAD

**Issue by shaneog** [udx/wp-stateless#44]
It would be great to be able to set the keyfile JSON as an environment variable, for example: WP_STATELESS_MEDIA_KEY_FILE_JSON

**Comment by antonkorotkov** [comment]
Could you try please using this one WP_STATELESS_MEDIA_KEY_FILE_PATH. Report please if it works or not. Thanks.

**Comment by shaneog** [comment]
I'm afraid that doesn't work, @antonkorotkov. 

![wp-stateless](https://cloud.githubusercontent.com/assets/130415/18128764/ce4c7dd0-6f5d-11e6-9359-feb08da0b76b.png)

**Comment by ewsopp** [comment]
@shaneog we updated constants in v2.0.0 and documented them all within the GitHub Wiki at https://github.com/wpCloud/wp-stateless/wiki/Constants

You can supply the service account key as plain text JSON via the `WP_STATELESS_MEDIA_JSON_KEY` constant or JSON file via the `WP_STATELESS_MEDIA_KEY_FILE_PATH` constant.

Please let us know if you have any issues. Thanks.
