### ISSUE TITLE
Incompatibility with Divi from version 2.3.x

### ISSUE THREAD

**Issue by JoakuGit** [udx/wp-stateless#441]
The plugin caused me problems in 3 different places with Divi from its version in 2.3.x which I had to go back to 2.2.0 (which works without problems)

The problems they cause are;
* Does not work on site builder (no load)
* The site's CSS is disarmed and so on.

**Comment by harrystymiest** [comment]
I had no issues with images not loading on sitebuilder in 2.3.x

**Comment by antonkorotkov** [comment]
@jackmoonishere hey. 

Do you have any specific steps to reproduce these issues? It will help us address them faster.

Thanks.

**Comment by planv** [comment]
@jackmoonishere 

Is issue still relevant?

**Comment by ewsopp** [comment]
Closing for now. 

Please reopen if issue persists and provide as much detail as possible.
