### ISSUE TITLE
File Upload Error: Passing glue string after array is deprecated.

### ISSUE THREAD

**Issue by renduples** [udx/wp-stateless#444]
We are getting the following errors during file upload:
Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/html/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298
Wordpress 5.3.2
PHP 7.4.2 
Stateless Mode

**Comment by antonkorotkov** [comment]
@renduples thanks you for pointing. We will try to address this as soon as possible.

**Comment by antonkorotkov** [comment]
The fix will be included in the next release. Thanks.
