### ISSUE TITLE
CLI for manual Sync 

### ISSUE THREAD

**Issue by renduples** [udx/wp-stateless#447]
I have noticed in the code - https://github.com/wpCloud/wp-stateless/tree/v2.3/lib/cli  There are a few CLI commands like upgrade. Are there any plans to expand the CLI? For example to resync a single/range/or all objects in the library. As currently possible from the Admin Panel.

**Comment by antonkorotkov** [comment]
@renduples yes, you are right - there are some efforts done in the CLI direction but the current implementation is outdated and was not supported for a while.

We will try to review if it is something we can spend time on. Thank you for your interest.

**Comment by ewsopp** [comment]
spawned issues at https://github.com/wpCloud/wp-stateless/issues/451 and https://github.com/wpCloud/wp-stateless/issues/450
