### ISSUE TITLE
Sync media according to new Bucket Folder settings

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#449]
This new sync method will allow the user to move files after change the Bucket Folder value.

- [ ] ~~We won't do regeneration to increase performance.~~

- [x] Add sync link in the Media library.

- [x] We will copy the files to the new location on GCS.

- [x] Also copy the file to the new location in the server if available.

**Comment by alimuzzaman** [comment]
@ewsopp @planv 
This might cause a problem with hardcoded URLs in pages/posts.
Maybe we should add a warning.

**Comment by ewsopp** [comment]
Do we delete files when doing a sync?

**Comment by alimuzzaman** [comment]
@antonkorotkov will it be viable to replace old URLs with the new URL in post content/meta for all attachments?

For example if a site have lots of posts.

**Comment by alimuzzaman** [comment]
@ewsopp 
> Do we delete files when doing a sync?

No. But this can be a problem for site with lots of media.

**Comment by alimuzzaman** [comment]
@planv is this option was added to CLI?

**Comment by planv** [comment]
@alimuzzaman Not yet.

- [x] Add new sync option to CLI


I will add it after we finish new sync method on admin panel.

**Comment by planv** [comment]
@alimuzzaman  I added new option `use_wildcards` or CLI sync command.

**Comment by alimuzzaman** [comment]
@planv how do I use `use_wildcards`?

**Comment by planv** [comment]
@alimuzzaman Please use this command
`wp stateless sync images --force --use_wildcards`

**Comment by alimuzzaman** [comment]
It's working.
