### ISSUE TITLE
Always getting an error - Could not connect to Google Storage bucket. 

### ISSUE THREAD

**Issue by jj999** [udx/wp-stateless#45]
Hi guys,

Your plugin is what I need, but I always get below error:

WP-Stateless is not active due to following errors:
Could not connect to Google Storage bucket. Please, be sure that bucket with name 'my-bucket' exists.

I'm using WP 4.6.1 (multisite) and also it seems Google has added roles (and permissions?) into the service account. I tried different settings - with storage roles and without, with permissions and without, but I always get the same error. My bucket exists and I use the same name for bucket as for service account. I enabled WP_DEBUG and in Settings/Media Debug section I can see correct bucket name and content of JSON file, but not sure how to debug it further.

I was looking into get_client() in class-bootstrap.php - what is the best way to obtain more detailed erorr report? 

Thank you.

**Comment by Mashenka** [comment]
Hello.

Try to check your user account and JSON credentials one more time.

Regards.

**Comment by jj999** [comment]
Bucket name is correct and JSON credentials were copy/pasted from service account when I created it. I also found error message from is_connected(): (I'm trying to access it from Google compute Engine)
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "Forbidden"
   }
  ],
  "code": 403,
  "message": "Forbidden"
 }
}
And here is more detailed message: [http://pastebin.com/Li6vXNNT](http://pastebin.com/Li6vXNNT) (sensitive info removed)
Can I see somewhere in the cloud console why is it forbidden?

**Comment by Mashenka** [comment]
Account which you have at the moment does not have access to that bucket. Try to re-create your account.

**Comment by jj999** [comment]
Mashenka - thank you very much, it seems it is starting to work :) :+1:

**Comment by Mashenka** [comment]
Can you give steps for other users who will have similar issue how to fix that?

Thanks.

**Comment by jj999** [comment]
It seems to me google added new field called "role" into Service account creation screen. The easiest thing is to not to select any role, and then go to your bucket and add new permission - for your Service user you just created - for example: You add permission for **User**, you enter **Service user name** - my-project-bucket-user@my-project-123456.iam.gserviceaccount.com and add permission as **Writer**. Also be careful when you create service account with different name than bucket - then don't mistake one with another when configuring wp-stateless - you need to enter bucket name in the Settings/Media/Credentials/Bucket  ;)

**Comment by Mashenka** [comment]
Thanks for feedback.

**Comment by blesphil** [comment]
Hi,

WP-Stateless is showing an error all the time. I adjusted the roles and settings in GCS Console (There's not much settings to play around in the plugin itself-which I say is amazing-keep it simple), but it shows the same error all the time:

"WP-Stateless is not active due to following errors: Could not connect to Google Storage bucket."

I found a couple of threads that talk of the same problem, but the solutions provided there (even the one mentioned here) did not work for me.

Some Additional Info: I am still on a development server (localhost), could that be the reason for not being able to connect to the GCS bucket?

Warm regards,

Bles

**Comment by ewsopp** [comment]
This is a resolved issue, but anyone who may come across this thread during research should update to the latest version and review the manual configuration instructions at https://github.com/wpCloud/wp-stateless/wiki/Manual-Setup

**Comment by markokhman** [comment]
My problem was that i had some empty lines in JSON private key field. Made me crazy, but this message might save your time

**Comment by Mashenka** [comment]
@markusila thank you for the feedback. We appreciate it.
