### ISSUE TITLE
Review and clean up the current CLI implementation

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#450]
The current CLI implementation is outdated and it is possible that it may just not work.
Need to review it and test/fix/cleanup or remove and start from scratch if needed.

**Comment by antonkorotkov** [comment]
I think the new command (`wp sm`) should be renamed to something else less generic because `sm` could interfere with another third-party command. How about `wp stateless` at least?

**Comment by planv** [comment]
The current CLI implementation is working. 
Command `upgrade` uses for update postmeta from old structure to new.

Renamed command `sm` to `stateless`.

**Comment by antonkorotkov** [comment]
Ok, let it exist then.

**Comment by ewsopp** [comment]
@alimuzzaman can you test this please?

**Comment by alimuzzaman** [comment]
OK, testing.

**Comment by planv** [comment]
@alimuzzaman Is it ok for you or you have any suggestions?

**Comment by alimuzzaman** [comment]
Command sm renamed to stateless.

`wp stateless sync images`
