### ISSUE TITLE
Show image information about image thumbnail and other sizes

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#452]
Show information about image sizes on the edit media page.

**Comment by ewsopp** [comment]
![IMG_20200407_083229](https://user-images.githubusercontent.com/5578537/78672066-20e8ed00-78ae-11ea-876a-d43ee0aa93be.jpg)

**Comment by planv** [comment]
@ewsopp 
I added information about sizes to metabox on media edit page.
But for now we haven't functionality for synchronize separated size.

![image](https://user-images.githubusercontent.com/5268508/80143700-e2457900-85b5-11ea-8a0c-6606df2642f7.png)

**Comment by planv** [comment]
Related issue #470 , all information there.  
I think we can close this issue.
