### ISSUE TITLE
Multisite compatible?

### ISSUE THREAD

**Issue by cturnbull** [udx/wp-stateless#453]
Hello,

How does WP Stateless compatibility for multisite work?

Can, for example, the media library on one site be synchronised with GCS if another site has uploaded some media? Can both sites share the same attachment?

**Comment by ykawato** [comment]
I tried this plugin on multisite. 
Unfortunately, the files were not saved under a blog_id folder, so all the files were in the same bucket. Hence, when I upload the same image from different blogs under the multisite, the file name will conflict, and I could not upload the latter one.

**Comment by planv** [comment]
@ykawato 

The fix will be included in the next release.

Before for prevent issue with same filenames you can enable option `Cache-Busting`

![image](https://user-images.githubusercontent.com/5268508/83158468-7eaaf000-a10d-11ea-9e0e-4adb77ad7602.png)

**Comment by lopesval** [comment]
Hello, is this multisite issue fixed? Does it maintain the same folder structure with a folder for each site named with block ID?

**Comment by planv** [comment]
Hello @lopesval 

In the next release will be added the ability to use `wildcards` for field `Folder`. 
This will make it possible to use the `blog ID` in the path structure

![изображение](https://user-images.githubusercontent.com/5268508/84374357-8d51d680-abe6-11ea-92e4-5ba1ed35c64f.png)

**Comment by lopesval** [comment]
Wow great🙏🏾 thank you

**Comment by planv** [comment]
This has been fixed in 3.0

Closing the ticket.
