### ISSUE TITLE
Could not connect to Google Storage bucket. Could not resolve host: http://www.googleapis.com

### ISSUE THREAD

**Issue by harshmanvar** [udx/wp-stateless#456]
My site is using the wp-stateless plugin. It was working well but suddenly started giving error like

WP-Stateless is not active due to following errors:
Could not connect to Google Storage bucket. Could not resolve host: http://www.googleapis.com

however i have not updated anything. it was working well.

**Comment by ctzkane** [comment]
I just experienced this issue. My problem was that there was a stale 'sm::is_connected_to_gs' transient (probably from syncing the dev database back from prod)

Deleting the transient from wp_cli fixed the issue for me.

**Comment by alimuzzaman** [comment]
@ctzkane saving the settings has the same effect.

**Comment by planv** [comment]
Hello @harshmanvar 

Is issue still relevant?

**Comment by harshmanvar** [comment]
No, not facing issue now

**Comment by antonkorotkov** [comment]
That could be just temporary unavailable Google's API. Closing for now.
