### ISSUE TITLE
Test gravity form compatibility

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#457]
https://wordpress.org/support/topic/gravity-forms-uploads-not-working/
https://wordpress.org/support/topic/wp-stateless-not-being-used-for-file-uploads/

https://wordpress.org/support/topic/gravtiy-forms-export-doesnt-work/

**Comment by alimuzzaman** [comment]
@ewsopp 
With the development version, the Gravity Form is working fine.

Currently, the GF structure their directory regardless of the WP Organize Media option.
So year month is included twice in the URL.

//storage.googleapis.com/stateless-udx-io/sites/2/**2020/03**/gravity_forms/6546....../**2020/03**/15813978-bingimageoftheday.jpg

**Comment by ewsopp** [comment]
Did you test the "Multiple Files" option on the _File Upload_ field? 

![image](https://user-images.githubusercontent.com/5578537/76918099-dfab8180-689b-11ea-8639-51efcf58db30.png)

Did you test multiple _File Upload_ fields on a single form?

![image](https://user-images.githubusercontent.com/5578537/76918188-12ee1080-689c-11ea-94bc-6e4a6bd40d4e.png)

**Comment by alimuzzaman** [comment]
@ewsopp yes I have tested that.
