### ISSUE TITLE
WP-Stateless Activated on New Server Slow or Offline

### ISSUE THREAD

**Issue by 4loveofpunk** [udx/wp-stateless#46]
Hello,

I had this plugin on 20 plus sites with EasyApache 4 / CloudLinux / Nginx combo and everything was perfect. I just set up a brand new server with the same combination and have tracked down that if this plugin is enabled, the site slows to 3 minute load times or I get "website is offline" for any site that I activate wp-stateless on. Once deactivated, everything for the site works perfectly.

I am the server admin so have full access and curious if there is maybe some php requirement for the plugin that I don't have enabled and if you guys are aware of anything necessary to make this work?

I can give more info if needed, just really curious if I'm missing something small.

Latest version of cPanel, Latest version of EA4, Latest version of PHP 7 and running prefork.

**Comment by andypotanin** [comment]
@4loveofpunk is this problem still happening? Were you able to resolve?

**Comment by 4loveofpunk** [comment]
@andypotanin it is not. Not sure what the problem was (maybe an extension not enabled on the server at the time) but I'm since moved to new VPS and everything seems to be working great!

**Comment by andypotanin** [comment]
Okay glad to hear.
