### ISSUE TITLE
Filtering upload_dir 

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#461]
## Single site:
`/%date_year%/%date_month%/`
Empty Bucket Folder. 
Organize Media enabled.
### Original/Stateless disabled:
```
Array
(
    [path] => /var/www/wp-content/uploads/2020/03
    [url] => https://alim.rabbit.ci/wp-content/uploads/2020/03
    [subdir] => /2020/03
    [basedir] => /var/www/wp-content/uploads
    [baseurl] => https://alim.rabbit.ci/wp-content/uploads
    [error] => 
)
```
### After Filter:
```
Array
(
    [path] => /var/www/wp-content/uploads/2020/03
    [url] => https://alim.rabbit.ci/wp-content/uploads/2020/03
    [subdir] => /2020/03
    [basedir] => /var/www/wp-content/uploads
    [baseurl] => https://alim.rabbit.ci/wp-content/uploads
    [error] => 
)
```

## Multisite:
`/sites/%site_id%/%date_year%/%date_month%/`
Organize Media enabled.
### Original/Stateless disabled:
```
Array
(
    [path] => /var/www/wp-content/uploads/sites/2/2020/03
    [url] => http://test1.stateless.ci/wp-content/uploads/sites/2/2020/03
    [subdir] => /2020/03
    [basedir] => /var/www/wp-content/uploads/sites/2
    [baseurl] => http://test1.stateless.ci/wp-content/uploads/sites/2
    [error] => 
)
```
### After Filter:
```
Array
(
    [path] => /var/www/wp-content/uploads/sites/2/2020/03
    [url] => http://test1.stateless.ci/wp-content/uploads/sites/2/2020/03
    [subdir] => /sites/2/2020/03
    [basedir] => /var/www/wp-content/uploads
    [baseurl] => http://test1.stateless.ci/wp-content/uploads
    [error] => 
)
```

**Comment by alimuzzaman** [comment]
@antonkorotkov 
How should we handle `subdir `and `basedir`/`baseurl`?

For the single site, we can match the original data.

But in multisite, `/sites/2/` was included in `basedir `instead of `subdir`. But we can't divide like that because we use one field (Bucket Folder).

What do you think if we append `subdir` to `basedir` and make `subdir` empty?

**Comment by alimuzzaman** [comment]
This only concerns multisite.
With the current implementation, the gravity form creates its directory in uploads dir instead of the specific `sites` dir.

1. We can move `Bucket Folder` into `basedir` from `subdir`. Not sure how plugins will react with dynamic `basedir` that can changes over time.
2. We can take two inputs in `Bucket Folder` one for `basedir` where wildcard evaluates to static value another for `subdir` with dynamic value.

**Comment by andypotanin** [comment]
@alimuzzaman I've been assigned to this, I assume that means we should have a meeting? FYI @ewsopp

**Comment by ewsopp** [comment]
Good question. Let me digest it and see if we need you.

**Comment by alimuzzaman** [comment]
@ewsopp I want to split `Bucket Folder` into two fields. 
Because in multisite with our current implementation base_dir is root upload dir, instead of separate dir (sites/2) for each site.

This create problem with other plugins, ex. GF. GF creates its dir in root upload dir instead of site-specific dir(sites/2).

**Comment by alimuzzaman** [comment]
This also break non synced media after migration/fresh install if the `basedir` doesn't match.

- [x] We may use `wp_get_attachment_metadata` filter to prepend `sites/{id}` to the `file` meta for non-synced media.

**Comment by alimuzzaman** [comment]
@planv do you have any idea?

**Comment by ewsopp** [comment]
> This create problem with other plugins, ex. GF. GF creates its dir in root upload dir instead of site-specific dir(sites/2).

Why can't this be supported via our compatibility feature?

**Comment by alimuzzaman** [comment]
@ewsopp 
>Why can't this be supported via our compatibility feature?

I am not sure that would be possible to do for most of the plugin.


But this also create a problem for non-synced media.
https://github.com/wpCloud/wp-stateless/issues/461#issuecomment-601862587

**Comment by planv** [comment]
https://github.com/wpCloud/wp-stateless/issues/461#issuecomment-600332315

@alimuzzaman Maybe we could add this to `function _wp_upload_dir` ?

<img width="791" alt="изображение" src="https://user-images.githubusercontent.com/5268508/77368689-73ca8c80-6d65-11ea-96e1-518c585051f5.png">

And do not add `sites/$site_id/` in `function root_dir_wildcards`

**Comment by alimuzzaman** [comment]
>And do not add sites/$site_id/ in function root_dir_wildcards

Yes we can do that. It will be safe but wildcard functionality will be reduced.

@ewsopp what do you think?

**Comment by ewsopp** [comment]
> This only concerns multisite.
> With the current implementation, the gravity form creates its directory in uploads dir instead of the specific `sites` dir.
> 
> 1. We can move `Bucket Folder` into `basedir` from `subdir`. Not sure how plugins will react with dynamic `basedir` that can changes over time.
> 2. We can take two inputs in `Bucket Folder` one for `basedir` where wildcard evaluates to static value another for `subdir` with dynamic value.

WP-Stateless Core is responsible for objects that are registered in the Media Library. If a plugin doesn't follow this method of storing uploads, then we create a compatibility for it.

We've already created a compatibility for Gravity Forms. Why can't we extend this existing compatibility to keep the files stored however Gravity Forms prefers it (in its own upload directory)?

**Comment by alimuzzaman** [comment]
- [x] We will use `wp_get_attachment_metadata` to fix link for non-synced media.

**Comment by alimuzzaman** [comment]
@planv made new changes here.
https://github.com/wpCloud/wp-stateless/commit/1aea477ab78794cfbe2137575fccbd4f9c205577

**Comment by planv** [comment]
## Single site:
`/%date_year%/%date_month%/`
Empty Bucket Folder. 
Organize Media enabled.
### Original/Stateless disabled:
```
Array
(
    [path] => /var/www/wp-content/uploads/2020/03
    [url] => https://alim.rabbit.ci/wp-content/uploads/2020/03
    [subdir] => /2020/03
    [basedir] => /var/www/wp-content/uploads
    [baseurl] => https://alim.rabbit.ci/wp-content/uploads
    [error] => 
)
```
### After Filter:
```
Array
(
    [path] => /var/www/wp-content/uploads/2020/03
    [url] => https://alim.rabbit.ci/wp-content/uploads/2020/03
    [subdir] => /2020/03
    [basedir] => /var/www/wp-content/uploads
    [baseurl] => https://alim.rabbit.ci/wp-content/uploads
    [error] => 
)
```

## Multisite:
`/sites/%site_id%/%date_year%/%date_month%/` or `/sites/%site_id%/`
Organize Media enabled.
### Original/Stateless disabled:
```
Array
(
    [path] => /var/www/wp-content/uploads/sites/2/2020/03
    [url] => http://test1.stateless.ci/wp-content/uploads/sites/2/2020/03
    [subdir] => /2020/03
    [basedir] => /var/www/wp-content/uploads/sites/2
    [baseurl] => http://test1.stateless.ci/wp-content/uploads/sites/2
    [error] => 
)
```
### After Filter:
```
Array
(
    [path] => /var/www/wp-content/uploads/sites/2/2020/03
    [url] => http://test1.stateless.ci/wp-content/uploads/sites/2/2020/03
    [subdir] => /2020/03
    [basedir] => /var/www/wp-content/uploads/sites/2
    [baseurl] => http://test1.stateless.ci/wp-content/uploads/sites/2
    [error] => 
)
```
