### ISSUE TITLE
Review migration 

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#462]
- [x] Review fresh install with existing non synced media.

- [x] Review upgrade

**Comment by alimuzzaman** [comment]
# Mapping for Existing Users

This should account for all current configurations. Are we missing anything? 

- [x] If _Organization_ is enabled **AND** _ Bucket Folder_ is empty: Single Site
- [x] If _Organization_ is enabled **AND** _ Bucket Folder_ is not empty: Previous bucket folder + Single Site
- [x] If _Organization_ is disabled: Custom
- [x] If they have a value in _Bucket Folder_: Custom, and keep that setting.
- [ ] In multisite prefix with `/sites/%site_id%/` value evaluated from above condition.

**Comment by planv** [comment]
@alimuzzaman 

>  If Organization is enabled AND _ Bucket Folder_ is not empty: Previous bucket folder + Single Site

it will be `Custom`, no?

<img width="776" alt="изображение" src="https://user-images.githubusercontent.com/5268508/77580898-6d631e80-6ee5-11ea-9cdc-39395fc73c09.png">

**Comment by alimuzzaman** [comment]
Custom folder should have been at the beginning.

**Comment by alimuzzaman** [comment]
Yes it will be custom.

**Comment by alimuzzaman** [comment]
@ewsopp **Organization** is enabled AND **Bucket Folder** is not empty:

Single site: `/bucket_folder/%date_year%/%date_month%/`.
Multisite:  `/sites/%site_id%/multisite/%date_year%/%date_month%/`.

**Comment by planv** [comment]
> Single site: /multisite/%date_year%/%date_month%/.

Are we using `multisite` on path?

>  AND Bucket Folder is not empty:

So we add current value `Bucket Folder` to path.

**Comment by alimuzzaman** [comment]
> Are we using multisite on path?

It's just a bucket folder value I used, nothing to do with multisite.

> So we add current value Bucket Folder to path.

Yes

**Comment by ewsopp** [comment]
> @ewsopp **Organization** is enabled AND **Bucket Folder** is not empty:
> 
> Single site: `/bucket_folder/%date_year%/%date_month%/`.
> Multisite: `/sites/%site_id%/multisite/%date_year%/%date_month%/`.

Why is `/multisite/` included in the path here?

Also - if **Organization** is enabled AND **Bucket Folder** is not empty: then shouldn't we set it as custom for both single site and multisite? 

Custom: `/bucket_folder/%date_year%/%date_month%/`

**Comment by planv** [comment]
> Why is /multisite/ included in the path here?

It is typo. Should be `bucket_folder` instead `multisite`.

> Also - if Organization is enabled AND Bucket Folder is not empty: then shouldn't we set it as custom for both single site and multisite?

> Custom: /bucket_folder/%date_year%/%date_month%/

Yes, it is `Custom`, but we will also have `/sites/%site_id%/` for multisite.

Single site: `/bucket_folder/%date_year%/%date_month%/`
Multisite: `/sites/%site_id%/bucket_folder/%date_year%/%date_month%/`

**Comment by alimuzzaman** [comment]
@ewsopp 
> Also - if Organization is enabled AND Bucket Folder is not empty: then shouldn't we set it as custom for both single site and multisite?

As it will not affect existing media, I think including `sites/%site_id%` makes more sense to me.

Where `/bucket_folder/%date_year%/%date_month%/`  keep URL structure on GCS same.

**Comment by ewsopp** [comment]
> @ewsopp **Organization** is enabled AND **Bucket Folder** is not empty:
> 
> Single site: `/bucket_folder/%date_year%/%date_month%/`.
> Multisite: `/sites/%site_id%/multisite/%date_year%/%date_month%/`.



> > Why is /multisite/ included in the path here?
> 
> It is typo. Should be `bucket_folder` instead `multisite`.
> 
> > Also - if Organization is enabled AND Bucket Folder is not empty: then shouldn't we set it as custom for both single site and multisite?
> 
> > Custom: /bucket_folder/%date_year%/%date_month%/
> 
> Yes, it is `Custom`, but we will also have `/sites/%site_id%/` for multisite.
> 
> Single site: `/bucket_folder/%date_year%/%date_month%/`
> Multisite: `/sites/%site_id%/bucket_folder/%date_year%/%date_month%/`

If that is the case, why would it not follow the following CUSTOM setting...

`/bucket_folder/%date_year%/%date_month%/`

If we did not support `/sites/%site_id%/` before, why would we add it in now? You will effectively change the setting they had.

During this upgrade, we don't want to change anyone's setting. They should upgrade gracefully without affecting their custom settings. Right?

**Comment by alimuzzaman** [comment]
> During this upgrade, we don't want to change anyone's setting. They should upgrade gracefully without affecting their custom settings. Right?

OK

**Comment by ewsopp** [comment]
@planv @alimuzzaman do you both agree?

The real question is this: Do we update their settings to reflect the proper multisite organization or do we keep their settings as-is?

My feeling is that we leave it as-is. Otherwise we are effectively changing their settings without them knowing. Thoughts?

**Comment by alimuzzaman** [comment]
~~Yes, we should keep the setting as is.~~

**Comment by planv** [comment]
> If we did not support /sites/%site_id%/ before, why would we add it in now? You will effectively change the setting they had.

WordPress uses this structure `\sites\$site_id\` by default for multisite since version 3.5 (December 11, 2012)
https://wordpress.org/support/article/multisite-network-administration/#uploaded-file-path

So I think that we should keep `\sites\$site_id\` for multisite.

@alimuzzaman We also could add new condition for Multisite on our wildcards functionality. What do you think?
<img width="942" alt="изображение" src="https://user-images.githubusercontent.com/5268508/78834063-a081d380-79f6-11ea-9762-08549dfe0037.png">

**Comment by alimuzzaman** [comment]
@planv 

> We also could add new condition for Multisite on our wildcards functionality. What do you think?

if you are talking about `Bootstrap::_wp_upload_dir` function, the whole point of that function is to get the root upload dir without sites/id postfix.


@ewsopp 
We have to keep in mind that to keep the GCS URL same we are removing `sites/id` from the server.
Previously the server had `sites/id` dir but GCS didn't have it.


Because we were removing `wp_upload_dir()['basedir']` from the file path before which includes `sites/id`. That's why I created `_wp_upload_dir` function which don't include `sites/id`.

**Comment by alimuzzaman** [comment]
Migration working as expected.
