### ISSUE TITLE
rename and relocate bucket folder setting

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#463]
This setting also affects how files are stored locally for _CDN_ and _Backup_ modes. It's not solely tied to the Google Cloud Storage. 

As such, I think a couple minor changes are needed...

- [x] rename setting label from _Bucket Folder_ to _Folder_

![image](https://user-images.githubusercontent.com/5578537/77501937-cff9e300-6e2f-11ea-9e34-55291564df13.png)

- [x] move the _Folder_ setting within the _File URL_ settings group, just below the _Preview_ setting.

![image](https://user-images.githubusercontent.com/5578537/77502022-02a3db80-6e30-11ea-9b46-8c05697c4d0d.png)

**Comment by planv** [comment]
Done

<img width="1022" alt="изображение" src="https://user-images.githubusercontent.com/5268508/77529720-d53f4800-6e98-11ea-9a19-a0a9721f115f.png">

**Comment by planv** [comment]
@alimuzzaman Check it please

**Comment by alimuzzaman** [comment]
Looks fine.
