### ISSUE TITLE
Initialize settings object in bootstrap construct

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#465]

**Comment by planv** [comment]
@alimuzzaman 
I can't save option `Don't override` for `Folder` on settings for multisite.

<img width="746" alt="изображение" src="https://user-images.githubusercontent.com/5268508/77668908-b5894c00-6f8c-11ea-8dcb-cf4b9e4e768f.png">

**Comment by planv** [comment]
Each time when I reload page I see this error 
<img width="912" alt="изображение" src="https://user-images.githubusercontent.com/5268508/77673597-0b60f280-6f93-11ea-9fc0-f151c6b30c2d.png">

In 1-2 sec it hides

**Comment by alimuzzaman** [comment]
This is expected. We are using JS to hide it.
So if there is any JS error, it will be displayed.

**Comment by planv** [comment]
Checked, works for me. Thanks
