### ISSUE TITLE
Accessing setup wizard when the Service Account JSON is present

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#466]
Currently, there is no instruction on how a user can access the setup wizard after they had set the **Service Account JSON**.

We need to inform the user that the setup wizard will appear if they remove the **Service Account JSON**.

**Comment by ewsopp** [comment]
Should we just update the `Service Account JSON` field description? 

> Private key in JSON format for the service account WP-Stateless will use to connect to your Google Cloud project and bucket.

to

> Private key in JSON format for the service account WP-Stateless will use to connect to your Google Cloud project and bucket. Empty this field to access the Stateless Setup Assistant.

![image](https://user-images.githubusercontent.com/5578537/91873337-e316a780-ec46-11ea-8014-35422a2af97e.png)

**Comment by antonkorotkov** [comment]
> Should we just update the `Service Account JSON` field description?
> 
> > Private key in JSON format for the service account WP-Stateless will use to connect to your Google Cloud project and bucket.
> 
> to
> 
> > Private key in JSON format for the service account WP-Stateless will use to connect to your Google Cloud project and bucket. Empty this field to access the Stateless Setup Assistant.
> 
> ![image](https://user-images.githubusercontent.com/5578537/91873337-e316a780-ec46-11ea-8014-35422a2af97e.png)

I would do like this for now. We can do something more advanced later.
