### ISSUE TITLE
Custom Domain Support?

### ISSUE THREAD

**Issue by AJB99** [udx/wp-stateless#47]
Hi there,

Great plugin, thanks for this.

Is there a way that I can force WP-Stateless to use a custom domain?

For example, I've got the following bucket `cdn.mysite.com` and I'd like have WP-Stateless create URLs for any uploaded media as `https://cdn.mysite.com/media/file-name-here.jpg`.

Thanks in advance for any help!

**Comment by andypotanin** [comment]
@AJB99 Not yet. If you don't mind, please add this idea to http://feedback.usabilitydynamics.com/forums/353541-wp-stateless that way we'll be able to add it to the queue. Thanks.
