### ISSUE TITLE
recreate attachment metabox panel using metabox.io

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#470]
Recreate the metabox on the attachment detail page using metabox.io

Name the metabox "Stateless" and using the tabs extension to group settings.

![IMG_20200407_083229](https://user-images.githubusercontent.com/5578537/78671554-72dd4300-78ad-11ea-908b-6fddd0ea67c5.jpg)

![screenshot-7](https://user-images.githubusercontent.com/5578537/78671499-5f31dc80-78ad-11ea-886e-9ae1e2c4f7fd.png)

**Comment by planv** [comment]
@ewsopp 
Metabox was recreated using metabox.io.
Added 2 tabs - `Thumbnails` and `Meta`.
Also I replaced metabox from left side to center. Below `Description`. It make sense?

![image](https://user-images.githubusercontent.com/5268508/80143728-ee313b00-85b5-11ea-9c38-f21874856ee2.png)

![image](https://user-images.githubusercontent.com/5268508/80144118-9941f480-85b6-11ea-9e91-c20fcb76f87f.png)

![image](https://user-images.githubusercontent.com/5268508/80144758-bfb45f80-85b7-11ea-896b-c5e75a34fc78.png)

**Comment by ewsopp** [comment]
Looking great so far.

# Updates

![image](https://user-images.githubusercontent.com/5578537/80153430-7c43fc00-858b-11ea-8660-be0d73380d1a.png)

1 - remove colons in the labels.
2 - replace the open link icon with https://developer.wordpress.org/resource/dashicons/#external
3 - increase spacing between the field and icons a bit.

![image](https://user-images.githubusercontent.com/5578537/80153847-55d29080-858c-11ea-98d6-b97ab7ec7164.png)

1 - remove colons in the labels.
2 - put value into an read-only text field (similar to the bucket field below it).
3 - add [external dashicon icon](https://developer.wordpress.org/resource/dashicons/#external) that links to the bucket in the GCP Console (`https://console.cloud.google.com/storage/browser/BUCKET_NAME_HERE`).

# Questions

How are you detecting what thumbnail files are available?

How are you detecting what thumbnail sizes are registered? 

If a thumbnail file does not exist for a registered thumbnail size, do we show an empty field?

Are you able to determine what registered a particular thumbnail size (core, plugin, or theme)?

**Comment by planv** [comment]
Done.

![image](https://user-images.githubusercontent.com/5268508/80201793-52431600-862d-11ea-9866-24735a89298f.png)

![image](https://user-images.githubusercontent.com/5268508/80201828-6555e600-862d-11ea-8625-6cf737c5d9e4.png)

> How are you detecting what thumbnail files are available?

I added information about sizes to `sm_cloud` meta. Related issue #268. 


> How are you detecting what thumbnail sizes are registered?

I can select all sizes which registered on WP. It is standard sizes: `thumbnail`, `medium`, `medium_large`, `large`. And registered on themes or plugins, for example: `twentyseventeen-featured-image`, `twentyseventeen-thumbnail-avatar`.


> If a thumbnail file does not exist for a registered thumbnail size, do we show an empty field?

No, right now I show only thumbnail sizes which was synced. 
For example, we couldn't have thumbnail size `large` for small image. Only small sizes.
![image](https://user-images.githubusercontent.com/5268508/80203130-5708c980-862f-11ea-8edd-771b95b2f677.png)

> Are you able to determine what registered a particular thumbnail size (core, plugin, or theme)?

I only can separate core sizes (`thumbnail`, `medium`, `medium_large`, `large`) and plugin/theme sizes.

**Comment by alimuzzaman** [comment]
@planv We will need a sync all button like before.

**Comment by ewsopp** [comment]
Good catch Alim!

Lets try this...

![image](https://user-images.githubusercontent.com/5578537/80610935-f6e79e00-8a07-11ea-9ecd-301e46f2b1ac.png)

1. [Button Group](https://docs.metabox.io/fields/button-group/) with `Regenerate` setting label and `Regenerate & Sync` button label.
2. Use a [Heading](https://docs.metabox.io/fields/heading/) above the thumbnails with the title `Files`.

**Comment by planv** [comment]
Done.
I added simple button instead Button Group. 

![image](https://user-images.githubusercontent.com/5268508/80641855-2cbf6d80-8a6e-11ea-8bab-76d9f7b6d821.png)

Also I added sync for selected size.

**Comment by ewsopp** [comment]
This looks great.
