### ISSUE TITLE
add metabox into attachment details modal

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#471]
At some point, WordPress Core added this new view for attachment objects. We should ensure our stateless metabox is added into this view as well. 

![image](https://user-images.githubusercontent.com/5578537/78673692-7faf6600-78b0-11ea-9526-64be49c8b808.png)

**Comment by planv** [comment]
@ewsopp 
I added new metabox. 
But on modal view we can't use tabs structure, metabox.io tabs does not support it. Should I add fields from tab `Meta` to this metabox too? 

![image](https://user-images.githubusercontent.com/5268508/80254288-95c86f00-8683-11ea-9880-a25adf5ec449.png)

**Comment by ewsopp** [comment]
Are we able to add a button here that links to the Stateless metabox on the attachment detail page?

**Comment by planv** [comment]
Sure. It can be button or link.

![image](https://user-images.githubusercontent.com/5268508/80524833-f06e0d80-8998-11ea-988f-d15cf68e20bd.png)

![image](https://user-images.githubusercontent.com/5268508/80524611-8fded080-8998-11ea-94bd-67dbb321bf71.png)

**Comment by ewsopp** [comment]
Lets just go with the text link. Looks nice and fits the style of WordPress core.

Good work.

**Comment by planv** [comment]
Done.
