### ISSUE TITLE
LiteSpeed Cache issue in multi-site

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#472]
Activating LiteSpeed Cache results in a fatal error. WordPress gets unusable.

**Comment by planv** [comment]
Fixed. LiteSpeed Cache activated on multisite. Ckecked compatibility with WP-Stateless version 2.4 - it is ok.

<img width="664" alt="изображение" src="https://user-images.githubusercontent.com/5268508/78720424-5d5c2d80-792e-11ea-96c0-c8c1af573f3c.png">

<img width="1385" alt="изображение" src="https://user-images.githubusercontent.com/5268508/78720404-53d2c580-792e-11ea-98a3-247abc84a238.png">
