### ISSUE TITLE
Metabox isn't showing 

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#473]
Metabox isn't showing properly when stateless is disabled or image isn't synced.

![image](https://user-images.githubusercontent.com/6744156/78677543-af3e8c80-7909-11ea-8e4e-16973cd08698.png)

**Comment by planv** [comment]
@ewsopp 
Which data we should show on metabox when image isn't synced yet?
Link `Regenerate and Sync with GCS`  only?

**Comment by ewsopp** [comment]
Lets get further along with https://github.com/wpCloud/wp-stateless/issues/470 and then handle this.

**Comment by planv** [comment]
@ewsopp Seems we are finished with #470. 

I added button `Regenerate and Sync with GCS` to metabox if image is not synced yet. 

![image](https://user-images.githubusercontent.com/5268508/80687914-b190a280-8ad3-11ea-829b-293a3aad5651.png)

**Comment by ewsopp** [comment]
Looks good.
