### ISSUE TITLE
Move sm_cloud meta data to it's own table

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#475]
sm_cloud meta has lots of data. And for media-heavy sites, it can be a problem.  

Sometimes we only need a single field but we are pulling all the data.

If we make custom table we would be able to do a custom query on `sm_cloud`.

For more info and possible columns for table see #383.

**Comment by antonkorotkov** [comment]
I think we can skip this for now for 3.0.0

**Comment by methnen** [comment]
Just wanted to add my vote to this one. We ran into this exact problem, storing all of this in the post_meta table gets unwieldy fast for any larger site.

**Comment by ewsopp** [comment]
@methnen we're working on this now. Thank you for your interest!

**Comment by planv** [comment]
It was implemented and released with version `4.0`.
Closing the ticket.
