### ISSUE TITLE
Google Suites for NonProfits/Google Drive

### ISSUE THREAD

**Issue by dvhirst** [udx/wp-stateless#479]
Hello, this plugin is set to work with Google Cloud Storage -- does it also work with Google Suites / Drive?  This is another form of cloud storage from Google, and it would be very helpful if I could use Google Drive cloud storage as the offload point for my WordPress media library.  Thanks for your response.

**Comment by alimuzzaman** [comment]
Sorry, it's not possible.

**Comment by dvhirst** [comment]
Not possible, or just not set to work that way now?

**Comment by alimuzzaman** [comment]
> Not possible, or just not set to work that way now?

not set to work that way now.

**Comment by dvhirst** [comment]
What would it take to make the necessary changes to support GSuites/Drive?  Seriously, I'd like to know what it would take to make this happen.  Thanks.

**Comment by alimuzzaman** [comment]
@dvhirst it will require a lot of work. Though we use a separate adapter to upload to GCS (Google Cloud Storage), some codes are still here and there.

We don't have any plans to do it now. Currently, we are working on making the current GCS experience better.

If you are a developer you can send us a pull request.

**Comment by dvhirst** [comment]
OK, thanks for letting me know.  I am not a developer, more a system admin, not eager to take on additional resources/storage from Google when the organization already has plenty available.  If the situation changes, I'm eager to hear it.

**Comment by ewsopp** [comment]
We have no future plans on supporting Google Drive. WP-Stateless is only focused on Google Cloud Storage at this time.
