### ISSUE TITLE
No File URL Replacement even from plugin enable

### ISSUE THREAD

**Issue by harshmanvar** [udx/wp-stateless#480]
``
![Selection_043](https://user-images.githubusercontent.com/50694399/80475987-622d6380-8967-11ea-912d-556a0655f658.png)

I have configured plugin in wordpress with CDN and tried File URL Replacement enable but it's still not replacing URL however older url still loading from `/wp-contet`  locally.

**Comment by planv** [comment]
Hello @harshmanvar 

Did you sync old images with GCS?

Is issue still relevant after update to version 3.0.4?

**Comment by harshmanvar** [comment]
it's working now
