### ISSUE TITLE
rename current "Stateless" mode to "Ephemeral"

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#481]
We are adding a new "Stateless" mode that will not use local storage at all, even temporarily as the current stateless mode does. I want to use the "Stateless" name for that new mode.

This newly named "Ephemeral" mode should remain the default mode set by the Stateless Setup Assistant (current functionality). 

- [x] rename `Stateless` mode to `Ephemeral`.
- [x] update this mode's description from

> Store and serve media files with Google Cloud Storage only. Media files are not stored locally.

to 

> Store and serve media files with Google Cloud Storage only. Media files are not stored locally, but local storage is used temporarily for processing and is required for certain compatibles. 

![image](https://user-images.githubusercontent.com/5578537/80768975-dc9de500-8b19-11ea-8e61-60d0f59a4491.png)

**Comment by planv** [comment]
Done. 
Also changed all related usage `stateless` mode in code, so in the future we won't have misunderstanding with mode `stateless` and `ephemeral`.

![image](https://user-images.githubusercontent.com/5268508/80804624-62736c00-8bbe-11ea-85de-6050a384827f.png)

**Comment by alimuzzaman** [comment]
@planv did you wrote a migration script for the renaming of the mode?

**Comment by planv** [comment]
@alimuzzaman Yes

**Comment by alimuzzaman** [comment]
@ewsopp can we add `Previously known as Stateless` or something similar in front of **ephemeral**?

Users may get confused.
