### ISSUE TITLE
add new stateless mode and test compatibilites

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#482]
- [x] Add the new "Stateless" mode that does not use local storage at all.
- [x] Determine which compatibilities work and which compatibilities do NOT work with this new mode.

**Comment by planv** [comment]
@ewsopp With new "Stateless" mode I can't add files to `Bucket` root. It needs to have folder in `Bucket`.

So new field `Folder` shouldn't be empty for "Stateless" mode
![image](https://user-images.githubusercontent.com/5268508/81679011-9ec68800-945a-11ea-89ef-8aa5fb354bbc.png)

**Comment by alimuzzaman** [comment]
![image](https://user-images.githubusercontent.com/6744156/81684059-751c5980-9478-11ea-9e7d-0ae453aa1476.png)

**Comment by planv** [comment]
Yes, compatibility with Imagify not working on `Stateless` mode. 
Imagify add mediafiles to local server

**Comment by planv** [comment]
# Review compatibility with "Stateless" mode

- [x] Advanced Custom Fields Image Crop Addon   - not working 
- [x] BuddyBoss   - not working
- [x] BuddyPress   - not working
- [x] Divi   - working, compatibility only for filename and cache busting
- [x] Dynamic Image Support   - working
- [x] Easy Digital Downloads   - not working
- [x] Elementor Page Builder   - working
- [x] EWWW Image Optimizer   - not working, problem with thumbnails sizes
- [x] Gravity Forms   - working
- [x] Imagify Image Optimizer   - not working
- [x] LearnDash LMS  - working, compatibility only for cache busting
- [x] LiteSpeed Cache   - not working
- [x] Polylang Pro   - working
- [x] ShortPixel Image Optimizer   - not working
- [x] Simple Local Avatars   - not working, uses local path
- [x] SiteOrigin CSS   - working
- [x] SiteOrigin Widget Bundle   - working
- [x] VidoRev   - working
- [x] WooCommerce Extra Product Options   - working
- [x] WP Retina 2x Pro - now working
- [x] WP Smush   - working
- [x] WPBakery Page Builder   - notworking
- [x] WPForms   - working

**Comment by ewsopp** [comment]
> @ewsopp With new "Stateless" mode I can't add files to `Bucket` root. It needs to have folder in `Bucket`.

Should we just default to the standard Wordpress organization scheme?

**Comment by planv** [comment]
> Should we just default to the standard Wordpress organization scheme?

Yes, we can use our predefined values for Single site and for Multisite by default.

**Comment by planv** [comment]
@ewsopp I added predefined value for field `Folder` on `Stateless mode`.
Also I added notice, maybe need to change text on it? 
<img width="1499" alt="изображение" src="https://user-images.githubusercontent.com/5268508/82048267-0b40c180-96bd-11ea-83f7-e37d5febdfc1.png">

**Comment by planv** [comment]
@ewsopp 

> Determine which compatibilities work and which compatibilities do NOT work with this new mode.

I have checked compatibilities with new mode. Most of them are working. 
List of compatibilities with comments - https://github.com/wpCloud/wp-stateless/issues/482#issuecomment-627301779

**Comment by planv** [comment]
@ewsopp 

Should we disable and hide from list compatibilities which not working on `Stateless` mode?

**Comment by ewsopp** [comment]
I don't think we should hide it. Lets disable it, similar to how we treat compatibilities that are disabled when the related plugin is not active.

![image](https://user-images.githubusercontent.com/5578537/82334112-86ec8800-99b5-11ea-973e-992cf763a4ec.png)

We probably should also add the following message:

> This compatibility does not support _Stateless_ mode.

# Mockup

![image](https://user-images.githubusercontent.com/5578537/82334319-cd41e700-99b5-11ea-9f55-7c78ca514936.png)

**Comment by planv** [comment]
Done.

![image](https://user-images.githubusercontent.com/5268508/82382429-96f77c80-9a34-11ea-8e1e-2dc1af3cb6e4.png)

**Comment by alimuzzaman** [comment]
Working fine.
