### ISSUE TITLE
PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /lib/Google/src/Google/Service/Resource.php on line 298

### ISSUE THREAD

**Issue by execash** [udx/wp-stateless#483]
Hi
Im getting this error while i import with wp all import. Whenever i upload images, import speed is so slow then i logged it and found this.

PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/html/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Whenever i dont upload images while importing, import speed is just fine as regular.

I use Php 7.4.4 on OpenLiteSpeed web server on gcp.

**Comment by execash** [comment]
I use Php 7.4.4 on openlitespeed web server on gcp.

**Comment by planv** [comment]
Hello execash 

It was fixed with issue #444 . The fix will be included in the next release.

Thanks.
