### ISSUE TITLE
Image files are not deleted from server in Stateless mode

### ISSUE THREAD

**Issue by YannickMol** [udx/wp-stateless#484]
Hi Team,

I have been using your plugin in Stateless mode. When uploading an image, Wordpress scales the image and generates all image sizes correctly. These are all correctly uploaded to Google Cloud. 
However, the full size images remain on my server, how can this be fixed?

Regards,
Yannick

**Comment by antonkorotkov** [comment]
This is fixed in 3.1.0. We are going to release it at the nearest time.
