### ISSUE TITLE
elementor compatibility

### ISSUE THREAD

**Issue by execash** [udx/wp-stateless#485]
Hi guys

Whenever I installed wp-stateless first time, before activating & saving the setting of the stateless mode, i just ignored css mimetype. However i cant reach them at server or cloud storage. They dont exist. And now im unable to edit pages. However if i upload the css files manually over ftp, it gets deleted by plugin. Even with the manual upload, im not able to use edit function of elementor just coz its unable to locate css guess. Then i disabled the compability of elementor but somehow whenever i reload the page, plugin setting keeps lookin for css's in the bucket too. 

Is there a fix available that i can my elementor work correctly?

**Comment by antonkorotkov** [comment]
Hey @execash 

if this is still relevant, can you try upgrading to 3.0.4 and run sync of non-library files? Be sure to check all your remote folders settings are correct once you upgraded.

**Comment by planv** [comment]
Fixed in version 3.0.4. Closing the ticket.
