### ISSUE TITLE
compatibility for Google App Engine

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#486]
With the recent changes to the _Stateless_ mode (https://github.com/wpCloud/wp-stateless/issues/482), we can now add proper support for Google App Engine. 

- [x] develop the logic required for WP-Stateless and WordPress to work correctly on Google App Engine. 
- [x] add control to Compatibility tab to enable this logic.
  - title: `Google App Engine`
  - description: `Ensures compatibility between WordPress media and Google App Engine in Stateless mode.`
- [x] add support for wp-config constant. `WP_STATELESS_COMPATIBILITY_GAE`
- [x] add support for enabling/disabling via the wp-stateless network settings panel.
- [x] setup assistant: detect if current WordPress site is hosted on App Engine, if so - automatically enable this compatibility and the new _Stateless_ mode.
- [x] add App Engine detection to our standard compatibility checks and prompt the user to enable this compatibility (as we do with other compatibilities).
- [x] display notice when user tries to enable compatibility when mode is set to anything but "Stateless".
  - title: `WP-Stateless: Current Mode is not compatible with Google App Engine.`
  - description: `Google App Engine compatibility requires WP-Stateless in Stateless mode.`

**Comment by joeyorlando** [comment]
Props to this. Your plugin is way more robust/feature-rich compared to the Google plugin.

Any estimated date of release for v3? Eagerly awaiting :)

**Comment by ewsopp** [comment]
We don't have an estimate at this time.

We're looking for those interested in helping us with testing release candidates. If you're interested, please shoot me an email and I'll reach out when we're ready to test this feature. My email is `eric@udx.io`

**Comment by alimuzzaman** [comment]
Working fine.
