### ISSUE TITLE
litespeed cache php fatal error

### ISSUE THREAD

**Issue by execash** [udx/wp-stateless#487]
[08-May-2020 05:59:34 UTC] PHP Fatal error:  Uncaught Error: Class 'LiteSpeed_Cache' not found in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/compatibility/lite-speed-cache.php:84
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(287): wpCloud\StatelessMedia\LSCacheWP->sync_image()
#1 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#2 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action()
#3 /var/www/html/wp-content/plugins/litespeed-cache/src/img-optm.cls.php(896): do_action()
#4 /var/www/html/wp-content/plugins/litespeed-cache/src/img-optm.cls.php(781): LiteSpeed\Img_Optm->pull()
#5 /var/www/html/wp-includes/class-wp-hook.php(287): LiteSpeed\Img_Optm::cron_pull()
#6 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#7 /var/www/html/wp-includes/plugin.php(544): WP_Hook->do_action()
#8 /var/www/html/wp-cron.php(138): do_action_ref_array()
#9 {main}
  thrown in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/compatibility/lite-speed-cache.php on line 84
[08-May-2020 06:01:36 UTC] PHP Fatal error:  Uncaught Error: Class 'LiteSpeed_Cache' not found in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/compatibility/lite-speed-cache.php:84
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(287): wpCloud\StatelessMedia\LSCacheWP->sync_image()
#1 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#2 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action()
#3 /var/www/html/wp-content/plugins/litespeed-cache/src/img-optm.cls.php(896): do_action()
#4 /var/www/html/wp-content/plugins/litespeed-cache/src/img-optm.cls.php(781): LiteSpeed\Img_Optm->pull()
#5 /var/www/html/wp-includes/class-wp-hook.php(287): LiteSpeed\Img_Optm::cron_pull()
#6 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#7 /var/www/html/wp-includes/plugin.php(544): WP_Hook->do_action()
#8 /var/www/html/wp-cron.php(138): do_action_ref_array()
#9 {main}
  thrown in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/compatibility/lite-speed-cache.php on line 84

**Comment by planv** [comment]
Related issue #491

**Comment by planv** [comment]
Fixed on issue #491
