### ISSUE TITLE
incompatibility with Litespeed ( again ) 

### ISSUE THREAD

**Issue by razantes555** [udx/wp-stateless#491]
I just spoke with Litespeed support and they helped me allot to figure out many things. It's seems wp-stateless have some issues with last version of the litespeed cache.
``( ! ) Fatal error: Uncaught Error: Class 'LiteSpeed_Cache' not found in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/compatibility/lite-speed-cache.php on line 84
( ! ) Error: Class 'LiteSpeed_Cache' not found in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/compatibility/lite-speed-cache.php on line 84
Call Stack
#	Time	Memory	Function	Location
1	0.0001	370784	{main}( )	.../admin.php:0
2	0.0001	371264	require_once( '/var/www/html/wp-load.php' )	.../admin.php:34
3	0.0001	371952	require_once( '/var/www/html/wp-config.php' )	.../wp-load.php:37
4	0.0001	373552	require_once( '/var/www/html/wp-settings.php' )	.../wp-config.php:35
5	0.1139	3757760	do_action( )	.../wp-settings.php:540
6	0.1139	3758136	WP_Hook->do_action( )	.../plugin.php:478
7	0.1139	3758136	WP_Hook->apply_filters( )	.../class-wp-hook.php:311
8	0.1540	5150432	LiteSpeed\Core->after_user_init( )	.../class-wp-hook.php:287
9	0.1561	5205336	LiteSpeed\Core->proceed_action( )	.../core.cls.php:221
10	0.1561	5205336	LiteSpeed\Router::handler( )	.../core.cls.php:273
11	0.1581	5502504	LiteSpeed\Img_Optm::handler( )	.../router.cls.php:701
12	0.1587	5553192	LiteSpeed\Img_Optm->pull( )	.../img-optm.cls.php:1847
13	0.2213	6229568	do_action( )	.../img-optm.cls.php:896
14	0.2213	6229944	WP_Hook->do_action( )	.../plugin.php:478
15	0.2213	6229944	WP_Hook->apply_filters( )	.../class-wp-hook.php:311
16	0.2214	6231072	wpCloud\StatelessMedia\LSCacheWP->sync_image( )	.../class-wp-hook.php:287
There has been a critical error on your website. Please check your site admin email inbox for `instructions.`

instructions from Litespeed support ( I didn't tested yet - but, I`ll do shortly )
`$rm_ori_bkup = \LiteSpeed_Cache::config( \LiteSpeed_Cache_Config::OPT_MEDIA_RM_ORI_BKUP ) ;
is replaced with
$rm_ori_bkup = apply_filter('litespeed_conf', 'img_optm-rm_bkup' );
And for the rest of their code, the API is here: https://docs.litespeedtech.com/lscache/lscwp/api/
docs.litespeedtech.com
API | LSCache for WordPress | LiteSpeed Documentation
LiteSpeed Cache for WordPress API hook reference.`

**Comment by planv** [comment]
Fixed

**Comment by razantes555** [comment]
I don't know if worked before ... but somehow seems imagify & shortpixels also ain't working & playing nicely with wp-stateless plugin, in short similar errors as with the litespeed setup the plugins don't have access to save thumbnail & optimized imaged back to where they are supposed to put them ( in stateless mode )

**Comment by alimuzzaman** [comment]
Working fine now.
