### ISSUE TITLE
File URL Replacement does not worked

### ISSUE THREAD

**Issue by dodiiriyanto** [udx/wp-stateless#492]
Hi,

I've updated WP-Stateless 2.3.2 in WP 5.4.1. But for some reason File URL Replacement seems no longer worked. I have excluded PDF as supported file types, but the GCS still to add generated number before file name. 

I have even disabled File URL Replacement, but generated code still appear before file name.

Could you please advice?

Thanks,
Dd

**Comment by planv** [comment]
Hello @dodiiriyanto 

Did you try disable `Cache-Busting` ?

![image](https://user-images.githubusercontent.com/5268508/85038485-4ab46f00-b18f-11ea-93c9-d1b1960f0760.png)

**Comment by planv** [comment]
Hello @dodiiriyanto 

Is issue still relevant?

**Comment by planv** [comment]
Closing the ticket.

@dodiiriyanto Please re-open the ticket if you still have this issue.
