### ISSUE TITLE
wp_stateless_file_name filter 

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#493]
The `wp_stateless_file_name`  filter has been changed by changes made for  #149.

Previously it was used to:

1. Get gs name from the local file path (relative or absolute).
2. Get a local file path (relative to upload dir) from the GCS URL.

Now due to changes made by #149:

1. We can get a gs name from the local file path (relative or absolute).

But we can't convert a GCS URL to local file path and can't identify the attachment.

For example `attachment_url_to_postid` tries to convert GCS URL to file path relative to upload dir.
Now it will fail in some cases.

I would like the conversion process to work both ways.

We can remove the year, month wildcard and remove base_dir from file path then prefix with bucket folder value. Just like it used to work before.

**Comment by planv** [comment]
> If we remove the year, month wildcard and remove base_dir from file path then prefix with bucket folder value. Just like it used to work before.

Also, in this case we will return to using WP core setting `Organize my uploads into month- and year-based folders` on GCS path.

**Comment by planv** [comment]
@alimuzzaman I fixed it for `attachment_url_to_postid`. Please check my last commit.

> I would like the conversion process to work both ways.

I added new function `parse_root_dir_wildcards`, now we can retrieve `month` and `year` from path and use it on function `root_dir_wildcards` (I added third parameter for it).

**Comment by planv** [comment]
Also we need to fix function `the_content_filter`

**Comment by planv** [comment]
Function `the_content_filter` [fixed](https://github.com/wpCloud/wp-stateless/commit/87490b7289ae67c72ff128bee5b1abc902318a5d).

@alimuzzaman Problem which you describe is solved?

**Comment by alimuzzaman** [comment]
@ewsopp What do you think if we remove `%date_year%`  and `%date_month%`?


The current solution works but not as solid as before.

@planv have solved some problems it caused but can't be sure there won't be more problems.

**Comment by alimuzzaman** [comment]
@ewsopp already removed it.

Is this ok?
![image](https://user-images.githubusercontent.com/6744156/83412822-9bf8fa80-a43c-11ea-98ba-f4c19f550488.png)

**Comment by ewsopp** [comment]
Where are the month and year tags?

**Comment by alimuzzaman** [comment]
@ewsopp 
> Where are the month and year tags?

We will get Y/M like before using `organization` settings like we used to do before. 

Having Y/M tags create unnecessary problems. It breaks backward compatibility of `wp_stateless_file_name` filter.

This filter is responsible for converting the local URL to the GCS URL and vice versa.
With the new approach(Y/M tags) it mostly works but we can't make it 100% perfect like before. 


If you want we can keep the Y/M tags and solve problems when they appear.
To me, the hassle Y/M tags will create isn't worth it. I am not feeling comfortable with the changes.

@planv what do you think?


## Some idea:
We can make Y/M into one tag and show it as bellow. Underneath it will be just the `organization` setting. 
![image](https://user-images.githubusercontent.com/6744156/83689324-a79d1a80-a610-11ea-9e3a-5924faaf2338.png)

**Comment by ewsopp** [comment]
What if we replicate the logic for generating the current year and current month? Rather than using WordPress to generate these pieces for us, could we generate them ourselves to get it to work?

`%year%` and `%month%` could be separate tags and the webmaster can place them in the same format that WordPress does. ex: `/sites/%site_id%/%year%/%month%/`

**Comment by alimuzzaman** [comment]
@ewsopp yes, that's similar to what @planv had done.

But that can cause some unforseen problems in future. Though @planv had solved some of the problems.

~~If you want we can just revert back to Y/M and try to solve problems when they arrives.~~

**Comment by ewsopp** [comment]
> Now it will fail in some cases.

@alimuzzaman in [your original comment](https://github.com/wpCloud/wp-stateless/issues/493#issue-622346504) on this issue, you mention that this method _will fail in some cases_. Can you give us some specific examples?

**Comment by alimuzzaman** [comment]
I am talking in the context of @planv implementation.

> Get a local file path (relative to upload dir) from the GCS URL.

1. Can we get a local path with GCS URL without attachment ID? 

Now we can just remove `https://storage.googleapis.com/udx-ci-develop-alim/{{Bucket Folder}}` 

How do we get the local path from GCS URL if you have Y/M in the wildcard?

**Comment by alimuzzaman** [comment]
Ex. 
Users have Organization enabled, but don't have Y/M in Bucket `Folder` option. 
I don't see any way to get the local path in this case.

**Comment by planv** [comment]
> How do we get the local path from GCS URL if you have Y/M in the wildcard?

We can [retrieve](https://github.com/wpCloud/wp-stateless/issues/493#issuecomment-633565040) `year` and `month` from GCS URL.  

if we have URL `https://storage.googleapis.com/stateless-udx-ci-develop-vova/custom_folder/2020/06/4343-1-300x225.jpg`
We can retrieve 2020 and 06 from this URL and use it for local path `/2020/06/4343-1-300x225.jpg`

But in case if user has enabled `Organize my uploads into month- and year-based folders` - we always need have tags `%year%` and `%month%` on our Bucket Folder field.

And in this way we can use `year` and `month` when we generate GCS path from local path.

**Comment by alimuzzaman** [comment]
> We can retrieve year and month from GCS URL.

@planv if you don't have Y/M in Bucket Folder option?

> And in this way we can use year and month when we generate GCS path from local path.

I think you have done it already.

> But in case if user has enabled Organize my uploads into month- and year-based folders - we always need have tags %year% and %month% on our wildcards.

Not sure how we can enforce that.

**Comment by planv** [comment]
@alimuzzaman Field `Bucket Folder` must be consistent with option `Organize my uploads into month- and year-based folders`

**Comment by planv** [comment]
> I think you have done it already.

Yes, it is already done.

> Not sure how we can enforce that.

We can make these tags required if Organization is enabled. And add notice for clients. 
So if Organization is enabled - client can't remove these tags from Folder Bucket.

**Comment by ewsopp** [comment]
Can we disable the `Organize my uploads into month- and year-based folders` option entirely? Disable it and direct user to configure the setting within WP-Stateless settings area.

**Comment by planv** [comment]
> Can we disable the Organize my uploads into month- and year-based folders option entirely? Disable it and direct user to configure the setting within WP-Stateless settings area.

@ewsopp 

`Organize my uploads into month- and year-based folders` applies only for local path, and `Bucket Folder` applies for GCS path. It is not solving problem. The issue not in this option.

We must have this option available because it is Core functionality. 
In case if it is enabled we need to force using `%year%` and `%month%` tags and this will solve problem.
So we have 2 options - we are doing like this or we will remove these tags totally as Alim propose.

**Comment by alimuzzaman** [comment]
If you want to force then my idea of combining them into one is a good idea.
https://github.com/wpCloud/wp-stateless/issues/493#issuecomment-638464764

**Comment by ewsopp** [comment]
If we have a single `%date_year%/%date_month%` tag, we could easily map it to the core `Organize my uploads into month- and year-based folders` setting, correct?

**Comment by alimuzzaman** [comment]
Yes, it will be as postfix.

**Comment by ewsopp** [comment]
`%date_year%/%date_month%` would have to be added to the end?

**Comment by alimuzzaman** [comment]
Yes

**Comment by ewsopp** [comment]
To recap:

1. combine `%date_year%` and `%date_month%` into a single tag: `%date_year%/%date_month%`
2. map the `%date_year%/%date_month%` tag to the core `Organize my uploads into month- and year-based folders` setting.
3. force the `%date_year%/%date_month%` tag at the end of the custom folder path.

@alimuzzaman is this correct?

@planv @antonkorotkov what do you both think of this?

**Comment by alimuzzaman** [comment]
> force the %date_year%/%date_month% tag at the end of the custom folder path.

We don't need to force it. If the user has the **organization** enabled Y/M will be shown as postfix.

**Edit**:
It won't be added to the custom folder path, it will just look like it has been added.

**Comment by planv** [comment]
> If you want to force then my idea of combining them into one is a good idea.
#493 (comment)

No. We can use separated tags `%year%` and `%month%`. 
If Organization is enabled - these both tags should be in Bucket Folder. It can be at the end, or at the beginning, doesn't matter.

**Comment by planv** [comment]
> combine %date_year% and %date_month% into a single tag: %date_year%/%date_month%

Yes

> map the %date_year%/%date_month% tag to the core Organize my uploads into month- and year-based folders setting.

Yes. 

> force the %date_year%/%date_month% tag at the end of the custom folder path.

Yes. If user has enabled Organization and haven't tags `%year%` and `%month%` on Bucket Folder yet.

**Comment by planv** [comment]
We can add checkbox ` Organize my uploads into month- and year-based folders` to our settings page, it will repeat WP core functionality (applies for local path), and also add/remove `/%year%/%month%/` from field Bucket Folder.

1. Not checked
![image](https://user-images.githubusercontent.com/5268508/85023761-d6bd9b00-b17d-11ea-8005-f5b1891c9fa0.png)

2. Checked
![image](https://user-images.githubusercontent.com/5268508/85024138-5c414b00-b17e-11ea-870d-8acffaca49e8.png)

3. Checked with new folder 
![image](https://user-images.githubusercontent.com/5268508/85028495-cf998b80-b183-11ea-9c78-cf92e5f1b0a2.png)

**Comment by planv** [comment]
I added new select for field `Folder`. 
Also combined tags `%date_year%` and `%date_month%` to tag `%date_year/date_month%`.
This tag map to the WP core setting ` Organize my uploads into month- and year-based folders `

![image](https://user-images.githubusercontent.com/5268508/85566079-6066e000-b638-11ea-995b-38cf605cc43a.png)

![image](https://user-images.githubusercontent.com/5268508/85566109-665cc100-b638-11ea-9923-7dedc5617fe1.png)

**Comment by ewsopp** [comment]
Great work so far. Some suggestions for improvement...

- [x] remove the `x` remove icon from each tag, and simply allow the user to click the tag to remove it.
- [x] visualize the `/` as its own tag.

![image](https://user-images.githubusercontent.com/5578537/85661653-f7f22000-b684-11ea-8309-bf51dcc2cae2.png)

- [x] dashes should be accepted. 

![image](https://user-images.githubusercontent.com/5578537/85660372-8d8cb000-b683-11ea-955f-d75665b9ec29.png)

- [x] typing `/` should close out the typed text as it's own tag and add a following `/` tag.

Some questions about capability...

- Can we allow the user to click into the folder structure? It seems user is limited to adding onto the end of the constructed folder path. Forces the user to clear chunks of the path to make edits. 
- Can we do validation? For example, ensure there are no consecutive `/` tags (resulting in an empty folder name).

**Comment by planv** [comment]
> Can we allow the user to click into the folder structure? It seems user is limited to adding onto the end of the constructed folder path. Forces the user to clear chunks of the path to make edits.

No. 

> Can we do validation? For example, ensure there are no consecutive / tags (resulting in an empty folder name).

Sure. We have validation for this field on server side.

**Comment by ewsopp** [comment]
- [x] add a slash `/` to the open and close recipe for Single Site.

![image](https://user-images.githubusercontent.com/5578537/85800801-9b881280-b70f-11ea-824c-622463cf4289.png)

- [x] same with the Multisite recipe, and include slashes between each directory.

![image](https://user-images.githubusercontent.com/5578537/85800830-a93d9800-b70f-11ea-8380-09434feaa7fe.png)

- [x] styling - maybe we should extend the length of the fields to provide more visibility of the preview and maintain consistent styling. 

![image](https://user-images.githubusercontent.com/5578537/85801188-56181500-b710-11ea-8606-6fd4574558e7.png)

- [x] styling - adjust the height of the folder field to match other fields.

![image](https://user-images.githubusercontent.com/5578537/85801234-6d570280-b710-11ea-8d77-29824b6ac2f0.png)

- [x] in testing, I was not able to save an empty value. upon save and refresh, it would show previous setting. empty is a valid state of the field if the webmaster wants to dump everything in the bucket without any folder organization.

**Comment by planv** [comment]
Done

![image](https://user-images.githubusercontent.com/5268508/85859406-ce8cdd80-b7c5-11ea-94e4-8a000c89b679.png)

**Comment by alimuzzaman** [comment]
@planv @ewsopp 
We should remove repetitive 

![image](https://user-images.githubusercontent.com/6744156/90519113-705af600-e189-11ea-95f4-112882c2570e.png)

**Comment by planv** [comment]
@alimuzzaman 
You can remove tags by clicking on it. Or save form and `wrong` tags will be deleted automatically.

**Comment by alimuzzaman** [comment]
`%date_year/date_month%` placeholder is always returning the current Y/M.

**Comment by planv** [comment]
@alimuzzaman 

> %date_year/date_month% placeholder is always returning the current Y/M.

We retrieve `year` and `month` from received path.
https://github.com/wpCloud/wp-stateless/blob/latest/lib/classes/class-bootstrap.php#L875-L879

So if we have year and month in path - we will use it instead current year and month.

**Comment by ewsopp** [comment]
@planv @antonkorotkov could either of you review the recent updates here? Close out if satisfactory.
