### ISSUE TITLE
Move Stateless management UI to dedicated admin page under Media.

### ISSUE THREAD

**Issue by andypotanin** [udx/wp-stateless#50]

**Comment by ewsopp** [comment]
Settings Panel specification at https://docs.google.com/a/usabilitydynamics.com/document/d/1OXrUcdISv2Kcoa3QUlqyYntNGP3ot1LSkUttc90yL1I/edit?usp=sharing

- [x] Settings tab
  - [x] General group
    - [x] Mode setting
    - [x] File URL Replacement
    - [x] Dynamic Image Support
  - [x] Google Cloud Storage (GCS) group
    - [x] Bucket setting
    - [x] Bucket Folder setting
    - [x] Service Account JSON setting
    - [x] Cache-Control setting
    - [x] Delete GCS File
  - [x] File URL group
    - [x] Preview
    - ~~Domain setting~~
    - ~~HTTPS setting~~
    - [x] Organization setting
    - [x] Cache-Busting setting
  - ~~Thumbnails group~~
  - ~~Synchronization group~~
  - ~~Compression group~~
- ~~Support tab~~
- [x] Sync Tab

**Comment by alimuzzaman** [comment]
What about the **Stateless Sync** menu?

**Comment by alimuzzaman** [comment]
Todo: Also use a filter for meta to replace with GCS URL (**File URL Replacement**).

**Comment by ewsopp** [comment]
> What about the Stateless Sync menu?

- [x] Move the "Stateless Sync" page to a "Sync" tab within our new settings panel.

- [x] hide cache-control text field when the setting is disabled.

![image](https://user-images.githubusercontent.com/5578537/27929499-436e29d2-6261-11e7-9891-56b8bd12ca63.png)

- [x] preview file url field: extend field length and update field value with actual example file url.

![image](https://user-images.githubusercontent.com/5578537/27929628-aaacda62-6261-11e7-9184-b82ed6d202f5.png)

- [x] Remove HTTS setting for now. We will bring this back once we incorporate cloudfront.

**Comment by ewsopp** [comment]
- [x] remove Support tab.

![image](https://user-images.githubusercontent.com/5578537/28079381-2e125daa-6636-11e7-9289-f873f12db493.png)

- [x] remove the colons `:` from the setting titles, and remove the selected value from the `Mode` title.

![image](https://user-images.githubusercontent.com/5578537/28079918-1f6e7df4-6638-11e7-9617-0340947064ea.png)

- [x] remove the `Thumbnails`, `Synchronization` and `Compression` setting sections.

![image](https://user-images.githubusercontent.com/5578537/28079951-349bdaaa-6638-11e7-9eaf-00666d833379.png)

**Comment by ewsopp** [comment]
- [x] remove the old `Tools > Stateless Sync` menu item and page. https://sandbox-uds-io-develop-alim.c.rabbitci.com/wp-admin/tools.php?page=stateless-regenerate
 
![image](https://user-images.githubusercontent.com/5578537/28168201-55b8e6fe-67ac-11e7-9b68-9be8298847cc.png)

**Comment by ewsopp** [comment]
- [x] set page title: `WP-Stateless`
- [x] set page description: `Upload and serve your WordPress media files from Google Cloud Storage.`

![image](https://user-images.githubusercontent.com/5578537/28168371-eb9c30ae-67ac-11e7-86f2-6ae248f8c9a4.png)
