### ISSUE TITLE
add compatibility for Gravity Forms Signature Add-On

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#501]
- https://www.gravityforms.com/add-ons/signature/
- https://docs.gravityforms.com/category/signature-add-on/

Package this comaptibility as it's own compactibility that can be enabled/disbaled separate from the Gravity Forms compatibility.

**Comment by ewsopp** [comment]
@alimuzzaman this should have it's own compatibility control within the settings panel and constant.

- [x] constant: `WP_STATELESS_COMPATIBILITY_GF_SIG`
- [x] control title: `Gravity Forms Signature Add-On`
- [x] control description: `Enables support for signature images generated by the signature add-on for Gravity Forms.`

**Comment by alimuzzaman** [comment]
@ewsopp completed.
