### ISSUE TITLE
Broke when I switched to Multisite. 

### ISSUE THREAD

**Issue by floatbeta** [udx/wp-stateless#503]
Hi the plugin was working perfectly, but then I enabled Multisite and it no longer works.

I can't upload anything and none of the images or videos show up on the site anymore.

I Network activated it and it stopped working.
I disabled it and then enabled it on the main site, but it still doesn't work.

I am using nginx, php7.4.6-fpm and mysql 8.0.20, 
my server has libav and ffmpeg installed, along with ImageMagic and GD.

But it worked before that. I did add directives in my site.conf file on nginx but I am looking into what could be the cause.

Has anyone else experienced the same?

**Comment by floatbeta** [comment]
Debug Output

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /var/www/rocketstack/wp-content/plugins/wp-stateless/lib/Google/src/Google/Service/Resource.php on line 298
200

**Comment by planv** [comment]
Hello @floatbeta 

The fix will be included in the next release.
Fixed on issue [446](https://github.com/wpCloud/wp-stateless/issues/446).

**Comment by planv** [comment]
This has been fixed in 3.0
