### ISSUE TITLE
Store data in table other than wp_postmeta?

### ISSUE THREAD

**Issue by methnen** [udx/wp-stateless#510]
Curious about thoughts on this.

We're using this plugin on a site that's been around a long time and at various times had some pretty high content creation rates.

So we've got somewhere around 160,000+ and growing images in our media library.

Recently we had a small scale DDOS attack on the site and when that happened it brought some bottle necks to the surface (as these things often do).

One was that our wp_postmeta table had grown to a point that it was causing some long queries that allowed things to back up on the query end sometimes.

After doing a bit of investigation it became clear that the sm_cloud postmeta is now taking up the second largest amount of storage space in the wp_postmeta table with the next largest chunk being orders significantly less.

I'm wondering if anyone has contemplated moving this data to it's own table? Or making that an option somehow?

**Comment by planv** [comment]
Hello @methnen 

We already have such an issue - https://github.com/udx/wp-stateless/issues/475

Closing the current ticket.
