### ISSUE TITLE
Cache Issue

### ISSUE THREAD

**Issue by seanhudson** [udx/wp-stateless#514]
I'm getting the following errors with the plugin which breaks the entire site.

`Fatal error: Uncaught Error: Class 'Google\Auth\Cache\MemoryCacheItemPool' not found in /var/www/content.homesliceapp.com/public/wp-content/plugins/wp-stateless/lib/Google/src/Google/Client.php on line 1025`

`Error: Class 'Google\Auth\Cache\MemoryCacheItemPool' not found in /var/www/content.homesliceapp.com/public/wp-content/plugins/wp-stateless/lib/Google/src/Google/Client.php on line 1025`

Has anyone else had an issue like this?

**Comment by antonkorotkov** [comment]
If you are using git ignore then check if you are ignoring the `Cache` folders. If so, then make it so that it does not ignore the following path: `wp-content/plugins/wp-stateless-new/lib/Google/vendor/google/auth/src/Cache`

**Comment by planv** [comment]
Hello @seanhudson 

Is issue still relevant?

**Comment by planv** [comment]
Closing the ticket.

@seanhudson  Please re-open the ticket if you still have this issue.
