### ISSUE TITLE
BuddyBoss

### ISSUE THREAD

**Issue by welshlamb10** [udx/wp-stateless#516]
Hi,

Great plugin! Does this work with BuddyBoss Platform?

Many thanks

**Comment by planv** [comment]
Hello @AshleyBale 

Yes, WP-Stateless has a compatibility with Buddy Boss.
Please go to compatibility tab to enable Buddy Boss compatibility.

![изображение](https://user-images.githubusercontent.com/5268508/89419474-10e8f900-d73a-11ea-8e48-86592ecddf9f.png)

![изображение](https://user-images.githubusercontent.com/5268508/89419651-47267880-d73a-11ea-83c5-3ae3bde7bd62.png)

**Comment by welshlamb10** [comment]
Awesome!
