### ISSUE TITLE
Litespeed Cache compatibility error

### ISSUE THREAD

**Issue by AlexIacoban** [udx/wp-stateless#519]
Image optimization in Litespeed Cache does not work with WP Stateless. I get a fatal error when I "Pull images"

I have contacted Litespeed and their response was:
“Please contact WP stateless, the error is on their file, but I think it might be due to our v3 that changed some API, please attach this link (https://wordpress.org/support/topic/changes-to-api-and-cli/) to them as well.”

Fatal error: Uncaught Error: Class 'LiteSpeed_Cache' not found
in /home/luderior/public_html/wp-content/plugins/wp-stateless/lib/classes/compatibility/lite-speed-cache.php on line 84

Call stack:

wpCloud\S\LSCacheWP::sync_image()
wp-includes/class-wp-hook.php:287
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:311
WP_Hook::do_action()
wp-includes/plugin.php:478
do_action()
wp-content/plugins/litespeed-cache/src/img-optm.cls.php:926
LiteSpeed\Img_Optm::pull()
wp-content/plugins/litespeed-cache/src/img-optm.cls.php:1865
LiteSpeed\Img_Optm::handler()
wp-content/plugins/litespeed-cache/src/router.cls.php:707
LiteSpeed\Router::handler()
wp-content/plugins/litespeed-cache/src/core.cls.php:276
LiteSpeed\Core::proceed_action()
wp-content/plugins/litespeed-cache/src/core.cls.php:224
LiteSpeed\Core::after_user_init()
wp-includes/class-wp-hook.php:287
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:311
WP_Hook::do_action()
wp-includes/plugin.php:478
do_action()
wp-settings.php:540
require_once()
wp-config.php:89
require_once()
wp-load.php:37
require_once()
wp-admin/admin.php:34

**Comment by planv** [comment]
Hello @AlexIacoban  

The fix will be included in the next release.
Fixed on issue [491](https://github.com/wpCloud/wp-stateless/issues/491).

**Comment by planv** [comment]
This has been fixed in 3.0
