### ISSUE TITLE
Expose REST API for Jobs

### ISSUE THREAD

**Issue by andypotanin** [udx/wp-stateless#52]
We need to expose the ability to run a part of a job (batch) as well as see some basic detail about a job using the WordPress REST API.

For example:

`http://example.com/wp-json/wp-stateless/v1/jobs` would return a list of jobs that are available while `http://example.com/wp-json/wp-stateless/v1/job/2343243` would return detail about a job.  I've created the placeholder endpoint already, it looks like this:
![image](https://cloud.githubusercontent.com/assets/1255935/21639713/7402ad00-d23f-11e6-83d9-a10ab81a2da0.png)

Lastly, `http://example.com/wp-json/wp-stateless/v1/job/2343243/step/1` would trigger the first step of the job to run.  

This implementation will allow us to run jobs from our API servers so users who start jobs don't have to keep their browser open for several days. We will cover how to submit a job to our API shortly.

**Comment by alimuzzaman** [comment]
@andypotanin Please clarify

> Lastly, http://example.com/wp-json/wp-stateless/v1/job/2343243/step/1 would trigger the first step of the job to run.

 What do you mean by **first step**? first attachment?

**Comment by ewsopp** [comment]
Closing for now. We may return to this in the future.
