### ISSUE TITLE
Permission notice error after upgrading to 5.5.0

### ISSUE THREAD

**Issue by thecodeassassin** [udx/wp-stateless#522]
Hi, 

The following message popped up after upgrading to 5.5.0

Notice: register_rest_route was called incorrectly. The REST API route definition for wp-stateless/v1/status is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /srv/maxroll/site/wp-includes/functions.php on line 5225

**Comment by planv** [comment]
Hello @thecodeassassin 

The fix will be included in the next release.
