### ISSUE TITLE
rewrite sync

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#523]
Develop a synchronization process that does not require the user to keep the web browser open. 

The synchronization process should provide a progress indicator. If the user can expand the progress indicator to see the details of what is happening, that would be a plus.

When the synchronization process is done, email a notice to the WordPress user who triggered the synchronization.

A synchronization process should be able to be started from the setup assistant and/or from with the settings panel.

**Comment by antonkorotkov** [comment]
@ewsopp I don't think this should be a part of the 3.0.0 release. We are too late with it to add more huge features like this. This may delay the release by another month or so. Do we really want it in 3.0.0?

**Comment by antonkorotkov** [comment]
This is what we are going to use for the background processing https://github.com/deliciousbrains/wp-background-processing

**Comment by antonkorotkov** [comment]
I'm investigating where we are now and how we will refactor the current sync function. And here is a bug as for me: when I enable `Use Bucket Folder setting` the Method radio is being unchecked.

![image](https://user-images.githubusercontent.com/2276882/91849252-6eeafc80-ec64-11ea-8730-16830edf4c65.png)

@planv any thoughts?

**Comment by planv** [comment]
@antonkorotkov Yes, you are right. I'll fix it soon. Thanks

**Comment by antonkorotkov** [comment]
@ewsopp I created a new branch for it. https://github.com/wpCloud/wp-stateless/tree/develop-sync

Regarding the functionality - as I understand we need to keep existing UI, controls and methods of synchronization but make it possible to close the browser. Correct? 

We can remove `Bulk Size` option though.

**Comment by ewsopp** [comment]
> as I understand we need to keep existing UI, controls and methods of synchronization but make it possible to close the browser. Correct?

You can change anything. Make it great.

**Comment by antonkorotkov** [comment]
Since we are going to install a composer package that may be used by other plugins we need to add it to our own namespace to prevent conflicts. This library suggests this package for this: https://packagist.org/packages/coenjacobs/mozart

I'm going to test if it works.

**Comment by planv** [comment]
@antonkorotkov 

https://github.com/wpCloud/wp-stateless/issues/523#issuecomment-684804549
> I'm investigating where we are now and how we will refactor the current sync function. And here is a bug as for me: when I enable Use Bucket Folder setting the Method radio is being unchecked.

Fixed.

**Comment by antonkorotkov** [comment]
> The synchronization process should provide a progress indicator. If the user can expand the progress indicator to see the details of what is happening, that would be a plus.

I think we can show something like Processed *X* out of *Y* but showing a detailed log of what happened will be a problem, especially, for large amounts of media, because this information needs to be stored somewhere.

**Comment by antonkorotkov** [comment]
implemented
