### ISSUE TITLE
Compatibility error with litespeed cache

### ISSUE THREAD

**Issue by FlickTheManual** [udx/wp-stateless#527]
Hi there, I know it comes already, but it back :laughing: 

I would to gathered some new image with the `Pull Image` button:

![image](https://user-images.githubusercontent.com/2384206/91810902-bf039800-ec3f-11ea-8c67-dd6c5c0eaeeb.png)

then get *fatal error* :skull: 

I got some issue with the compatibility and litespeed cache: `Class 'LiteSpeed_Cache' not found in wp-stateless/lib/classes/compatibility/lite-speed-cache.php:84`

```log
Class 'LiteSpeed_Cache' not found in wp-content/plugins/wp-stateless/lib/classes/compatibility/lite-speed-cache.php:84
Stack trace:
#0 wp-includes/class-wp-hook.php(287): wpCloud\StatelessMedia\LSCacheWP->sync_image(Object(stdClass), 'w...')
#1 wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 wp-content/plugins/litespeed-cache/src/img-optm.cls.php(925): do_action('litespeed_img_p...', Object(stdClass), 'w...')
#4 wp-content/plugins/litespeed-cache/src/img-optm.cls.php(1864): LiteSpeed\Img_Optm->pull()
#5 wp-content/plugins/litespeed-cache/src/router.cls.php(711): LiteSpeed\Img_Optm::handler()
#6 wp-content/plugins/litespeed-cache/src/core.cls.php(270): LiteSpeed\Router::handler('LiteSpeed\\img_o...')
#7 wp-content/plugins/litespeed-cache/src/core.cls.php(219): L...
```

anybody have a luck with this?

anyway good work for this plugin :+1:

**Comment by FlickTheManual** [comment]
Update: If I remove the compatibility, it works

I got the same issue with compatibility on resync and optimized version with Litespeed cache.

With compatibility: ERROR :warning: :warning: :warning:
Without: no worry :smile:

**Comment by planv** [comment]
Hello @FlickTheManual 

The fix will be included in the next release.
Fixed on issue [491](https://github.com/wpCloud/wp-stateless/issues/491).

**Comment by FlickTheManual** [comment]
hi @planv ok, I wait @ it so  :smile: 
thanks for the support

**Comment by FlickTheManual** [comment]
hi @planv I've got another strange issue, so I make it here to throw this problem:

I use the litespeed cdn with quic.cloud, and use it for images optimization (compression + webp)
all my images are in wp-upload, but not in the storage (i use the `stateless` settings)

I don't know if this issue comes from wp-stateless or litespeed-cache, so i push this here ;)

thanks for the review

**Comment by FlickTheManual** [comment]
hi @planv , just testing the new version 
it seems to be worked, :+1: 
I monitor this version upload process and throw if I show new problems

nice job :clap: :clap: :clap:

try it for the webp replacement from lscache too, if you mind where this hang, up to me :)

**Comment by FlickTheManual** [comment]
hi @planv,

storytime! :rofl: 

how did it work the `Ephemeral` with ls-cache please?

I see that with their CDN (quic.cloud), the webp is finally return in the good folder, 
but theses images are saved in the `uploads` folder only, and not go to the Google Storage correctly.

none of theses optimized images nor their webp version got to the GS, and did hurt the website.

also I haven't got a lot of storage in order to saves theses medias, 
that's why I'd used the `stateless` mode before the update: to show my image directly in the storage, and no files in the uploads...

How can make a clean sync on the GS and remove the medias uploaded in the wp-contents/uploads folder, please?

thanks for support

**Comment by FlickTheManual** [comment]
hello @planv, new problem are coming

now we got the webp on storage (yepeee :rofl: ) but, because the but is coming too,

the webp doesn't follow the folder medias upload dirs, it make all @ the root storage,

for the update :D of this issues

**Comment by planv** [comment]
This is fixed in 3.1.0. We are going to release it at the nearest time.

**Comment by FlickTheManual** [comment]
:clap: like the new sync ui,
eager to test tomorrow :drooling_face:

**Comment by FlickTheManual** [comment]
hey there, 

Nice job everybody, the webp comes to the correct folder :tada:

---

can we have a little summary of the sync usage with the new UI pls?
I'm fear of use your sync tabs for the webp,
so I would love to know how to sync between the two:
- do not delete the existing images on the GS,
-  delete the media on the legacy 

what's the sync workflow please? and wat button I must click to start a manual sync?

![image](https://user-images.githubusercontent.com/2384206/97960801-89a83180-1dcb-11eb-86dc-b76458affcd2.png)

what the diff between `Media Library Image` and `Compatibility Files`?

sorry for all of this questions :blush:
