### ISSUE TITLE
update console iframe URL to production

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#529]
Currently, the plugin uses the `staging` URL for setup wizard. Before the release, we need to make sure the `iframe` is using the `production` URL of console.stateless.ci. As I can see we don't even host it yet.

**Comment by antonkorotkov** [comment]
I created a PR https://github.com/udx/console.stateless.ci/pull/81

@kavaribes I think you can help here. Can we make sure `console.stateless.ci` points to the `production` of `console-stateless-ci`?

**Comment by kavaribes** [comment]
`console.stateless.ci` has just internal CNAME.
![image](https://user-images.githubusercontent.com/17166792/91983508-77126d00-ed34-11ea-8064-67bd8b25be44.png)

Where it should follows? To `console.stateless.ci`?
@antonkorotkov

**Comment by kavaribes** [comment]
![image](https://user-images.githubusercontent.com/17166792/91986627-99f15100-ed35-11ea-8249-0379e48dcf22.png)

![image](https://user-images.githubusercontent.com/17166792/91986573-86de8100-ed35-11ea-8434-e925d89ca901.png)

**Comment by antonkorotkov** [comment]
> `console.stateless.ci` has just internal CNAME.
> ![image](https://user-images.githubusercontent.com/17166792/91983508-77126d00-ed34-11ea-8064-67bd8b25be44.png)
> 
> Where it should follows? To `console.stateless.ci`?
> @antonkorotkov

I don't know, we just need https://console.stateless.ci/ to show the `production` of https://github.com/udx/console.stateless.ci 

Looks like you already did that. I see a 404 error there which is correct for now.

**Comment by antonkorotkov** [comment]
I've merged `staging` to `production`. Looks like deployed successfully.  https://console.stateless.ci

![image](https://user-images.githubusercontent.com/2276882/91986993-1b48e380-ed36-11ea-9470-56703033e4c9.png)

Thanks @kavaribes

**Comment by antonkorotkov** [comment]
Now I get the following error when trying to login with Google:

> The JavaScript origin in the request, https://console.stateless.ci, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/541786531381-bgmdnk38gnoqhm9m0ncb7nu5m5t01hk5.apps.googleusercontent.com?project=541786531381 to update the authorized JavaScript origins.

It means the production domain is not added to the App. Going to do this.

**Comment by antonkorotkov** [comment]
We need to complete this info and submit the app for review https://console.developers.google.com/apis/credentials/consent/edit?authuser=1&project=usability-dynamics&duration=P1D

![image](https://user-images.githubusercontent.com/2276882/91997339-a9c36200-ed42-11ea-8810-622fdf550ba5.png)

**Comment by antonkorotkov** [comment]
@ewsopp in order to submit the app for approval we need to submit this form. Do you want me to do it or you want this under your control?

![image](https://user-images.githubusercontent.com/2276882/92002810-f1e58300-ed48-11ea-883d-5430f7aff01b.png)

**Comment by antonkorotkov** [comment]
@kavaribes I need your help again. I need my branch domain https://console-stateless-ci-develop-anton.rabbit.ci/ to work. I created a branch in https://github.com/udx/console.stateless.ci but not sure what else needs to be done. I see 502 error now.

**Comment by antonkorotkov** [comment]
@ewsopp I just realized that we can leave OAuth app as is for now. Since wizard is hosted separately we can change it later when it is approved. The approval can take several weeks.

Closing the issue.
