### ISSUE TITLE
Convert Stateless Sync to use "Stateless Jobs"

### ISSUE THREAD

**Issue by andypotanin** [udx/wp-stateless#53]
We need a better way of storing active "jobs" that have been started - e.g. synchronization. I believe we should create a custom post type (e.g. `wp_stateless_job`) that would be hidden from the UI but used internally for:

- [ ] Having a unique ID for a running job.
- [ ] Use post meta to record detail about the job - e.g. when it was started, if there have been any issues with a running job that require user action, etc.
- [ ] We could create additional jobs that the user should run. For example, while running Stateless Sync we find out that thumbnail sizes are missing for some objects, instead of regenerating thumbnails right away we could add the information about what needs to be done to another regeneration job that may be ran later.

So, whenever the Stateless Sync process is ran from this screen:
![image](https://cloud.githubusercontent.com/assets/1255935/21639475/38a8004e-d23e-11e6-8884-c49213a9c60b.png)
we should be creating our `wp_stateless_job` posts internally.  

This also means that that whoever started the job can clone their browser but the job progress/step will be stored in the database.

**Comment by andypotanin** [comment]
Once this implementation is done, the current UI (that uses AJAX to make ongoing requests) should still work as before. We will be implementing our remote job runner in https://github.com/wpCloud/wp-stateless/issues/54 issue.

**Comment by ewsopp** [comment]
Closing for now. We may return to this in the future.
