### ISSUE TITLE
setup wizard on localhost

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#530]
Since the site needs to be publicly accessible for the wizard to work - should we add anything to the wizard or to the plugin that will warn users about it? 

Currently, there is nothing that says that it will not work on `localhost`. Users will only notice that on the latest setup step and I'm not sure we show any error message about the fact that the wizard cannot reach the site.

@ewsopp

**Comment by antonkorotkov** [comment]
As for me, it should be done on the wizard side on the very first step. Once the setup wizard is open it should check the status by doing the request to this endpoint https://api.stateless.ci/docs/#/WP%20v1/post_v1_wp_status
Depending on the response we should show a message that the wizard is not available (if not site is not accessible) or show the first setup step.

**Comment by antonkorotkov** [comment]
Also, I don't think that we should allow users to access the console directly, at least right now.

**Comment by ewsopp** [comment]
If the situation arises, then we should display a message explaining why the console is not loading. We can point them to the manual setup instructions.

Something like...

> The automatic setup assistant requires your website to be on a publicly accessible network in order to properly function. For example, it will not work on _localhost_. If this is not possible, try following our [manual setup instructions](https://wp-stateless.github.io/docs/manual-setup/) to complete your setup.

What do you think?

**Comment by antonkorotkov** [comment]
> If the situation arises, then we should display a message explaining why the console is not loading. We can point them to the manual setup instructions.
> 
> Something like...
> 
> > The automatic setup assistant requires your website to be on a publicly accessible network in order to properly function. For example, it will not work on _localhost_. If this is not possible, try following our [manual setup instructions](https://wp-stateless.github.io/docs/manual-setup/) to complete your setup.
> 
> What do you think?

That makes sense. But I'm not sure about the appearance of that. I mean design. Anyways, I'll create an issue in udx/console.stateless.ci repository.

**Comment by antonkorotkov** [comment]
Created an issue in corresponding repo https://github.com/udx/console.stateless.ci/issues/82
