### ISSUE TITLE
root dir vs. wildcard issue

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#531]
I think I've found an issue while testing the upgrading process.

Upgrading from `2.3.2`.

The `Bucket Folder` (root_dir) option is set to nothing and the `Organize` option is `enabled`.

![image](https://user-images.githubusercontent.com/2276882/91979019-c73a0100-ed2d-11ea-854a-81672bf96aa7.png)

![image](https://user-images.githubusercontent.com/2276882/91979086-e2a50c00-ed2d-11ea-8796-fd84799e44b9.png)

After the upgrade to the `latest` the Folder option looks correct: 

![image](https://user-images.githubusercontent.com/2276882/91979321-43ccdf80-ed2e-11ea-91b5-e608c144f32e.png)

But in the database it is set to:

![image](https://user-images.githubusercontent.com/2276882/91979539-9ad2b480-ed2e-11ea-82bd-ab5578202edb.png)

And if I re-sync I get the following URL structure which is not what is desired: 

![image](https://user-images.githubusercontent.com/2276882/91979741-df5e5000-ed2e-11ea-9c75-837a45d6d7bf.png)

**Comment by antonkorotkov** [comment]
The same happens if `Bucket Folder` was set to `/`.

**Comment by antonkorotkov** [comment]
This is what is happening when `Bucket Folder` was set to `test`.
UI looks correct:

![image](https://user-images.githubusercontent.com/2276882/91982346-c6579e00-ed32-11ea-9fc7-6b8c9a53f5ef.png)

But database option looks weird:

![image](https://user-images.githubusercontent.com/2276882/91982433-e7b88a00-ed32-11ea-8a86-bd40ebaa6ee3.png)

Basically, the date organization folders are duplicating.

**Comment by planv** [comment]
Fixed. Issue was related to version comparing `2.4` and `2.4.0-RC.3`. We need to use numeric version in codebase. 
@alimuzzaman  FYI ^

**Comment by antonkorotkov** [comment]
Ok, thanks, I'm going to test it today again

**Comment by antonkorotkov** [comment]
Works for me now
