### ISSUE TITLE
network setting - folder override is not respected at site level

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#534]
In the below screenshots, the network settings has the `Folder` setting configured. This configuration is not respected at the individual network site level.

# Network Setting - Folder

The folder setting is configured to override the individual site setting.

![image](https://user-images.githubusercontent.com/5578537/92010006-4708a100-ed17-11ea-829c-589cef947b79.png)

# Site - Folder

The folder setting on an individual site is editable.

![image](https://user-images.githubusercontent.com/5578537/92010091-5e478e80-ed17-11ea-8895-e22867445611.png)

**Comment by antonkorotkov** [comment]
I'm going to test this.

**Comment by antonkorotkov** [comment]
It works. Also tested the actual process of uploading media on multisite. All works.

![image](https://user-images.githubusercontent.com/2276882/92216951-adb8c680-ee9f-11ea-9554-cd1b91e22f24.png)

![image](https://user-images.githubusercontent.com/2276882/92217394-52d39f00-eea0-11ea-903a-bdffc83b04d8.png)
