### ISSUE TITLE
Elementor CSS file not show after finish setup wp-stateless

### ISSUE THREAD

**Issue by msulaimanmisri** [udx/wp-stateless#536]
Hello there developers. Do you have any idea how to fix my website that broken after installing wp-stateless? This plugin is great. But the thing is I can't use it with Elementor (basic and Pro).

**Comment by antonkorotkov** [comment]
Have you enabled Elementor support in the Compatibility tab?

**Comment by msulaimanmisri** [comment]
Yeah, I've enable and disable it many times. But nothing happens 🤔

**Comment by antonkorotkov** [comment]
Can you provide the specific steps to reproduce your problem?

Plugins and WordPress versions, modes, and features that you use and everything that could help us. Thanks.

**Comment by antonkorotkov** [comment]
Hey @msulaimanmisri 

If this is still relevant - this might be fixed in the 3.0.4 version that we are going to release out today.

**Comment by planv** [comment]
Fixed in version 3.0.4. Closing the ticket.
