### ISSUE TITLE
Implement API Job handler via UD Product API.

### ISSUE THREAD

**Issue by andypotanin** [udx/wp-stateless#54]
Whenever a job is started an API request is made to the UD Product API. The Product API will then act as a browser would, running the job in batches by making requests back to the WordPress site. 

This means large jobs that span days can be ran in the background. This API will be free, but we will require some sort of authentication token for WP-Stateless installs for resource-managing purposes, we can piggyback off of whatever token Freemius creates (ref: https://github.com/wpCloud/wp-stateless/issues/48). 

Workflow:

1. A WordPress user decides its time to run a Stateless Sync process. They press a "Start Sync" button.
2. An AJAX request is made to the WordPress API (or admin-ajax.php) which creates a Stateless Job explained here https://github.com/wpCloud/wp-stateless/issues/53. 
3. After a Stateless Job post is created and we have a `post_id` the server should make a request to the Product API which starts the job right away.
4. The UI should periodically make AJAX requests to WordPress to check on job status while the panel with the progress bar, and other job details, is open.

### Job Start Request
We are creating and starting a job, with ID of `12345`.

```
curl -XPOST \
  -H 'content-type:application/json' \
  -H 'x-ud-token:lsdajflkasdjf' \
  -d '--- see Example Job Object below ---' \
   http://api.usabilitydynamics.com/product/stateless/v1/job/12345/
```
The response will be a JSON object.

### Example Job Object:
```json
{
  "callback_url": "https://workspace.uds.io/wp-admin/admin-ajax.php?action=stateless_process_image&id=%data_id%",
  "data": [ 746411, 746408, 746405, 746402, 746399, 746349, 746340, 746337, 746334 ],
  "meta": { "user_email": "asadf@dfsf.com" },
  "options": { "retry": "forever", "notifyOnFail": "aasdfas@adslkfj.com" }
}
```

Example response: 

```json
{
  "ok": true,
  "message": "Job started."
}
```

So first "step" in job would make a request here:
`https://workspace.uds.io/wp-admin/admin-ajax.php?action=stateless_process_image&id=746411`

* If response is a 200 and is a JSON object, mark as complete, start next step.
* If response is anything else, try again [5] times. 
* Log everything to Elasticsearch.

**Comment by andypotanin** [comment]
@alimuzzaman coordinate with @kavaribes on this, he is setting up the API here https://github.com/UsabilityDynamics/node-product-api/issues/7.

**Comment by kavaribes** [comment]
We need any token at request to Product API for safe callback request.

**Comment by andypotanin** [comment]
@kavaribes so:

```json
{
  "callback_url": "https://workspace.uds.io/wp-json/stateless-v1/process_image/%data_id%",
  "callback_secret": "rism-coqd-tqvh-rsiq",
  "payload": [ 746411, 746408, 746405, 746402, 746399, 746349, 746340, 746337, 746334 ],
  "meta": { "user_email": "asadf@dfsf.com" },
  "options": { "retry": "forever", "notifyOnFail": "aasdfas@adslkfj.com" }
}
```

* `callback_url` - The URL our Job API will make requests to, replacing the `%data_id%` with an item from the `data` array.
* `callback_secret` - secret hash generated by the WordPress site for this particular job. Its up to the WordPress site to verify it.
* `payload` - Array of items we use to iterate. (We called this `data` above, but I think `payload` makes more sense. 
* `meta` - Any additional information.
* `options` - Detail pertaining to Job.

Agree?

**Comment by kavaribes** [comment]
@andypotanin Yes. And for host available request needed home url. Parse `callback_url` or maybe send from WP in object home url?

**Comment by ewsopp** [comment]
Closing for now. We may return to this in the future.
