### ISSUE TITLE
File paths not correct after upgrade to 3.0

### ISSUE THREAD

**Issue by thecodeassassin** [udx/wp-stateless#544]
File URLs are wrong since we upgraded to 3.0.

The "File url" when adding images from the media library it loads the local path (wp-content)

What we expect is the File URL to be equal to WP_STATELESS_MEDIA_CUSTOM_DOMAIN.

This is not at all the case.

When we reverted back to 2.3.2 it works fine. 

Screenshot of the wrong URL using 3.0:
http://tca0.nl/YdS

When using 2.3.2:
http://tca0.nl/PaZ

**Comment by antonkorotkov** [comment]
Does it happen on a multisite or single-site installation?

**Comment by walle89** [comment]
> Does it happen on a multisite or single-site installation?

I have the same issue. It's a multisite setup with subdir config.

**Comment by thecodeassassin** [comment]
> Does it happen on a multisite or single-site installation?

Single-site installation.

**Comment by antonkorotkov** [comment]
Can you guys try upgrading to 3.0.2?

**Comment by walle89** [comment]
Nope, the bug is still there. Also I got this error on the meta page:

> Notice: Undefined index: width in /var/www/html/public/app/plugins/wp-stateless/lib/classes/class-bootstrap.php on line 740

**Comment by thecodeassassin** [comment]
Confirmed, bug is still there.

**Comment by antonkorotkov** [comment]
- Do you set the domain name exactly using the constant `WP_STATELESS_MEDIA_CUSTOM_DOMAIN`?
- Is the Bucket Name the same as the Custom Domain?
- What Mode is enabled?

**Comment by thecodeassassin** [comment]
1. No, also not sure what you mean by this. I assume you mean if the domain serving the assets is the same as wordpress. In case you meant that, no.
2. No
3. Stateless

**Comment by walle89** [comment]
1. No, we don't use CANME with our buckets.
1. No
1. Stateless

**Comment by antonkorotkov** [comment]
@thecodeassassin I assume the image is loading from your configured remote path but in the `File URL` field you see the wrong URL displayed. And there is no such file locally (since you are on `stateless` mode). Is that all correct?

**Comment by thecodeassassin** [comment]
@antonkorotkov that is exactly correct

**Comment by antonkorotkov** [comment]
The issue has been replicated and will be fixed today in 3.0.3 release. Thanks for your patience and contribution.

**Comment by antonkorotkov** [comment]
@thecodeassassin please, try upgrading to 3.0.3

**Comment by walle89** [comment]
It's working for me in my development environment. Thank you for the quick fix!
