### ISSUE TITLE
Post-processing of the image failed

### ISSUE THREAD

**Issue by tripledm** [udx/wp-stateless#547]
New errors that started today and no other plugins update and also not the theme or any other parts.

When viewing media library via WP Admin I can see initial list, I cannot search and when I upload an image I get the below error:

Post-processing of the image failed likely because the server is busy or does not have enough resources. Uploading a smaller image may help. Suggested maximum size is 2500 pixels.

When editing a post and selecting featured image and then search the gallery then it hangs and this error keeps repeating:

POST /wp-admin/admin-ajax.php 503 jquery.js?ver=1.12.4-wp:

When I try upload in image this error and in console and below error message visible:

POST /wp-admin/async-upload.php 503 moxie.min.js?ver=1.3.5:1

Post-processing of the image failed likely because the server is busy or does not have enough resources. Uploading a smaller image may help. Suggested maximum size is 2500 pixels.

The only thing that resolve it is setting it to Disabled - Disable Stateless Media.
It is set to CDN and no changes made today so is GCS down or what is the problem? (bucket location Belgium but I could not find any services down)

**Comment by antonkorotkov** [comment]
related https://wordpress.org/support/topic/admin-ajax-php-errors-cannot-upload-or-search-media-library/

**Comment by antonkorotkov** [comment]
should be fixed by #553
