### ISSUE TITLE
Problem with version 3.0 with attachment_url_to_postid and WP_Customize_Image_Control

### ISSUE THREAD

**Issue by mjezegou** [udx/wp-stateless#548]
Hello, I'm having trouble in Ephemeral mode ans m, the attachment_url_to_postid function and WP_Customize_Image_Control classe doesn't return anything to me.
I am multisite (network) with a folder 'custom'.

**Comment by mjezegou** [comment]
By regenerating the transients like this the image reappears : 

global $wpdb;
    $query = "SELECT post_id FROM $wpdb->postmeta WHERE meta_key = 'sm_cloud' AND meta_value LIKE '%s'";
    $post_id = $wpdb->get_var( $wpdb->prepare( $query, '%' . $url . '%' ) );
    if($post_id){
	    set_transient("stateless_url_to_postid_" . md5($url), $post_id);
    }

**Comment by mjezegou** [comment]
Do we have to regenerate all the transients? By what means?
I tried to regenerate the images through the interface but without success

**Comment by antonkorotkov** [comment]
@mjezegou not sure what is your problem for now but can you try the following:

Add this to you `wp-config.php`:

```php
define('WP_STATELESS_LEGACY_URL_TO_POSTID', true);
```

**Comment by mjezegou** [comment]
Thanks, I am testing this

**Comment by planv** [comment]
@mjezegou 

Is issue still relevant?

**Comment by planv** [comment]
Closing the ticket.

@mjezegou Please re-open the ticket if you still have this issue.
