### ISSUE TITLE
[3.0] Currently configured via Network Settings

### ISSUE THREAD

**Issue by planv** [udx/wp-stateless#549]
> https://wordpress.org/support/topic/3-0-currently-configured-via-network-settings/
litemotiv
(@litemotiv)
22 hours, 49 minutes ago
I just upgraded a multisite installation to v3.0 and i notice that the folder/root-dir setting now shows the text:
“Currently configured via Network Settings”
The installation is on a multisite but is activated on a few single blogs so not activated network-wide. How can i change this setting per blog like with the old version of the plugin?
Currently the automatic folder structure that wp-stateless is using is different from the earlier manual folders and is creating new folders in the bucket, which is a bit of a problem.
Thank you and best regards,
-lite

We don't have value for [wp_sm_version](https://github.com/udx/wp-stateless/blob/b1f78040166a50137f4d90c3684f3636ea8c5168/lib/classes/class-upgrader.php#L18) if plugin was activated for separated blog, not for a network even if it is `multisite`.

**Comment by antonkorotkov** [comment]
This is related to an issue in upgrader. https://github.com/wpCloud/wp-stateless/blob/245d4f4a8e59c0ae1a01b709faff46ddba17e99f/lib/classes/class-upgrader.php#L19

Going to fix it in terms of 3.0.2 release.

**Comment by antonkorotkov** [comment]
fixed
