### ISSUE TITLE
[Suggestion] adding files synchronizing purpose

### ISSUE THREAD

**Issue by FlickTheManual** [udx/wp-stateless#550]
Hi there :raised_hand_with_fingers_splayed: 

superb plugin, yes I know, I say it often.

here are some suggestions I'll add for synchronization:

- process boundary
- detailed logging (with an option for logs)
- put the mass synchronization process in the background  
- How about a beer? 

### Put a process limit for sync in the sync tab.

The goal would be to test with this limit the synchronization of files without having to synchronize them all at once, just to test if the sync queue works.

this could help us before starting the mass synchronization and lighten the process.

### Detailed logging

better debuggin process, with an option to add logs to files

### background synchronization

just to have a hand on the backoffice while the plugin is doing its job

...

What do you mean a last idea? no I put it like that, I think that drinking a drink between passionate people can be interesting :rofl: 

see ya team :+1:

**Comment by antonkorotkov** [comment]
Hey @FlickTheManual 

in terms of this issue #523 we are working on a completely new way to sync media. It is going to be a background process. And we will try to consider your other suggestions as well.
