### ISSUE TITLE
Replacement behavior of img tag - srcset attribute

### ISSUE THREAD

**Issue by mythnc** [udx/wp-stateless#558]
I am kind of curious to the replace behavior of `srcset` attribute in `img` tag.

When I chose Backup mode, and after synchronized, I found that the URL in `src` attribute is still WordPress URL, but the URLs in `srcset` attribute are replaced to gcp URLs in `img` tag

 I think all URLs inside img tag should not been changed, because I chose `Backup` mode.

I tried to read source code and found that srcset urls will be replaced regardless of mode.

I am not sure this is an expected behavior or a bug?

ref:
https://github.com/udx/wp-stateless/blob/v3.0/lib/classes/class-bootstrap.php#L415

**Comment by planv** [comment]
This is fixed in 3.1.0. We are going to release it at the nearest time.
