### ISSUE TITLE
elementor compatibility

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#560]
It looks like there may be two problems with our elementor compatibility and the latest v3.0 release of wp-stateless.

1. The uploaded CSS files don't have proper permissions set and are not publicly accessible.
2. They are not stored in the correct `/elementor/css/` directory. They are being uploaded into the root directory of the bucket.

**Comment by ewsopp** [comment]
@antonkorotkov did this fix the permission problem as well? The release notes only mention the location, and the problem with permissions was not mentioned. 

In my original bug report above, the uploaded file permissions were not set to public. 

A user just reported the problem, so it leads me to believe the permissions were not fixed. See https://wordpress.org/support/topic/elementor-css-files-have-been-synced-to-gcs-but-cannot-be-accessed-after-publis-2/

**Comment by antonkorotkov** [comment]
> @antonkorotkov did this fix the permission problem as well? The release notes only mention the location, and the problem with permissions was not mentioned.
> 
> In my original bug report above, the uploaded file permissions were not set to public.
> 
> A user just reported the problem, so it leads me to believe the permissions were not fixed. See https://wordpress.org/support/topic/elementor-css-files-have-been-synced-to-gcs-but-cannot-be-accessed-after-publis-2/

We could not replicate the permissions issue. We don't know the steps to reproduce it so we decided it was a temp problem with the API or something. Looks like it needs more attention.

**Comment by luckysistemi** [comment]
css files are now stored in the "elementor" folder at the root of the bucket.
I think it lacks a parameter to define the base folder for it or split "folder" option in two parts
