### ISSUE TITLE
Default Directory error wp-content to wpcontent

### ISSUE THREAD

**Issue by planv** [udx/wp-stateless#565]
https://wordpress.org/support/topic/default-directory-error-wp-content-to-wpcontent/

hello

previously I used the default setting just fine. After updating the plugin, there were a lot of errors. between them the default wp-content folder changes to wpcontent.

https://prnt.sc/upa6a9

how to back default from wpcontent to wp-content again?

Please help. Thanks

**Comment by antonkorotkov** [comment]
Fixed by this commit https://github.com/udx/wp-stateless/commit/796d34d525414edd8dfa2a55a8c7a034fac739d6
