### ISSUE TITLE
Sync in Stateless mode

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#575]
While developing background sync we've noticed that Stateless mode works partially. Some files were processed but the whole process has stopped because of the similar error: 

> [09-Oct-2020 16:20:31 UTC] Background Sync - Media Library Images: Stopped due to error - Unable to open gs://edmstadium-bluehost-temp4/2020/10/2020/10/2020-1003-baytown-houstonraceway-julianbajsel-processed-006.jpg using mode w+: fopen(gs://edmstadium-bluehost-temp4/2020/10/2020/10/2020-1003-baytown-houstonraceway-julianbajsel-processed-006.jpg): failed to open stream: &quot;wpCloud\StatelessMedia\StreamWrapper::stream_open&quot; call failed

I think this is because this specific file was not found on the server and was requested from GCS in order to regenerate metadata.

**Comment by antonkorotkov** [comment]
@planv I see commits tied to this issue but I don't remember whether they fix the exact problem I described in the issue or something else?

**Comment by planv** [comment]
@antonkorotkov Yes, current problem is fixed.
