### ISSUE TITLE
Override default Cache Control - Not Working

### ISSUE THREAD

**Issue by ghost** [udx/wp-stateless#58]
My Catch Control is set to "public, max-age=2592000, must-revalidate" but it doesn't work it, HTTP header is still set to 10hrs for some reason

Stuff removed from function.php (maybe i am removing something thats required by this plugin?)
http://pastebin.com/raw/dBQh5XwQ

**Comment by ewsopp** [comment]
@LiveChief can you test this out for us? I believe it now resolved with v2.1. Available for download at  https://github.com/wpCloud/wp-stateless/archive/v2.1.zip

**Comment by ewsopp** [comment]
Worked with my tests. Closing for now.
