### ISSUE TITLE
[3.10] cannot view sync page on some site

### ISSUE THREAD

**Issue by FlickTheManual** [udx/wp-stateless#581]
Hi there

I've got a new problem with frontend sync on some sites that using wp-stateless 3.10:

![image](https://user-images.githubusercontent.com/2384206/96100568-91b83400-0ee5-11eb-9949-73e0d6e5cc5f.png)

seen in console log:

![image](https://user-images.githubusercontent.com/2384206/96100664-ac8aa880-0ee5-11eb-8042-2a35ba61227c.png)

```
Error: [ng:areq] http://errors.angularjs.org/1.5.0/ng/areq?p0=wpStatelessProcessing&p1=not%20a%20function%2C%20got%20undefined
    at angular.min.js?ver=1.5.0:6
    at sb (angular.min.js?ver=1.5.0:23)
    at Sa (angular.min.js?ver=1.5.0:23)
    at angular.min.js?ver=1.5.0:86
    at A (angular.min.js?ver=1.5.0:64)
    at u (angular.min.js?ver=1.5.0:65)
    at g (angular.min.js?ver=1.5.0:58)
    at g (angular.min.js?ver=1.5.0:58)
    at g (angular.min.js?ver=1.5.0:58)
    at g (angular.min.js?ver=1.5.0:58)
```

I'm investigating why, but I make this issue if anybody can solve this.

👋

**Comment by antonkorotkov** [comment]
Looks like you have locally cached JS and CSS assets. Can you try hard refresh or maybe clean the cache in the browser settings?

**Comment by FlickTheManual** [comment]
:rofl: erf, my bad, it seems that the page not correctly loaded, not a wp-stateless problem, so... 
@antonkorotkov exactly that problem I see it when a make a clean browser cache (f***ing chrome :rofl: )

thanks man :+1: 

So I'll close this issue
