### ISSUE TITLE
Not all images have replaced urls

### ISSUE THREAD

**Issue by soanvig** [udx/wp-stateless#583]
Hello!

I just:
1. installed wp-stateless
2. set ephemeral mode
3. synchronized all files
4. double-checked they are all present in bucket - they are
5. enabled URL replacement (configured with default `jpg jpeg png gif pdf` file types)

And it seems to work, with some exceptions. 

For example here:

https://gorzkayuca.com/2020/02/20/14-uroki-konsumpcji/

The last image has no replaced url, when the rest has. In media file browser it has GCS address. But on page it still has local address.

What's also interesting is that all the images that are replaced on the site, doesn't work in the editor (the URL is not replaced to use GCS address, yet it tries to load: https://gorzkayuca.com/wp-content/uploads/2020/08/000667612W-1024x683.jpg, but that URL does not exist for some reason). The image that is not replaced on site, works correctly in editor.

Newly created posts using the same images seem to work. Also if I manually replace all images with different images, and bring back originals (using media library of course), it works  both in editor and on site. But doing that for every post is dreadful

Any ideas?

wp-stateless: 3.1.0
Wordpress: 5.5.1

**Comment by planv** [comment]
Hello @soanvig 

You have image `https://storage.googleapis.com/gorzkayuca/2020/08/DSC_0273-scaled-1024x576.jpg` instead `https://storage.googleapis.com/gorzkayuca/2020/08/DSC_0273-1024x576.jpg`
As you can see image on GCS has suffix `-scaled`. 

WordPress introduced that in version 5.3 - ref https://make.wordpress.org/core/2019/10/09/introducing-handling-of-big-images-in-wordpress-5-3/

**Comment by soanvig** [comment]
@planv I am manually replacing all images now, so I updated link to the post that still has the problem - last photo. It uses local version instead of GCS version.

But anyway, GCS version indeed has `scaled` suffix. It still doesn't explain why it's not loaded.

**Comment by planv** [comment]
@soanvig 

Your image in GCS has suffix `-scaled`
https://storage.googleapis.com/gorzkayuca/2020/02/menu-sc-scaled-768x1024.jpg

You can disable `scaling` in WordPress, please read about that in the article above.

**Comment by soanvig** [comment]
Yes, I saw it, but disabling scaling is a bad idea, isn't it?

Or is it automatically handled anyway by stateless plugin during creating various versions of images.

EDIT: I have disabled that scaling via https://wordpress.org/plugins/disable-big-image-threshold/ plugin, resynced images, but the problem still occurs. If that means I still need to fix all images manually, then it's bad...

**Comment by planv** [comment]
If you want to use scaled version - you have to replace images in your post manually.

**Comment by soanvig** [comment]
I don't care for the version I use.

My problems are:
1. Images using `-scaled` suffix on GCS work in editor and site, but use local URLs
2. Images not using `-scaled` suffix on GCS work on site using GCS urls, but don't work in editor at all

In both cases the fix is to **manually** replace all images with the same images already in library (so pick another one, then pick the correct one once again). Then everything works as expected.

I see some serious problem here.

**Comment by planv** [comment]
It was fixed with https://github.com/udx/wp-stateless/issues/596
Closing the ticket
