### ISSUE TITLE
Re-write media url domain

### ISSUE THREAD

**Issue by comzeradd** [udx/wp-stateless#584]
Hi,

_(Sorry if this already asked before, but I couldn’t find something relevant in the docs)_

I want to change the domain where the image are served from. Doing so doesn’t seem to have any immediate effect though. Running a full sync does work, but it seems a bit of overkill for changing just the media url. Is there any other way of doing that? If so, is there a wp-cli command that does that?

Thanks

**Comment by planv** [comment]
Hello @comzeradd 

Could you clarify please -do you want to change your site domain or change value for WP-Stateless setting `domain`? 

<img width="1280" alt="изображение" src="https://user-images.githubusercontent.com/5268508/96737131-fda70a80-13c5-11eb-96e6-7e740da600a7.png">

**Comment by comzeradd** [comment]
The latter :) I want to change the wp-stateless domain setting in your screenshot.

**Comment by planv** [comment]
@comzeradd 

Do you use the same `Domain` name as `Bucket` name?

<img width="1284" alt="изображение" src="https://user-images.githubusercontent.com/5268508/96999327-a7f56e00-153d-11eb-9ddc-01574350c986.png">

<img width="1280" alt="изображение" src="https://user-images.githubusercontent.com/5268508/96999356-b5aaf380-153d-11eb-976a-98dd4e40b8a8.png">

And images stored in this bucket?

**Comment by comzeradd** [comment]
The name of the GCS bucket is part of the domain name, so I can re-write it in a Cloudflare worker.

Example:
**Bucket**: `example-production`
**Domain**: `https://www.example.com/static/example-production/`

Instead of the default, which would have been:
**Domain**: `https://storage.googleapis.com/example-production/`

And yes mostly images and pdf files are stored in there.

**Comment by comzeradd** [comment]
Any suggestion on this? Doing a full re-syn works but it's a really slow process on instances with a lot of media.

**Comment by comzeradd** [comment]
Ended up using `wp search-replace` :)
