### ISSUE TITLE
compatibilities separation

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#595]

**Comment by antonkorotkov** [comment]
Example of a standalone plugin https://github.com/udx/wp-stateless-elementor-addon
Documentation at https://docs.google.com/document/d/1dbWJb5k-J2L4mkLzpN8CIESIudCnEYoCFAi8lEf3UU8/edit#

Should be enough for someone to continue where I stopped.

**Comment by antonkorotkov** [comment]
@hotdevcoder please, start from `buddyboss` compatibility and do the same I did with https://github.com/udx/wp-stateless-elementor-addon

**Comment by antonkorotkov** [comment]
@hotdevcoder use this repo I just created https://github.com/udx/wp-stateless-boddyboss-addon

**Comment by hotdevcoder** [comment]
okay cool
