### ISSUE TITLE
function get_stateless_media_data_count halting server

### ISSUE THREAD

**Issue by vzani** [udx/wp-stateless#598]
Hello

Last days we have seen a CPU pick of database server caused by the SQL function 

```
SELECT COUNT(meta_id)
            FROM " . $wpdb->postmeta . "
            WHERE meta_key = %s
```
          
ran by function _get_stateless_media_data_count_

I see that the query can be very slow depending on the number of rows on table wp_postmeta (which is our case).

For now I´m disabling this check but I think a simple solution would be to update

`update_option( 'ud_ping_' ....`

Right after the check if the ping is needed:

```
        if (
          false === $response ||
          empty( $response ) ||
          empty( $response[ 'time' ] ) ||
          ( time() - $response[ 'time' ] ) >= DAY_IN_SECONDS
        ) {
```
, and not after the execution. What is happening here is that many many many executions of

```
$this->api->ping( apply_filters('ud-api-client-ping-args', array(
            'product_id' => $this->slug,
            'version' => $this->args[ 'version' ],
            'detected_products' => base64_encode( json_encode( $detected_products ) ),
          ), $this, $detected_products))
```

Are happening in parallel. If the first execution sets the updated option timestamp, the 2nd execution would not happen.

Thanks

**Comment by planv** [comment]
It was Improved and released with version `4.0`.
Closing the ticket.
