### ISSUE TITLE
thumbnails in media library are no longer stateless

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#6]
The thumbnails displayed in the media library are no longer referencing stateless URLs. The thumbnails still exist on Google Cloud Storage, but they are no longer referenced by the media library when displaying thumbnails in the backend. I think this began with WordPress 4.4.

**Media Library View**
Thumbnails load broken in list view, but fine in grid view.

![image](https://cloud.githubusercontent.com/assets/5578537/12075959/0e0e5ab0-b163-11e5-9035-4b279db8d27c.png)

![image](https://cloud.githubusercontent.com/assets/5578537/12075968/57763bd2-b163-11e5-96c4-ef25f0cbf65a.png)

**Media Object View**
Loads fine on the single view of the media object.

![image](https://cloud.githubusercontent.com/assets/5578537/12075963/2397b098-b163-11e5-8208-fc9941296bfc.png)

**Comment by ewsopp** [comment]
Same issue with the 'Featured Image' block on the edit post screen.

![image](https://cloud.githubusercontent.com/assets/5578537/12075947/9072116e-b162-11e5-9136-662d0ebb81c4.png)

**Comment by antonkorotkov** [comment]
That was happening on RDC because WP-Stateless was outdated there. I've updated it and images went back. I'm about to utilize wp-updates.com for WP-Stateless to make it easy distributable.
