### ISSUE TITLE
Litespeed Cache Webp issue

### ISSUE THREAD

**Issue by tpatalas** [udx/wp-stateless#602]
Hi,

First of all, Thank you for the amazing plugin for free!

Below is my issue:

Setting:
1) Ephemeral
2) Litespeed Cache > Image Optimization Settings > Image WebP Replacement
3) Compatibility is on

I was expecting:
1) Users upload images > local image is served until Webp is available (this is normal Litespeed behavior when I use local storage)

What is actually happening:
1) Users upload images > returns error until Webp is available. (it returns no images) > returns Webp images when It is available.

So I was reasoning with myself It is happening because Google Storage does not have the image yet while Litepseed preparing Webp.

However, this makes me wonder does Ephemeral should use the local storage temporarily?

If this is the known issue, would it be possible to add a little task to your roadmap?

Thank you

**Comment by JuanxCursed** [comment]
Related to #181, still without manage to work :(
