### ISSUE TITLE
Latest version breaks wp media import (CLI)

### ISSUE THREAD

**Issue by mg-online-dev** [udx/wp-stateless#603]
Reproduce by skipping all plugins except wp-stateless:

wp media import --user=1 https://mg.co.za/logo-white-467.png --post_id="365160" --title="A Title" --caption="A Caption" --alt="A Test" --desc="A Description" --featured_image --debug --skip-plugins=$(wp plugin list --field=name | grep -v ^wp-stateless$ | tr  '\n' ',')

(Fails with PHP 7.4 and PHP 8.0 on WordPress 5.6.2)

Workaround by downgrading to earlier version:
wp plugin delete wp-stateless
wp plugin install wp-stateless --version=3.0.3
wp plugin activate wp-stateless

wp media import will work again

**Comment by planv** [comment]
Hello @mg-online-dev 

It should be solved in version `3.4.0`.
Please let us know how it works for you.

**Comment by planv** [comment]
As we have not yet received a response from you in the past 7 days, we will be closing the current issue. 
If you have any questions, please feel free to re-open it.
