### ISSUE TITLE
Why Cannot change the "File URL Replacement"

### ISSUE THREAD

**Issue by asanobm** [udx/wp-stateless#604]
Hello
cannot change the "File URL Replacement".
how do I enable File URL Replacement?

wordpress version 5.4.2
php 7.4
WP-Stateless 2.3.2

Thank you.

![Screen_Shot_2021-03-17_at_8_32_54](https://user-images.githubusercontent.com/38549104/111394041-3fca4300-86fd-11eb-9861-1d14f0f948fe.png)

**Comment by planv** [comment]
Hello @asanobm 

It seems you have a Multisite. In this case you can change this value to `Don't override` on page `URL/wp-admin/network/settings.php?page=stateless-settings`
Then you will be able to change this setting for the current site.

**Comment by asanobm** [comment]
Hello @planv 

Thanks to you, the problem has been resolved.
