### ISSUE TITLE
Folder setting does not allow custom structure

### ISSUE THREAD

**Issue by btdevdesign** [udx/wp-stateless#608]
Steps to reproduce:

1. Go to Stateless Settings 
2. File URL section 
3. click Custom in Folder dropdown select field 
4. type in custom folder structure (in the this case: 1/%date_year/date_month%/ ) 
5. Click Save
6. Take note that the File URL has not changed.

**Comment by ewsopp** [comment]
This is fixed and will be released in the next version. Thank you!

**Comment by planv** [comment]
Fix was released with version `3.2.5`
Closing the ticket.
