### ISSUE TITLE
setup wizard - google login

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#61]
inspect design at https://projects.invisionapp.com/d/main#/console/10029877/214297216/inspect

![image](https://cloud.githubusercontent.com/assets/5578537/21994971/71d7e256-dbf0-11e6-8226-36c9c7fc944c.png)

- [x] Clicking "Google Login" button should initiate permissions request.
- [x] When the user accepts and returns to WordPress, proceed to Step 2.
- [x] If the user rejects and returns to WordPress, return to Step 1.

**Comment by ewsopp** [comment]
If the user clicks "Deny" on the Google permission request, we should return the user to Step 1 screen in the Stateless Setup.

Watch video at https://www.dropbox.com/s/0mxxaitj929iyr2/stateless-google-login-deny-01.mp4?dl=0

![image](https://cloud.githubusercontent.com/assets/5578537/25239628/7e284ed4-25be-11e7-948d-2b8d4962c820.png)

**Comment by alimuzzaman** [comment]
@andypotanin On deny it's redirect with `error=access_denied` parameter. If error param is set pass that to user site (state param) as done on success but with the error param.

This is the url google redirect after click Deny button. But `product api` don't recognize **`error`** parameter.
https://usabilitydynamics-node-product-api-production.c.rabbit.ci/stateless/v1/auth/google?error=access_denied&state=http://localhost/workspace.uds.io/wp-admin/upload.php?page%3Dstateless-setup-wizard%26step%3Dsetup-project

**Comment by ewsopp** [comment]
much better now. thanks!
