### ISSUE TITLE
WP Stateless makes hundreds of DB queries in multisite

### ISSUE THREAD

**Issue by Sly36** [udx/wp-stateless#612]
When in a multisite install (~70 sites for me), we have a lot of upstream timeout because WP Stateless queries a lot of options (9) for each sites, in my case 69*9 = 621 queries. And this is only for one user. 

It really hurts the DB performance and make the site unusable.

![Capture d’écran 2021-05-18 à 10 57 42](https://user-images.githubusercontent.com/3594200/118623593-b13f7400-b7c8-11eb-98fa-33af56c72a35.png)

I try to set the options with constants in wp-config.php but it changes nothing, the plugin queries the DB anyway. In the code it get the option from the DB before checking the constants.

Why do you check the options for all sites and not the current site only or just the network settings ? And why not using a serialized json to store config in one site option ?

**Comment by Sly36** [comment]
Is this project still being maintained?

**Comment by ewsopp** [comment]
Please upgrade to v4.0.1 to resolve this issue. Thank you!
