### ISSUE TITLE
image_downsize() PHP8 Required parameter $id follows optional parameter $false

### ISSUE THREAD

**Issue by rolandinsh** [udx/wp-stateless#619]
**ErrorException** Deprecated: Required parameter $id follows optional parameter $false 
in /wp-content/plugins/wp-stateless/lib/classes/class-bootstrap.php 1320 
(https://github.com/udx/wp-stateless/blob/v3.0/lib/classes/class-bootstrap.php#L1320)

- WP-Stateless: 3.1.1
- PHP: 8.0.9
- WP: 5.8

_Details_:
- file: `../wp-stateless/lib/classes/class-bootstrap.php`
- line: 1320
- message: Required parameter $id follows optional parameter $false

**Comment by rolandinsh** [comment]
Related same issue:  
- **Required parameter $size follows optional parameter $false**

**Comment by rolandinsh** [comment]
@megazalrock pull request will fix issue

**Comment by MervinPraison** [comment]
@rolandinsh I am facing the same error. Considering I have the latest version 3.1.1

1. Required parameter $id follows optional parameter $false
2. Required parameter $size follows optional parameter $false

**Comment by planv** [comment]
This was fixed in version 3.2.0.
