### ISSUE TITLE
GCS Bucket to Wordpress

### ISSUE THREAD

**Issue by 4inn** [udx/wp-stateless#624]
Hello, I have a query, when I upload images to my GCS Bucket I don't see them reflected in my Wordpress, is this normal?

Thanks

**Comment by simplenotezy** [comment]
This plugin is no longer being maintained. Check WordPress reviews. Have a look at https://wordpress.org/plugins/amazon-s3-and-cloudfront/

**Comment by planv** [comment]
Hello @4inn 

Which mode do you use?

**Comment by planv** [comment]
We’ve not heard back from you in a while. Closing the ticket. Feel free to open it again if issue is still relevant.
