### ISSUE TITLE
Media error: Format(s) not supported or source(s) not found

### ISSUE THREAD

**Issue by jaircuevajunior** [udx/wp-stateless#626]
When uploading a video to the library, the uploads goes well. But then when I click on the file to get details, it displays an error: "Media error: Format(s) not supported or source(s) not found".

<img width="295" alt="Captura de Tela 2022-01-21 às 15 51 07" src="https://user-images.githubusercontent.com/6161185/150585053-3b2144f6-1573-4aa2-bf17-7b794a48bf72.png">

When I insert that errored video on page, it just displays the same error so the video is not loaded.

The funny part is that that plugin has successfully uploaded the video to the Bucket, and the URL it gives to me is just pointing to the working video, like this one: https://cdn.rd.com.br/local/2022/01/f818c23c-file_example_mp4_480_1_5mg.mp4.

- I tried to replicate the steps with the plugin disabled and it just works.
- I tried with the plugin in Stateless, Ephemeral and CDN modes, none has worked.
- I tried with File URL Replacement, nothing.

Plugin version: 3.1.1.
Wordpress version: 5.8.2

Please, I hope you can help me.
Thanks.

**Comment by planv** [comment]
Hello @jaircuevajunior 

I've just tested uploading this video to Google Bucket - it works for me

<img width="1488" alt="изображение" src="https://user-images.githubusercontent.com/5268508/167123019-856c87ac-f0d9-4f43-87d0-202c6b850cd9.png">

It may be a conflict with other Plugins innstalled on your site.

**Comment by jaircuevajunior** [comment]
Hello @planv 

Thanks for the reply.

I've already fixed that.
The problem was in the header `Content-Security-Policy` which I was implementing in that time...
Precisely it was lacking the `media-src 'self' cdn.rd.com.br;` parameter.
I'm sorry, it has nothing to do with `wp-stateless` plugin.
We can close this issue.
