### ISSUE TITLE
Can't add a New Plugin using Upload Plugin with a zip File

### ISSUE THREAD

**Issue by apcabotaje** [udx/wp-stateless#627]
I am trying to upload a plugin called WebToffee which is in zip file but I have this error:

The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to go to the end of the archive 'gs://my-bucket-name/2022/02/6d05c767-wt-import-export-for-woo.zip'

I've also tried to install this plugin manually via SFTP which is not a good way to go (hassle for me) and when I install it, it can't import or export any users or orders. Please I need help and your insights, thanks!

**Comment by ThalesMatoso** [comment]
I couldn't install the template due to the same error

**Comment by planv** [comment]
Hello, @apcabotaje 

Which `mode` do you use?
When you tried to import/export users - did you have the same error?

**Comment by planv** [comment]
We’ve not heard back from you in a while. Closing the ticket. Feel free to open it again if issue is still relevant.
