### ISSUE TITLE
problem after the upgrade

### ISSUE THREAD

**Issue by deusngo** [udx/wp-stateless#628]
after yesterday WooCommerce upgrade the page gets an error and the add-on had to be disabled.
But now our eshop is without photos

WordPress έκδοση 5.9.1
Ενεργό θέμα: Storefront (έκδοση 3.9.1)
Τρέχων πρόσθετο: WP-Stateless (έκδοση 3.1.1)
Έκδοση PHP 7.4.28

Αυτό το πρόσθετο απέτυχε να φορτωθεί σωστά και έχει τεθεί σε παύση κατά τη διάρκεια της λειτουργίας αποκατάστασης.

Ένα σφάλμα τύπου E_ERROR εντοπίστηκε στη γραμμή 42 του αρχείου /usr/www/users/1998/thriftstore/wp-content/plugins/wp-stateless/lib/Google/vendor/guzzlehttp/guzzle/src/HandlerStack.php. Κωδικός σφάλματος: Uncaught Error: Call to undefined function GuzzleHttp\choose_handler() in /usr/www/users/1998/thriftstore/wp-content/plugins/wp-stateless/lib/Google/vendor/guzzlehttp/guzzle/src/HandlerStack.php:42 Stack trace: #0 /usr/www/users/1998/thriftstore/wp-content/plugins/wp-stateless/lib/Google/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create() #1 /usr/www/users/1998/thriftstore/wp-content/plugins/wp-stateless/lib/Google/src/Google/Client.php(1157): GuzzleHttp\Client->__construct(Array) #2 /usr/www/users/1998/thriftstore/wp-content/plugins/wp-stateless/lib/Google/src/Google/Client.php(1112): wpCloud\StatelessMedia\Google_Client\Google_Client->createDefaultHttpClient() #3 /usr/www/users/1998/thriftstore/wp-content/plugins/wp-stateless/lib/Google/src/Google/Client.php(381): wpCloud\StatelessMedia\Google_Client\Google_Client->getHttpClient() #4 /usr/www/users/1998/thriftstore/wp-content/plugins/wp-stateless/lib/Google/src/Google/Client.php(860): wpCloud\StatelessMedia\Google_Clie

**Comment by planv** [comment]
Hello, @deusngo 

I've just tested with WooCommerce Version 6.4.1 - I don't have such problem.
Can you please provide more details in English?

**Comment by planv** [comment]
Hello, @deusngo 

We have released a new version of WP-Stateless - 3.2.0.

**Comment by planv** [comment]
Was solved in version `3.2.0`. Closing the ticket
