### ISSUE TITLE
Is the plugin closed?

### ISSUE THREAD

**Issue by raveBolognesa** [udx/wp-stateless#629]
hello i've seen that que plugin apears as closed on wp plugin directory
are you going to remove it?
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/48025840/166896766-f8d252b8-54b0-4ddf-ab4a-37cb3690462c.png">

**Comment by planv** [comment]
Hello @raveBolognesa 

No, Plugin is not closed.
We are working on improvements right now.
It will be available on WordPress.org soon.

**Comment by thecodeassassin** [comment]
Hi @planv What is the reason for this? 

```
  Problem 1
    - Root composer.json requires wpackagist-plugin/wp-stateless, it could not be found in any version, there may be a typo in the package name.
```
    
We are now unable to update our code. If this was a conscious choice then why were all packages removed from wp-packagist? This is a serious issue.

**Comment by cwongyvr** [comment]
got the same wpackagist as above, any updates or anyone know a workaround?
![Screen Shot 2022-05-16 at 11 37 53 AM](https://user-images.githubusercontent.com/9586005/168660053-b600c7bd-3cbd-475b-92bd-ff5b2df30902.png)

**Comment by thecodeassassin** [comment]
> got the same wpackagist as above, any updates or anyone know a workaround? ![Screen Shot 2022-05-16 at 11 37 53 AM](https://user-images.githubusercontent.com/9586005/168660053-b600c7bd-3cbd-475b-92bd-ff5b2df30902.png)

For now we just committed the latest version to source control. I'd suggest doing that as well.

**Comment by planv** [comment]
Hello @raveBolognesa.

The WP-Stateless plugin is available for download on wordpress.org again, current stable version is 3.2.0.

**Comment by planv** [comment]
Hello @thecodeassassin .

We have released a new version of plugin. Can you please try update it using composer again?

**Comment by thecodeassassin** [comment]
It didn't work initially but I refreshed the package on wp-packagist. After that it started working again. Thanks!

In the future when this happens, please refresh the package here: https://wpackagist.org/search?q=wp-stateless&type=any&search=

Thanks.

**Comment by raveBolognesa** [comment]
yes now is working thanks!
