### ISSUE TITLE
Version 3.2.0 is not published on packagist

### ISSUE THREAD

**Issue by dlackty** [udx/wp-stateless#636]
As titled, the latest version on packagist is still 3.1.1:
https://packagist.org/packages/wpcloud/wp-stateless

**Comment by planv** [comment]
Hello @dlackty 

Plugin was updated to version 3.2.0 on packagist.org
https://packagist.org/packages/wpcloud/wp-stateless

**Comment by dlackty** [comment]
Thank you for the timely reply and also for the great work on this plugin.
