### ISSUE TITLE
WP-Stateless 3.2.0 doesn’t upload docs, only images

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#638]
reported at https://wordpress.org/support/topic/wp-stateless-3-2-0-doesnt-upload-docs-only-images/

> Problem:
> 
> – Uploaded images work OK
> 
> – Uploaded docs (PDF, DOCX etc) don’t work
> 
> After uploading a doc the filepath shows /wp-content/uploads/filename etc instead of the location in the bucket. The files themselves appear to be gone, they are not in the bucket and also not in the local upload path.
> 
> There are no errors in the server error.log.
> 
> This is on an updated webserver with the following details:
> 
> PHP 7.4
> WordPress Multisite 5.9.3, WP-Stateless running in ‘single site’ mode
> Ephemeral uploads

.

> Update: i can confirm the issue also occurs on standalone (non-multisite) installations.

**Comment by planv** [comment]
Fixed in version 3.2.1
