### ISSUE TITLE
Folder setting can't be saved from the settings page

### ISSUE THREAD

**Issue by lithrel** [udx/wp-stateless#639]
Hi :wave: 

Version 3.2.0
Probably since https://github.com/udx/wp-stateless/commit/6aee7ae0b0beeb2232ce6e1c82aa7e2041ae151a#diff-5c6a7480a4ecf0cea0a218a7c1641b8537fe28f30624802307b8baab0fd749ddR525

When selecting the option _"Single site"_ for _"File URL > Folder"_ in the settings, the option is not saved.
I think it's because `sanitize_text_field()` [returns an empty string](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/formatting.php#L5465-L5467) if given an array, and `root_dir` is posted as an array (ie: `sm[root_dir][] => "%date_year/date_month%"`). The option ends up empty after sanitize and [those lines](https://github.com/udx/wp-stateless/blob/v3.0/lib/classes/class-settings.php#L529-L542) are never executed.
Saving the options through the settings page after configuring this one through CLI also empties it.

I tested moving the sanitization [after the array condition](https://github.com/udx/wp-stateless/blob/251aa6c02799a2a7d1a35bddb03a2f12ecfe03ac/lib/classes/class-settings.php#L543) but it seems like WP function [strips the first characters](https://github.com/WordPress/wordpress-develop/blob/0b6bc9a386aa1a4c9b64818505e7657936367ff0/src/wp-includes/formatting.php#L5490-L5492) of the default patterns given, so `%date_year/date_month%` ends up as `te_year/date_month%`. Maybe we could skip sanitization of this setting for known values that are in `$this->wildcards` keys ?

Thank you for your work :heart:

**Comment by planv** [comment]
Hello @lithrel 

Thank you for your message.

It was fixed in version 3.2.2 and released to wordpress.org.
