### ISSUE TITLE
Google API client is out-of-date and a security risk.

### ISSUE THREAD

**Issue by doubleforte** [udx/wp-stateless#643]
The included Google API client `lib/Google` is recently out-of-date and tripping a Dependabot security warning. The `guzzlehttp/guzzle` included in this dist is v7.4.2 and the patch is included in v7.4.3.

https://github.com/advisories/GHSA-cwmx-hcrq-mhc3

The currently available Google library is up-to-date -- it's just not included in this wp-stateless package.

Thank you :)

**Comment by doubleforte** [comment]
More "high" security alerts from the out-of-date guzzle library embedded with the included Google library.

https://github.com/advisories/GHSA-q559-8m2m-g699
https://github.com/advisories/GHSA-25mq-v84q-4j7r
https://github.com/advisories/GHSA-f2wf-25xc-69c9
https://github.com/advisories/GHSA-w248-ffj2-4v5q

Anyway we can get the library updated to clear these issues? Installed is v7.4.2 and the latest v7.4.5 supposedly fixes all these.

**Comment by doubleforte** [comment]
Any progress on this?

This plugin is my last hold out to verify WordPress 6 support...I'd like to upgrade, but I'm nervous this might break.

**Comment by curtismchale** [comment]
@doubleforte if it's any help. I'm running 120 sites on WP 6 and it does seem to work. I have errors, but those may be with PHP 8 (which we're migrating to).

**Comment by doubleforte** [comment]
@curtismchale Thanks. I did end up moving to PHP 8 and yeah, WordPress has a ton of deprecation warnings. :(

This plugin seems to work ok on WordPress 6, but it's a bit worrying that there hasn't been much activity here. I like it...I hope it's not abandoned. :(

**Comment by planv** [comment]
Google API Client was updated to latest version. Will be released in version `3.2.3`

**Comment by planv** [comment]
Released. Closing the ticket.
Please let us know if you have any further questions
