### ISSUE TITLE
Upload error on RO Filesystem with Stateless mode

### ISSUE THREAD

**Issue by i2TIC** [udx/wp-stateless#645]
Hello,

We have noticed that the file upload on Stateless mode using a RO filesystem, only work on list mode in media library and Upload button on image block in posts. Trying to upload the file using the media library in grid mode (Drag & Drop and Add New button) fails, and trying to use the media library link in image block (which also allows to upload files from there) also fails.
The error is giving, is just that is unable to create the folder (which is normal in a RO filesystem).

I have disabled the RO filesystem for testing, and I have seen that works just fine. It creates the folder that was failing and then uploads the file as expected to the storage directly (the folder is kept empty).

In my case I think that I can fix it just creating a tmp filesystem on the wp-uploads folder to allow the WP to create the required folders on upload, but can be a problem in other cases and is not a real stateless mode then.

Best regards.

**Comment by planv** [comment]
Hello @i2TIC 

I tested it with new version and I did not have this issue. Can you please update `WP-Stateless` to version `3.2.3` and check it again?

**Comment by planv** [comment]
Closing the ticket.

Please let us know if the issue still persists for you.
