### ISSUE TITLE
plugin hangs for 15s when usabilitydynamics.com is down 

### ISSUE THREAD

**Issue by ckeeney** [udx/wp-stateless#646]
At the time this issue is created, [usabilitydynamics.com is down](https://downforeveryoneorjustme.com/usabilitydynamics.com).

![image](https://user-images.githubusercontent.com/8799010/180061786-007e1937-fe11-4cb0-81a1-c8ce42ee1f11.png)

Every page of wp-admin is loading extremely slowly, and Query Monitor points to an HTTP call made by wp-stateless to usabilitydynamics being the culprit.  This request times out after 15s, and blocks loading until it fails.

![image](https://user-images.githubusercontent.com/8799010/180062029-d880e6bb-d65c-4dcb-b692-8c63a336d90c.png)

**Comment by planv** [comment]
Hello @ckeeney 

Thank you for you notice! We've already fixed the issue.

**Comment by planv** [comment]
Closing the ticket.
