### ISSUE TITLE
Can't enable plugin - WP hangs

### ISSUE THREAD

**Issue by xo-pulss** [udx/wp-stateless#647]
Looked into debug log and found this problem.

> PHP Deprecated:  Return type of wpCloud\StatelessMedia\Sync\BackgroundSync::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ../wp-content/plugins/wp-stateless/lib/classes/sync/class-background-sync.php on line 429

How can we fix this?

**Comment by curtismchale** [comment]
@xo-pulss Are you using PHP 8.1.x by chance?

**Comment by planv** [comment]
Fixed.
Will be released in version 3.2.3

**Comment by planv** [comment]
Released. Closing the ticket.
Please let us know if you have any further questions
