### ISSUE TITLE
InvalidArgumentException: key must be a string when using hmac

### ISSUE THREAD

**Issue by ghost** [udx/wp-stateless#650]
Fatal error: Uncaught InvalidArgumentException: key must be a string when using hmac in /var/www/html/wp-content/plugins/lib/Google/vendor/firebase/php-jwt/src/JWT.php:233 Stack trace: #0 /var/www/html/wp-content/plugins/lib/Google/vendor/firebase/php-jwt/src/JWT.php(203): Firebase\JWT\JWT::sign('eyJ0eXAiOiJKV1Q...', false, 'HS256') #1 /var/www/html/wp-content/plugins/lib/classes/class-utility.php(740): Firebase\JWT\JWT::encode(Array, false, 'HS256') #2 /var/www/html/wp-content/plugins/lib/classes/class-bootstrap.php(1187): wpCloud\StatelessMedia\Utility::generate_jwt_token(Array, 86400) #3 /var/www/html/wp-includes/class-wp-hook.php(307): wpCloud\StatelessMedia\Bootstrap->admin_init('') #4 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #5 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #6 /var/www/html/wp-admin/admin.php(175): do_action('admin_init') #7 /var/www/html/wp-admin/plugins.php(10): require_once('/var/www/html/w...') #8 {main} thrown in /var/www/html/wp-content/plugins/lib/Google/vendor/firebase/php-jwt/src/JWT.php on line 233
There has been a critical error on this website. Please check your site admin email inbox for instructions.

I am facing this error after deploying my website to cloud run

**Comment by ckeeney** [comment]
On my installation, `defined('AUTH_SALT')` returns true, but `AUTH_SALT` is null.

I believe a fix for this is to check both that the `AUTH_SALT` constant is defined AND that it is a non-empty string.

https://github.com/udx/wp-stateless/blob/080281a556d1a727357d8d2d2bba939dcab2896b/lib/classes/class-utility.php#L738-L741

For those encountering this error, you can simply make sure your `AUTH_SALT` is defined as a non-empty string and this should go away, but the bug should be fixed so it properly defaults to the `admin_email` option when no salt is defined.

**Comment by planv** [comment]
Hello @mjad218 

This is fixed, will be released in version `3.2.3`

@ckeeney Thank you for participating

**Comment by planv** [comment]
Released. Closing the ticket.
Please let us know if you have any further questions
