### ISSUE TITLE
Problem Migrating from multisite to single site 

### ISSUE THREAD

**Issue by tottaz** [udx/wp-stateless#653]
I was hoping that wp-stateless would help me to migrate images as I moving my hosting server at the same time I am moving from a multi-site WordPress setup to a single-site setup, as my other sites in the multi-site are getting retired.

I set up wp-stateless on my multi-site, I use a single site for the folder settings and use the Backup mode to backup files to GCS.

On the new hosting - I am using Google Cloud Run, I activate wp-stateless and I use the Stateless mode, i can upload an image gives me errors.

Warning: Undefined variable $media in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-utility.php on line 349

Warning: Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-utility.php on line 522

Warning: Undefined variable $media in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-utility.php on line 349

Warning: Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-utility.php on line 522

Warning: Undefined variable $media in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-utility.php on line 349

Another problem is that the uploaded file is getting a prefix - a random number - **d62db080**-screenshot-2022-10-31-at-16.44.13.png - when I upload a file in multi-site I do not get this prefix.

I think this prefix causes me an issue when using WordPress export and import, so I export from my multi-site all the pages, post etc.

When I import in my single-site Cloud Run instance I get this error "Sorry, there has been an error. The file does not exist, please try again." - my import file name is  socialclimatetechnews.xml this is the file name when stored in GCS  711fc3b0-socialclimatetechnews.xml_.txt. Not sure if this is related to wp-stateless or something else, wp-stateless is used to upload files.

I have tried to use wp-stateless on my local test environment, to import the socialclimatetechnews.xml with wp-stateless enabled and in stateless mode, I get the same error - "Sorry, there has been an error. The file does not exist, please try again."

If I switch to wp-stateless mode to backup, I do not have a problem importing socialclimatetechnews.xml,

And yes, I have disabled all other plugins and tried them one by one.

One other thing, I am running WordPress in a Docker container, on the local machine I use Docker Desktop, and in the cloud, I use Cloud Run, same code base, only difference between running locally and with Cloud Run is only the wp-config.php file.

I hope there is someone that has experience a similar issue.

<img width="961" alt="Screenshot 2022-10-31 at 17 36 14" src="https://user-images.githubusercontent.com/1147629/199064896-f68047e3-ecd6-44a1-b19d-db41403199df.png">

**Comment by planv** [comment]
Hello @tottaz 

>Warning: Undefined variable $media in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-utility.php on line 349
Warning: Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-utility.php on line 522
Warning: Undefined variable $media in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-utility.php on line 349
Warning: Trying to access array offset on value of type null in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-utility.php on line 522
Warning: Undefined variable $media in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-utility.php on line 349

Fixed, will be released in version 3.2.3.


> Another problem is that the uploaded file is getting a prefix - a random number - d62db080-screenshot-2022-10-31-at-16.44.13.png - when I upload a file in multi-site I do not get this prefix.

Looks like`Cache-Busting` is Enabled
![изображение](https://github.com/udx/wp-stateless/assets/5268508/41672603-e872-4413-afde-8fd0bd95e622)

Can you please Disable this option and try Import again if it is still relevant.

**Comment by planv** [comment]
Released. Closing the ticket.
Please let us know if you have any further questions
