### ISSUE TITLE
Website Crashes when reinstalling Plugin

### ISSUE THREAD

**Issue by Dishoom007** [udx/wp-stateless#655]
I have installed plugin into several websites and it working fine, but on one of the website ( nanoschool.in) when I deleted the JSON to enter a new key the site crashed and even the admin was not accessible, I have to disable the plug-in to restore the website.

When I tried to re-install the plugin again the website crashes each time. Very much interested to use the plugin on the website, can you suggest a way out.

**Comment by planv** [comment]
Hello @Dishoom007 

I can not replicate the issue. Can you please provide PHP logs?

**Comment by planv** [comment]
We have not received any response for past 3 weeks.
Closing the ticket.
Please let us know if you have any further questions
