### ISSUE TITLE
Recover files moved to the bucket

### ISSUE THREAD

**Issue by charlesg** [udx/wp-stateless#657]
Current setting is "Stateless" but I would like to recover ALL the files from the bucket to their original location in the media folder. If If I change the setting to CDN, will files previously migrated be recovered?

I need the media/ folder restored to prepare for a migration to another host.

**Comment by planv** [comment]
Hello @charlesg 

Sorry for the late respond.

Yes, you can use `CDN` mode for that.

Closing the ticket.
