### ISSUE TITLE
Auto created bucket is invisible

### ISSUE THREAD

**Issue by alexlii1971** [udx/wp-stateless#658]
Hello,

I tried to create a bucket by automatic methods.  I can upload images to the bucket, but it is invisible at https://console.cloud.google.com/storage/browser

When tried gsutil ls -lR gs://$BUCKETNAME, it show:404 no such bucket.

Then, I tried to manually create a bucket, and it is listed at https://console.cloud.google.com/storage/browser, but problem is that I can't upload the image to the bucket, and it shows "Not connected to GCS".

So, two questions please?

1#  would you please let us know how to set the automatically created bucket to be visible or could be listed in the cloud storage dashboard?

2# Anyway to connect the manually created buckets?

Thanks

**Comment by planv** [comment]
Hello @alexlii1971 

Are you sure that you use correct `Service Account`? 
It looks like `WP-Stateless` can upload images to auto-created bucket and they are exist there, but you do not see this bucket at Google Cloud Storage?

> 2# Anyway to connect the manually created buckets?

Yes, you can set it up through this option
![изображение](https://github.com/udx/wp-stateless/assets/5268508/261f7a6d-38da-467f-914c-9e1468ae9b8e)

**Comment by planv** [comment]
We have not received any response for past 3 weeks.
Closing the ticket.
Please let us know if you have any further questions
