### ISSUE TITLE
plugin JS in admin resolves to 404

### ISSUE THREAD

**Issue by hatsumatsu** [udx/wp-stateless#659]
We are currently seeing this old issue https://github.com/udx/wp-stateless/issues/143 in a fresh install within a bitnami/wordpress docker container.

- Wordpress 6.1.1
- wp-stateless 3.2.2

In wp-admin there is a call to `ud-dismiss.js` located at

`{THEME_FOLDER_URL}/bitnami/wordpress/wp-content/plugins/wp-stateless/vendor/udx/lib-wp-bootstrap/static/scripts/ud-dismiss.js`. In our case this resolves to `http://localhost/wp-content/themes/{theme}/bitnami/wordpress/wp-content/plugins/wp-stateless/vendor/udx/lib-wp-bootstrap/static/scripts/ud-dismiss.js?ver=6.1.1`

**Comment by planv** [comment]
Hello @hatsumatsu 

Is this issue still relevant?
Does `bitnami/wordpress` add `{THEME_FOLDER_URL}` to the URL?

**Comment by planv** [comment]
We have not received any response for past 3 weeks.
Closing the ticket.
Please let us know if you have any further questions
