### ISSUE TITLE
Media Library Sync

### ISSUE THREAD

**Issue by jeremystewart21** [udx/wp-stateless#660]
Hi Team, we have setup wp-stateless with an existing wordpress website and all seems to be going well. The backlog of images still on the wp host server is around 14,000 (about 10gb)
I have tested syncing with a limit of 500. I'm nervous to pull the trigger on all 14,000?
Will this impact my website performance?
<img width="449" alt="Screen Shot 2023-02-16 at 3 05 03 pm" src="https://user-images.githubusercontent.com/78531318/219292442-e16086d7-a69e-4eb3-a814-d0d128349eea.png">

**Comment by planv** [comment]
Hello @jeremystewart21 

`WP-Stateless` processes images one by one, not all together, but full sync takes up memory and CPU on the server. 
It would be better to test it on `staging` environment and determine how much Memory and CPU it takes in your case.

Closing the ticket.
