### ISSUE TITLE
Is it possible to use WP-Stateless plug-in to only display files from a bucket and not store/backup any image from Wordpress media

### ISSUE THREAD

**Issue by JakeEllis** [udx/wp-stateless#661]
I am looking for a plugin to display images on one particular web page from a GCS bucket location. Is that something that wp-stateless can do? I cannot find a good description of what the various modes can and cannot do so I apologize for the question in the issues forum.

If not, are you aware of a plugin that can perform this task? I am trying to avoid writing my own JS code to make this happen.

**Comment by LorenzoInvernizzi** [comment]
to serve images i think you need in any case the image url, you can simply make the bucket public and remove the list capability and directly point to the images in you webapp. It also depends how the url are stored in your data. The plugin hande the uploads and serving of images, but once you have the url you can directly point to it, so if you dont need to upload images you could avoid to use the plugin.

Hope it helps

**Comment by planv** [comment]
Hello @JakeEllis 

Yes, `WP-Stateless` can upload images from WordPress Media to Google Cloud Storage, then you can use it on the page.

Let me know if you have additional questions. Closing the ticket for now
