### ISSUE TITLE
wp-stateless works partially in google cloud run

### ISSUE THREAD

**Issue by LorenzoInvernizzi** [udx/wp-stateless#662]
Good Morning,

I am experiencind a weird behaviour:
wp-stateless works perfectly locally, while wp-stateless works partially in google cloud run (containerized):

- by using the 'add new' tab  under media i can successfully load images:
![image](https://user-images.githubusercontent.com/21220248/229041167-af71f799-d57e-4915-be57-6495f1356106.png)

- when i try to add a new image from the library shortcut or by uploading from the post itself i get the error: _**Unable to create directory wp-content/uploads/2023/03. Is its parent directory writable by the server?**_
![image](https://user-images.githubusercontent.com/21220248/229041531-547f00f1-84bc-4867-acdb-02147400175d.png)
![image](https://user-images.githubusercontent.com/21220248/229041702-b358d28e-a3f0-488a-8594-04633c40da28.png)

do you have any suggestions to where to look? like adding some particular logs in the plugin/debug it locally.

I already tried:
- disable and reactivate the plugin
- delete and reinstall the plugin.

Here my docker file:

```
FROM php:8.0-apache

RUN apt-get update && apt-get upgrade -yy \
  && apt-get install --no-install-recommends apt-utils libjpeg-dev libpng-dev libwebp-dev \
  libzip-dev zlib1g-dev libfreetype6-dev supervisor zip \
  unzip software-properties-common -yy \
  && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN docker-php-ext-install zip \
  && docker-php-ext-install mysqli pdo pdo_mysql \
  && docker-php-ext-install exif \
  && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
  && docker-php-ext-install -j "$(nproc)" gd \
  && a2enmod rewrite

WORKDIR /var/www/html
COPY . .

COPY .env.production .
ADD .env.production .env
ADD .htaccess-prod .htaccess
```

Thank You,
Lorenzo

**Comment by LorenzoInvernizzi** [comment]
It seems like that in case of the error the variable $time is nulle and the following code (inside wp_upload_dir definition) in the following if is never executed, hence the gcs path is not set :

	if ( $refresh_cache || empty( $cache[ $key ] ) ) {
		$cache[ $key ] = _wp_upload_dir( $time );
	}

**Comment by LorenzoInvernizzi** [comment]
+ commenting the following line at the start of the async-upload.php seems to fixed it but i dont know what else could co wrong then
// if (isset($_REQUEST['action']) && 'upload-attachment' === $_REQUEST['action']) {
// 	define('DOING_AJAX', true);
// }

**Comment by LorenzoInvernizzi** [comment]
it is still partially true, it solves one of the two cases

**Comment by LorenzoInvernizzi** [comment]
It is not something related to docker but to the ajax call: when the upload is trigger by an aiax call a temp file is saved into wp-content/uploads and immmediately after it gets moved to the bucket and deleted. This breaks the stateless approach. I debugged the code but i dont know how to solve it. IT seems the plugin is instantiated/available just after the ajax call
and not before.

Any suggestions?

**Comment by LorenzoInvernizzi** [comment]
temporary fix is to specify
define('UPLOADS', '/tmp');
in prodution

**Comment by planv** [comment]
You can redefine path for `uploads` folder or use `WP-Stateless` with `Stateless` mode - it will not store images locally, just send them to Google Cloud Storage.
Closing the ticket.
