### ISSUE TITLE
Is the orginal uploads/year/month URL preserved somewhere?

### ISSUE THREAD

**Issue by charlesg** [udx/wp-stateless#663]
The plugin ran in "stateless" mode for a while. Some images are now only in the bucket. I am trying to rebuild the uploads/<year>/<month> directory. Is the ORIGINAL URL, prior to the move to a bucket, preserved somewhere?

**Comment by planv** [comment]
@charlesg You can run full re-sync in `CDN` mode - it will download and save images from Google Bucket to local storage(uploads directory) .

**Comment by planv** [comment]
@charlesg Please let us know if the ticket is still relevant.
Closing the ticket for now.
