### ISSUE TITLE
Plugin functioning but seeing error message

### ISSUE THREAD

**Issue by scratchfoodie** [udx/wp-stateless#664]
Getting this error message at the top of site:
Deprecated: Return type of wpCloud\StatelessMedia\Sync\BackgroundSync::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/lostbluegrass.com/public_html/wp-content/plugins/wp-stateless/lib/classes/sync/class-background-sync.php on line 429

This occurred after adding a second virtual host on the same server in apache, the 2nd wordpress instance is functioning properly and not seeing this error message (2nd site also using wp-stateless).

**Comment by planv** [comment]
Duplicate https://github.com/udx/wp-stateless/issues/647

**Comment by planv** [comment]
Fixed.
Will be released in version 3.2.3

**Comment by planv** [comment]
Released. Closing the ticket.
Please let us know if you have any further questions
