### ISSUE TITLE
New PHP 8 issue

### ISSUE THREAD

**Issue by harrystymiest** [udx/wp-stateless#667]
On a New Server if PHP 8 is active I now get this Error if 7.4 is active all is fine 

(Direct directory is Redacted)

all to undefined function Symfony\Polyfill\Mbstring\iconv() in /home/clients/public_html/wp-content/plugins/wp-stateless/vendor/symfony/polyfill-mbstring/Mbstring.php:287 Stack trace: #0 /home/clients/public_html/wp-content/plugins/wp-stateless/vendor/symfony/polyfill-mbstring/Mbstring.php(570): Symfony\Polyfill\Mbstring\Mbstring::mb_convert_case('Core', 1, 'ASCII') #1 /home/clients/public_html/wp-content/plugins/wp-stateless/vendor/symfony/polyfill-mbstring/bootstrap.php(63): Symfony\Polyfill\Mbstring\Mbstring::mb_strtolower('Core', 'ASCII') #2 /home/clients/public_html/wp-content/plugins/wp-stateless/vendor/wpmetabox/meta-box/inc/autoloader.php(59): mb_strtolower('Core', 'ASCII') #3 /home/clients/public_html/wp-content/plugins/wp-stateless/vendor/wpmetabox/meta-box/inc/loader.php(88): RWMB_Autoloader->autoload('RWMB_Core') #4 /home/clients/public_html/wp-content/plugins/wp-stateless/vendor/wpmetabox/meta-box/meta-box.php(19): RWMB_Loader->init() #5 /home/clients/public_html/wp-content/plugins/wp-stateless/vendor/composer/autoload_real.php(66): require('/home/clients/p...') #6 /home/clients/public_html/wp-content/plugins/wp-stateless/vendor/composer/autoload_real.php(56): composerRequirec59d002476a452800baaf79c430753cb('8ca8a91f0a826d6...', '/home/clients/p...') #7 /home/clients/public_html/wp-content/plugins/wp-stateless/vendor/autoload.php(7): ComposerAutoloaderInitc59d002476a452800baaf79c430753cb::getLoader() #8 /home/clients/public_html/wp-content/plugins/wp-stateless/wp-stateless-media.php(60): require_once('/home/clients/p...') #9 /home/clients/public_html/wp-content/plugins/wp-stateless/wp-stateless-media.php(97): ud_check_stateless_media() #10 /home/clients/public_html/wp-settings.php(453): include_once('/home/clients/p...') #11 /home/clients/public_html/wp-config.php(100): require_once('/home/clients/p...') #12 /home/clients/public_html/wp-load.php(50): require_once('/home/clients/p...') #13 /home/clients/public_html/wp-blog-header.php(13): require_once('/home/clients/p...') #14 /home/clients/public_html/index.php(17): require('/home/clients/p...') #15 {main} thrown in /home/clients/public_html/wp-content/plugins/wp-stateless/vendor/symfony/polyfill-mbstring/Mbstring.php on line 287

**Comment by planv** [comment]
Replied here - https://wordpress.org/support/topic/new-php-8-issue/#post-16789654

**Comment by planv** [comment]
Closing the ticket.
Please let us know if you have any further questions
