### ISSUE TITLE
Website unresponsive after Upgrade

### ISSUE THREAD

**Issue by Dishoom007** [udx/wp-stateless#669]
Following is the email with error Code ( at bottom ) I have recieved from Wordpress after recent Upgrade to the latest virsion of WP-Stateless

Howdy!

WordPress has a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.

In this case, WordPress caught an error with one of your plugins, WP-Stateless.

First, visit your website (https://journals.stmjournals.com/) and check for any visible issues. Next, visit the page where the error was caught (https://journals.stmjournals.com/wp-admin/) and check for any visible issues.

Please contact your host for assistance with investigating this issue further.

If your site appears broken and you can't access your dashboard normally, WordPress now has a special "recovery mode". This lets you safely login to your dashboard and investigate further.

https://journals.stmjournals.com/wp-login.php?action=enter_recovery_mode&rm_token=PZ6G2sh4PEG5Z4py0IGCfs&rm_key=QNCsjbTT6Kwly5tU2pgTpX

To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.2.2
Active theme: Thrive Theme Builder (version 3.19.1)
Current plugin: WP-Stateless (version 3.2.3)
PHP version 7.4.33

Error Details
=============
An error of type E_COMPILE_ERROR was caused in line 313 of the file /home/p2387928/stmjournals.com_wpress/wp-content/plugins/wp-stateless/lib/Google/vendor/ramsey/uuid/src/Uuid.php. Error message: Declaration of Ramsey\Uuid\Uuid::unserialize(string $data): void must be compatible with Serializable::unserialize($serialized)

---------------
Pls let me know how to rectify the issue asap.

Regards

Puneet

**Comment by darrenbarklie** [comment]
Unfortunately this error took several of our client websites offline this morning, with only this PHP error returned:
```
Parse error: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /home/customer/www/[DOMAIN]/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/psr/cache/src/CacheItemInterface.php on line 104
```
With no access to the frontend or WordPress dashboard, we took the following steps to resolve:
1. Log in to hosting panel / FTP in to server
2. Rename the `/public_html/wp-content/plugins/wp-stateless/` directory (to deactivate the plugin)
3. Download previous version 3.2.2 [[link](https://downloads.wordpress.org/plugin/wp-stateless.3.2.2.zip)]
4. Login via WordPress dashboard, manually upload and activate v3.2.2 plugin
5. Delete v3.2.3 plugin

**Comment by planv** [comment]
@Dishoom007 @darrenbarklie 

We have just released new version `3.2.4`, these issues should be resolved there.

Please let us know if you still have any issues

`WP-Stateless` `3.2.3` requires PHP 8.0 and higher, if you use PHP 7.4 - please install `WP-Stateless` version `3.2.2` https://downloads.wordpress.org/plugin/wp-stateless.3.2.2.zip

**Comment by Dishoom007** [comment]
Thanks Dear, we have installed the plugin and following are the
observations.

1. The plug-in 3.2.4 worked when we upgraded to php 8
2. But since other plugins are not compatible with php 8, we have to
downgrade the php to 7.4
3. We have to install again WP-Stateless 3.2.2

SUGGESTION :

It would be good if you can make the new version 3.2.4 to work on php 7.4
also.

Regards

Puneet

**Comment by comzeradd** [comment]
Maybe it's better to avoid breaking php compatibility on a minor release tag.

**Comment by planv** [comment]
Hello @Dishoom007 

Thank you for your respond!

> It would be good if you can make the new version 3.2.4 to work on php 7.4 also.
Unfortunately, Google Library requires PHP 8.0 or higher.

------------

Hello @comzeradd 

Thank you for your respond!

> Maybe it's better to avoid breaking php compatibility on a minor release tag.

Sure, that's an excellent point!
This is how we will act in the future.


---------

Closing the ticket.
