### ISSUE TITLE
[VERY URGENT]Critical Error occurred

### ISSUE THREAD

**Issue by knchst** [udx/wp-stateless#670]
Error Logs
```shell
[Wed Jun 21 10:41:33.464668 2023] [proxy_fcgi:error] [pid 3644:tid 140127586113280] [client 106.146.22.223:50493] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected '=' in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/wp-stateless/vendor/symfony/string/Resources/functions.php on line 34'
```

![image](https://github.com/udx/wp-stateless/assets/13914484/9757c8db-38f7-415a-b41a-f3c71540f0de)

- can not access my wordpress site
- i tried restart wordpress & gcp compute engine
- Plugin Version : v3.2.3

**Comment by planv** [comment]
Hello @knchst 

Which version PHP installed on the Server?

**Comment by knchst** [comment]
@planv Hi, thanks for your support 🙏

i use 7.3.13
<img width="715" alt="image" src="https://github.com/udx/wp-stateless/assets/13914484/07a63eaa-cb65-4e91-a8f2-50867a8530b5">

**Comment by planv** [comment]
Can you try to deactivate the Plugin through `WP CLI`?

```
wp plugin deactivate wp-stateless
```

If it does not work - try to rename folder with `wp-stateless` plugin to `wp-stateless-3.2.3` and install `WP-Stateless` version `3.2.2` then.

Version `3.2.3` does not support PHP version `7.3`, I'll update information about that soon.

**Comment by knchst** [comment]
@planv thanks!


↓ result of `wp plugin deactivate wp-stateless`
```bash
developer@wordpress-2-vm:~$ sudo wp plugin deactivate wp-stateless --allow-root
PHP Fatal error:  Uncaught Error: Call to undefined function add_filter() in phar:///opt/bitnami/apps/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code:118
Stack trace:
#0 phar:///opt/bitnami/apps/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197): eval()
#1 phar:///opt/bitnami/apps/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#2 phar:///opt/bitnami/apps/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#3 phar:///opt/bitnami/apps/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#4 phar:///opt/bitnami/apps/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#5 phar:///opt/bitnami/apps/wordpress/bin/wp-cli.phar/php/boot-phar.php(11): include('phar:///opt/bit...')
#6 /opt/bitnami/apps/wordpress/bin/wp-cli.pha in phar:///opt/bitnami/apps/wordpress/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1197) : eval()'d code on line 118
```

i can not access my wordpress admin, so please give me MANUAL reinstall plugin's instruction 🙏

**Comment by knchst** [comment]
Download source code from [here](https://github.com/udx/wp-stateless/releases/tag/3.2.2) and extract to wp-content/plugins dir?

**Comment by planv** [comment]
> Download source code from [here](https://github.com/udx/wp-stateless/releases/tag/3.2.2) and extract to wp-content/plugins dir?

You can download version `3.2.2` from wordpress.org - https://downloads.wordpress.org/plugin/wp-stateless.3.2.2.zip

**Comment by planv** [comment]
> i can not access my wordpress admin,

try to rename folder with `wp-stateless` plugin to `wp-stateless-3.2.3`

```
mv wp-stateless wp-stateless-3.2.3
```

Then you will be able to login into admin panel

**Comment by knchst** [comment]
@planv Thanks so much ! It works!!
