### ISSUE TITLE
WP-Stateless Incompatible w/ WP Inline Uploader

### ISSUE THREAD

**Issue by cmdshepard** [udx/wp-stateless#675]
## Summary
WP-Statelss doesn't upload media in `ephemeral` and `stateless` mode when using the inline uploader (Media -> Library -> Add New).

Other modes were not tested. With debug enabled, no error is displayed in the logs.

When navigating to `media-new.php` to upload an asset, the plugin correctly uploads the media to GCP bucket.

## Technical Details
* Apache 
* Wordpress v6.3.1
* PHP v8.1.17 (Also tested with PHP 7 which has the same issue)
* WP-Stateless v3.2.4

## Steps to Reproduce
On a fresh instance of WordPress with no other plugins installed, install WP-Stateless & set it up using Manual mode.

Set the mode to `ephemeral` or `stateless`.

Navigate to the inline uploader by visiting `/wp-admin/upload.php`.

Trigger the inline uploader by clicking `Add New`.

Attempt to upload the media - the media will not be uploaded to GCP.

Now navigate to `/wp-admin/media-new.php`.

Add a file to upload - the media will be uploaded as expected.

**Comment by ewsopp** [comment]
This is fixed and will be released in the next version. Thank you!

**Comment by planv** [comment]
Fix was released with version `3.2.5`
Closing the ticket.
