### ISSUE TITLE
upgrade libraries

### ISSUE THREAD

**Issue by planv** [udx/wp-stateless#685]
Please upgrade all 3party libraries to latest versions

**Comment by balexey88** [comment]
* ENHANCEMENT - Updated Client library for Google APIs to version 2.15.1.
* ENHANCEMENT - Updated Meta Box library to version 5.8.2.
* ENHANCEMENT - Updated Meta Box Tabs to version 1.1.17.
* ENHANCEMENT - Updated JWT library.

**Comment by balexey88** [comment]
https://github.com/udx/wp-stateless/pull/690

**Comment by planv** [comment]
It was released with version `3.3.0`.
Closing the ticket
