### ISSUE TITLE
Google API client is out-of-date and a security risk.

### ISSUE THREAD

**Issue by doubleforte** [udx/wp-stateless#689]
The included Google API client lib/Google is recently out-of-date and tripping a Dependabot security warning. The `composer/composer` included in this dist is v1.10.26 and the patch is included in v1.10.27.

https://github.com/advisories/GHSA-jm6m-4632-36hf

Downloading the currently available Google library brings this package up-to-date -- it's just not included in this released wp-stateless package.

Thank you :)

**Comment by doubleforte** [comment]
Same issue with another Google dependency: `phpseclib/phpseclib` is out of date in this download.

https://github.com/advisories/GHSA-jpr7-q523-hx25

**Comment by planv** [comment]
Hello @doubleforte 

It will be updated in next release.

**Comment by planv** [comment]
Hello @doubleforte 

Updated Google API client was released with version `3.3.0`.

**Comment by planv** [comment]
Closing the ticket.
