### ISSUE TITLE
Slow admin panel

### ISSUE THREAD

**Issue by hilbertknl** [udx/wp-stateless#691]
Hello,

We started using WP Stateless a few weeks ago, all of our 176k images are uploaded to Google Cloud and it functions great!
The site started slowing down in the days after we started the uploads. Now, the average loading time is 42 seconds for every page in the back-end.

Via the MySQL command FULL PROCESS LIST, we found out every page in the back-end awaits the execution of a single MySQL command:
`SELECT COUNT(meta_id)
FROM wp_postmeta
WHERE meta_key = 'sm_cloud'`

We started looking in the code and found that this query gets executed at litteraly every pagina in the back-end. Thats 176k of rows to do a count on. For now, we commented the execution and returned "0". The back-end works fine after this change.

When navigating to Media --> Stateless --> Sync; We get an error "Errors encountered. Try reloading the page.". I don't know if this has to do with the same problem but I don't know.

**Comment by ewsopp** [comment]
Thank you for your report. We have a fix planned for this in the future.

**Comment by planv** [comment]
It was improved and released with version `4.0`.
Closing the ticket.
