### ISSUE TITLE
Critical Fatal Error after deleting GCP permissions

### ISSUE THREAD

**Issue by hamilton-seguin** [udx/wp-stateless#693]
I've had an issue since yesterday where none of the images I upload on my wp website are visible. The thumbnail after upload is just blank. There is a link to my GCP bucket but the link gives this error

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: voyageinstyle-net/2023/12/ba042ea9-vis07339.jpg</Details>
</Error>`

When trying to upload an image directly to the GCP bucket i have no problem.

So I tried to create a new API key for the wp-stateless I AM role, and change it in the settings of the plugin. It didn't help.
Finally, I tried to delete the role entirely in GCP to just create a new one. After deleting the IAM Service Role, my /wp-admin/ page is in critical error state.

<img width="815" alt="Screenshot 2023-12-21 at 16 57 55" src="https://github.com/udx/wp-stateless/assets/50454097/7af45cfe-c2fd-4626-b27a-1cd3033342c9">

After contacting my server admin at Cloudways, they fixed my admin backend by desactivating wp-stateless. Everytime I reactivate it, the backend instantly crashes. Giving me the critical error...

I tried to delete the plugin altogether and reinstalling it: same thing, instant crash + fatal error of the wordpress backend

**Please help !!**

On the servers of my WP app, here are the logs

`[Thu Dec 21 16:06:04.672793 2023] [proxy_fcgi:error] [pid 19226:tid 140643854505728] [client 101.53.249.189:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Google\\Cloud\\Core\\Exception\\ServiceException: {"error":{"code":401,"message":"Invalid Credentials","errors":[{"message":"Invalid Credentials","domain":"global","reason":"authError","locationType":"header","location":"Authorization"}]}} in /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php:398\nStack trace:\n#0 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php(215): Google\\Cloud\\Core\\RequestWrapper->convertToGoogleException()\n#1 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RestTrait.php(101): Google\\Cloud\\Core\\RequestWrapper->send()\n#2 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/Connection/Rest.php(723): Google\\C...; PHP message: PHP Fatal error:  Uncaught Google\\Cloud\\Core\\Exception\\ServiceException: {"error":{"code":401,"message":"Invalid Credentials","errors":[{"message":"Invalid Credentials","domain":"global","reason":"authError","locationType":"header","location":"Authorization"}]}} in /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php:398\nStack trace:\n#0 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php(215): Google\\Cloud\\Core\\RequestWrapper->convertToGoogleException()\n#1 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RestTrait.php(101): Google\\Cloud\\Core\\RequestWrapper->send()\n#2 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/Connection/Rest.php(723): Google\\C...', referer: https://voyageinstyle.net/wp-admin/

[Thu Dec 21 16:06:10.223100 2023] [proxy_fcgi:error] [pid 19226:tid 140643829327616] [client 101.53.249.189:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Google\\Cloud\\Core\\Exception\\ServiceException: {"error":{"code":401,"message":"Invalid Credentials","errors":[{"message":"Invalid Credentials","domain":"global","reason":"authError","locationType":"header","location":"Authorization"}]}} in /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php:398\nStack trace:\n#0 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php(215): Google\\Cloud\\Core\\RequestWrapper->convertToGoogleException()\n#1 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RestTrait.php(101): Google\\Cloud\\Core\\RequestWrapper->send()\n#2 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/Connection/Rest.php(723): Google\\C...; PHP message: PHP Fatal error:  Uncaught Google\\Cloud\\Core\\Exception\\ServiceException: {"error":{"code":401,"message":"Invalid Credentials","errors":[{"message":"Invalid Credentials","domain":"global","reason":"authError","locationType":"header","location":"Authorization"}]}} in /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php:398\nStack trace:\n#0 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php(215): Google\\Cloud\\Core\\RequestWrapper->convertToGoogleException()\n#1 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RestTrait.php(101): Google\\Cloud\\Core\\RequestWrapper->send()\n#2 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/Connection/Rest.php(723): Google\\C...'

[Thu Dec 21 16:06:10.614662 2023] [proxy_fcgi:error] [pid 19226:tid 140644139857664] [client 101.53.249.189:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Google\\Cloud\\Core\\Exception\\ServiceException: {"error":{"code":401,"message":"Invalid Credentials","errors":[{"message":"Invalid Credentials","domain":"global","reason":"authError","locationType":"header","location":"Authorization"}]}} in /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php:398\nStack trace:\n#0 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php(215): Google\\Cloud\\Core\\RequestWrapper->convertToGoogleException()\n#1 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RestTrait.php(101): Google\\Cloud\\Core\\RequestWrapper->send()\n#2 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/Connection/Rest.php(723): Google\\C...; PHP message: PHP Fatal error:  Uncaught Google\\Cloud\\Core\\Exception\\ServiceException: {"error":{"code":401,"message":"Invalid Credentials","errors":[{"message":"Invalid Credentials","domain":"global","reason":"authError","locationType":"header","location":"Authorization"}]}} in /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php:398\nStack trace:\n#0 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php(215): Google\\Cloud\\Core\\RequestWrapper->convertToGoogleException()\n#1 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RestTrait.php(101): Google\\Cloud\\Core\\RequestWrapper->send()\n#2 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/Connection/Rest.php(723): Google\\C...', referer: https://voyageinstyle.net/wp-admin/?no_cache

[Thu Dec 21 16:06:52.020523 2023] [proxy_fcgi:error] [pid 19226:tid 140644148250368] [client 40.77.167.25:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Google\\Cloud\\Core\\Exception\\ServiceException: {"error":{"code":401,"message":"Invalid Credentials","errors":[{"message":"Invalid Credentials","domain":"global","reason":"authError","locationType":"header","location":"Authorization"}]}} in /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php:398\nStack trace:\n#0 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php(215): Google\\Cloud\\Core\\RequestWrapper->convertToGoogleException()\n#1 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RestTrait.php(101): Google\\Cloud\\Core\\RequestWrapper->send()\n#2 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/Connection/Rest.php(723): Google\\C...; PHP message: PHP Fatal error:  Uncaught Google\\Cloud\\Core\\Exception\\ServiceException: {"error":{"code":401,"message":"Invalid Credentials","errors":[{"message":"Invalid Credentials","domain":"global","reason":"authError","locationType":"header","location":"Authorization"}]}} in /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php:398\nStack trace:\n#0 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php(215): Google\\Cloud\\Core\\RequestWrapper->convertToGoogleException()\n#1 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RestTrait.php(101): Google\\Cloud\\Core\\RequestWrapper->send()\n#2 /home/858676.cloudwaysapps.com/pqrajkhhmh/public_html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/Connection/Rest.php(723): Google\\C...'
`

**Comment by ewsopp** [comment]
@hamilton-seguin thank you for reporting! We'll take a look

**Comment by planv** [comment]
Hello @hamilton-seguin 

It was solved in version `3.4.0`.
Please let us know how it works for you.

**Comment by hamilton-seguin** [comment]
@planv Amazing, thank you guys. 
I had to create a new Service Account (could not use old key, or use a fresh key with the old Service Account) But it's all working now :)
