### ISSUE TITLE
PHP Error with WooCommerce

### ISSUE THREAD

**Issue by mcreef** [udx/wp-stateless#696]
Hello,

my server logs are getting filled with this error:

PHP Warning: Undefined array key "class" in /var/www/vhosts/xxxxxxxx/httpdocs/wp-content/plugins/wp-stateless/lib/classes/compatibility/woocommerce.php on line 37

How can this be fixed?

**Comment by ewsopp** [comment]
@mcreef thank you for reporting. We'll take a look!

**Comment by ewsopp** [comment]
We fixed it, and it will be released in version v3.4. Most likely next week. Thank you

**Comment by planv** [comment]
Hello @mcreef 

It was solved in version `3.4.0`.
Please let us know how it works for you.

**Comment by planv** [comment]
As we have not yet received a response from you in the past 7 days, we will be closing the current issue. 
If you have any questions, please feel free to re-open it.
