### ISSUE TITLE
[feature request] Custom domain + CDN + HTTPS

### ISSUE THREAD

**Issue by gabohuber** [udx/wp-stateless#699]
Hello wp-stetaless team,

Would be nice to have any option for activating HTTPS when CDN and custom domain (images.domain.com) is enabled and configured.

**Comment by balexey88** [comment]
Hello @gabohuber,

It is possible to use you custom domain + HTTPS on the current version of WP-Stateless. But probably you will require a load balancer for this.

Please take a look at this discussion, I hope this will help you: https://github.com/udx/wp-stateless/issues/291#issuecomment-419833166

Please let us know if you have any more questions.

**Comment by gabohuber** [comment]
Hello @balexey88,

Thank you very much, solved my issue!

**Comment by gabohuber** [comment]
Hello @balexey88,

Thank you very much, solved my issue!
