### ISSUE TITLE
logout button doesn't appear to work

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#70]
Clicking the logout button sends me back to Step 1, this is good.

However, when I click the "Google Login" button again I am not prompted to login with Google. It simply shows the previous account I logged-in with.

It doesn't seem to actually log me out.

**Comment by alimuzzaman** [comment]
It's worked fine when sin into multiple account.
If you have sin into only one account then it login automatically.
@andypotanin Need to show the login prompt every time or logout option in API.
&max_auth_age=0
Something like [No prompt for re-authentication with OAUth2. Why and how to force it?
](http://stackoverflow.com/questions/19379627/no-prompt-for-re-authentication-with-oauth2-why-and-how-to-force-it)

**Comment by andypotanin** [comment]
@alimuzzaman What do you mean by:
> It's worked fine when sin into multiple account

User can sign in into multiple Google accounts at the same time with oAuth? 

I guess I'm really not sure what the issue is.

**Comment by alimuzzaman** [comment]
@andypotanin 
User can't sine into multiple/another account when loged in to one account.
I mean when user loged in multiple account already. In this case it show account to choose.
![image](https://cloud.githubusercontent.com/assets/6744156/24415808/88821494-1404-11e7-8d14-785aaa5cf64b.png)
But if there are only one account nothing showed.
I can show you, if not clear.

**Comment by alimuzzaman** [comment]
Should user ask for login for every time user click "Google Login" button or only after user click logout?

**Comment by ewsopp** [comment]
Only after the user click's the logout button.

**Comment by alimuzzaman** [comment]
@andypotanin add parameter **`max_auth_age=0`** to auth url  if it's passed from user site.
Maybe [https://github.com/UsabilityDynamics/node-product-api/blob/production/routes/stateless-v1/index.js#L332](https://github.com/UsabilityDynamics/node-product-api/blob/production/routes/stateless-v1/index.js#L332)
