### ISSUE TITLE
RETRY_HEADER_KEY Fatal Error

### ISSUE THREAD

**Issue by matt-m-LA** [udx/wp-stateless#702]
I am experimenting with a web site to try and install wp-stateless. 

I am occasionally getting this error:

Fatal error: Uncaught Error: Undefined constant Google\Cloud\Core\Retry::RETRY_HEADER_KEY in /var/www/html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php:291 Stack trace: #0 /var/www/html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php(210): Google\Cloud\Core\RequestWrapper->applyHeaders(Object(GuzzleHttp\Psr7\Request), Array) #1 /var/www/html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RestTrait.php(102): Google\Cloud\Core\RequestWrapper->send(Object(GuzzleHttp\Psr7\Request), Array) #2 /var/www/html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/Connection/Rest.php(730): Google\Cloud\Storage\Connection\Rest->traitSend('objects', 'list', Array) #3 /var/www/html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/Connection/Rest.php(258): Google\Cloud\Storage\Connection\Rest->send('objects', 'list', Array) #4 /var/www/html/wp-content/themes/starter-theme/vendor/google/cloud-core/src/Iterator/PageIteratorTrait.php(238): Google\Cloud\Storage\Connection\Rest->listObjects(Array) #5 /var/www/html/wp-content/themes/starter-theme/vendor/google/cloud-storage/src/ObjectPageIterator.php(55): Google\Cloud\Storage\ObjectPageIterator->executeCall() #6 /var/www/html/wp-content/themes/starter-theme/vendor/google/cloud-core/src/Iterator/ItemIteratorTrait.php(93): Google\Cloud\Storage\ObjectPageIterator->current() #7 /var/www/html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/StreamWrapper.php(774): Google\Cloud\Storage\ObjectIterator->current() #8 /var/www/html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-storage/src/StreamWrapper.php(604): Google\Cloud\Storage\StreamWrapper->getDirectoryInfo('sites/www/2024/...') #9 /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-gs-stream-wrapper.php(53): Google\Cloud\Storage\StreamWrapper->url_stat('gs://dev-images...', 6) #10 [internal function]: wpCloud\StatelessMedia\StreamWrapper->url_stat('gs://dev-images...', 6) #11 /var/www/html/wp-includes/functions.php(2059): file_exists('gs://dev-images...') #12 /var/www/html/wp-includes/functions.php(2393): wp_mkdir_p('gs://dev-images...') #13 /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-bootstrap.php(1066): wp_upload_dir() #14 /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-bootstrap.php(1037): wpCloud\StatelessMedia\Bootstrap->convert_to_gs_link(Array) #15 /var/www/html/wp-includes/class-wp-hook.php(326): wpCloud\StatelessMedia\Bootstrap->post_metadata_filter(NULL, 15540, '_wp_attached_fi...', true) #16 /var/www/html/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array) #17 /var/www/html/wp-includes/meta.php(635): apply_filters('get_post_metada...', NULL, 15540, '_wp_attached_fi...', true, 'post') #18 /var/www/html/wp-includes/meta.php(574): get_metadata_raw('post', 15540, '_wp_attached_fi...', true) #19 /var/www/html/wp-includes/post.php(2526): get_metadata('post', 15540, '_wp_attached_fi...', true) #20 /var/www/html/wp-includes/post.php(753): get_post_meta(15540, '_wp_attached_fi...', true) #21 /var/www/html/wp-includes/post.php(6677): get_attached_file(15540) #22 /var/www/html/wp-includes/post.php(6730): wp_attachment_is('image', Object(WP_Post)) #23 /var/www/html/wp-includes/media.php(192): wp_attachment_is_image(15540) #24 /var/www/html/wp-includes/media.php(970): image_downsize(15540, 'full') #25 /var/www/html/wp-includes/media.php(1179): wp_get_attachment_image_src(15540, 'full', false) #26 /var/www/html/wp-includes/general-template.php(971): wp_get_attachment_image_url(15540, 'full') #27 /var/www/html/wp-includes/general-template.php(1012): get_site_icon_url(512, '', 0) #28 /var/www/html/wp-includes/general-template.php(3404): has_site_icon() #29 /var/www/html/wp-includes/class-wp-hook.php(324): wp_site_icon('') #30 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #31 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #32 /var/www/html/wp-login.php(123): do_action('login_head') #33 /var/www/html/wp-login.php(1473): login_header('Log In', '', Object(WP_Error)) #34 {main} thrown in /var/www/html/wp-content/plugins/wp-stateless/lib/Google/vendor/google/cloud-core/src/RequestWrapper.php on line 291

No idea what that error is, why it is happening, or what to do about it.

Any ideas?

**Comment by planv** [comment]
Hello @matt-m-LA 

The constant `RETRY_HEADER_KEY` is declared in this script 

https://github.com/udx/wp-stateless/blob/5f8b7d0b1ae23df2ada32a92f800025354068b0b/lib/Google/vendor/google/cloud-core/src/Retry.php#L28

----

Your Theme also includes `Google` library

```
https://github.com/udx/wp-stateless/issues/4 /var/www/html/wp-content/themes/starter-theme/vendor/google/cloud-core/src/Iterator/PageIteratorTrait.php(238): Google\Cloud\Storage\Connection\Rest->listObjects(Array) https://github.com/udx/wp-stateless/issues/5 /var/www/html/wp-content/themes/starter-theme/vendor/google/cloud-storage/src/ObjectPageIterator.php(55): Google\Cloud\Storage\ObjectPageIterator->executeCall() https://github.com/udx/wp-stateless/issues/6 /var/www/html/wp-content/themes/starter-theme/vendor/google/cloud-core/src/Iterator/ItemIteratorTrait.php(93): Google\Cloud\Storage\ObjectPageIterator->current()
```

Looks like there is a conflict between the `Google` libraries in the`WP-Stateless` and the`Starter theme`
Please make sure the `Google` library in your theme is updated to the latest version

**Comment by ewsopp** [comment]
Closing issue for now. Please followup with notes if you need further guidance.
