### ISSUE TITLE
The server cannot process the image

### ISSUE THREAD

**Issue by michaelaguiar** [udx/wp-stateless#704]
I am getting the error `The server cannot process the image. This can happen if the server is busy or does not have enough resources to complete the task. Uploading a smaller image may help. Suggested maximum size is 2560 pixels.` when trying to upload an image. The image is a very small image that weighs around 60kb. This error happens for all images I try to upload.

I have wp-stateless set to `ephemeral`. I am also able to upload photos directly to the filesystem if I disable wp-stateless.

When I go into stateless-settings and hit `sync`, I get the error `Path cannot be empty`. I have the `WP_STATELESS_MEDIA_KEY_FILE_PATH` config var set to `null`, and my json set in `WP_STATELESS_MEDIA_JSON_KEY`.

Any idea what my issue could be?

**Comment by planv** [comment]
Hello @michaelaguiar 

Can you try to remove `WP_STATELESS_MEDIA_KEY_FILE_PATH` from your config file?
Because if it is set - it should not be `null`.

**Comment by michaelaguiar** [comment]
Commented that line out and same error. Thanks for the quick response though!

**Comment by michaelaguiar** [comment]
I should also mention that this is running on a Google Cloud Run instance. If there is a better way to use the instance service account instead of defining it via json, that would be useful!

**Comment by michaelaguiar** [comment]
Ok, I have this narrowed down to Caddy for the web server. I switched back to NGINX and it's working.

Does anyone know if there are specific server options I need to set in Caddy to get it working?

**Comment by michaelaguiar** [comment]
Ok - looks like this is an issue only with PHP v8.1 and higher. I am submitting a PR to fix this in the v4.0 branch!

**Comment by balexey88** [comment]
Hello @michaelaguiar ,

Thank you for your expertise and contribution!

Just 2 small notices:
* Please remove your changes from `wp-stateless-media.php` file. You made changes in version `3.2.5` and our latest public version is `3.4.0`. So there is a high risk of merge conflicts.
*  Please edit your PR into `latest` branch (instead of `v4.0`)

Thank you!

**Comment by michaelaguiar** [comment]
Done!

Is it generally best to keep all contributions in the `latest` branch? I suppose this update also benefits latest, but if it were very specific to `v4.0`, then send to that branch?

**Comment by balexey88** [comment]
Thanks a lot @michaelaguiar ! We will accept PR and publish the changes in the next release.

>Is it generally best to keep all contributions in the latest branch? I suppose this update also benefits latest, but if it were very specific to v4.0, then send to that branch?

This is more related to internal workflow, so please don't bother :)

**Comment by michaelaguiar** [comment]
Sounds great, thanks for the quick feedback!
