### ISSUE TITLE
google cloud service account

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#72]
What name do we give the service account on Google Cloud? What role do we assign this account?

**Comment by alimuzzaman** [comment]
@ewsopp Service account uses bucketId bucketName with stateless prefix (If already don't have in bucket name).

**Comment by ewsopp** [comment]
What role do we assign this account?

**Comment by alimuzzaman** [comment]
@ewsopp Service account doesn't get any global role. It's only get `Owner` role to selected/created bucket.
