### ISSUE TITLE
Undefined array key "file" on videos

### ISSUE THREAD

**Issue by engvie** [udx/wp-stateless#728]
I get this warning when a video is about to be displayed.

`Undefined array key "file" in /var/www/html/wp-content/plugins/wp-stateless/lib/classes/class-bootstrap.php on line 1510`

I get this if I dump the metadata:

`array(10) {
  ["bitrate"]=>
  int(15180947)
  ["filesize"]=>
  int(9510156)
  ["mime_type"]=>
  string(15) "video/quicktime"
  ["length"]=>
  int(5)
  ["length_formatted"]=>
  string(4) "0:05"
  ["width"]=>
  int(1080)
  ["height"]=>
  int(1080)
  ["fileformat"]=>
  string(3) "mp4"
  ["dataformat"]=>
  string(9) "quicktime"
  ["created_timestamp"]=>
  int(1698416877)
}`

Maybe similar to this one:
[Issue: 724](https://github.com/udx/wp-stateless/issues/724)

**Comment by balexey88** [comment]
Hello @engvie ,

From the information you provided I assume that you are uploading `qicktime` video in `Stateless` mode.
I've tried a couple of sample quicktime `mov` videos, they uploaded correctly, but some of them did not play at all, some of them played only audio, etc. 
When you upload a video file, WordPress processes it to get the file metadata like video dimensions, bitrate, timing, etc. And this depends much on the video format you use, server software and so on. 
I would suggest you to convert the video to `mp4` format as the most commonly used format and check if this resolves the issue.

Please let us know if this works.

**Comment by ewsopp** [comment]
@engvie, any feedback here? We will close this issue if no response is received within the next 7 to 10 days.

**Comment by engvie** [comment]
Hello @balexey88 ,

It works if I convert it to an mp4 👍

**But should the warning still be there? I mean the video works even if it throws an warning. Should an "isset()" be in place?**
The error also appears in admin:
<img width="1188" alt="Screenshot 2024-04-15 at 10 57 27" src="https://github.com/udx/wp-stateless/assets/5121709/0d305dab-1532-4456-b6fa-44e90ae4b63e">

**Comment by balexey88** [comment]
Hello @engvie ,

The issue with warning will be resolved in the next release.

Thanks for your feedback!

**Comment by balexey88** [comment]
Hello @engvie,

The change is included into our new release 4.0.3.

Thanks!
