### ISSUE TITLE
Could Not Connect to GCS Bucket Error

### ISSUE THREAD

**Issue by blesphil** [udx/wp-stateless#73]
Hi,

WP-Stateless is showing an error all the time. I adjusted the roles and settings in GCS Console (There's not much settings to play around in the plugin itself-which I say is amazing-keep it simple), but it shows the same error all the time:

"WP-Stateless is not active due to following errors: Could not connect to Google Storage bucket."

I found a couple of threads that talk of the same problem, but the solutions provided there did not work for me.

Some Additional Info: I am still on a development server (localhost), could that be the reason for not being able to connect to the GCS bucket?

Warm regards,

Bles

**Comment by ewsopp** [comment]
After you create the service account, try setting the role to "Storage Admin". This should give it the appropriate access to all buckets in the project.

**Comment by blesphil** [comment]
Hi Eric,

Thanks for the prompt reply. I tried that as well. Still the same error.

"WP-Stateless is not active due to following errors: Could not connect to Google Storage bucket. Please, be sure that bucket with name (bucketname) exists."

Bles

**Comment by ewsopp** [comment]
Did you create a bucket on the Google Cloud project? The current production release of WP-Stateless does not create the bucket for you. 

Also - make sure the bucket name setting matches the name on Google Cloud. I usually just name it "stateless" or "media" to keep it simple.

**Comment by blesphil** [comment]
Hi Eric,

I created the bucket in the GC Console. And then I just entered the name of the bucket in the name area of the plugin, and then I entered the JSON key in the required area.

I tried this on a live (demo) server and it works. Maybe the plugin (or GCS) doesn't work it out on a development server (localhost). Would've been nice if it did (as I like to do all the site work offline and then take it all together online, at least in the beginning).

Hope this helps. 

Warm regards,

Bles

**Comment by ewsopp** [comment]
Hmm - you might be right. I don't work locally, so I cannot confirm this myself. I'll make a note of this and maybe we can build `localhost` support in a future release.

**Comment by blesphil** [comment]
Yeah... Thanks for the help Eric! And the excellent plugin! You guys are doing a great job! Please let me know if I can be of any help in any way!

**Comment by totranquilo** [comment]
Fix this error when reviewing bucket permission by adding the new user created to manage
