### ISSUE TITLE
Deprecated class

### ISSUE THREAD

**Issue by VovaChampion** [udx/wp-stateless#742]
WP Version 6.5.2
PHP version 8.3.3-1+ubuntu20.04.1+deb.sury.org+1 (Supports 64bit values)

Deprecated: Creation of dynamic property wpCloud\StatelessMedia\GS_Client::$key_json is deprecated in /www/tandlakaresecmsb_276/public/wp-content/plugins/wp-stateless/lib/classes/class-gs-client.php on line 66 ->
https://php.watch/versions/8.2/dynamic-properties-deprecated

Deprecated: Calling get_class() without arguments is deprecated in /www/tandlakaresecmsb_276/public/wp-content/plugins/wp-stateless/lib/Google/src/Http/REST.php on line 58 -> https://php.watch/versions/8.3/get_class-get_parent_class-parameterless-deprecated

**Comment by balexey88** [comment]
Hello @VovaChampion,

> Deprecated: Creation of dynamic property wpCloud\StatelessMedia\GS_Client::$key_json is deprecated

This is fixed in our latest release 4.0.3

> Deprecated: Calling get_class() without arguments is deprecated

This will be updated in our next release.

Thanks a lot for sharing and have a nice day.

**Comment by balexey88** [comment]
Hello @VovaChampion ,

We updated dependencies in our new release 4.1.1, so the issue you mentioned should be fixed.
Thanks!
