### ISSUE TITLE
Changing Cache-Busting to Disable does not save

### ISSUE THREAD

**Issue by Jessedev1** [udx/wp-stateless#758]
Hello,

I am trying to disable the Cache-Busting option, but when saving the field does not get updated.
Could someone please tell me how to fix this issue?

Plugin version: 3.4.1
Wordpress version: 6.3

Mode: Ephemeral
File URL Replacement: Enable Editor & Meta
Supported File Types: jpg jpeg png gif pdf mp4 mov
Cache-Control: public, max-age=36000, must-revalidate
Delete GCS File: Enable
Dynamic Image Support: Enable

**Comment by balexey88** [comment]
Hello @Jessedev1 ,

`Cache Busting` is always on for `Ephemeral` mode. But you can override this behavior by setting [WP_STATELESS_MEDIA_CACHE_BUSTING](https://stateless.udx.io/docs/constants/#wpstatelessmediacachebusting) constant in `wp-config.php`

```php
define('WP_STATELESS_MEDIA_CACHE_BUSTING', false);
```

Please let us know if this helps.

**Comment by Jessedev1** [comment]
@balexey88 
Thats it, thank you for the help and fast response!

**Comment by Jessedev1** [comment]
@balexey88 
I've noticed the cache_busting field is only disabled for the **stateless** mode.

I have submitted a pull request (#759) to also disable the field and show the notice when selecting the **ephemeral** mode.
This will help other users with this question. Again, thanks for your help!
