### ISSUE TITLE
Regenerate all stateless images and synchronize Google Storage with local server

### ISSUE THREAD

**Issue by kevin25** [udx/wp-stateless#76]
I resized and synced images but i saw nothing on my GSE.

**Comment by Mashenka** [comment]
Hello.

It seems you are talking about this issue - https://github.com/wpCloud/wp-stateless/issues/28
You can contact us directly I will send you version where that fixed.
https://www.usabilitydynamics.com/contact-us/

Regards.

**Comment by kevin25** [comment]
I want to synchronize the images only. But i haven't found any images after having synchronized. I'll contact you shortly. Thank you
