### ISSUE TITLE
Add JSON Key Support 

### ISSUE THREAD

**Issue by andypotanin** [udx/wp-stateless#8]
Right now we require a p12 key to be added to the site and it then must be referenced in the Media settings by providing its path. This requires the key to be added to the codebase or uploaded to the Media library, neither option is ideal.

GCS now allows for a JSON key to be used instead of a p12 key and we should allow for the key to be copied and pasted into a textarea and saved in WordPress options. 

Support for old p12 keys should still be available although hidden from the UI so that old installations still work but new installations, and old, can now be configured with the JSON key.

**Comment by Mashenka** [comment]
@alimuzzaman Let me know when you available for a skype call. I need to explain you this issue directly

**Comment by andypotanin** [comment]
Progress?

**Comment by Mashenka** [comment]
started yesterday

**Comment by antonkorotkov** [comment]
I had to upgrade Google Api Client to new 2.0.0 version that allows to use JSON for auth. But p12 auth is no longer supported in this version. So I've migrated it to JSON completely.

**Comment by antonkorotkov** [comment]
Also, plugins now requires PHP 5.5+

**Comment by andypotanin** [comment]
@antonkorotkov Is this done? Please verify that its deployed/available on https://workspace.uds.io so we can test/review.

**Comment by antonkorotkov** [comment]
Done, and on workspace.
