### ISSUE TITLE
buckets don't have ids

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#82]
I don't think buckets have an ID. The bucket name is unique across the entire Google Cloud infrastructure, so the name is both the name and ID.

We shouldn't be doing anything with IDs for buckets.

Do you have any logic that has to do with bucket IDs? 

![image](https://cloud.githubusercontent.com/assets/5578537/25244607/73b80050-25cf-11e7-9f7f-c533f9f69411.png)

**Comment by ewsopp** [comment]
I still see this. What is it?

![image](https://cloud.githubusercontent.com/assets/5578537/25863919/87e89fa8-34bb-11e7-834e-a3bd7dc84bf4.png)

**Comment by alimuzzaman** [comment]
You still have the old version. check on https://sandbox-uds-io-develop-alim.c.rabbit.ci/wp-admin/upload.php?page=stateless-setup-wizard&step=setup-project

**Comment by ewsopp** [comment]
Looks correct now. Thanks!
