### ISSUE TITLE
Problem using WP_STATELESS_MEDIA_KEY_FILE_PATH: Service Account JSON is invalid.

### ISSUE THREAD

**Issue by BaldwinKoo** [udx/wp-stateless#86]
Error:
WP-Stateless is not active due to following errors:

    Service Account JSON is invalid.

wpconfig file:
```
define( 'WP_STATELESS_MEDIA_BUCKET', getenv('STATELESS_MEDIA_BUCKET'));
define( 'WP_STATELESS_MEDIA_MODE', 'cdn');
define( 'WP_STATELESS_MEDIA_ROOT_DIR', 'files/');
define( 'WP_STATELESS_MEDIA_KEY_FILE_PATH', '/etc/secrets/credentials.json');
```

I uploaded the credentials.json file to /etc/secrets/

**Comment by Mashenka** [comment]
Hello.

Try to disable all third party plugins to investigate the issue.

Regards.

**Comment by BaldwinKoo** [comment]
Hi,

Thanks for the fast response, the wordpress site is a fresh install in a docker container.

I did verify the json key worked when i disabled the key file path and added it in manually through the options page. So there is nothing wrong with the json key itself.

Seems as if the plugin cannot read credentials.json for some reason.

**Comment by Mashenka** [comment]
So that is correct way to add creds on option's page. Is that working for you without issues?

Where did you found information that they need to be set up in config file?

**Comment by BaldwinKoo** [comment]
Yes that way does work without issues but I need to define everything inside the config so I do not need to input my json key manually every time my container restarts.

The options were found in the readme.md

```
define( 'WP_STATELESS_MEDIA_BUCKET', 'media.application-domain.com' );
define( 'WP_STATELESS_MEDIA_MODE', 'cdn' );
define( 'WP_STATELESS_MEDIA_KEY_FILE_PATH', '/var/www/wp-content/keys/application-name-service-id.p12' );
define( 'WP_STATELESS_MEDIA_SERVICE_ACCOUNT', '12345689-hash@developer.gserviceaccount.com' );
```

**Comment by Mashenka** [comment]
@alimuzzaman do you know the reason why that may not work?

**Comment by alimuzzaman** [comment]
**p12** key file format is no longer supported. In order to support new **JSON** format this feature has
 been removed. I have added the feature using JSON key format instead of p12. You will find the changes here https://github.com/wpCloud/wp-stateless/commit/a449b5c14bd170a347051cf7c587b3a213b18f67

**Comment by alimuzzaman** [comment]
@BaldwinKoo You can apply only this changes https://github.com/wpCloud/wp-stateless/commit/a449b5c14bd170a347051cf7c587b3a213b18f67 (#92-#131 is must) on your site, as this will be on next release.
Or you can use the **`latest`** branch( latest branch is stable but have some unfinished feature) after @Mashenka merge the pull request.

**Comment by BaldwinKoo** [comment]
Added those lines and it works perfectly. 

Loving this plugin,  keep it up!
