### ISSUE TITLE
add 'Stateless' mode

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#9]
- [x] add new mode called 'Stateless'
- [x] when enabled, local files should be deleted once they are uploaded and confirmed to be stored on Google Cloud Storage (GCS).

![image](https://cloud.githubusercontent.com/assets/5578537/12422937/3f1d2744-be97-11e5-9392-36d93d7463ec.png)

**Comment by andypotanin** [comment]
To to be clear, we do NOTHING with any media that was added without wp-stateless. We want to avoid having any sort of batch process that may remove older media.

**Comment by timwhite** [comment]
@andypotanin Can you please clarify. If we set the mode to stateless, and rerun the "sync/upload" wizard, will it delete the local files? I have a site I'd like to migrate to stateless mode (to free up space on the server), and I'm trying to work out how to get it to delete the existing media files after upload.
Thanks

**Comment by ewsopp** [comment]
@timwhite Stateless mode will delete the local file upon successful upload to Google Cloud Storage. This will only affect newly uploaded files after configuring this Mode setting.

In your situation, you could set mode to `Stateless`, run the regeneration/sync option, and delete the files manually via SFTP or SSH. Be sure to have a backup too - just in case.
