### ISSUE TITLE
cached is_connected_to_gs status

### ISSUE THREAD

**Issue by zesarone** [udx/wp-stateless#91]
I have an issue with speed that i tracked down to the following line being deactivated.
https://github.com/wpCloud/wp-stateless/blob/v1.0/lib/classes/class-bootstrap.php#L586

Is there a reason for this? 
It seems to work well with the is_connected_to_gs caching active.

**Comment by Mashenka** [comment]
@alimuzzaman can you check that please

**Comment by zesarone** [comment]
Excellent! Thank you for a quick fix.
