### ISSUE TITLE
Please re-run composer dump-autoload

### ISSUE THREAD

**Issue by tivnet** [udx/wp-stateless#94]
The version from wp-org crashed on my comp until I re-generated the autoload files (Composer 1.4.2).

**Comment by andypotanin** [comment]
@alimuzzaman this done?

**Comment by alimuzzaman** [comment]
@andypotanin Fix on released version https://github.com/wpCloud/wp-stateless/tree/v1.0-issue-94
Also done in latest

**Comment by andypotanin** [comment]
@alimuzzaman if its done juts close out the issue. @kavaribes and @fqjony are working on this this week so we are trying to close out any old issues and merge any unmerged branches.
