### ISSUE TITLE
PHP Warning:  preg_replace()

### ISSUE THREAD

**Issue by tivnet** [udx/wp-stateless#95]
PHP Warning:  preg_replace(): Compilation failed: PCRE does not support \L, \l, \N{name}, \U, or \u at offset 17 in class-utility.php on line 74

**Comment by ewsopp** [comment]
@alimuzzaman can you investigate this issue please? Thanks

**Comment by alimuzzaman** [comment]
@tivnet Was that on windows server?

**Comment by tivnet** [comment]
@alimuzzaman yes
