### ISSUE TITLE
add support for static hosting with subdomain

### ISSUE THREAD

**Issue by reuben-li** [udx/wp-stateless#98]
There should be an option to allow buckets which have been set with a subdomain CNAME record to serve images directly from the subdomain.

For example:
A bucket is named `subdomain.domain.com` and has a CNAME alias to `c.storage.googleapis.com`. Currently, the plugin will have image paths as:
> https://storage.googleapis.com/subdomain.domain.com/image.jpg

However, in this case, it would make more sense to have it as:
> https://subdomain.domain.com/image.jpg

**Comment by alimuzzaman** [comment]
@reuben-li Check this issue #88

**Comment by ewsopp** [comment]
@reuben-li we are going to include this in the next release. Hopefully, it will ship by next week. Thanks!

**Comment by ewsopp** [comment]
@alimuzzaman I'm not sure this is working correctly.

I updated the setting to use `something.traciesaidyes.com`, and then I tested an image upload and got a `storage.googleapis.com` image url.

![image](https://user-images.githubusercontent.com/5578537/28169785-6266254c-67b1-11e7-8024-640704686707.png)

![image](https://user-images.githubusercontent.com/5578537/28169841-8a123ce8-67b1-11e7-9f2e-27e44aa1f283.png)

**Comment by alimuzzaman** [comment]
@ewsopp You can't just put any address. The domain and bucket name must be same.

**Comment by syaifulsz** [comment]
@alimuzzaman why is the plugin requires custom domain need to be the same as the bucket name?

> You can't just put any address. The domain and bucket name must be same.

I would suggest that whatever user add into custom_domain field, should be the base url for images.

**Comment by ewsopp** [comment]
> why is the plugin requires custom domain need to be the same as the bucket name?

@syaifulsz this is actually what Google Cloud Storage requires in order to use a CNAME with the bucket. 

> I would suggest that whatever user add into custom_domain field, should be the base url for images.

This was my original intent for this field, but @alimuzzaman pointed out it might cause confusion with the user since of the aforementioned limitation with Google Bucket naming with a custom CNAME.

What do you think based on this new knowledge?
